In [8]:
#Dependencies
import pandas as pd
import numpy as np
import requests
import json
import pprint

In [2]:
#The base url indicates the dataset with "WWDI"
base_url = "https://www.quandl.com/api/v3/datasets/WWDI/"

In [3]:
api_key = "&api_key=pzEzrjcJ5yrvoXBad3uy"

In [4]:
country_codes = pd.read_csv("country_codes.csv", delimiter="|", error_bad_lines=False)
country_codes.head()

          COUNTRY CODE
0     Afghanistan  AFG
1          Africa  AFR
2         Albania  ALB
3         Algeria  DZA
4  American Samoa  ASM

In [10]:
for index, row in country_codes.iterrows():
    var = row["CODE"]
    print(var)
    dataset = "_SP_POP_TOTL"
    query = base_url + var + dataset + "?&" + api_key
    response = requests.get(query)
    data = response.json()
    pprint.pprint(data)

AFG
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 35530081.0],
                      ['2016-12-31', 34656032.0],
                      ['2015-12-31', 33736494.0],
                      ['2014-12-31', 32758020.0],
                      ['2013-12-31', 31731688.0],
                      ['2012-12-31', 30696958.0],
                      ['2011-12-31', 29708599.0],
                      ['2010-12-31', 28803167.0],
                      ['2009-12-31', 28004331.0],
                      ['2008-12-31', 27294031.0],
                      ['2007-12-31', 26616792.0],
                      ['2006-12-31', 25893450.0],
                      ['2005-12-31', 25070798.0],
                      ['2004-12-31', 24118979.0],
                      ['2003-12-31', 23064851.0],
                      ['2002-12-31', 21979923.0],
                      ['2001-12-31', 20966463.0],
                      ['2000-12-31', 20093756.0],
                      ['1999-12-31', 19403676.0],
                      ['1998-12-31', 18863999.0],
                      ['1997-12-31', 18381605.0],
                      ['1996-12-31', 17822884.0],
                      ['1995-12-31', 17099541.0],
                      ['1994-12-31', 16172719.0],
                      ['1993-12-31', 15095099.0],
                      ['1992-12-31', 13981231.0],
                      ['1991-12-31', 12993657.0],
                      ['1990-12-31', 12249114.0],
                      ['1989-12-31', 11777609.0],
                      ['1988-12-31', 11540888.0],
                      ['1987-12-31', 11502761.0],
                      ['1986-12-31', 11601041.0],
                      ['1985-12-31', 11783050.0],
                      ['1984-12-31', 12047115.0],
                      ['1983-12-31', 12389269.0],
                      ['1982-12-31', 12749645.0],
                      ['1981-12-31', 13053954.0],
                      ['1980-12-31', 13248370.0],
                      ['1979-12-31', 13306695.0],
                      ['1978-12-31', 13237734.0],
                      ['1977-12-31', 13067538.0],
                      ['1976-12-31', 12840299.0],
                      ['1975-12-31', 12590286.0],
                      ['1974-12-31', 12321541.0],
                      ['1973-12-31', 12027822.0],
                      ['1972-12-31', 11721940.0],
                      ['1971-12-31', 11417825.0],
                      ['1970-12-31', 11126123.0],
                      ['1969-12-31', 10854428.0],
                      ['1968-12-31', 10604346.0],
                      ['1967-12-31', 10372630.0],
                      ['1966-12-31', 10152331.0],
                      ['1965-12-31', 9938414.0],
                      ['1964-12-31', 9731361.0],
                      ['1963-12-31', 9533954.0],
                      ['1962-12-31', 9345868.0],
                      ['1961-12-31', 9166764.0],
                      ['1960-12-31', 8996351.0],
                      ['1959-12-31', 8834445.0],
                      ['1958-12-31', 8680946.0],
                      ['1957-12-31', 8535807.0],
                      ['1956-12-31', 8399030.0],
                      ['1955-12-31', 8270581.0],
                      ['1954-12-31', 8150447.0],
                      ['1953-12-31', 8038596.0],
                      ['1952-12-31', 7934980.0],
                      ['1951-12-31', 7839510.0],
                      ['1950-12-31', 7752118.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'AFG_SP_POP_TOTL',
             'description': 'Population, total - Afghanistan. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22081907,
             'limit': None,
             'name': 'Population, total - Afghanistan',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:26:03.776Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
AFR
{'quandl_error': {'code': 'QECx02',
                  'message': 'You have submitted an incorrect Quandl code. '
                             'Please check your Quandl codes and try again.'}}
ALB
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 2873457.0],
                      ['2016-12-31', 2876101.0],
                      ['2015-12-31', 2880703.0],
                      ['2014-12-31', 2889104.0],
                      ['2013-12-31', 2895092.0],
                      ['2012-12-31', 2900401.0],
                      ['2011-12-31', 2905195.0],
                      ['2010-12-31', 2913021.0],
                      ['2009-12-31', 2927519.0],
                      ['2008-12-31', 2947314.0],
                      ['2007-12-31', 2970017.0],
                      ['2006-12-31', 2992547.0],
                      ['2005-12-31', 3011487.0],
                      ['2004-12-31', 3026939.0],
                      ['2003-12-31', 3039616.0],
                      ['2002-12-31', 3051010.0],
                      ['2001-12-31', 3060173.0],
                      ['2000-12-31', 3089027.0],
                      ['1999-12-31', 3108778.0],
                      ['1998-12-31', 3128530.0],
                      ['1997-12-31', 3148281.0],
                      ['1996-12-31', 3168033.0],
                      ['1995-12-31', 3187784.0],
                      ['1994-12-31', 3207536.0],
                      ['1993-12-31', 3227287.0],
                      ['1992-12-31', 3247039.0],
                      ['1991-12-31', 3266790.0],
                      ['1990-12-31', 3286542.0],
                      ['1989-12-31', 3227943.0],
                      ['1988-12-31', 3142336.0],
                      ['1987-12-31', 3083605.0],
                      ['1986-12-31', 3022635.0],
                      ['1985-12-31', 2964762.0],
                      ['1984-12-31', 2904429.0],
                      ['1983-12-31', 2843960.0],
                      ['1982-12-31', 2784278.0],
                      ['1981-12-31', 2726056.0],
                      ['1980-12-31', 2671997.0],
                      ['1979-12-31', 2617832.0],
                      ['1978-12-31', 2566266.0],
                      ['1977-12-31', 2513546.0],
                      ['1976-12-31', 2458526.0],
                      ['1975-12-31', 2404831.0],
                      ['1974-12-31', 2350124.0],
                      ['1973-12-31', 2296752.0],
                      ['1972-12-31', 2243126.0],
                      ['1971-12-31', 2187853.0],
                      ['1970-12-31', 2135479.0],
                      ['1969-12-31', 2081695.0],
                      ['1968-12-31', 2022272.0],
                      ['1967-12-31', 1965598.0],
                      ['1966-12-31', 1914573.0],
                      ['1965-12-31', 1864791.0],
                      ['1964-12-31', 1814135.0],
                      ['1963-12-31', 1762621.0],
                      ['1962-12-31', 1711319.0],
                      ['1961-12-31', 1659800.0],
                      ['1960-12-31', 1608800.0],
                      ['1959-12-31', 1561012.0],
                      ['1958-12-31', 1512765.0],
                      ['1957-12-31', 1466124.0],
                      ['1956-12-31', 1421417.0],
                      ['1955-12-31', 1378998.0],
                      ['1954-12-31', 1339240.0],
                      ['1953-12-31', 1302536.0],
                      ['1952-12-31', 1269302.0],
                      ['1951-12-31', 1239971.0],
                      ['1950-12-31', 1215002.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'ALB_SP_POP_TOTL',
             'description': 'Population, total - Albania. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22084258,
             'limit': None,
             'name': 'Population, total - Albania',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:26:17.205Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
DZA

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 41318142.0],
                      ['2016-12-31', 40606052.0],
                      ['2015-12-31', 39871528.0],
                      ['2014-12-31', 39113313.0],
                      ['2013-12-31', 38338562.0],
                      ['2012-12-31', 37565847.0],
                      ['2011-12-31', 36819558.0],
                      ['2010-12-31', 36117637.0],
                      ['2009-12-31', 35465760.0],
                      ['2008-12-31', 34860715.0],
                      ['2007-12-31', 34300076.0],
                      ['2006-12-31', 33777915.0],
                      ['2005-12-31', 33288437.0],
                      ['2004-12-31', 32831096.0],
                      ['2003-12-31', 32403514.0],
                      ['2002-12-31', 31995046.0],
                      ['2001-12-31', 31592153.0],
                      ['2000-12-31', 31183660.0],
                      ['1999-12-31', 30765613.0],
                      ['1998-12-31', 30335732.0],
                      ['1997-12-31', 29886839.0],
                      ['1996-12-31', 29411415.0],
                      ['1995-12-31', 28904298.0],
                      ['1994-12-31', 28362253.0],
                      ['1993-12-31', 27786259.0],
                      ['1992-12-31', 27181094.0],
                      ['1991-12-31', 26554329.0],
                      ['1990-12-31', 25912367.0],
                      ['1989-12-31', 25257672.0],
                      ['1988-12-31', 24591492.0],
                      ['1987-12-31', 23917897.0],
                      ['1986-12-31', 23241272.0],
                      ['1985-12-31', 22565905.0],
                      ['1984-12-31', 21893853.0],
                      ['1983-12-31', 21228289.0],
                      ['1982-12-31', 20575701.0],
                      ['1981-12-31', 19943664.0],
                      ['1980-12-31', 19337715.0],
                      ['1979-12-31', 18760761.0],
                      ['1978-12-31', 18212326.0],
                      ['1977-12-31', 17690184.0],
                      ['1976-12-31', 17190239.0],
                      ['1975-12-31', 16709099.0],
                      ['1974-12-31', 16247113.0],
                      ['1973-12-31', 15804428.0],
                      ['1972-12-31', 15377093.0],
                      ['1971-12-31', 14960109.0],
                      ['1970-12-31', 14550034.0],
                      ['1969-12-31', 14144438.0],
                      ['1968-12-31', 13744387.0],
                      ['1967-12-31', 13354197.0],
                      ['1966-12-31', 12980267.0],
                      ['1965-12-31', 12626952.0],
                      ['1964-12-31', 12295970.0],
                      ['1963-12-31', 11985136.0],
                      ['1962-12-31', 11690153.0],
                      ['1961-12-31', 11404859.0],
                      ['1960-12-31', 11124888.0],
                      ['1959-12-31', 10848973.0],
                      ['1958-12-31', 10578449.0],
                      ['1957-12-31', 10316288.0],
                      ['1956-12-31', 10065822.0],
                      ['1955-12-31', 9829719.0],
                      ['1954-12-31', 9609505.0],
                      ['1953-12-31', 9405443.0],
                      ['1952-12-31', 9216397.0],
                      ['1951-12-31', 9039910.0],
                      ['1950-12-31', 8872247.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'DZA_SP_POP_TOTL',
             'description': 'Population, total - Algeria. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22123346,
             'limit': None,
             'name': 'Population, total - Algeria',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:30:57.323Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
ASM
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 55641.0],
                      ['2016-12-31', 55599.0],
                      ['2015-12-31', 55537.0],
                      ['2014-12-31', 55437.0],
                      ['2013-12-31', 55307.0],
                      ['2012-12-31', 55230.0],
                      ['2011-12-31', 55320.0],
                      ['2010-12-31', 55637.0],
                      ['2009-12-31', 56227.0],
                      ['2008-12-31', 57030.0],
                      ['2007-12-31', 57903.0],
                      ['2006-12-31', 58650.0],
                      ['2005-12-31', 59118.0],
                      ['2004-12-31', 59264.0],
                      ['2003-12-31', 59117.0],
                      ['2002-12-31', 58731.0],
                      ['2001-12-31', 58175.0],
                      ['2000-12-31', 57521.0],
                      ['1999-12-31', 56770.0],
                      ['1998-12-31', 55901.0],
                      ['1997-12-31', 54941.0],
                      ['1996-12-31', 53929.0],
                      ['1995-12-31', 52868.0],
                      ['1994-12-31', 51803.0],
                      ['1993-12-31', 50720.0],
                      ['1992-12-31', 49593.0],
                      ['1991-12-31', 48375.0],
                      ['1990-12-31', 47038.0],
                      ['1989-12-31', 45593.0],
                      ['1988-12-31', 44047.0],
                      ['1987-12-31', 42450.0],
                      ['1986-12-31', 40837.0],
                      ['1985-12-31', 39241.0],
                      ['1984-12-31', 37688.0],
                      ['1983-12-31', 36160.0],
                      ['1982-12-31', 34738.0],
                      ['1981-12-31', 33493.0],
                      ['1980-12-31', 32457.0],
                      ['1979-12-31', 31673.0],
                      ['1978-12-31', 31102.0],
                      ['1977-12-31', 30689.0],
                      ['1976-12-31', 30321.0],
                      ['1975-12-31', 29932.0],
                      ['1974-12-31', 29488.0],
                      ['1973-12-31', 29014.0],
                      ['1972-12-31', 28492.0],
                      ['1971-12-31', 27916.0],
                      ['1970-12-31', 27292.0],
                      ['1969-12-31', 26614.0],
                      ['1968-12-31', 25885.0],
                      ['1967-12-31', 25116.0],
                      ['1966-12-31', 24321.0],
                      ['1965-12-31', 23520.0],
                      ['1964-12-31', 22698.0],
                      ['1963-12-31', 21882.0],
                      ['1962-12-31', 21117.0],
                      ['1961-12-31', 20486.0],
                      ['1960-12-31', 20013.0],
                      ['1959-12-31', 19734.0],
                      ['1958-12-31', 19602.0],
                      ['1957-12-31', 19598.0],
                      ['1956-12-31', 19652.0],
                      ['1955-12-31', 19702.0],
                      ['1954-12-31', 19729.0],
                      ['1953-12-31', 19677.0],
                      ['1952-12-31', 19540.0],
                      ['1951-12-31', 19296.0],
                      ['1950-12-31', 18940.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'ASM_SP_POP_TOTL',
             'description': 'Population, total - American Samoa. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22091892,
             'limit': None,
             'name': 'Population, total - American Samoa',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:26:42.925Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
AND

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 76965.0],
                      ['2016-12-31', 77281.0],
                      ['2015-12-31', 78014.0],
                      ['2014-12-31', 79223.0],
                      ['2013-12-31', 80788.0],
                      ['2012-12-31', 82431.0],
                      ['2011-12-31', 83751.0],
                      ['2010-12-31', 84449.0],
                      ['2009-12-31', 84462.0],
                      ['2008-12-31', 83861.0],
                      ['2007-12-31', 82683.0],
                      ['2006-12-31', 80991.0],
                      ['2005-12-31', 78867.0],
                      ['2004-12-31', 76244.0],
                      ['2003-12-31', 73182.0],
                      ['2002-12-31', 70049.0],
                      ['2001-12-31', 67341.0],
                      ['2000-12-31', 65390.0],
                      ['1999-12-31', 64370.0],
                      ['1998-12-31', 64142.0],
                      ['1997-12-31', 64327.0],
                      ['1996-12-31', 64360.0],
                      ['1995-12-31', 63850.0],
                      ['1994-12-31', 62677.0],
                      ['1993-12-31', 60971.0],
                      ['1992-12-31', 58888.0],
                      ['1991-12-31', 56671.0],
                      ['1990-12-31', 54509.0],
                      ['1989-12-31', 52448.0],
                      ['1988-12-31', 50434.0],
                      ['1987-12-31', 48455.0],
                      ['1986-12-31', 46517.0],
                      ['1985-12-31', 44600.0],
                      ['1984-12-31', 42706.0],
                      ['1983-12-31', 40867.0],
                      ['1982-12-31', 39114.0],
                      ['1981-12-31', 37500.0],
                      ['1980-12-31', 36067.0],
                      ['1979-12-31', 34818.0],
                      ['1978-12-31', 33737.0],
                      ['1977-12-31', 32771.0],
                      ['1976-12-31', 31777.0],
                      ['1975-12-31', 30705.0],
                      ['1974-12-31', 29520.0],
                      ['1973-12-31', 28232.0],
                      ['1972-12-31', 26892.0],
                      ['1971-12-31', 25559.0],
                      ['1970-12-31', 24276.0],
                      ['1969-12-31', 23058.0],
                      ['1968-12-31', 21890.0],
                      ['1967-12-31', 20758.0],
                      ['1966-12-31', 19647.0],
                      ['1965-12-31', 18549.0],
                      ['1964-12-31', 17469.0],
                      ['1963-12-31', 16412.0],
                      ['1962-12-31', 15370.0],
                      ['1961-12-31', 14375.0],
                      ['1960-12-31', 13411.0],
                      ['1959-12-31', 12498.0],
                      ['1958-12-31', 11615.0],
                      ['1957-12-31', 10779.0],
                      ['1956-12-31', 9989.0],
                      ['1955-12-31', 9232.0],
                      ['1954-12-31', 8525.0],
                      ['1953-12-31', 7865.0],
                      ['1952-12-31', 7247.0],
                      ['1951-12-31', 6689.0],
                      ['1950-12-31', 6196.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'AND_SP_POP_TOTL',
             'description': 'Population, total - Andorra. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22084988,
             'limit': None,
             'name': 'Population, total - Andorra',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:26:19.778Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
AGO
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 29784193.0],
                      ['2016-12-31', 28813463.0],
                      ['2015-12-31', 27859305.0],
                      ['2014-12-31', 26920466.0],
                      ['2013-12-31', 25998340.0],
                      ['2012-12-31', 25096150.0],
                      ['2011-12-31', 24218565.0],
                      ['2010-12-31', 23369131.0],
                      ['2009-12-31', 22549547.0],
                      ['2008-12-31', 21759420.0],
                      ['2007-12-31', 20997687.0],
                      ['2006-12-31', 20262399.0],
                      ['2005-12-31', 19552542.0],
                      ['2004-12-31', 18865716.0],
                      ['2003-12-31', 18203369.0],
                      ['2002-12-31', 17572649.0],
                      ['2001-12-31', 16983266.0],
                      ['2000-12-31', 16440924.0],
                      ['1999-12-31', 15949766.0],
                      ['1998-12-31', 15504318.0],
                      ['1997-12-31', 15088981.0],
                      ['1996-12-31', 14682284.0],
                      ['1995-12-31', 14268994.0],
                      ['1994-12-31', 13841301.0],
                      ['1993-12-31', 13403734.0],
                      ['1992-12-31', 12968345.0],
                      ['1991-12-31', 12553446.0],
                      ['1990-12-31', 12171441.0],
                      ['1989-12-31', 11827237.0],
                      ['1988-12-31', 11513968.0],
                      ['1987-12-31', 11218268.0],
                      ['1986-12-31', 10921037.0],
                      ['1985-12-31', 10609042.0],
                      ['1984-12-31', 10277321.0],
                      ['1983-12-31', 9931562.0],
                      ['1982-12-31', 9582156.0],
                      ['1981-12-31', 9244507.0],
                      ['1980-12-31', 8929900.0],
                      ['1979-12-31', 8641521.0],
                      ['1978-12-31', 8376147.0],
                      ['1977-12-31', 8130988.0],
                      ['1976-12-31', 7900997.0],
                      ['1975-12-31', 7682479.0],
                      ['1974-12-31', 7474338.0],
                      ['1973-12-31', 7277960.0],
                      ['1972-12-31', 7094834.0],
                      ['1971-12-31', 6927269.0],
                      ['1970-12-31', 6776381.0],
                      ['1969-12-31', 6642632.0],
                      ['1968-12-31', 6523791.0],
                      ['1967-12-31', 6414995.0],
                      ['1966-12-31', 6309770.0],
                      ['1965-12-31', 6203299.0],
                      ['1964-12-31', 6093321.0],
                      ['1963-12-31', 5980417.0],
                      ['1962-12-31', 5866061.0],
                      ['1961-12-31', 5753024.0],
                      ['1960-12-31', 5643182.0],
                      ['1959-12-31', 5536779.0],
                      ['1958-12-31', 5432717.0],
                      ['1957-12-31', 5329099.0],
                      ['1956-12-31', 5224003.0],
                      ['1955-12-31', 5116071.0],
                      ['1954-12-31', 5004763.0],
                      ['1953-12-31', 4890469.0],
                      ['1952-12-31', 4774561.0],
                      ['1951-12-31', 4659333.0],
                      ['1950-12-31', 4548023.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'AGO_SP_POP_TOTL',
             'description': 'Population, total - Angola. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22082813,
             'limit': None,
             'name': 'Population, total - Angola',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:26:10.706Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
ATG
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 102012.0],
                      ['2016-12-31', 100963.0],
                      ['2015-12-31', 99923.0],
                      ['2014-12-31', 98875.0],
                      ['2013-12-31', 97824.0],
                      ['2012-12-31', 96777.0],
                      ['2011-12-31', 95719.0],
                      ['2010-12-31', 94661.0],
                      ['2009-12-31', 93581.0],
                      ['2008-12-31', 92478.0],
                      ['2007-12-31', 91381.0],
                      ['2006-12-31', 90301.0],
                      ['2005-12-31', 89253.0],
                      ['2004-12-31', 88257.0],
                      ['2003-12-31', 87293.0],
                      ['2002-12-31', 86266.0],
                      ['2001-12-31', 85057.0],
                      ['2000-12-31', 83584.0],
                      ['1999-12-31', 81831.0],
                      ['1998-12-31', 79851.0],
                      ['1997-12-31', 77739.0],
                      ['1996-12-31', 75628.0],
                      ['1995-12-31', 73619.0],
                      ['1994-12-31', 71719.0],
                      ['1993-12-31', 69938.0],
                      ['1992-12-31', 68427.0],
                      ['1991-12-31', 67307.0],
                      ['1990-12-31', 66696.0],
                      ['1989-12-31', 66627.0],
                      ['1988-12-31', 67058.0],
                      ['1987-12-31', 67845.0],
                      ['1986-12-31', 68809.0],
                      ['1985-12-31', 69782.0],
                      ['1984-12-31', 70725.0],
                      ['1983-12-31', 71639.0],
                      ['1982-12-31', 72448.0],
                      ['1981-12-31', 73066.0],
                      ['1980-12-31', 73442.0],
                      ['1979-12-31', 73528.0],
                      ['1978-12-31', 73324.0],
                      ['1977-12-31', 72875.0],
                      ['1976-12-31', 72285.0],
                      ['1975-12-31', 71609.0],
                      ['1974-12-31', 70878.0],
                      ['1973-12-31', 70066.0],
                      ['1972-12-31', 69176.0],
                      ['1971-12-31', 68188.0],
                      ['1970-12-31', 67098.0],
                      ['1969-12-31', 65910.0],
                      ['1968-12-31', 64655.0],
                      ['1967-12-31', 63360.0],
                      ['1966-12-31', 62059.0],
                      ['1965-12-31', 60781.0],
                      ['1964-12-31', 59524.0],
                      ['1963-12-31', 58294.0],
                      ['1962-12-31', 57144.0],
                      ['1961-12-31', 56144.0],
                      ['1960-12-31', 55339.0],
                      ['1959-12-31', 54722.0],
                      ['1958-12-31', 54241.0],
                      ['1957-12-31', 53838.0],
                      ['1956-12-31', 53420.0],
                      ['1955-12-31', 52897.0],
                      ['1954-12-31', 52208.0],
                      ['1953-12-31', 51262.0],
                      ['1952-12-31', 49999.0],
                      ['1951-12-31', 48365.0],
                      ['1950-12-31', 46303.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'ATG_SP_POP_TOTL',
             'description': 'Population, total - Antigua and Barbuda. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22092953,
             'limit': None,
             'name': 'Population, total - Antigua and Barbuda',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:26:45.775Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
ARB

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 414491886.0],
                      ['2016-12-31', 406452690.0],
                      ['2015-12-31', 398304960.0],
                      ['2014-12-31', 390043028.0],
                      ['2013-12-31', 381702086.0],
                      ['2012-12-31', 373306993.0],
                      ['2011-12-31', 364895878.0],
                      ['2010-12-31', 356508908.0],
                      ['2009-12-31', 348145094.0],
                      ['2008-12-31', 339825483.0],
                      ['2007-12-31', 331653797.0],
                      ['2006-12-31', 323773264.0],
                      ['2005-12-31', 316264728.0],
                      ['2004-12-31', 309162029.0],
                      ['2003-12-31', 302434519.0],
                      ['2002-12-31', 296026575.0],
                      ['2001-12-31', 289850357.0],
                      ['2000-12-31', 283832016.0],
                      ['1999-12-31', 277962869.0],
                      ['1998-12-31', 272235146.0],
                      ['1997-12-31', 266575075.0],
                      ['1996-12-31', 260843462.0],
                      ['1995-12-31', 255029671.0],
                      ['1994-12-31', 247435930.0],
                      ['1993-12-31', 241286091.0],
                      ['1992-12-31', 235037179.0],
                      ['1991-12-31', 230829868.0],
                      ['1990-12-31', 224735446.0],
                      ['1989-12-31', 216787402.0],
                      ['1988-12-31', 210844771.0],
                      ['1987-12-31', 204942549.0],
                      ['1986-12-31', 199093767.0],
                      ['1985-12-31', 193310301.0],
                      ['1984-12-31', 187610756.0],
                      ['1983-12-31', 182005827.0],
                      ['1982-12-31', 176490084.0],
                      ['1981-12-31', 171051950.0],
                      ['1980-12-31', 165689490.0],
                      ['1979-12-31', 160392488.0],
                      ['1978-12-31', 155183724.0],
                      ['1977-12-31', 150133054.0],
                      ['1976-12-31', 145332378.0],
                      ['1975-12-31', 140843298.0],
                      ['1974-12-31', 136696761.0],
                      ['1973-12-31', 132863416.0],
                      ['1972-12-31', 129269375.0],
                      ['1971-12-31', 125807419.0],
                      ['1970-12-31', 122398374.0],
                      ['1969-12-31', 119016542.0],
                      ['1968-12-31', 115680165.0],
                      ['1967-12-31', 112406932.0],
                      ['1966-12-31', 109230593.0],
                      ['1965-12-31', 106174988.0],
                      ['1964-12-31', 103239902.0],
                      ['1963-12-31', 100411076.0],
                      ['1962-12-31', 97682294.0],
                      ['1961-12-31', 95044497.0],
                      ['1960-12-31', 92490932.0],
                      ['1959-12-31', 90018422.0],
                      ['1958-12-31', 87627077.0],
                      ['1957-12-31', 85318898.0],
                      ['1956-12-31', 83096049.0],
                      ['1955-12-31', 80959463.0],
                      ['1954-12-31', 78908442.0],
                      ['1953-12-31', 76940169.0],
                      ['1952-12-31', 75049780.0],
                      ['1951-12-31', 73230347.0],
                      ['1950-12-31', 71473047.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'ARB_SP_POP_TOTL',
             'description': 'Population, total - Arab World. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22086114,
             'limit': None,
             'name': 'Population, total - Arab World',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:26:23.654Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
ARG
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 44271041.0],
                      ['2016-12-31', 43847430.0],
                      ['2015-12-31', 43417765.0],
                      ['2014-12-31', 42981515.0],
                      ['2013-12-31', 42539925.0],
                      ['2012-12-31', 42096739.0],
                      ['2011-12-31', 41656879.0],
                      ['2010-12-31', 41223889.0],
                      ['2009-12-31', 40799407.0],
                      ['2008-12-31', 40382389.0],
                      ['2007-12-31', 39970224.0],
                      ['2006-12-31', 39558890.0],
                      ['2005-12-31', 39145488.0],
                      ['2004-12-31', 38728696.0],
                      ['2003-12-31', 38309379.0],
                      ['2002-12-31', 37889370.0],
                      ['2001-12-31', 37471509.0],
                      ['2000-12-31', 37057452.0],
                      ['1999-12-31', 36648068.0],
                      ['1998-12-31', 36241590.0],
                      ['1997-12-31', 35833969.0],
                      ['1996-12-31', 35419682.0],
                      ['1995-12-31', 34994814.0],
                      ['1994-12-31', 34558115.0],
                      ['1993-12-31', 34110917.0],
                      ['1992-12-31', 33655151.0],
                      ['1991-12-31', 33193918.0],
                      ['1990-12-31', 32729739.0],
                      ['1989-12-31', 32263561.0],
                      ['1988-12-31', 31795517.0],
                      ['1987-12-31', 31326473.0],
                      ['1986-12-31', 30857244.0],
                      ['1985-12-31', 30388783.0],
                      ['1984-12-31', 29920904.0],
                      ['1983-12-31', 29454738.0],
                      ['1982-12-31', 28993987.0],
                      ['1981-12-31', 28543364.0],
                      ['1980-12-31', 28105888.0],
                      ['1979-12-31', 27684534.0],
                      ['1978-12-31', 27277741.0],
                      ['1977-12-31', 26878565.0],
                      ['1976-12-31', 26477152.0],
                      ['1975-12-31', 26066975.0],
                      ['1974-12-31', 25644506.0],
                      ['1973-12-31', 25213388.0],
                      ['1972-12-31', 24782949.0],
                      ['1971-12-31', 24366439.0],
                      ['1970-12-31', 23973058.0],
                      ['1969-12-31', 23605987.0],
                      ['1968-12-31', 23261278.0],
                      ['1967-12-31', 22932203.0],
                      ['1966-12-31', 22608748.0],
                      ['1965-12-31', 22283390.0],
                      ['1964-12-31', 21953929.0],
                      ['1963-12-31', 21621840.0],
                      ['1962-12-31', 21287682.0],
                      ['1961-12-31', 20953077.0],
                      ['1960-12-31', 20619075.0],
                      ['1959-12-31', 20285531.0],
                      ['1958-12-31', 19951323.0],
                      ['1957-12-31', 19614847.0],
                      ['1956-12-31', 19274528.0],
                      ['1955-12-31', 18929346.0],
                      ['1954-12-31', 18579037.0],
                      ['1953-12-31', 18224150.0],
                      ['1952-12-31', 17866096.0],
                      ['1951-12-31', 17507130.0],
                      ['1950-12-31', 17150336.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'ARG_SP_POP_TOTL',
             'description': 'Population, total - Argentina. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22089259,
             'limit': None,
             'name': 'Population, total - Argentina',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:26:34.003Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
ARM

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 2930450.0],
                      ['2016-12-31', 2924816.0],
                      ['2015-12-31', 2916950.0],
                      ['2014-12-31', 2906220.0],
                      ['2013-12-31', 2893509.0],
                      ['2012-12-31', 2881922.0],
                      ['2011-12-31', 2875581.0],
                      ['2010-12-31', 2877311.0],
                      ['2009-12-31', 2888584.0],
                      ['2008-12-31', 2908220.0],
                      ['2007-12-31', 2933056.0],
                      ['2006-12-31', 2958500.0],
                      ['2005-12-31', 2981259.0],
                      ['2004-12-31', 3000612.0],
                      ['2003-12-31', 3017806.0],
                      ['2002-12-31', 3033897.0],
                      ['2001-12-31', 3050655.0],
                      ['2000-12-31', 3069588.0],
                      ['1999-12-31', 3089017.0],
                      ['1998-12-31', 3108684.0],
                      ['1997-12-31', 3133086.0],
                      ['1996-12-31', 3168215.0],
                      ['1995-12-31', 3217342.0],
                      ['1994-12-31', 3283660.0],
                      ['1993-12-31', 3363098.0],
                      ['1992-12-31', 3442810.0],
                      ['1991-12-31', 3505251.0],
                      ['1990-12-31', 3538165.0],
                      ['1989-12-31', 3536469.0],
                      ['1988-12-31', 3504651.0],
                      ['1987-12-31', 3451942.0],
                      ['1986-12-31', 3392256.0],
                      ['1985-12-31', 3335935.0],
                      ['1984-12-31', 3285595.0],
                      ['1983-12-31', 3238594.0],
                      ['1982-12-31', 3193686.0],
                      ['1981-12-31', 3148092.0],
                      ['1980-12-31', 3099751.0],
                      ['1979-12-31', 3049105.0],
                      ['1978-12-31', 2997411.0],
                      ['1977-12-31', 2944379.0],
                      ['1976-12-31', 2889579.0],
                      ['1975-12-31', 2832757.0],
                      ['1974-12-31', 2773747.0],
                      ['1973-12-31', 2712781.0],
                      ['1972-12-31', 2650484.0],
                      ['1971-12-31', 2587706.0],
                      ['1970-12-31', 2525065.0],
                      ['1969-12-31', 2462925.0],
                      ['1968-12-31', 2401140.0],
                      ['1967-12-31', 2339124.0],
                      ['1966-12-31', 2276031.0],
                      ['1965-12-31', 2211316.0],
                      ['1964-12-31', 2144998.0],
                      ['1963-12-31', 2077575.0],
                      ['1962-12-31', 2009526.0],
                      ['1961-12-31', 1941491.0],
                      ['1960-12-31', 1874120.0],
                      ['1959-12-31', 1807917.0],
                      ['1958-12-31', 1743303.0],
                      ['1957-12-31', 1680714.0],
                      ['1956-12-31', 1620593.0],
                      ['1955-12-31', 1563505.0],
                      ['1954-12-31', 1510171.0],
                      ['1953-12-31', 1461424.0],
                      ['1952-12-31', 1418276.0],
                      ['1951-12-31', 1381872.0],
                      ['1950-12-31', 1353510.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'ARM_SP_POP_TOTL',
             'description': 'Population, total - Armenia. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22091195,
             'limit': None,
             'name': 'Population, total - Armenia',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:26:40.388Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
ABW
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 105264.0],
                      ['2016-12-31', 104822.0],
                      ['2015-12-31', 104341.0],
                      ['2014-12-31', 103795.0],
                      ['2013-12-31', 103187.0],
                      ['2012-12-31', 102577.0],
                      ['2011-12-31', 102053.0],
                      ['2010-12-31', 101669.0],
                      ['2009-12-31', 101453.0],
                      ['2008-12-31', 101353.0],
                      ['2007-12-31', 101220.0],
                      ['2006-12-31', 100832.0],
                      ['2005-12-31', 100031.0],
                      ['2004-12-31', 98737.0],
                      ['2003-12-31', 97017.0],
                      ['2002-12-31', 94992.0],
                      ['2001-12-31', 92898.0],
                      ['2000-12-31', 90853.0],
                      ['1999-12-31', 89005.0],
                      ['1998-12-31', 87277.0],
                      ['1997-12-31', 85451.0],
                      ['1996-12-31', 83200.0],
                      ['1995-12-31', 80324.0],
                      ['1994-12-31', 76700.0],
                      ['1993-12-31', 72504.0],
                      ['1992-12-31', 68235.0],
                      ['1991-12-31', 64622.0],
                      ['1990-12-31', 62149.0],
                      ['1989-12-31', 61032.0],
                      ['1988-12-31', 61079.0],
                      ['1987-12-31', 61833.0],
                      ['1986-12-31', 62644.0],
                      ['1985-12-31', 63026.0],
                      ['1984-12-31', 62836.0],
                      ['1983-12-31', 62201.0],
                      ['1982-12-31', 61345.0],
                      ['1981-12-31', 60567.0],
                      ['1980-12-31', 60096.0],
                      ['1979-12-31', 59980.0],
                      ['1978-12-31', 60103.0],
                      ['1977-12-31', 60366.0],
                      ['1976-12-31', 60586.0],
                      ['1975-12-31', 60657.0],
                      ['1974-12-31', 60528.0],
                      ['1973-12-31', 60243.0],
                      ['1972-12-31', 59840.0],
                      ['1971-12-31', 59440.0],
                      ['1970-12-31', 59063.0],
                      ['1969-12-31', 58726.0],
                      ['1968-12-31', 58386.0],
                      ['1967-12-31', 58055.0],
                      ['1966-12-31', 57715.0],
                      ['1965-12-31', 57360.0],
                      ['1964-12-31', 57032.0],
                      ['1963-12-31', 56695.0],
                      ['1962-12-31', 56225.0],
                      ['1961-12-31', 55438.0],
                      ['1960-12-31', 54211.0],
                      ['1959-12-31', 52531.0],
                      ['1958-12-31', 50497.0],
                      ['1957-12-31', 48241.0],
                      ['1956-12-31', 45933.0],
                      ['1955-12-31', 43724.0],
                      ['1954-12-31', 41760.0],
                      ['1953-12-31', 40148.0],
                      ['1952-12-31', 38964.0],
                      ['1951-12-31', 38267.0],
                      ['1950-12-31', 38068.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'ABW_SP_POP_TOTL',
             'description': 'Population, total - Aruba. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22081204,
             'limit': None,
             'name': 'Population, total - Aruba',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:25:58.458Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
AUS
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 24598933.0],
                      ['2016-12-31', 24210809.0],
                      ['2015-12-31', 23850784.0],
                      ['2014-12-31', 23504138.0],
                      ['2013-12-31', 23145901.0],
                      ['2012-12-31', 22742475.0],
                      ['2011-12-31', 22340024.0],
                      ['2010-12-31', 22031750.0],
                      ['2009-12-31', 21691700.0],
                      ['2008-12-31', 21249200.0],
                      ['2007-12-31', 20827600.0],
                      ['2006-12-31', 20697900.0],
                      ['2005-12-31', 20394800.0],
                      ['2004-12-31', 20127400.0],
                      ['2003-12-31', 19895400.0],
                      ['2002-12-31', 19651400.0],
                      ['2001-12-31', 19413000.0],
                      ['2000-12-31', 19153000.0],
                      ['1999-12-31', 18926000.0],
                      ['1998-12-31', 18711000.0],
                      ['1997-12-31', 18517000.0],
                      ['1996-12-31', 18311000.0],
                      ['1995-12-31', 18072000.0],
                      ['1994-12-31', 17855000.0],
                      ['1993-12-31', 17667000.0],
                      ['1992-12-31', 17495000.0],
                      ['1991-12-31', 17284000.0],
                      ['1990-12-31', 17065100.0],
                      ['1989-12-31', 16814400.0],
                      ['1988-12-31', 16532200.0],
                      ['1987-12-31', 16263900.0],
                      ['1986-12-31', 16018400.0],
                      ['1985-12-31', 15758000.0],
                      ['1984-12-31', 15544000.0],
                      ['1983-12-31', 15369000.0],
                      ['1982-12-31', 15178000.0],
                      ['1981-12-31', 14927000.0],
                      ['1980-12-31', 14692000.0],
                      ['1979-12-31', 14514000.0],
                      ['1978-12-31', 14358000.0],
                      ['1977-12-31', 14192000.0],
                      ['1976-12-31', 14033000.0],
                      ['1975-12-31', 13893000.0],
                      ['1974-12-31', 13723000.0],
                      ['1973-12-31', 13380000.0],
                      ['1972-12-31', 13177000.0],
                      ['1971-12-31', 12937000.0],
                      ['1970-12-31', 12507000.0],
                      ['1969-12-31', 12263000.0],
                      ['1968-12-31', 12009000.0],
                      ['1967-12-31', 11799000.0],
                      ['1966-12-31', 11651000.0],
                      ['1965-12-31', 11388000.0],
                      ['1964-12-31', 11167000.0],
                      ['1963-12-31', 10950000.0],
                      ['1962-12-31', 10742000.0],
                      ['1961-12-31', 10483000.0],
                      ['1960-12-31', 10276477.0],
                      ['1959-12-31', 10046139.0],
                      ['1958-12-31', 9824580.0],
                      ['1957-12-31', 9610800.0],
                      ['1956-12-31', 9403377.0],
                      ['1955-12-31', 9200846.0],
                      ['1954-12-31', 9001822.0],
                      ['1953-12-31', 8805083.0],
                      ['1952-12-31', 8609591.0],
                      ['1951-12-31', 8414469.0],
                      ['1950-12-31', 8218997.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'AUS_SP_POP_TOTL',
             'description': 'Population, total - Australia. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22094555,
             'limit': None,
             'name': 'Population, total - Australia',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:26:50.664Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
AUT

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 8809212.0],
                      ['2016-12-31', 8736668.0],
                      ['2015-12-31', 8642699.0],
                      ['2014-12-31', 8546356.0],
                      ['2013-12-31', 8479823.0],
                      ['2012-12-31', 8429991.0],
                      ['2011-12-31', 8391643.0],
                      ['2010-12-31', 8363404.0],
                      ['2009-12-31', 8343323.0],
                      ['2008-12-31', 8321496.0],
                      ['2007-12-31', 8295487.0],
                      ['2006-12-31', 8268641.0],
                      ['2005-12-31', 8227829.0],
                      ['2004-12-31', 8171966.0],
                      ['2003-12-31', 8121423.0],
                      ['2002-12-31', 8081957.0],
                      ['2001-12-31', 8042293.0],
                      ['2000-12-31', 8011566.0],
                      ['1999-12-31', 7992324.0],
                      ['1998-12-31', 7976789.0],
                      ['1997-12-31', 7968041.0],
                      ['1996-12-31', 7959017.0],
                      ['1995-12-31', 7948278.0],
                      ['1994-12-31', 7936118.0],
                      ['1993-12-31', 7905633.0],
                      ['1992-12-31', 7840709.0],
                      ['1991-12-31', 7754891.0],
                      ['1990-12-31', 7677850.0],
                      ['1989-12-31', 7619567.0],
                      ['1988-12-31', 7585317.0],
                      ['1987-12-31', 7574586.0],
                      ['1986-12-31', 7569794.0],
                      ['1985-12-31', 7564985.0],
                      ['1984-12-31', 7561434.0],
                      ['1983-12-31', 7561910.0],
                      ['1982-12-31', 7574140.0],
                      ['1981-12-31', 7568710.0],
                      ['1980-12-31', 7549433.0],
                      ['1979-12-31', 7549425.0],
                      ['1978-12-31', 7562305.0],
                      ['1977-12-31', 7568430.0],
                      ['1976-12-31', 7565525.0],
                      ['1975-12-31', 7578903.0],
                      ['1974-12-31', 7599038.0],
                      ['1973-12-31', 7586115.0],
                      ['1972-12-31', 7544201.0],
                      ['1971-12-31', 7500482.0],
                      ['1970-12-31', 7467086.0],
                      ['1969-12-31', 7441055.0],
                      ['1968-12-31', 7415403.0],
                      ['1967-12-31', 7376998.0],
                      ['1966-12-31', 7322066.0],
                      ['1965-12-31', 7270889.0],
                      ['1964-12-31', 7223801.0],
                      ['1963-12-31', 7175811.0],
                      ['1962-12-31', 7129864.0],
                      ['1961-12-31', 7086299.0],
                      ['1960-12-31', 7047539.0],
                      ['1959-12-31', 7011632.0],
                      ['1958-12-31', 6987299.0],
                      ['1957-12-31', 6968701.0],
                      ['1956-12-31', 6954658.0],
                      ['1955-12-31', 6944174.0],
                      ['1954-12-31', 6936580.0],
                      ['1953-12-31', 6931618.0],
                      ['1952-12-31', 6929474.0],
                      ['1951-12-31', 6930746.0],
                      ['1950-12-31', 6936445.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'AUT_SP_POP_TOTL',
             'description': 'Population, total - Austria. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22096230,
             'limit': None,
             'name': 'Population, total - Austria',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:26:55.585Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
AZE
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 9862429.0],
                      ['2016-12-31', 9757812.0],
                      ['2015-12-31', 9649341.0],
                      ['2014-12-31', 9535079.0],
                      ['2013-12-31', 9416801.0],
                      ['2012-12-31', 9295784.0],
                      ['2011-12-31', 9173082.0],
                      ['2010-12-31', 9054332.0],
                      ['2009-12-31', 8947243.0],
                      ['2008-12-31', 8763400.0],
                      ['2007-12-31', 8581300.0],
                      ['2006-12-31', 8484550.0],
                      ['2005-12-31', 8391850.0],
                      ['2004-12-31', 8306500.0],
                      ['2003-12-31', 8234100.0],
                      ['2002-12-31', 8171950.0],
                      ['2001-12-31', 8111200.0],
                      ['2000-12-31', 8048600.0],
                      ['1999-12-31', 7982750.0],
                      ['1998-12-31', 7913000.0],
                      ['1997-12-31', 7838250.0],
                      ['1996-12-31', 7763000.0],
                      ['1995-12-31', 7685000.0],
                      ['1994-12-31', 7597000.0],
                      ['1993-12-31', 7495000.0],
                      ['1992-12-31', 7382000.0],
                      ['1991-12-31', 7271000.0],
                      ['1990-12-31', 7159000.0],
                      ['1989-12-31', 7126891.0],
                      ['1988-12-31', 7010036.0],
                      ['1987-12-31', 6893500.0],
                      ['1986-12-31', 6778633.0],
                      ['1985-12-31', 6666455.0],
                      ['1984-12-31', 6557585.0],
                      ['1983-12-31', 6452076.0],
                      ['1982-12-31', 6349558.0],
                      ['1981-12-31', 6249320.0],
                      ['1980-12-31', 6150738.0],
                      ['1979-12-31', 6053645.0],
                      ['1978-12-31', 5957929.0],
                      ['1977-12-31', 5863134.0],
                      ['1976-12-31', 5768724.0],
                      ['1975-12-31', 5674137.0],
                      ['1974-12-31', 5579077.0],
                      ['1973-12-31', 5483084.0],
                      ['1972-12-31', 5385267.0],
                      ['1971-12-31', 5284532.0],
                      ['1970-12-31', 5180025.0],
                      ['1969-12-31', 5071930.0],
                      ['1968-12-31', 4960235.0],
                      ['1967-12-31', 4843870.0],
                      ['1966-12-31', 4721525.0],
                      ['1965-12-31', 4592610.0],
                      ['1964-12-31', 4456689.0],
                      ['1963-12-31', 4315128.0],
                      ['1962-12-31', 4171425.0],
                      ['1961-12-31', 4030320.0],
                      ['1960-12-31', 3895396.0],
                      ['1959-12-31', 3768331.0],
                      ['1958-12-31', 3649191.0],
                      ['1957-12-31', 3537027.0],
                      ['1956-12-31', 3430660.0],
                      ['1955-12-31', 3329387.0],
                      ['1954-12-31', 3233166.0],
                      ['1953-12-31', 3142813.0],
                      ['1952-12-31', 3060011.0],
                      ['1951-12-31', 2987267.0],
                      ['1950-12-31', 2927921.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'AZE_SP_POP_TOTL',
             'description': 'Population, total - Azerbaijan. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22098155,
             'limit': None,
             'name': 'Population, total - Azerbaijan',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:27:01.494Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
BHS

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 395361.0],
                      ['2016-12-31', 391232.0],
                      ['2015-12-31', 386838.0],
                      ['2014-12-31', 382169.0],
                      ['2013-12-31', 377240.0],
                      ['2012-12-31', 372039.0],
                      ['2011-12-31', 366568.0],
                      ['2010-12-31', 360832.0],
                      ['2009-12-31', 354856.0],
                      ['2008-12-31', 348676.0],
                      ['2007-12-31', 342328.0],
                      ['2006-12-31', 335830.0],
                      ['2005-12-31', 329249.0],
                      ['2004-12-31', 322526.0],
                      ['2003-12-31', 315746.0],
                      ['2002-12-31', 309157.0],
                      ['2001-12-31', 303135.0],
                      ['2000-12-31', 297890.0],
                      ['1999-12-31', 293572.0],
                      ['1998-12-31', 290060.0],
                      ['1997-12-31', 286970.0],
                      ['1996-12-31', 283790.0],
                      ['1995-12-31', 280150.0],
                      ['1994-12-31', 275895.0],
                      ['1993-12-31', 271165.0],
                      ['1992-12-31', 266134.0],
                      ['1991-12-31', 261116.0],
                      ['1990-12-31', 256336.0],
                      ['1989-12-31', 251849.0],
                      ['1988-12-31', 247579.0],
                      ['1987-12-31', 243393.0],
                      ['1986-12-31', 239131.0],
                      ['1985-12-31', 234687.0],
                      ['1984-12-31', 230015.0],
                      ['1983-12-31', 225187.0],
                      ['1982-12-31', 220275.0],
                      ['1981-12-31', 215396.0],
                      ['1980-12-31', 210661.0],
                      ['1979-12-31', 206032.0],
                      ['1978-12-31', 201513.0],
                      ['1977-12-31', 197111.0],
                      ['1976-12-31', 192902.0],
                      ['1975-12-31', 188882.0],
                      ['1974-12-31', 185099.0],
                      ['1973-12-31', 181488.0],
                      ['1972-12-31', 177839.0],
                      ['1971-12-31', 173863.0],
                      ['1970-12-31', 169354.0],
                      ['1969-12-31', 164248.0],
                      ['1968-12-31', 158627.0],
                      ['1967-12-31', 152609.0],
                      ['1966-12-31', 146366.0],
                      ['1965-12-31', 140054.0],
                      ['1964-12-31', 133698.0],
                      ['1963-12-31', 127333.0],
                      ['1962-12-31', 121083.0],
                      ['1961-12-31', 115108.0],
                      ['1960-12-31', 109528.0],
                      ['1959-12-31', 104405.0],
                      ['1958-12-31', 99769.0],
                      ['1957-12-31', 95603.0],
                      ['1956-12-31', 91897.0],
                      ['1955-12-31', 88617.0],
                      ['1954-12-31', 85773.0],
                      ['1953-12-31', 83371.0],
                      ['1952-12-31', 81426.0],
                      ['1951-12-31', 79985.0],
                      ['1950-12-31', 79085.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'BHS_SP_POP_TOTL',
             'description': 'Population, total - Bahamas, The. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22112596,
             'limit': None,
             'name': 'Population, total - Bahamas, The',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:27:48.401Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
BHR
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 1492584.0],
                      ['2016-12-31', 1425171.0],
                      ['2015-12-31', 1371855.0],
                      ['2014-12-31', 1336397.0],
                      ['2013-12-31', 1315411.0],
                      ['2012-12-31', 1300217.0],
                      ['2011-12-31', 1278269.0],
                      ['2010-12-31', 1240862.0],
                      ['2009-12-31', 1185029.0],
                      ['2008-12-31', 1114590.0],
                      ['2007-12-31', 1035891.0],
                      ['2006-12-31', 958414.0],
                      ['2005-12-31', 889168.0],
                      ['2004-12-31', 829848.0],
                      ['2003-12-31', 778711.0],
                      ['2002-12-31', 735148.0],
                      ['2001-12-31', 697549.0],
                      ['2000-12-31', 664614.0],
                      ['1999-12-31', 636545.0],
                      ['1998-12-31', 613702.0],
                      ['1997-12-31', 594930.0],
                      ['1996-12-31', 578668.0],
                      ['1995-12-31', 563699.0],
                      ['1994-12-31', 549588.0],
                      ['1993-12-31', 536213.0],
                      ['1992-12-31', 523087.0],
                      ['1991-12-31', 509765.0],
                      ['1990-12-31', 495931.0],
                      ['1989-12-31', 481090.0],
                      ['1988-12-31', 465202.0],
                      ['1987-12-31', 448973.0],
                      ['1986-12-31', 433482.0],
                      ['1985-12-31', 419430.0],
                      ['1984-12-31', 407227.0],
                      ['1983-12-31', 396454.0],
                      ['1982-12-31', 385950.0],
                      ['1981-12-31', 374120.0],
                      ['1980-12-31', 359888.0],
                      ['1979-12-31', 342798.0],
                      ['1978-12-31', 323473.0],
                      ['1977-12-31', 303175.0],
                      ['1976-12-31', 283752.0],
                      ['1975-12-31', 266543.0],
                      ['1974-12-31', 251911.0],
                      ['1973-12-31', 239527.0],
                      ['1972-12-31', 229155.0],
                      ['1971-12-31', 220312.0],
                      ['1970-12-31', 212605.0],
                      ['1969-12-31', 206043.0],
                      ['1968-12-31', 200653.0],
                      ['1967-12-31', 196063.0],
                      ['1966-12-31', 191780.0],
                      ['1965-12-31', 187431.0],
                      ['1964-12-31', 182887.0],
                      ['1963-12-31', 178140.0],
                      ['1962-12-31', 173144.0],
                      ['1961-12-31', 167894.0],
                      ['1960-12-31', 162427.0],
                      ['1959-12-31', 156777.0],
                      ['1958-12-31', 150982.0],
                      ['1957-12-31', 145109.0],
                      ['1956-12-31', 139268.0],
                      ['1955-12-31', 133585.0],
                      ['1954-12-31', 128253.0],
                      ['1953-12-31', 123489.0],
                      ['1952-12-31', 119586.0],
                      ['1951-12-31', 116832.0],
                      ['1950-12-31', 115611.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'BHR_SP_POP_TOTL',
             'description': 'Population, total - Bahrain. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22111089,
             'limit': None,
             'name': 'Population, total - Bahrain',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:27:43.481Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
BGD
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 164669751.0],
                      ['2016-12-31', 162951560.0],
                      ['2015-12-31', 161200886.0],
                      ['2014-12-31', 159405279.0],
                      ['2013-12-31', 157571292.0],
                      ['2012-12-31', 155727053.0],
                      ['2011-12-31', 153911916.0],
                      ['2010-12-31', 152149102.0],
                      ['2009-12-31', 150454708.0],
                      ['2008-12-31', 148805814.0],
                      ['2007-12-31', 147139191.0],
                      ['2006-12-31', 145368004.0],
                      ['2005-12-31', 143431101.0],
                      ['2004-12-31', 141307489.0],
                      ['2003-12-31', 139019001.0],
                      ['2002-12-31', 136600667.0],
                      ['2001-12-31', 134107160.0],
                      ['2000-12-31', 131581243.0],
                      ['1999-12-31', 129029691.0],
                      ['1998-12-31', 126447965.0],
                      ['1997-12-31', 123854640.0],
                      ['1996-12-31', 121269645.0],
                      ['1995-12-31', 118706871.0],
                      ['1994-12-31', 116182267.0],
                      ['1993-12-31', 113695139.0],
                      ['1992-12-31', 111221938.0],
                      ['1991-12-31', 108727432.0],
                      ['1990-12-31', 106188642.0],
                      ['1989-12-31', 103599232.0],
                      ['1988-12-31', 100975321.0],
                      ['1987-12-31', 98343809.0],
                      ['1986-12-31', 95742431.0],
                      ['1985-12-31', 93199865.0],
                      ['1984-12-31', 90732362.0],
                      ['1983-12-31', 88338242.0],
                      ['1982-12-31', 86007331.0],
                      ['1981-12-31', 83721268.0],
                      ['1980-12-31', 81470860.0],
                      ['1979-12-31', 79236776.0],
                      ['1978-12-31', 77033846.0],
                      ['1977-12-31', 74925896.0],
                      ['1976-12-31', 72999136.0],
                      ['1975-12-31', 71305923.0],
                      ['1974-12-31', 69884420.0],
                      ['1973-12-31', 68691185.0],
                      ['1972-12-31', 67597470.0],
                      ['1971-12-31', 66424744.0],
                      ['1970-12-31', 65047770.0],
                      ['1969-12-31', 63417394.0],
                      ['1968-12-31', 61579473.0],
                      ['1967-12-31', 59620669.0],
                      ['1966-12-31', 57672990.0],
                      ['1965-12-31', 55834038.0],
                      ['1964-12-31', 54129100.0],
                      ['1963-12-31', 52532417.0],
                      ['1962-12-31', 51030137.0],
                      ['1961-12-31', 49592802.0],
                      ['1960-12-31', 48199747.0],
                      ['1959-12-31', 46847445.0],
                      ['1958-12-31', 45546484.0],
                      ['1957-12-31', 44314819.0],
                      ['1956-12-31', 43169927.0],
                      ['1955-12-31', 42121524.0],
                      ['1954-12-31', 41169065.0],
                      ['1953-12-31', 40300362.0],
                      ['1952-12-31', 39491056.0],
                      ['1951-12-31', 38705076.0],
                      ['1950-12-31', 37894681.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'BGD_SP_POP_TOTL',
             'description': 'Population, total - Bangladesh. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22107514,
             'limit': None,
             'name': 'Population, total - Bangladesh',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:27:32.405Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
BRB

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 285719.0],
                      ['2016-12-31', 284996.0],
                      ['2015-12-31', 284217.0],
                      ['2014-12-31', 283385.0],
                      ['2013-12-31', 282509.0],
                      ['2012-12-31', 281585.0],
                      ['2011-12-31', 280601.0],
                      ['2010-12-31', 279569.0],
                      ['2009-12-31', 278470.0],
                      ['2008-12-31', 277319.0],
                      ['2007-12-31', 276150.0],
                      ['2006-12-31', 275039.0],
                      ['2005-12-31', 274009.0],
                      ['2004-12-31', 273091.0],
                      ['2003-12-31', 272258.0],
                      ['2002-12-31', 271478.0],
                      ['2001-12-31', 270685.0],
                      ['2000-12-31', 269847.0],
                      ['1999-12-31', 268922.0],
                      ['1998-12-31', 267950.0],
                      ['1997-12-31', 266945.0],
                      ['1996-12-31', 265942.0],
                      ['1995-12-31', 264959.0],
                      ['1994-12-31', 264015.0],
                      ['1993-12-31', 263089.0],
                      ['1992-12-31', 262184.0],
                      ['1991-12-31', 261275.0],
                      ['1990-12-31', 260374.0],
                      ['1989-12-31', 259458.0],
                      ['1988-12-31', 258527.0],
                      ['1987-12-31', 257611.0],
                      ['1986-12-31', 256736.0],
                      ['1985-12-31', 255924.0],
                      ['1984-12-31', 255193.0],
                      ['1983-12-31', 254518.0],
                      ['1982-12-31', 253841.0],
                      ['1981-12-31', 253080.0],
                      ['1980-12-31', 252194.0],
                      ['1979-12-31', 251177.0],
                      ['1978-12-31', 250032.0],
                      ['1977-12-31', 248784.0],
                      ['1976-12-31', 247444.0],
                      ['1975-12-31', 246034.0],
                      ['1974-12-31', 244539.0],
                      ['1973-12-31', 242976.0],
                      ['1972-12-31', 241441.0],
                      ['1971-12-31', 240035.0],
                      ['1970-12-31', 238848.0],
                      ['1969-12-31', 237913.0],
                      ['1968-12-31', 237199.0],
                      ['1967-12-31', 236621.0],
                      ['1966-12-31', 236044.0],
                      ['1965-12-31', 235374.0],
                      ['1964-12-31', 234547.0],
                      ['1963-12-31', 233587.0],
                      ['1962-12-31', 232586.0],
                      ['1961-12-31', 231678.0],
                      ['1960-12-31', 230939.0],
                      ['1959-12-31', 230349.0],
                      ['1958-12-31', 229830.0],
                      ['1957-12-31', 229212.0],
                      ['1956-12-31', 228350.0],
                      ['1955-12-31', 227073.0],
                      ['1954-12-31', 225260.0],
                      ['1953-12-31', 222809.0],
                      ['1952-12-31', 219636.0],
                      ['1951-12-31', 215703.0],
                      ['1950-12-31', 210992.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'BRB_SP_POP_TOTL',
             'description': 'Population, total - Barbados. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22124450,
             'limit': None,
             'name': 'Population, total - Barbados',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:28:25.600Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
BLR
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 9507875.0],
                      ['2016-12-31', 9501534.0],
                      ['2015-12-31', 9489616.0],
                      ['2014-12-31', 9474511.0],
                      ['2013-12-31', 9465997.0],
                      ['2012-12-31', 9464495.0],
                      ['2011-12-31', 9473172.0],
                      ['2010-12-31', 9490583.0],
                      ['2009-12-31', 9506765.0],
                      ['2008-12-31', 9527985.0],
                      ['2007-12-31', 9560953.0],
                      ['2006-12-31', 9604924.0],
                      ['2005-12-31', 9663915.0],
                      ['2004-12-31', 9730146.0],
                      ['2003-12-31', 9796749.0],
                      ['2002-12-31', 9865548.0],
                      ['2001-12-31', 9928549.0],
                      ['2000-12-31', 9979610.0],
                      ['1999-12-31', 10026738.0],
                      ['1998-12-31', 10069000.0],
                      ['1997-12-31', 10117000.0],
                      ['1996-12-31', 10160000.0],
                      ['1995-12-31', 10194000.0],
                      ['1994-12-31', 10227000.0],
                      ['1993-12-31', 10239000.0],
                      ['1992-12-31', 10216000.0],
                      ['1991-12-31', 10194000.0],
                      ['1990-12-31', 10189000.0],
                      ['1989-12-31', 10170000.0],
                      ['1988-12-31', 10140000.0],
                      ['1987-12-31', 10111000.0],
                      ['1986-12-31', 10043000.0],
                      ['1985-12-31', 9975000.0],
                      ['1984-12-31', 9910000.0],
                      ['1983-12-31', 9843000.0],
                      ['1982-12-31', 9776000.0],
                      ['1981-12-31', 9710000.0],
                      ['1980-12-31', 9643000.0],
                      ['1979-12-31', 9584000.0],
                      ['1978-12-31', 9525000.0],
                      ['1977-12-31', 9463000.0],
                      ['1976-12-31', 9411000.0],
                      ['1975-12-31', 9367000.0],
                      ['1974-12-31', 9317584.0],
                      ['1973-12-31', 9257272.0],
                      ['1972-12-31', 9188968.0],
                      ['1971-12-31', 9115576.0],
                      ['1970-12-31', 9040000.0],
                      ['1969-12-31', 8960304.0],
                      ['1968-12-31', 8874552.0],
                      ['1967-12-31', 8785648.0],
                      ['1966-12-31', 8696496.0],
                      ['1965-12-31', 8610000.0],
                      ['1964-12-31', 8524224.0],
                      ['1963-12-31', 8437232.0],
                      ['1962-12-31', 8351928.0],
                      ['1961-12-31', 8271216.0],
                      ['1960-12-31', 8198000.0],
                      ['1959-12-31', 8118264.0],
                      ['1958-12-31', 8039303.0],
                      ['1957-12-31', 7961111.0],
                      ['1956-12-31', 7883679.0],
                      ['1955-12-31', 7807000.0],
                      ['1954-12-31', 7805199.0],
                      ['1953-12-31', 7803399.0],
                      ['1952-12-31', 7801599.0],
                      ['1951-12-31', 7799799.0],
                      ['1950-12-31', 7798000.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'BLR_SP_POP_TOTL',
             'description': 'Population, total - Belarus. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22116156,
             'limit': None,
             'name': 'Population, total - Belarus',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:27:59.539Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
BEL

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 11372068.0],
                      ['2016-12-31', 11331422.0],
                      ['2015-12-31', 11274196.0],
                      ['2014-12-31', 11209057.0],
                      ['2013-12-31', 11182817.0],
                      ['2012-12-31', 11128246.0],
                      ['2011-12-31', 11047744.0],
                      ['2010-12-31', 10895586.0],
                      ['2009-12-31', 10796493.0],
                      ['2008-12-31', 10709973.0],
                      ['2007-12-31', 10625700.0],
                      ['2006-12-31', 10547958.0],
                      ['2005-12-31', 10478617.0],
                      ['2004-12-31', 10421137.0],
                      ['2003-12-31', 10376133.0],
                      ['2002-12-31', 10332785.0],
                      ['2001-12-31', 10286570.0],
                      ['2000-12-31', 10251250.0],
                      ['1999-12-31', 10226419.0],
                      ['1998-12-31', 10203008.0],
                      ['1997-12-31', 10181245.0],
                      ['1996-12-31', 10156637.0],
                      ['1995-12-31', 10136811.0],
                      ['1994-12-31', 10115603.0],
                      ['1993-12-31', 10084475.0],
                      ['1992-12-31', 10045158.0],
                      ['1991-12-31', 10004486.0],
                      ['1990-12-31', 9967379.0],
                      ['1989-12-31', 9937697.0],
                      ['1988-12-31', 9901664.0],
                      ['1987-12-31', 9870234.0],
                      ['1986-12-31', 9861823.0],
                      ['1985-12-31', 9858308.0],
                      ['1984-12-31', 9855372.0],
                      ['1983-12-31', 9855520.0],
                      ['1982-12-31', 9856303.0],
                      ['1981-12-31', 9858982.0],
                      ['1980-12-31', 9859242.0],
                      ['1979-12-31', 9848382.0],
                      ['1978-12-31', 9839534.0],
                      ['1977-12-31', 9830358.0],
                      ['1976-12-31', 9818227.0],
                      ['1975-12-31', 9800700.0],
                      ['1974-12-31', 9772419.0],
                      ['1973-12-31', 9741720.0],
                      ['1972-12-31', 9711115.0],
                      ['1971-12-31', 9673162.0],
                      ['1970-12-31', 9655549.0],
                      ['1969-12-31', 9646032.0],
                      ['1968-12-31', 9618756.0],
                      ['1967-12-31', 9580991.0],
                      ['1966-12-31', 9527807.0],
                      ['1965-12-31', 9463667.0],
                      ['1964-12-31', 9378113.0],
                      ['1963-12-31', 9289770.0],
                      ['1962-12-31', 9220578.0],
                      ['1961-12-31', 9183948.0],
                      ['1960-12-31', 9153489.0],
                      ['1959-12-31', 9093483.0],
                      ['1958-12-31', 9035709.0],
                      ['1957-12-31', 8978760.0],
                      ['1956-12-31', 8922420.0],
                      ['1955-12-31', 8866744.0],
                      ['1954-12-31', 8812159.0],
                      ['1953-12-31', 8759521.0],
                      ['1952-12-31', 8710135.0],
                      ['1951-12-31', 8665736.0],
                      ['1950-12-31', 8628489.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'BEL_SP_POP_TOTL',
             'description': 'Population, total - Belgium. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22101695,
             'limit': None,
             'name': 'Population, total - Belgium',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:27:12.990Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
BLZ
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 374681.0],
                      ['2016-12-31', 366954.0],
                      ['2015-12-31', 359288.0],
                      ['2014-12-31', 351694.0],
                      ['2013-12-31', 344181.0],
                      ['2012-12-31', 336701.0],
                      ['2011-12-31', 329192.0],
                      ['2010-12-31', 321608.0],
                      ['2009-12-31', 313929.0],
                      ['2008-12-31', 306165.0],
                      ['2007-12-31', 298407.0],
                      ['2006-12-31', 290747.0],
                      ['2005-12-31', 283277.0],
                      ['2004-12-31', 276089.0],
                      ['2003-12-31', 269130.0],
                      ['2002-12-31', 262206.0],
                      ['2001-12-31', 254984.0],
                      ['2000-12-31', 247315.0],
                      ['1999-12-31', 239026.0],
                      ['1998-12-31', 230284.0],
                      ['1997-12-31', 221606.0],
                      ['1996-12-31', 213676.0],
                      ['1995-12-31', 206963.0],
                      ['1994-12-31', 201674.0],
                      ['1993-12-31', 197616.0],
                      ['1992-12-31', 194317.0],
                      ['1991-12-31', 191126.0],
                      ['1990-12-31', 187552.0],
                      ['1989-12-31', 183469.0],
                      ['1988-12-31', 179028.0],
                      ['1987-12-31', 174320.0],
                      ['1986-12-31', 169568.0],
                      ['1985-12-31', 164921.0],
                      ['1984-12-31', 160347.0],
                      ['1983-12-31', 155822.0],
                      ['1982-12-31', 151500.0],
                      ['1981-12-31', 147566.0],
                      ['1980-12-31', 144155.0],
                      ['1979-12-31', 141305.0],
                      ['1978-12-31', 138965.0],
                      ['1977-12-31', 136989.0],
                      ['1976-12-31', 135147.0],
                      ['1975-12-31', 133260.0],
                      ['1974-12-31', 131307.0],
                      ['1973-12-31', 129294.0],
                      ['1972-12-31', 127150.0],
                      ['1971-12-31', 124793.0],
                      ['1970-12-31', 122182.0],
                      ['1969-12-31', 119261.0],
                      ['1968-12-31', 116061.0],
                      ['1967-12-31', 112692.0],
                      ['1966-12-31', 109347.0],
                      ['1965-12-31', 106119.0],
                      ['1964-12-31', 103069.0],
                      ['1963-12-31', 100164.0],
                      ['1962-12-31', 97384.0],
                      ['1961-12-31', 94703.0],
                      ['1960-12-31', 92064.0],
                      ['1959-12-31', 89490.0],
                      ['1958-12-31', 86956.0],
                      ['1957-12-31', 84509.0],
                      ['1956-12-31', 82141.0],
                      ['1955-12-31', 79870.0],
                      ['1954-12-31', 77687.0],
                      ['1953-12-31', 75560.0],
                      ['1952-12-31', 73427.0],
                      ['1951-12-31', 71241.0],
                      ['1950-12-31', 68919.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'BLZ_SP_POP_TOTL',
             'description': 'Population, total - Belize. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22118005,
             'limit': None,
             'name': 'Population, total - Belize',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:28:05.235Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
BEN

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 11175692.0],
                      ['2016-12-31', 10872298.0],
                      ['2015-12-31', 10575952.0],
                      ['2014-12-31', 10286712.0],
                      ['2013-12-31', 10004451.0],
                      ['2012-12-31', 9729160.0],
                      ['2011-12-31', 9460802.0],
                      ['2010-12-31', 9199259.0],
                      ['2009-12-31', 8944706.0],
                      ['2008-12-31', 8696916.0],
                      ['2007-12-31', 8454791.0],
                      ['2006-12-31', 8216896.0],
                      ['2005-12-31', 7982225.0],
                      ['2004-12-31', 7750004.0],
                      ['2003-12-31', 7520555.0],
                      ['2002-12-31', 7295394.0],
                      ['2001-12-31', 7076733.0],
                      ['2000-12-31', 6865951.0],
                      ['1999-12-31', 6664098.0],
                      ['1998-12-31', 6470265.0],
                      ['1997-12-31', 6281639.0],
                      ['1996-12-31', 6094259.0],
                      ['1995-12-31', 5905558.0],
                      ['1994-12-31', 5714220.0],
                      ['1993-12-31', 5521763.0],
                      ['1992-12-31', 5331803.0],
                      ['1991-12-31', 5149499.0],
                      ['1990-12-31', 4978496.0],
                      ['1989-12-31', 4820016.0],
                      ['1988-12-31', 4672852.0],
                      ['1987-12-31', 4535263.0],
                      ['1986-12-31', 4404506.0],
                      ['1985-12-31', 4278501.0],
                      ['1984-12-31', 4156819.0],
                      ['1983-12-31', 4039949.0],
                      ['1982-12-31', 3927714.0],
                      ['1981-12-31', 3820128.0],
                      ['1980-12-31', 3717165.0],
                      ['1979-12-31', 3618526.0],
                      ['1978-12-31', 3523938.0],
                      ['1977-12-31', 3433439.0],
                      ['1976-12-31', 3347173.0],
                      ['1975-12-31', 3265165.0],
                      ['1974-12-31', 3187412.0],
                      ['1973-12-31', 3113675.0],
                      ['1972-12-31', 3043567.0],
                      ['1971-12-31', 2976572.0],
                      ['1970-12-31', 2912340.0],
                      ['1969-12-31', 2850661.0],
                      ['1968-12-31', 2791590.0],
                      ['1967-12-31', 2735307.0],
                      ['1966-12-31', 2682159.0],
                      ['1965-12-31', 2632356.0],
                      ['1964-12-31', 2585965.0],
                      ['1963-12-31', 2542859.0],
                      ['1962-12-31', 2502896.0],
                      ['1961-12-31', 2465867.0],
                      ['1960-12-31', 2431622.0],
                      ['1959-12-31', 2400127.0],
                      ['1958-12-31', 2371453.0],
                      ['1957-12-31', 2345717.0],
                      ['1956-12-31', 2323056.0],
                      ['1955-12-31', 2303587.0],
                      ['1954-12-31', 2287385.0],
                      ['1953-12-31', 2274476.0],
                      ['1952-12-31', 2264871.0],
                      ['1951-12-31', 2258476.0],
                      ['1950-12-31', 2255226.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'BEN_SP_POP_TOTL',
             'description': 'Population, total - Benin. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22103660,
             'limit': None,
             'name': 'Population, total - Benin',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:27:19.445Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
BMU
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 65441.0],
                      ['2016-12-31', 65341.0],
                      ['2015-12-31', 65239.0],
                      ['2014-12-31', 65139.0],
                      ['2013-12-31', 65001.0],
                      ['2012-12-31', 64798.0],
                      ['2011-12-31', 64564.0],
                      ['2010-12-31', 65124.0],
                      ['2009-12-31', 65636.0],
                      ['2008-12-31', 65273.0],
                      ['2007-12-31', 64888.0],
                      ['2006-12-31', 64523.0],
                      ['2005-12-31', 64154.0],
                      ['2004-12-31', 63740.0],
                      ['2003-12-31', 63325.0],
                      ['2002-12-31', 62912.0],
                      ['2001-12-31', 62504.0],
                      ['2000-12-31', 61833.0],
                      ['1999-12-31', 61285.0],
                      ['1998-12-31', 60943.0],
                      ['1997-12-31', 60497.0],
                      ['1996-12-31', 60129.0],
                      ['1995-12-31', 59746.0],
                      ['1994-12-31', 59320.0],
                      ['1993-12-31', 58910.0],
                      ['1992-12-31', 58595.0],
                      ['1991-12-31', 59021.0],
                      ['1990-12-31', 59326.0],
                      ['1989-12-31', 58841.0],
                      ['1988-12-31', 58347.0],
                      ['1987-12-31', 57849.0],
                      ['1986-12-31', 57382.0],
                      ['1985-12-31', 56898.0],
                      ['1984-12-31', 56423.0],
                      ['1983-12-31', 55930.0],
                      ['1982-12-31', 55449.0],
                      ['1981-12-31', 55050.0],
                      ['1980-12-31', 54670.0],
                      ['1979-12-31', 53800.0],
                      ['1978-12-31', 53600.0],
                      ['1977-12-31', 53400.0],
                      ['1976-12-31', 53200.0],
                      ['1975-12-31', 53000.0],
                      ['1974-12-31', 53400.0],
                      ['1973-12-31', 53800.0],
                      ['1972-12-31', 54200.0],
                      ['1971-12-31', 54600.0],
                      ['1970-12-31', 55000.0],
                      ['1969-12-31', 54000.0],
                      ['1968-12-31', 53000.0],
                      ['1967-12-31', 52000.0],
                      ['1966-12-31', 51000.0],
                      ['1965-12-31', 50100.0],
                      ['1964-12-31', 48900.0],
                      ['1963-12-31', 47700.0],
                      ['1962-12-31', 46600.0],
                      ['1961-12-31', 45500.0],
                      ['1960-12-31', 44400.0],
                      ['1959-12-31', 43804.0],
                      ['1958-12-31', 43216.0],
                      ['1957-12-31', 42637.0],
                      ['1956-12-31', 42064.0],
                      ['1955-12-31', 41500.0],
                      ['1954-12-31', 40966.0],
                      ['1953-12-31', 40440.0],
                      ['1952-12-31', 39920.0],
                      ['1951-12-31', 39407.0],
                      ['1950-12-31', 38900.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'BMU_SP_POP_TOTL',
             'description': 'Population, total - Bermuda. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22119006,
             'limit': None,
             'name': 'Population, total - Bermuda',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:28:08.895Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
BTN
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 807610.0],
                      ['2016-12-31', 797765.0],
                      ['2015-12-31', 787386.0],
                      ['2014-12-31', 776448.0],
                      ['2013-12-31', 764961.0],
                      ['2012-12-31', 752967.0],
                      ['2011-12-31', 740510.0],
                      ['2010-12-31', 727641.0],
                      ['2009-12-31', 714458.0],
                      ['2008-12-31', 700950.0],
                      ['2007-12-31', 686958.0],
                      ['2006-12-31', 672228.0],
                      ['2005-12-31', 656639.0],
                      ['2004-12-31', 640282.0],
                      ['2003-12-31', 623434.0],
                      ['2002-12-31', 606399.0],
                      ['2001-12-31', 589600.0],
                      ['2000-12-31', 573416.0],
                      ['1999-12-31', 557543.0],
                      ['1998-12-31', 542155.0],
                      ['1997-12-31', 528754.0],
                      ['1996-12-31', 519282.0],
                      ['1995-12-31', 514877.0],
                      ['1994-12-31', 516503.0],
                      ['1993-12-31', 523117.0],
                      ['1992-12-31', 531525.0],
                      ['1991-12-31', 537284.0],
                      ['1990-12-31', 537280.0],
                      ['1989-12-31', 530257.0],
                      ['1988-12-31', 517273.0],
                      ['1987-12-31', 500437.0],
                      ['1986-12-31', 482952.0],
                      ['1985-12-31', 467178.0],
                      ['1984-12-31', 453720.0],
                      ['1983-12-31', 441847.0],
                      ['1982-12-31', 431050.0],
                      ['1981-12-31', 420380.0],
                      ['1980-12-31', 409172.0],
                      ['1979-12-31', 397390.0],
                      ['1978-12-31', 385384.0],
                      ['1977-12-31', 373324.0],
                      ['1976-12-31', 361455.0],
                      ['1975-12-31', 349982.0],
                      ['1974-12-31', 338943.0],
                      ['1973-12-31', 328312.0],
                      ['1972-12-31', 318045.0],
                      ['1971-12-31', 308053.0],
                      ['1970-12-31', 298301.0],
                      ['1969-12-31', 288774.0],
                      ['1968-12-31', 279515.0],
                      ['1967-12-31', 270622.0],
                      ['1966-12-31', 262244.0],
                      ['1965-12-31', 254464.0],
                      ['1964-12-31', 247325.0],
                      ['1963-12-31', 240778.0],
                      ['1962-12-31', 234706.0],
                      ['1961-12-31', 228918.0],
                      ['1960-12-31', 223288.0],
                      ['1959-12-31', 217773.0],
                      ['1958-12-31', 212384.0],
                      ['1957-12-31', 207165.0],
                      ['1956-12-31', 202174.0],
                      ['1955-12-31', 197457.0],
                      ['1954-12-31', 193011.0],
                      ['1953-12-31', 188816.0],
                      ['1952-12-31', 184790.0],
                      ['1951-12-31', 180825.0],
                      ['1950-12-31', 176797.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'BTN_SP_POP_TOTL',
             'description': 'Population, total - Bhutan. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22127540,
             'limit': None,
             'name': 'Population, total - Bhutan',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:28:35.810Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
BOL

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 11051600.0],
                      ['2016-12-31', 10887882.0],
                      ['2015-12-31', 10724705.0],
                      ['2014-12-31', 10562159.0],
                      ['2013-12-31', 10400264.0],
                      ['2012-12-31', 10239004.0],
                      ['2011-12-31', 10078343.0],
                      ['2010-12-31', 9918242.0],
                      ['2009-12-31', 9758748.0],
                      ['2008-12-31', 9599855.0],
                      ['2007-12-31', 9441444.0],
                      ['2006-12-31', 9283334.0],
                      ['2005-12-31', 9125409.0],
                      ['2004-12-31', 8967741.0],
                      ['2003-12-31', 8810420.0],
                      ['2002-12-31', 8653345.0],
                      ['2001-12-31', 8496375.0],
                      ['2000-12-31', 8339512.0],
                      ['1999-12-31', 8182712.0],
                      ['1998-12-31', 8026254.0],
                      ['1997-12-31', 7870855.0],
                      ['1996-12-31', 7717443.0],
                      ['1995-12-31', 7566714.0],
                      ['1994-12-31', 7418861.0],
                      ['1993-12-31', 7273825.0],
                      ['1992-12-31', 7131707.0],
                      ['1991-12-31', 6992521.0],
                      ['1990-12-31', 6856244.0],
                      ['1989-12-31', 6723046.0],
                      ['1988-12-31', 6592787.0],
                      ['1987-12-31', 6464732.0],
                      ['1986-12-31', 6337893.0],
                      ['1985-12-31', 6211550.0],
                      ['1984-12-31', 6085496.0],
                      ['1983-12-31', 5959960.0],
                      ['1982-12-31', 5835182.0],
                      ['1981-12-31', 5711599.0],
                      ['1980-12-31', 5589575.0],
                      ['1979-12-31', 5469123.0],
                      ['1978-12-31', 5350322.0],
                      ['1977-12-31', 5233677.0],
                      ['1976-12-31', 5119833.0],
                      ['1975-12-31', 5009257.0],
                      ['1974-12-31', 4902168.0],
                      ['1973-12-31', 4798509.0],
                      ['1972-12-31', 4698083.0],
                      ['1971-12-31', 4600591.0],
                      ['1970-12-31', 4505778.0],
                      ['1969-12-31', 4413590.0],
                      ['1968-12-31', 4324064.0],
                      ['1967-12-31', 4237125.0],
                      ['1966-12-31', 4152668.0],
                      ['1965-12-31', 4070590.0],
                      ['1964-12-31', 3990857.0],
                      ['1963-12-31', 3913395.0],
                      ['1962-12-31', 3838097.0],
                      ['1961-12-31', 3764813.0],
                      ['1960-12-31', 3693449.0],
                      ['1959-12-31', 3623965.0],
                      ['1958-12-31', 3556360.0],
                      ['1957-12-31', 3490684.0],
                      ['1956-12-31', 3427002.0],
                      ['1955-12-31', 3365360.0],
                      ['1954-12-31', 3305836.0],
                      ['1953-12-31', 3248461.0],
                      ['1952-12-31', 3193289.0],
                      ['1951-12-31', 3140336.0],
                      ['1950-12-31', 3089646.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'BOL_SP_POP_TOTL',
             'description': 'Population, total - Bolivia. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22120778,
             'limit': None,
             'name': 'Population, total - Bolivia',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:28:14.324Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
BIH
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 3507017.0],
                      ['2016-12-31', 3516816.0],
                      ['2015-12-31', 3535961.0],
                      ['2014-12-31', 3566002.0],
                      ['2013-12-31', 3604999.0],
                      ['2012-12-31', 3648200.0],
                      ['2011-12-31', 3688865.0],
                      ['2010-12-31', 3722084.0],
                      ['2009-12-31', 3746561.0],
                      ['2008-12-31', 3763599.0],
                      ['2007-12-31', 3774000.0],
                      ['2006-12-31', 3779468.0],
                      ['2005-12-31', 3781530.0],
                      ['2004-12-31', 3781287.0],
                      ['2003-12-31', 3779247.0],
                      ['2002-12-31', 3775807.0],
                      ['2001-12-31', 3771284.0],
                      ['2000-12-31', 3766706.0],
                      ['1999-12-31', 3759118.0],
                      ['1998-12-31', 3750485.0],
                      ['1997-12-31', 3752431.0],
                      ['1996-12-31', 3780378.0],
                      ['1995-12-31', 3843712.0],
                      ['1994-12-31', 3948816.0],
                      ['1993-12-31', 4087999.0],
                      ['1992-12-31', 4239154.0],
                      ['1991-12-31', 4371603.0],
                      ['1990-12-31', 4463422.0],
                      ['1989-12-31', 4506653.0],
                      ['1988-12-31', 4508056.0],
                      ['1987-12-31', 4478519.0],
                      ['1986-12-31', 4435504.0],
                      ['1985-12-31', 4392130.0],
                      ['1984-12-31', 4350746.0],
                      ['1983-12-31', 4308106.0],
                      ['1982-12-31', 4265310.0],
                      ['1981-12-31', 4222511.0],
                      ['1980-12-31', 4179855.0],
                      ['1979-12-31', 4138819.0],
                      ['1978-12-31', 4100350.0],
                      ['1977-12-31', 4063191.0],
                      ['1976-12-31', 4025265.0],
                      ['1975-12-31', 3985103.0],
                      ['1974-12-31', 3942223.0],
                      ['1973-12-31', 3897255.0],
                      ['1972-12-31', 3851151.0],
                      ['1971-12-31', 3805285.0],
                      ['1970-12-31', 3760527.0],
                      ['1969-12-31', 3717466.0],
                      ['1968-12-31', 3675452.0],
                      ['1967-12-31', 3632669.0],
                      ['1966-12-31', 3586634.0],
                      ['1965-12-31', 3535640.0],
                      ['1964-12-31', 3478995.0],
                      ['1963-12-31', 3417574.0],
                      ['1962-12-31', 3353226.0],
                      ['1961-12-31', 3288602.0],
                      ['1960-12-31', 3225668.0],
                      ['1959-12-31', 3165191.0],
                      ['1958-12-31', 3106894.0],
                      ['1957-12-31', 3049919.0],
                      ['1956-12-31', 2993271.0],
                      ['1955-12-31', 2936309.0],
                      ['1954-12-31', 2878849.0],
                      ['1953-12-31', 2821308.0],
                      ['1952-12-31', 2764713.0],
                      ['1951-12-31', 2710651.0],
                      ['1950-12-31', 2661296.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'BIH_SP_POP_TOTL',
             'description': 'Population, total - Bosnia and Herzegovina. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22114348,
             'limit': None,
             'name': 'Population, total - Bosnia and Herzegovina',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:27:53.922Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
BWA

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 2291661.0],
                      ['2016-12-31', 2250260.0],
                      ['2015-12-31', 2209197.0],
                      ['2014-12-31', 2168573.0],
                      ['2013-12-31', 2128507.0],
                      ['2012-12-31', 2089315.0],
                      ['2011-12-31', 2051339.0],
                      ['2010-12-31', 2014866.0],
                      ['2009-12-31', 1979882.0],
                      ['2008-12-31', 1946351.0],
                      ['2007-12-31', 1914414.0],
                      ['2006-12-31', 1884238.0],
                      ['2005-12-31', 1855852.0],
                      ['2004-12-31', 1829330.0],
                      ['2003-12-31', 1804339.0],
                      ['2002-12-31', 1779953.0],
                      ['2001-12-31', 1754935.0],
                      ['2000-12-31', 1728340.0],
                      ['1999-12-31', 1699862.0],
                      ['1998-12-31', 1669625.0],
                      ['1997-12-31', 1637635.0],
                      ['1996-12-31', 1604060.0],
                      ['1995-12-31', 1569094.0],
                      ['1994-12-31', 1532622.0],
                      ['1993-12-31', 1494693.0],
                      ['1992-12-31', 1455833.0],
                      ['1991-12-31', 1416731.0],
                      ['1990-12-31', 1377912.0],
                      ['1989-12-31', 1339624.0],
                      ['1988-12-31', 1301818.0],
                      ['1987-12-31', 1264314.0],
                      ['1986-12-31', 1226810.0],
                      ['1985-12-31', 1189114.0],
                      ['1984-12-31', 1151292.0],
                      ['1983-12-31', 1113539.0],
                      ['1982-12-31', 1075889.0],
                      ['1981-12-31', 1038397.0],
                      ['1980-12-31', 1001158.0],
                      ['1979-12-31', 964166.0],
                      ['1978-12-31', 927585.0],
                      ['1977-12-31', 891926.0],
                      ['1976-12-31', 857855.0],
                      ['1975-12-31', 825840.0],
                      ['1974-12-31', 796095.0],
                      ['1973-12-31', 768512.0],
                      ['1972-12-31', 742835.0],
                      ['1971-12-31', 718639.0],
                      ['1970-12-31', 695597.0],
                      ['1969-12-31', 673640.0],
                      ['1968-12-31', 652843.0],
                      ['1967-12-31', 633154.0],
                      ['1966-12-31', 614613.0],
                      ['1965-12-31', 597190.0],
                      ['1964-12-31', 580799.0],
                      ['1963-12-31', 565353.0],
                      ['1962-12-31', 550840.0],
                      ['1961-12-31', 537249.0],
                      ['1960-12-31', 524552.0],
                      ['1959-12-31', 512647.0],
                      ['1958-12-31', 501398.0],
                      ['1957-12-31', 490626.0],
                      ['1956-12-31', 480148.0],
                      ['1955-12-31', 469740.0],
                      ['1954-12-31', 459238.0],
                      ['1953-12-31', 448442.0],
                      ['1952-12-31', 437169.0],
                      ['1951-12-31', 425265.0],
                      ['1950-12-31', 412531.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'BWA_SP_POP_TOTL',
             'description': 'Population, total - Botswana. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22129368,
             'limit': None,
             'name': 'Population, total - Botswana',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:28:42.183Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
BRA
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 209288278.0],
                      ['2016-12-31', 207652865.0],
                      ['2015-12-31', 205962108.0],
                      ['2014-12-31', 204213133.0],
                      ['2013-12-31', 202408632.0],
                      ['2012-12-31', 200560983.0],
                      ['2011-12-31', 198686688.0],
                      ['2010-12-31', 196796269.0],
                      ['2009-12-31', 194895996.0],
                      ['2008-12-31', 192979029.0],
                      ['2007-12-31', 191026637.0],
                      ['2006-12-31', 189012412.0],
                      ['2005-12-31', 186917361.0],
                      ['2004-12-31', 184738458.0],
                      ['2003-12-31', 182482149.0],
                      ['2002-12-31', 180151021.0],
                      ['2001-12-31', 177750670.0],
                      ['2000-12-31', 175287587.0],
                      ['1999-12-31', 172759243.0],
                      ['1998-12-31', 170170640.0],
                      ['1997-12-31', 167545164.0],
                      ['1996-12-31', 164913306.0],
                      ['1995-12-31', 162296612.0],
                      ['1994-12-31', 159705123.0],
                      ['1993-12-31', 157132682.0],
                      ['1992-12-31', 154564278.0],
                      ['1991-12-31', 151976577.0],
                      ['1990-12-31', 149352145.0],
                      ['1989-12-31', 146691981.0],
                      ['1988-12-31', 144001542.0],
                      ['1987-12-31', 141273488.0],
                      ['1986-12-31', 138499464.0],
                      ['1985-12-31', 135676281.0],
                      ['1984-12-31', 132800684.0],
                      ['1983-12-31', 129882321.0],
                      ['1982-12-31', 126947365.0],
                      ['1981-12-31', 124030908.0],
                      ['1980-12-31', 121159761.0],
                      ['1979-12-31', 118342626.0],
                      ['1978-12-31', 115577669.0],
                      ['1977-12-31', 112867867.0],
                      ['1976-12-31', 110213082.0],
                      ['1975-12-31', 107612100.0],
                      ['1974-12-31', 105069367.0],
                      ['1973-12-31', 102584278.0],
                      ['1972-12-31', 100143598.0],
                      ['1971-12-31', 97728961.0],
                      ['1970-12-31', 95326793.0],
                      ['1969-12-31', 92935072.0],
                      ['1968-12-31', 90557064.0],
                      ['1967-12-31', 88191378.0],
                      ['1966-12-31', 85837799.0],
                      ['1965-12-31', 83498020.0],
                      ['1964-12-31', 81168654.0],
                      ['1963-12-31', 78854019.0],
                      ['1962-12-31', 76573248.0],
                      ['1961-12-31', 74351763.0],
                      ['1960-12-31', 72207554.0],
                      ['1959-12-31', 70146513.0],
                      ['1958-12-31', 68164042.0],
                      ['1957-12-31', 66248946.0],
                      ['1956-12-31', 64387823.0],
                      ['1955-12-31', 62569196.0],
                      ['1954-12-31', 60784892.0],
                      ['1953-12-31', 59030858.0],
                      ['1952-12-31', 57307476.0],
                      ['1951-12-31', 55619224.0],
                      ['1950-12-31', 53974729.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'BRA_SP_POP_TOTL',
             'description': 'Population, total - Brazil. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22122780,
             'limit': None,
             'name': 'Population, total - Brazil',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:28:20.432Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
BRN

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 428697.0],
                      ['2016-12-31', 423196.0],
                      ['2015-12-31', 417542.0],
                      ['2014-12-31', 411704.0],
                      ['2013-12-31', 405716.0],
                      ['2012-12-31', 399748.0],
                      ['2011-12-31', 394013.0],
                      ['2010-12-31', 388662.0],
                      ['2009-12-31', 383772.0],
                      ['2008-12-31', 379252.0],
                      ['2007-12-31', 374864.0],
                      ['2006-12-31', 370250.0],
                      ['2005-12-31', 365158.0],
                      ['2004-12-31', 359523.0],
                      ['2003-12-31', 353389.0],
                      ['2002-12-31', 346867.0],
                      ['2001-12-31', 340117.0],
                      ['2000-12-31', 333241.0],
                      ['1999-12-31', 326289.0],
                      ['1998-12-31', 319222.0],
                      ['1997-12-31', 312038.0],
                      ['1996-12-31', 304699.0],
                      ['1995-12-31', 297192.0],
                      ['1994-12-31', 289525.0],
                      ['1993-12-31', 281751.0],
                      ['1992-12-31', 273963.0],
                      ['1991-12-31', 266274.0],
                      ['1990-12-31', 258785.0],
                      ['1989-12-31', 251514.0],
                      ['1988-12-31', 244458.0],
                      ['1987-12-31', 237622.0],
                      ['1986-12-31', 230972.0],
                      ['1985-12-31', 224512.0],
                      ['1984-12-31', 218227.0],
                      ['1983-12-31', 212136.0],
                      ['1982-12-31', 206128.0],
                      ['1981-12-31', 200085.0],
                      ['1980-12-31', 193949.0],
                      ['1979-12-31', 187656.0],
                      ['1978-12-31', 181257.0],
                      ['1977-12-31', 174773.0],
                      ['1976-12-31', 168224.0],
                      ['1975-12-31', 161671.0],
                      ['1974-12-31', 155109.0],
                      ['1973-12-31', 148560.0],
                      ['1972-12-31', 142073.0],
                      ['1971-12-31', 135726.0],
                      ['1970-12-31', 129583.0],
                      ['1969-12-31', 123653.0],
                      ['1968-12-31', 117950.0],
                      ['1967-12-31', 112494.0],
                      ['1966-12-31', 107316.0],
                      ['1965-12-31', 102425.0],
                      ['1964-12-31', 97848.0],
                      ['1963-12-31', 93576.0],
                      ['1962-12-31', 89516.0],
                      ['1961-12-31', 85596.0],
                      ['1960-12-31', 81745.0],
                      ['1959-12-31', 77919.0],
                      ['1958-12-31', 74150.0],
                      ['1957-12-31', 70457.0],
                      ['1956-12-31', 66862.0],
                      ['1955-12-31', 63420.0],
                      ['1954-12-31', 60120.0],
                      ['1953-12-31', 56968.0],
                      ['1952-12-31', 53927.0],
                      ['1951-12-31', 50961.0],
                      ['1950-12-31', 48001.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'BRN_SP_POP_TOTL',
             'description': 'Population, total - Brunei Darussalam. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22125955,
             'limit': None,
             'name': 'Population, total - Brunei Darussalam',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:28:30.515Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
BGR
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 7075991.0],
                      ['2016-12-31', 7127822.0],
                      ['2015-12-31', 7177991.0],
                      ['2014-12-31', 7223938.0],
                      ['2013-12-31', 7265115.0],
                      ['2012-12-31', 7305888.0],
                      ['2011-12-31', 7348328.0],
                      ['2010-12-31', 7395599.0],
                      ['2009-12-31', 7444443.0],
                      ['2008-12-31', 7492561.0],
                      ['2007-12-31', 7545338.0],
                      ['2006-12-31', 7601022.0],
                      ['2005-12-31', 7658972.0],
                      ['2004-12-31', 7716860.0],
                      ['2003-12-31', 7775327.0],
                      ['2002-12-31', 7837161.0],
                      ['2001-12-31', 8009142.0],
                      ['2000-12-31', 8170172.0],
                      ['1999-12-31', 8210624.0],
                      ['1998-12-31', 8256786.0],
                      ['1997-12-31', 8312068.0],
                      ['1996-12-31', 8362826.0],
                      ['1995-12-31', 8406067.0],
                      ['1994-12-31', 8443591.0],
                      ['1993-12-31', 8472313.0],
                      ['1992-12-31', 8540164.0],
                      ['1991-12-31', 8632367.0],
                      ['1990-12-31', 8718289.0],
                      ['1989-12-31', 8876972.0],
                      ['1988-12-31', 8981446.0],
                      ['1987-12-31', 8971359.0],
                      ['1986-12-31', 8958171.0],
                      ['1985-12-31', 8960547.0],
                      ['1984-12-31', 8960679.0],
                      ['1983-12-31', 8939738.0],
                      ['1982-12-31', 8917457.0],
                      ['1981-12-31', 8891117.0],
                      ['1980-12-31', 8861535.0],
                      ['1979-12-31', 8825940.0],
                      ['1978-12-31', 8814032.0],
                      ['1977-12-31', 8804183.0],
                      ['1976-12-31', 8758599.0],
                      ['1975-12-31', 8720742.0],
                      ['1974-12-31', 8678745.0],
                      ['1973-12-31', 8620967.0],
                      ['1972-12-31', 8576200.0],
                      ['1971-12-31', 8536395.0],
                      ['1970-12-31', 8489574.0],
                      ['1969-12-31', 8434172.0],
                      ['1968-12-31', 8369603.0],
                      ['1967-12-31', 8310226.0],
                      ['1966-12-31', 8258057.0],
                      ['1965-12-31', 8204168.0],
                      ['1964-12-31', 8144340.0],
                      ['1963-12-31', 8078145.0],
                      ['1962-12-31', 8012946.0],
                      ['1961-12-31', 7943118.0],
                      ['1960-12-31', 7867374.0],
                      ['1959-12-31', 7792759.0],
                      ['1958-12-31', 7717389.0],
                      ['1957-12-31', 7642268.0],
                      ['1956-12-31', 7568951.0],
                      ['1955-12-31', 7499009.0],
                      ['1954-12-31', 7433978.0],
                      ['1953-12-31', 7375320.0],
                      ['1952-12-31', 7324411.0],
                      ['1951-12-31', 7282560.0],
                      ['1950-12-31', 7250999.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'BGR_SP_POP_TOTL',
             'description': 'Population, total - Bulgaria. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22109423,
             'limit': None,
             'name': 'Population, total - Bulgaria',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:27:38.158Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
BFA

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 19193382.0],
                      ['2016-12-31', 18646433.0],
                      ['2015-12-31', 18110624.0],
                      ['2014-12-31', 17585977.0],
                      ['2013-12-31', 17072723.0],
                      ['2012-12-31', 16571216.0],
                      ['2011-12-31', 16081904.0],
                      ['2010-12-31', 15605217.0],
                      ['2009-12-31', 15141099.0],
                      ['2008-12-31', 14689726.0],
                      ['2007-12-31', 14252021.0],
                      ['2006-12-31', 13829177.0],
                      ['2005-12-31', 13421930.0],
                      ['2004-12-31', 13030569.0],
                      ['2003-12-31', 12654621.0],
                      ['2002-12-31', 12293100.0],
                      ['2001-12-31', 11944587.0],
                      ['2000-12-31', 11607942.0],
                      ['1999-12-31', 11282701.0],
                      ['1998-12-31', 10968724.0],
                      ['1997-12-31', 10665546.0],
                      ['1996-12-31', 10372745.0],
                      ['1995-12-31', 10089878.0],
                      ['1994-12-31', 9816588.0],
                      ['1993-12-31', 9552476.0],
                      ['1992-12-31', 9297113.0],
                      ['1991-12-31', 9050084.0],
                      ['1990-12-31', 8811034.0],
                      ['1989-12-31', 8579823.0],
                      ['1988-12-31', 8356305.0],
                      ['1987-12-31', 8140073.0],
                      ['1986-12-31', 7930694.0],
                      ['1985-12-31', 7727907.0],
                      ['1984-12-31', 7531242.0],
                      ['1983-12-31', 7340905.0],
                      ['1982-12-31', 7158255.0],
                      ['1981-12-31', 6985160.0],
                      ['1980-12-31', 6822843.0],
                      ['1979-12-31', 6671656.0],
                      ['1978-12-31', 6530819.0],
                      ['1977-12-31', 6398935.0],
                      ['1976-12-31', 6274037.0],
                      ['1975-12-31', 6154545.0],
                      ['1974-12-31', 6040041.0],
                      ['1973-12-31', 5930483.0],
                      ['1972-12-31', 5825173.0],
                      ['1971-12-31', 5723381.0],
                      ['1970-12-31', 5624600.0],
                      ['1969-12-31', 5528174.0],
                      ['1968-12-31', 5434041.0],
                      ['1967-12-31', 5343019.0],
                      ['1966-12-31', 5256363.0],
                      ['1965-12-31', 5174870.0],
                      ['1964-12-31', 5098890.0],
                      ['1963-12-31', 5027821.0],
                      ['1962-12-31', 4960326.0],
                      ['1961-12-31', 4894580.0],
                      ['1960-12-31', 4829288.0],
                      ['1959-12-31', 4764077.0],
                      ['1958-12-31', 4699340.0],
                      ['1957-12-31', 4635955.0],
                      ['1956-12-31', 4574942.0],
                      ['1955-12-31', 4517155.0],
                      ['1954-12-31', 4463168.0],
                      ['1953-12-31', 4413202.0],
                      ['1952-12-31', 4367134.0],
                      ['1951-12-31', 4324494.0],
                      ['1950-12-31', 4284461.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'BFA_SP_POP_TOTL',
             'description': 'Population, total - Burkina Faso. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22105509,
             'limit': None,
             'name': 'Population, total - Burkina Faso',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:27:25.927Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
BDI
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 10864245.0],
                      ['2016-12-31', 10524117.0],
                      ['2015-12-31', 10199270.0],
                      ['2014-12-31', 9891790.0],
                      ['2013-12-31', 9600186.0],
                      ['2012-12-31', 9319710.0],
                      ['2011-12-31', 9043508.0],
                      ['2010-12-31', 8766930.0],
                      ['2009-12-31', 8489031.0],
                      ['2008-12-31', 8212264.0],
                      ['2007-12-31', 7939573.0],
                      ['2006-12-31', 7675338.0],
                      ['2005-12-31', 7423289.0],
                      ['2004-12-31', 7182451.0],
                      ['2003-12-31', 6953113.0],
                      ['2002-12-31', 6741569.0],
                      ['2001-12-31', 6555829.0],
                      ['2000-12-31', 6400706.0],
                      ['1999-12-31', 6278940.0],
                      ['1998-12-31', 6186352.0],
                      ['1997-12-31', 6112097.0],
                      ['1996-12-31', 6041112.0],
                      ['1995-12-31', 5962058.0],
                      ['1994-12-31', 5871607.0],
                      ['1993-12-31', 5771398.0],
                      ['1992-12-31', 5661139.0],
                      ['1991-12-31', 5542048.0],
                      ['1990-12-31', 5415415.0],
                      ['1989-12-31', 5280024.0],
                      ['1988-12-31', 5135956.0],
                      ['1987-12-31', 4987736.0],
                      ['1986-12-31', 4841565.0],
                      ['1985-12-31', 4702066.0],
                      ['1984-12-31', 4571292.0],
                      ['1983-12-31', 4448728.0],
                      ['1982-12-31', 4333386.0],
                      ['1981-12-31', 4223195.0],
                      ['1980-12-31', 4116817.0],
                      ['1979-12-31', 4013310.0],
                      ['1978-12-31', 3913768.0],
                      ['1977-12-31', 3821194.0],
                      ['1976-12-31', 3739659.0],
                      ['1975-12-31', 3671494.0],
                      ['1974-12-31', 3618585.0],
                      ['1973-12-31', 3578490.0],
                      ['1972-12-31', 3544047.0],
                      ['1971-12-31', 3505391.0],
                      ['1970-12-31', 3455606.0],
                      ['1969-12-31', 3391753.0],
                      ['1968-12-31', 3316233.0],
                      ['1967-12-31', 3234023.0],
                      ['1966-12-31', 3152723.0],
                      ['1965-12-31', 3077876.0],
                      ['1964-12-31', 3010859.0],
                      ['1963-12-31', 2949926.0],
                      ['1962-12-31', 2893669.0],
                      ['1961-12-31', 2839666.0],
                      ['1960-12-31', 2786106.0],
                      ['1959-12-31', 2732438.0],
                      ['1958-12-31', 2679141.0],
                      ['1957-12-31', 2627233.0],
                      ['1956-12-31', 2577735.0],
                      ['1955-12-31', 2531184.0],
                      ['1954-12-31', 2487390.0],
                      ['1953-12-31', 2445420.0],
                      ['1952-12-31', 2403511.0],
                      ['1951-12-31', 2359123.0],
                      ['1950-12-31', 2308920.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'BDI_SP_POP_TOTL',
             'description': 'Population, total - Burundi. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22099995,
             'limit': None,
             'name': 'Population, total - Burundi',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:27:07.758Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
CPV

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 546388.0],
                      ['2016-12-31', 539560.0],
                      ['2015-12-31', 532913.0],
                      ['2014-12-31', 526437.0],
                      ['2013-12-31', 520106.0],
                      ['2012-12-31', 513979.0],
                      ['2011-12-31', 508067.0],
                      ['2010-12-31', 502384.0],
                      ['2009-12-31', 496963.0],
                      ['2008-12-31', 491723.0],
                      ['2007-12-31', 486438.0],
                      ['2006-12-31', 480795.0],
                      ['2005-12-31', 474567.0],
                      ['2004-12-31', 467664.0],
                      ['2003-12-31', 460147.0],
                      ['2002-12-31', 452106.0],
                      ['2001-12-31', 443716.0],
                      ['2000-12-31', 435079.0],
                      ['1999-12-31', 426285.0],
                      ['1998-12-31', 417323.0],
                      ['1997-12-31', 408175.0],
                      ['1996-12-31', 398773.0],
                      ['1995-12-31', 389127.0],
                      ['1994-12-31', 379156.0],
                      ['1993-12-31', 369014.0],
                      ['1992-12-31', 359090.0],
                      ['1991-12-31', 349934.0],
                      ['1990-12-31', 341883.0],
                      ['1989-12-31', 335184.0],
                      ['1988-12-31', 329671.0],
                      ['1987-12-31', 324893.0],
                      ['1986-12-31', 320183.0],
                      ['1985-12-31', 315069.0],
                      ['1984-12-31', 309397.0],
                      ['1983-12-31', 303368.0],
                      ['1982-12-31', 297285.0],
                      ['1981-12-31', 291602.0],
                      ['1980-12-31', 286657.0],
                      ['1979-12-31', 282415.0],
                      ['1978-12-31', 278739.0],
                      ['1977-12-31', 275767.0],
                      ['1976-12-31', 273652.0],
                      ['1975-12-31', 272423.0],
                      ['1974-12-31', 272292.0],
                      ['1973-12-31', 273005.0],
                      ['1972-12-31', 273651.0],
                      ['1971-12-31', 272992.0],
                      ['1970-12-31', 270198.0],
                      ['1969-12-31', 264909.0],
                      ['1968-12-31', 257509.0],
                      ['1967-12-31', 248747.0],
                      ['1966-12-31', 239770.0],
                      ['1965-12-31', 231428.0],
                      ['1964-12-31', 223846.0],
                      ['1963-12-31', 216908.0],
                      ['1962-12-31', 210867.0],
                      ['1961-12-31', 205956.0],
                      ['1960-12-31', 202310.0],
                      ['1959-12-31', 199906.0],
                      ['1958-12-31', 198539.0],
                      ['1957-12-31', 197928.0],
                      ['1956-12-31', 197700.0],
                      ['1955-12-31', 197421.0],
                      ['1954-12-31', 196635.0],
                      ['1953-12-31', 194837.0],
                      ['1952-12-31', 191527.0],
                      ['1951-12-31', 186130.0],
                      ['1950-12-31', 178066.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'CPV_SP_POP_TOTL',
             'description': 'Population, total - Cabo Verde. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22103989,
             'limit': None,
             'name': 'Population, total - Cabo Verde',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:29:55.979Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
KHM
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 16005373.0],
                      ['2016-12-31', 15762370.0],
                      ['2015-12-31', 15517635.0],
                      ['2014-12-31', 15270790.0],
                      ['2013-12-31', 15022692.0],
                      ['2012-12-31', 14776866.0],
                      ['2011-12-31', 14537886.0],
                      ['2010-12-31', 14308740.0],
                      ['2009-12-31', 14090208.0],
                      ['2008-12-31', 13880509.0],
                      ['2007-12-31', 13676693.0],
                      ['2006-12-31', 13474489.0],
                      ['2005-12-31', 13270201.0],
                      ['2004-12-31', 13063377.0],
                      ['2003-12-31', 12853124.0],
                      ['2002-12-31', 12634729.0],
                      ['2001-12-31', 12402473.0],
                      ['2000-12-31', 12152354.0],
                      ['1999-12-31', 11883636.0],
                      ['1998-12-31', 11597739.0],
                      ['1997-12-31', 11295880.0],
                      ['1996-12-31', 10980273.0],
                      ['1995-12-31', 10653558.0],
                      ['1994-12-31', 10315376.0],
                      ['1993-12-31', 9968275.0],
                      ['1992-12-31', 9621504.0],
                      ['1991-12-31', 9286976.0],
                      ['1990-12-31', 8973342.0],
                      ['1989-12-31', 8689152.0],
                      ['1988-12-31', 8433798.0],
                      ['1987-12-31', 8196037.0],
                      ['1986-12-31', 7958976.0],
                      ['1985-12-31', 7712978.0],
                      ['1984-12-31', 7446019.0],
                      ['1983-12-31', 7168236.0],
                      ['1982-12-31', 6918101.0],
                      ['1981-12-31', 6748193.0],
                      ['1980-12-31', 6692107.0],
                      ['1979-12-31', 6768724.0],
                      ['1978-12-31', 6955566.0],
                      ['1977-12-31', 7194279.0],
                      ['1976-12-31', 7402873.0],
                      ['1975-12-31', 7522593.0],
                      ['1974-12-31', 7531424.0],
                      ['1973-12-31', 7447285.0],
                      ['1972-12-31', 7300152.0],
                      ['1971-12-31', 7137749.0],
                      ['1970-12-31', 6994848.0],
                      ['1969-12-31', 6879184.0],
                      ['1968-12-31', 6778723.0],
                      ['1967-12-31', 6685321.0],
                      ['1966-12-31', 6584766.0],
                      ['1965-12-31', 6467197.0],
                      ['1964-12-31', 6331583.0],
                      ['1963-12-31', 6183747.0],
                      ['1962-12-31', 6028551.0],
                      ['1961-12-31', 5873015.0],
                      ['1960-12-31', 5722370.0],
                      ['1959-12-31', 5578675.0],
                      ['1958-12-31', 5441319.0],
                      ['1957-12-31', 5308142.0],
                      ['1956-12-31', 5176658.0],
                      ['1955-12-31', 5045288.0],
                      ['1954-12-31', 4913695.0],
                      ['1953-12-31', 4783092.0],
                      ['1952-12-31', 4656277.0],
                      ['1951-12-31', 4537543.0],
                      ['1950-12-31', 4432714.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'KHM_SP_POP_TOTL',
             'description': 'Population, total - Cambodia. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22158657,
             'limit': None,
             'name': 'Population, total - Cambodia',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:35:40.264Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
CMR

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 24053727.0],
                      ['2016-12-31', 23439189.0],
                      ['2015-12-31', 22834522.0],
                      ['2014-12-31', 22239904.0],
                      ['2013-12-31', 21655715.0],
                      ['2012-12-31', 21082383.0],
                      ['2011-12-31', 20520447.0],
                      ['2010-12-31', 19970495.0],
                      ['2009-12-31', 19432541.0],
                      ['2008-12-31', 18907008.0],
                      ['2007-12-31', 18395389.0],
                      ['2006-12-31', 17899562.0],
                      ['2005-12-31', 17420795.0],
                      ['2004-12-31', 16959081.0],
                      ['2003-12-31', 16513822.0],
                      ['2002-12-31', 16084886.0],
                      ['2001-12-31', 15671927.0],
                      ['2000-12-31', 15274234.0],
                      ['1999-12-31', 14891891.0],
                      ['1998-12-31', 14523570.0],
                      ['1997-12-31', 14165423.0],
                      ['1996-12-31', 13812472.0],
                      ['1995-12-31', 13460994.0],
                      ['1994-12-31', 13109660.0],
                      ['1993-12-31', 12758881.0],
                      ['1992-12-31', 12408931.0],
                      ['1991-12-31', 12060729.0],
                      ['1990-12-31', 11715218.0],
                      ['1989-12-31', 11372160.0],
                      ['1988-12-31', 11031817.0],
                      ['1987-12-31', 10696274.0],
                      ['1986-12-31', 10368300.0],
                      ['1985-12-31', 10050023.0],
                      ['1984-12-31', 9742263.0],
                      ['1983-12-31', 9445003.0],
                      ['1982-12-31', 9158566.0],
                      ['1981-12-31', 8883016.0],
                      ['1980-12-31', 8618354.0],
                      ['1979-12-31', 8364835.0],
                      ['1978-12-31', 8122529.0],
                      ['1977-12-31', 7890969.0],
                      ['1976-12-31', 7669445.0],
                      ['1975-12-31', 7457362.0],
                      ['1974-12-31', 7254468.0],
                      ['1973-12-31', 7060603.0],
                      ['1972-12-31', 6875228.0],
                      ['1971-12-31', 6697745.0],
                      ['1970-12-31', 6527635.0],
                      ['1969-12-31', 6364569.0],
                      ['1968-12-31', 6208282.0],
                      ['1967-12-31', 6058539.0],
                      ['1966-12-31', 5915123.0],
                      ['1965-12-31', 5777834.0],
                      ['1964-12-31', 5646316.0],
                      ['1963-12-31', 5520332.0],
                      ['1962-12-31', 5399922.0],
                      ['1961-12-31', 5285231.0],
                      ['1960-12-31', 5176268.0],
                      ['1959-12-31', 5072801.0],
                      ['1958-12-31', 4974431.0],
                      ['1957-12-31', 4880594.0],
                      ['1956-12-31', 4790714.0],
                      ['1955-12-31', 4704233.0],
                      ['1954-12-31', 4620627.0],
                      ['1953-12-31', 4539443.0],
                      ['1952-12-31', 4460318.0],
                      ['1951-12-31', 4382927.0],
                      ['1950-12-31', 4307022.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'CMR_SP_POP_TOTL',
             'description': 'Population, total - Cameroon. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22095004,
             'limit': None,
             'name': 'Population, total - Cameroon',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:29:24.603Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
CAN
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 36708083.0],
                      ['2016-12-31', 36264604.0],
                      ['2015-12-31', 35832513.0],
                      ['2014-12-31', 35535348.0],
                      ['2013-12-31', 35152370.0],
                      ['2012-12-31', 34750545.0],
                      ['2011-12-31', 34342780.0],
                      ['2010-12-31', 34005274.0],
                      ['2009-12-31', 33628571.0],
                      ['2008-12-31', 33245773.0],
                      ['2007-12-31', 32887928.0],
                      ['2006-12-31', 32570505.0],
                      ['2005-12-31', 32312000.0],
                      ['2004-12-31', 31995000.0],
                      ['2003-12-31', 31676000.0],
                      ['2002-12-31', 31362000.0],
                      ['2001-12-31', 31081900.0],
                      ['2000-12-31', 30769700.0],
                      ['1999-12-31', 30499200.0],
                      ['1998-12-31', 30247900.0],
                      ['1997-12-31', 29987200.0],
                      ['1996-12-31', 29671900.0],
                      ['1995-12-31', 29354000.0],
                      ['1994-12-31', 29111906.0],
                      ['1993-12-31', 28833410.0],
                      ['1992-12-31', 28519597.0],
                      ['1991-12-31', 28171682.0],
                      ['1990-12-31', 27791000.0],
                      ['1989-12-31', 27379000.0],
                      ['1988-12-31', 26895000.0],
                      ['1987-12-31', 26550000.0],
                      ['1986-12-31', 26204000.0],
                      ['1985-12-31', 25942000.0],
                      ['1984-12-31', 25702000.0],
                      ['1983-12-31', 25456000.0],
                      ['1982-12-31', 25202000.0],
                      ['1981-12-31', 24900000.0],
                      ['1980-12-31', 24593000.0],
                      ['1979-12-31', 24277000.0],
                      ['1978-12-31', 24036000.0],
                      ['1977-12-31', 23796000.0],
                      ['1976-12-31', 23518000.0],
                      ['1975-12-31', 23209000.0],
                      ['1974-12-31', 22774087.0],
                      ['1973-12-31', 22369408.0],
                      ['1972-12-31', 21993631.0],
                      ['1971-12-31', 21645535.0],
                      ['1970-12-31', 21324000.0],
                      ['1969-12-31', 21028000.0],
                      ['1968-12-31', 20744000.0],
                      ['1967-12-31', 20412000.0],
                      ['1966-12-31', 20048000.0],
                      ['1965-12-31', 19678000.0],
                      ['1964-12-31', 19325000.0],
                      ['1963-12-31', 18964000.0],
                      ['1962-12-31', 18614000.0],
                      ['1961-12-31', 18271000.0],
                      ['1960-12-31', 17909009.0],
                      ['1959-12-31', 17502043.0],
                      ['1958-12-31', 17069068.0],
                      ['1957-12-31', 16621973.0],
                      ['1956-12-31', 16174093.0],
                      ['1955-12-31', 15735988.0],
                      ['1954-12-31', 15314040.0],
                      ['1953-12-31', 14909614.0],
                      ['1952-12-31', 14518772.0],
                      ['1951-12-31', 14132558.0],
                      ['1950-12-31', 13736997.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'CAN_SP_POP_TOTL',
             'description': 'Population, total - Canada. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22085407,
             'limit': None,
             'name': 'Population, total - Canada',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:28:54.015Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
CSS

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 7284294.0],
                      ['2016-12-31', 7245472.0],
                      ['2015-12-31', 7204948.0],
                      ['2014-12-31', 7162679.0],
                      ['2013-12-31', 7118888.0],
                      ['2012-12-31', 7074129.0],
                      ['2011-12-31', 7029022.0],
                      ['2010-12-31', 6984096.0],
                      ['2009-12-31', 6939534.0],
                      ['2008-12-31', 6895315.0],
                      ['2007-12-31', 6851221.0],
                      ['2006-12-31', 6806838.0],
                      ['2005-12-31', 6761932.0],
                      ['2004-12-31', 6716373.0],
                      ['2003-12-31', 6670276.0],
                      ['2002-12-31', 6623792.0],
                      ['2001-12-31', 6577216.0],
                      ['2000-12-31', 6530691.0],
                      ['1999-12-31', 6484510.0],
                      ['1998-12-31', 6438587.0],
                      ['1997-12-31', 6392040.0],
                      ['1996-12-31', 6343683.0],
                      ['1995-12-31', 6292827.0],
                      ['1994-12-31', 6238576.0],
                      ['1993-12-31', 6181538.0],
                      ['1992-12-31', 6124265.0],
                      ['1991-12-31', 6070204.0],
                      ['1990-12-31', 6021614.0],
                      ['1989-12-31', 5979907.0],
                      ['1988-12-31', 5943661.0],
                      ['1987-12-31', 5908886.0],
                      ['1986-12-31', 5870023.0],
                      ['1985-12-31', 5823242.0],
                      ['1984-12-31', 5766957.0],
                      ['1983-12-31', 5702754.0],
                      ['1982-12-31', 5633661.0],
                      ['1981-12-31', 5564200.0],
                      ['1980-12-31', 5497756.0],
                      ['1979-12-31', 5435143.0],
                      ['1978-12-31', 5375393.0],
                      ['1977-12-31', 5317542.0],
                      ['1976-12-31', 5260062.0],
                      ['1975-12-31', 5201705.0],
                      ['1974-12-31', 5142246.0],
                      ['1973-12-31', 5082049.0],
                      ['1972-12-31', 5021359.0],
                      ['1971-12-31', 4960647.0],
                      ['1970-12-31', 4900059.0],
                      ['1969-12-31', 4839881.0],
                      ['1968-12-31', 4779624.0],
                      ['1967-12-31', 4718167.0],
                      ['1966-12-31', 4653919.0],
                      ['1965-12-31', 4585777.0],
                      ['1964-12-31', 4513246.0],
                      ['1963-12-31', 4436804.0],
                      ['1962-12-31', 4357746.0],
                      ['1961-12-31', 4277802.0],
                      ['1960-12-31', 4198307.0],
                      ['1959-12-31', 4119746.0],
                      ['1958-12-31', 4041880.0],
                      ['1957-12-31', 3964073.0],
                      ['1956-12-31', 3885646.0],
                      ['1955-12-31', 3806011.0],
                      ['1954-12-31', 3725115.0],
                      ['1953-12-31', 3643135.0],
                      ['1952-12-31', 3560678.0],
                      ['1951-12-31', 3478830.0],
                      ['1950-12-31', 3399006.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'CSS_SP_POP_TOTL',
             'description': 'Population, total - Caribbean small states. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22107383,
             'limit': None,
             'name': 'Population, total - Caribbean small states',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:30:06.870Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
CYM
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 61559.0],
                      ['2016-12-31', 60765.0],
                      ['2015-12-31', 59963.0],
                      ['2014-12-31', 59172.0],
                      ['2013-12-31', 58371.0],
                      ['2012-12-31', 57523.0],
                      ['2011-12-31', 56579.0],
                      ['2010-12-31', 55507.0],
                      ['2009-12-31', 54279.0],
                      ['2008-12-31', 52926.0],
                      ['2007-12-31', 51483.0],
                      ['2006-12-31', 50031.0],
                      ['2005-12-31', 48622.0],
                      ['2004-12-31', 47299.0],
                      ['2003-12-31', 46028.0],
                      ['2002-12-31', 44738.0],
                      ['2001-12-31', 43316.0],
                      ['2000-12-31', 41687.0],
                      ['1999-12-31', 39808.0],
                      ['1998-12-31', 37740.0],
                      ['1997-12-31', 35597.0],
                      ['1996-12-31', 33536.0],
                      ['1995-12-31', 31672.0],
                      ['1994-12-31', 30055.0],
                      ['1993-12-31', 28646.0],
                      ['1992-12-31', 27404.0],
                      ['1991-12-31', 26213.0],
                      ['1990-12-31', 25010.0],
                      ['1989-12-31', 23776.0],
                      ['1988-12-31', 22538.0],
                      ['1987-12-31', 21339.0],
                      ['1986-12-31', 20251.0],
                      ['1985-12-31', 19313.0],
                      ['1984-12-31', 18543.0],
                      ['1983-12-31', 17906.0],
                      ['1982-12-31', 17356.0],
                      ['1981-12-31', 16789.0],
                      ['1980-12-31', 16162.0],
                      ['1979-12-31', 15444.0],
                      ['1978-12-31', 14661.0],
                      ['1977-12-31', 13841.0],
                      ['1976-12-31', 13022.0],
                      ['1975-12-31', 12244.0],
                      ['1974-12-31', 11498.0],
                      ['1973-12-31', 10784.0],
                      ['1972-12-31', 10136.0],
                      ['1971-12-31', 9581.0],
                      ['1970-12-31', 9144.0],
                      ['1969-12-31', 8827.0],
                      ['1968-12-31', 8631.0],
                      ['1967-12-31', 8521.0],
                      ['1966-12-31', 8441.0],
                      ['1965-12-31', 8369.0],
                      ['1964-12-31', 8298.0],
                      ['1963-12-31', 8227.0],
                      ['1962-12-31', 8146.0],
                      ['1961-12-31', 8026.0],
                      ['1960-12-31', 7865.0],
                      ['1959-12-31', 7670.0],
                      ['1958-12-31', 7432.0],
                      ['1957-12-31', 7181.0],
                      ['1956-12-31', 6920.0],
                      ['1955-12-31', 6677.0],
                      ['1954-12-31', 6467.0],
                      ['1953-12-31', 6318.0],
                      ['1952-12-31', 6245.0],
                      ['1951-12-31', 6271.0],
                      ['1950-12-31', 6417.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'CYM_SP_POP_TOTL',
             'description': 'Population, total - Cayman Islands. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22109595,
             'limit': None,
             'name': 'Population, total - Cayman Islands',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:30:14.703Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
CAF
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 4659080.0],
                      ['2016-12-31', 4594621.0],
                      ['2015-12-31', 4546100.0],
                      ['2014-12-31', 4515392.0],
                      ['2013-12-31', 4499653.0],
                      ['2012-12-31', 4490416.0],
                      ['2011-12-31', 4476153.0],
                      ['2010-12-31', 4448525.0],
                      ['2009-12-31', 4404230.0],
                      ['2008-12-31', 4345386.0],
                      ['2007-12-31', 4275800.0],
                      ['2006-12-31', 4201758.0],
                      ['2005-12-31', 4127910.0],
                      ['2004-12-31', 4055036.0],
                      ['2003-12-31', 3981665.0],
                      ['2002-12-31', 3907612.0],
                      ['2001-12-31', 3832203.0],
                      ['2000-12-31', 3754986.0],
                      ['1999-12-31', 3676508.0],
                      ['1998-12-31', 3597385.0],
                      ['1997-12-31', 3517309.0],
                      ['1996-12-31', 3435821.0],
                      ['1995-12-31', 3352767.0],
                      ['1994-12-31', 3267670.0],
                      ['1993-12-31', 3181222.0],
                      ['1992-12-31', 3095807.0],
                      ['1991-12-31', 3014624.0],
                      ['1990-12-31', 2939780.0],
                      ['1989-12-31', 2872668.0],
                      ['1988-12-31', 2812244.0],
                      ['1987-12-31', 2755244.0],
                      ['1986-12-31', 2696982.0],
                      ['1985-12-31', 2634232.0],
                      ['1984-12-31', 2565803.0],
                      ['1983-12-31', 2493135.0],
                      ['1982-12-31', 2418844.0],
                      ['1981-12-31', 2346797.0],
                      ['1980-12-31', 2279821.0],
                      ['1979-12-31', 2218575.0],
                      ['1978-12-31', 2162249.0],
                      ['1977-12-31', 2110457.0],
                      ['1976-12-31', 2062405.0],
                      ['1975-12-31', 2017372.0],
                      ['1974-12-31', 1975521.0],
                      ['1973-12-31', 1936841.0],
                      ['1972-12-31', 1900317.0],
                      ['1971-12-31', 1864598.0],
                      ['1970-12-31', 1828709.0],
                      ['1969-12-31', 1792220.0],
                      ['1968-12-31', 1755344.0],
                      ['1967-12-31', 1718603.0],
                      ['1966-12-31', 1682885.0],
                      ['1965-12-31', 1648833.0],
                      ['1964-12-31', 1616516.0],
                      ['1963-12-31', 1585763.0],
                      ['1962-12-31', 1556661.0],
                      ['1961-12-31', 1529227.0],
                      ['1960-12-31', 1503508.0],
                      ['1959-12-31', 1479470.0],
                      ['1958-12-31', 1457113.0],
                      ['1957-12-31', 1436391.0],
                      ['1956-12-31', 1417218.0],
                      ['1955-12-31', 1399487.0],
                      ['1954-12-31', 1383073.0],
                      ['1953-12-31', 1367797.0],
                      ['1952-12-31', 1353470.0],
                      ['1951-12-31', 1339840.0],
                      ['1950-12-31', 1326652.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'CAF_SP_POP_TOTL',
             'description': 'Population, total - Central African Republic. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22083723,
             'limit': None,
             'name': 'Population, total - Central African Republic',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:28:48.642Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
TCD

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 14899994.0],
                      ['2016-12-31', 14452543.0],
                      ['2015-12-31', 14009413.0],
                      ['2014-12-31', 13569438.0],
                      ['2013-12-31', 13133589.0],
                      ['2012-12-31', 12705135.0],
                      ['2011-12-31', 12288651.0],
                      ['2010-12-31', 11887202.0],
                      ['2009-12-31', 11502786.0],
                      ['2008-12-31', 11133861.0],
                      ['2007-12-31', 10775708.0],
                      ['2006-12-31', 10421597.0],
                      ['2005-12-31', 10067009.0],
                      ['2004-12-31', 9710043.0],
                      ['2003-12-31', 9353201.0],
                      ['2002-12-31', 9001689.0],
                      ['2001-12-31', 8663012.0],
                      ['2000-12-31', 8342559.0],
                      ['1999-12-31', 8041846.0],
                      ['1998-12-31', 7759258.0],
                      ['1997-12-31', 7493251.0],
                      ['1996-12-31', 7241134.0],
                      ['1995-12-31', 7000722.0],
                      ['1994-12-31', 6772133.0],
                      ['1993-12-31', 6555603.0],
                      ['1992-12-31', 6349089.0],
                      ['1991-12-31', 6150081.0],
                      ['1990-12-31', 5956859.0],
                      ['1989-12-31', 5768086.0],
                      ['1988-12-31', 5584339.0],
                      ['1987-12-31', 5408087.0],
                      ['1986-12-31', 5243006.0],
                      ['1985-12-31', 5091535.0],
                      ['1984-12-31', 4954046.0],
                      ['1983-12-31', 4829094.0],
                      ['1982-12-31', 4715197.0],
                      ['1981-12-31', 4610167.0],
                      ['1980-12-31', 4512042.0],
                      ['1979-12-31', 4420716.0],
                      ['1978-12-31', 4335645.0],
                      ['1977-12-31', 4253989.0],
                      ['1976-12-31', 4172230.0],
                      ['1975-12-31', 4087948.0],
                      ['1974-12-31', 3999512.0],
                      ['1973-12-31', 3907632.0],
                      ['1972-12-31', 3815103.0],
                      ['1971-12-31', 3726091.0],
                      ['1970-12-31', 3643549.0],
                      ['1969-12-31', 3568376.0],
                      ['1968-12-31', 3499352.0],
                      ['1967-12-31', 3434811.0],
                      ['1966-12-31', 3372170.0],
                      ['1965-12-31', 3309573.0],
                      ['1964-12-31', 3246505.0],
                      ['1963-12-31', 3183551.0],
                      ['1962-12-31', 3121216.0],
                      ['1961-12-31', 3060355.0],
                      ['1960-12-31', 3001593.0],
                      ['1959-12-31', 2945101.0],
                      ['1958-12-31', 2890635.0],
                      ['1957-12-31', 2837762.0],
                      ['1956-12-31', 2786049.0],
                      ['1955-12-31', 2735208.0],
                      ['1954-12-31', 2685204.0],
                      ['1953-12-31', 2636261.0],
                      ['1952-12-31', 2588905.0],
                      ['1951-12-31', 2543900.0],
                      ['1950-12-31', 2502317.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'TCD_SP_POP_TOTL',
             'description': 'Population, total - Chad. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22266517,
             'limit': None,
             'name': 'Population, total - Chad',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:44:47.100Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
CHI
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 165314.0],
                      ['2016-12-31', 164541.0],
                      ['2015-12-31', 163758.0],
                      ['2014-12-31', 162969.0],
                      ['2013-12-31', 162180.0],
                      ['2012-12-31', 161358.0],
                      ['2011-12-31', 160497.0],
                      ['2010-12-31', 159581.0],
                      ['2009-12-31', 158603.0],
                      ['2008-12-31', 157581.0],
                      ['2007-12-31', 156513.0],
                      ['2006-12-31', 155411.0],
                      ['2005-12-31', 154294.0],
                      ['2004-12-31', 153170.0],
                      ['2003-12-31', 152038.0],
                      ['2002-12-31', 150901.0],
                      ['2001-12-31', 149793.0],
                      ['2000-12-31', 148725.0],
                      ['1999-12-31', 147687.0],
                      ['1998-12-31', 146671.0],
                      ['1997-12-31', 145715.0],
                      ['1996-12-31', 144829.0],
                      ['1995-12-31', 144046.0],
                      ['1994-12-31', 143384.0],
                      ['1993-12-31', 142819.0],
                      ['1992-12-31', 142258.0],
                      ['1991-12-31', 141568.0],
                      ['1990-12-31', 140671.0],
                      ['1989-12-31', 139530.0],
                      ['1988-12-31', 138187.0],
                      ['1987-12-31', 136716.0],
                      ['1986-12-31', 135230.0],
                      ['1985-12-31', 133808.0],
                      ['1984-12-31', 132453.0],
                      ['1983-12-31', 131156.0],
                      ['1982-12-31', 129979.0],
                      ['1981-12-31', 128981.0],
                      ['1980-12-31', 128212.0],
                      ['1979-12-31', 127692.0],
                      ['1978-12-31', 127390.0],
                      ['1977-12-31', 127183.0],
                      ['1976-12-31', 126902.0],
                      ['1975-12-31', 126415.0],
                      ['1974-12-31', 125682.0],
                      ['1973-12-31', 124725.0],
                      ['1972-12-31', 123614.0],
                      ['1971-12-31', 122413.0],
                      ['1970-12-31', 121197.0],
                      ['1969-12-31', 119972.0],
                      ['1968-12-31', 118726.0],
                      ['1967-12-31', 117474.0],
                      ['1966-12-31', 116227.0],
                      ['1965-12-31', 114995.0],
                      ['1964-12-31', 113773.0],
                      ['1963-12-31', 112595.0],
                      ['1962-12-31', 111457.0],
                      ['1961-12-31', 110399.0],
                      ['1960-12-31', 109420.0],
                      ['1959-12-31', 108525.0],
                      ['1958-12-31', 107711.0],
                      ['1957-12-31', 106968.0],
                      ['1956-12-31', 106268.0],
                      ['1955-12-31', 105609.0],
                      ['1954-12-31', 104972.0],
                      ['1953-12-31', 104323.0],
                      ['1952-12-31', 103661.0],
                      ['1951-12-31', 102967.0],
                      ['1950-12-31', 102234.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'CHI_SP_POP_TOTL',
             'description': 'Population, total - Channel Islands. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22087740,
             'limit': None,
             'name': 'Population, total - Channel Islands',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:29:01.078Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
CHL

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 18054726.0],
                      ['2016-12-31', 17909754.0],
                      ['2015-12-31', 17762681.0],
                      ['2014-12-31', 17613798.0],
                      ['2013-12-31', 17462982.0],
                      ['2012-12-31', 17309746.0],
                      ['2011-12-31', 17153357.0],
                      ['2010-12-31', 16993354.0],
                      ['2009-12-31', 16829442.0],
                      ['2008-12-31', 16661942.0],
                      ['2007-12-31', 16491687.0],
                      ['2006-12-31', 16319792.0],
                      ['2005-12-31', 16147064.0],
                      ['2004-12-31', 15973778.0],
                      ['2003-12-31', 15799542.0],
                      ['2002-12-31', 15623635.0],
                      ['2001-12-31', 15444969.0],
                      ['2000-12-31', 15262754.0],
                      ['1999-12-31', 15076952.0],
                      ['1998-12-31', 14887756.0],
                      ['1997-12-31', 14694835.0],
                      ['1996-12-31', 14497826.0],
                      ['1995-12-31', 14296613.0],
                      ['1994-12-31', 14091389.0],
                      ['1993-12-31', 13882668.0],
                      ['1992-12-31', 13671033.0],
                      ['1991-12-31', 13457244.0],
                      ['1990-12-31', 13242132.0],
                      ['1989-12-31', 13025797.0],
                      ['1988-12-31', 12809025.0],
                      ['1987-12-31', 12594145.0],
                      ['1986-12-31', 12384108.0],
                      ['1985-12-31', 12181028.0],
                      ['1984-12-31', 11985658.0],
                      ['1983-12-31', 11797534.0],
                      ['1982-12-31', 11615836.0],
                      ['1981-12-31', 11439144.0],
                      ['1980-12-31', 11266226.0],
                      ['1979-12-31', 11096868.0],
                      ['1978-12-31', 10930783.0],
                      ['1977-12-31', 10766419.0],
                      ['1976-12-31', 10601836.0],
                      ['1975-12-31', 10435534.0],
                      ['1974-12-31', 10267056.0],
                      ['1973-12-31', 10096295.0],
                      ['1972-12-31', 9922558.0],
                      ['1971-12-31', 9745189.0],
                      ['1970-12-31', 9563865.0],
                      ['1969-12-31', 9378243.0],
                      ['1968-12-31', 9188822.0],
                      ['1967-12-31', 8997325.0],
                      ['1966-12-31', 8806137.0],
                      ['1965-12-31', 8617077.0],
                      ['1964-12-31', 8430838.0],
                      ['1963-12-31', 8247415.0],
                      ['1962-12-31', 8067136.0],
                      ['1961-12-31', 7890156.0],
                      ['1960-12-31', 7716625.0],
                      ['1959-12-31', 7546713.0],
                      ['1958-12-31', 7380642.0],
                      ['1957-12-31', 7218587.0],
                      ['1956-12-31', 7060663.0],
                      ['1955-12-31', 6906838.0],
                      ['1954-12-31', 6756969.0],
                      ['1953-12-31', 6610731.0],
                      ['1952-12-31', 6467640.0],
                      ['1951-12-31', 6327085.0],
                      ['1950-12-31', 6188284.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'CHL_SP_POP_TOTL',
             'description': 'Population, total - Chile. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22089205,
             'limit': None,
             'name': 'Population, total - Chile',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:29:05.690Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
CHN
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 1386395000.0],
                      ['2016-12-31', 1378665000.0],
                      ['2015-12-31', 1371220000.0],
                      ['2014-12-31', 1364270000.0],
                      ['2013-12-31', 1357380000.0],
                      ['2012-12-31', 1350695000.0],
                      ['2011-12-31', 1344130000.0],
                      ['2010-12-31', 1337705000.0],
                      ['2009-12-31', 1331260000.0],
                      ['2008-12-31', 1324655000.0],
                      ['2007-12-31', 1317885000.0],
                      ['2006-12-31', 1311020000.0],
                      ['2005-12-31', 1303720000.0],
                      ['2004-12-31', 1296075000.0],
                      ['2003-12-31', 1288400000.0],
                      ['2002-12-31', 1280400000.0],
                      ['2001-12-31', 1271850000.0],
                      ['2000-12-31', 1262645000.0],
                      ['1999-12-31', 1252735000.0],
                      ['1998-12-31', 1241935000.0],
                      ['1997-12-31', 1230075000.0],
                      ['1996-12-31', 1217550000.0],
                      ['1995-12-31', 1204855000.0],
                      ['1994-12-31', 1191835000.0],
                      ['1993-12-31', 1178440000.0],
                      ['1992-12-31', 1164970000.0],
                      ['1991-12-31', 1150780000.0],
                      ['1990-12-31', 1135185000.0],
                      ['1989-12-31', 1118650000.0],
                      ['1988-12-31', 1101630000.0],
                      ['1987-12-31', 1084035000.0],
                      ['1986-12-31', 1066790000.0],
                      ['1985-12-31', 1051040000.0],
                      ['1984-12-31', 1036825000.0],
                      ['1983-12-31', 1023310000.0],
                      ['1982-12-31', 1008630000.0],
                      ['1981-12-31', 993885000.0],
                      ['1980-12-31', 981235000.0],
                      ['1979-12-31', 969005000.0],
                      ['1978-12-31', 956165000.0],
                      ['1977-12-31', 943455000.0],
                      ['1976-12-31', 930685000.0],
                      ['1975-12-31', 916395000.0],
                      ['1974-12-31', 900350000.0],
                      ['1973-12-31', 881940000.0],
                      ['1972-12-31', 862030000.0],
                      ['1971-12-31', 841105000.0],
                      ['1970-12-31', 818315000.0],
                      ['1969-12-31', 796025000.0],
                      ['1968-12-31', 774510000.0],
                      ['1967-12-31', 754550000.0],
                      ['1966-12-31', 735400000.0],
                      ['1965-12-31', 715185000.0],
                      ['1964-12-31', 698355000.0],
                      ['1963-12-31', 682335000.0],
                      ['1962-12-31', 665770000.0],
                      ['1961-12-31', 660330000.0],
                      ['1960-12-31', 667070000.0],
                      ['1959-12-31', 654954856.0],
                      ['1958-12-31', 643059744.0],
                      ['1957-12-31', 631380668.0],
                      ['1956-12-31', 619913704.0],
                      ['1955-12-31', 608655000.0],
                      ['1954-12-31', 595751355.0],
                      ['1953-12-31', 583121271.0],
                      ['1952-12-31', 570758949.0],
                      ['1951-12-31', 558658710.0],
                      ['1950-12-31', 546815000.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'CHN_SP_POP_TOTL',
             'description': 'Population, total - China. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22091060,
             'limit': None,
             'name': 'Population, total - China',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:29:11.276Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
COL

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 49065615.0],
                      ['2016-12-31', 48653419.0],
                      ['2015-12-31', 48228697.0],
                      ['2014-12-31', 47791911.0],
                      ['2013-12-31', 47342981.0],
                      ['2012-12-31', 46881475.0],
                      ['2011-12-31', 46406646.0],
                      ['2010-12-31', 45918097.0],
                      ['2009-12-31', 45416181.0],
                      ['2008-12-31', 44901544.0],
                      ['2007-12-31', 44374572.0],
                      ['2006-12-31', 43835722.0],
                      ['2005-12-31', 43285634.0],
                      ['2004-12-31', 42724163.0],
                      ['2003-12-31', 42152151.0],
                      ['2002-12-31', 41572491.0],
                      ['2001-12-31', 40988909.0],
                      ['2000-12-31', 40403958.0],
                      ['1999-12-31', 39819279.0],
                      ['1998-12-31', 39234062.0],
                      ['1997-12-31', 38645411.0],
                      ['1996-12-31', 38049038.0],
                      ['1995-12-31', 37441977.0],
                      ['1994-12-31', 36823537.0],
                      ['1993-12-31', 36195168.0],
                      ['1992-12-31', 35558682.0],
                      ['1991-12-31', 34916766.0],
                      ['1990-12-31', 34271565.0],
                      ['1989-12-31', 33624444.0],
                      ['1988-12-31', 32975535.0],
                      ['1987-12-31', 32324325.0],
                      ['1986-12-31', 31669776.0],
                      ['1985-12-31', 31011688.0],
                      ['1984-12-31', 30350086.0],
                      ['1983-12-31', 29687094.0],
                      ['1982-12-31', 29027162.0],
                      ['1981-12-31', 28375991.0],
                      ['1980-12-31', 27737900.0],
                      ['1979-12-31', 27113512.0],
                      ['1978-12-31', 26502166.0],
                      ['1977-12-31', 25905127.0],
                      ['1976-12-31', 25323406.0],
                      ['1975-12-31', 24756973.0],
                      ['1974-12-31', 24208021.0],
                      ['1973-12-31', 23674504.0],
                      ['1972-12-31', 23146803.0],
                      ['1971-12-31', 22611986.0],
                      ['1970-12-31', 22061215.0],
                      ['1969-12-31', 21490945.0],
                      ['1968-12-31', 20905059.0],
                      ['1967-12-31', 20311371.0],
                      ['1966-12-31', 19721462.0],
                      ['1965-12-31', 19144223.0],
                      ['1964-12-31', 18581974.0],
                      ['1963-12-31', 18033550.0],
                      ['1962-12-31', 17500171.0],
                      ['1961-12-31', 16982315.0],
                      ['1960-12-31', 16480383.0],
                      ['1959-12-31', 15994889.0],
                      ['1958-12-31', 15526390.0],
                      ['1957-12-31', 15075305.0],
                      ['1956-12-31', 14641720.0],
                      ['1955-12-31', 14225204.0],
                      ['1954-12-31', 13824726.0],
                      ['1953-12-31', 13438645.0],
                      ['1952-12-31', 13064689.0],
                      ['1951-12-31', 12699952.0],
                      ['1950-12-31', 12340899.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'COL_SP_POP_TOTL',
             'description': 'Population, total - Colombia. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22100867,
             'limit': None,
             'name': 'Population, total - Colombia',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:29:44.138Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
COM
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 813912.0],
                      ['2016-12-31', 795601.0],
                      ['2015-12-31', 777424.0],
                      ['2014-12-31', 759385.0],
                      ['2013-12-31', 741500.0],
                      ['2012-12-31', 723868.0],
                      ['2011-12-31', 706569.0],
                      ['2010-12-31', 689692.0],
                      ['2009-12-31', 673252.0],
                      ['2008-12-31', 657229.0],
                      ['2007-12-31', 641620.0],
                      ['2006-12-31', 626425.0],
                      ['2005-12-31', 611627.0],
                      ['2004-12-31', 597228.0],
                      ['2003-12-31', 583211.0],
                      ['2002-12-31', 569479.0],
                      ['2001-12-31', 555888.0],
                      ['2000-12-31', 542357.0],
                      ['1999-12-31', 528848.0],
                      ['1998-12-31', 515385.0],
                      ['1997-12-31', 501953.0],
                      ['1996-12-31', 488627.0],
                      ['1995-12-31', 475394.0],
                      ['1994-12-31', 462277.0],
                      ['1993-12-31', 449274.0],
                      ['1992-12-31', 436448.0],
                      ['1991-12-31', 423872.0],
                      ['1990-12-31', 411594.0],
                      ['1989-12-31', 399632.0],
                      ['1988-12-31', 387963.0],
                      ['1987-12-31', 376654.0],
                      ['1986-12-31', 365760.0],
                      ['1985-12-31', 355337.0],
                      ['1984-12-31', 345466.0],
                      ['1983-12-31', 336096.0],
                      ['1982-12-31', 326946.0],
                      ['1981-12-31', 317606.0],
                      ['1980-12-31', 307829.0],
                      ['1979-12-31', 297447.0],
                      ['1978-12-31', 286634.0],
                      ['1977-12-31', 275900.0],
                      ['1976-12-31', 265953.0],
                      ['1975-12-31', 257290.0],
                      ['1974-12-31', 250104.0],
                      ['1973-12-31', 244208.0],
                      ['1972-12-31', 239235.0],
                      ['1971-12-31', 234644.0],
                      ['1970-12-31', 230054.0],
                      ['1969-12-31', 225325.0],
                      ['1968-12-31', 220575.0],
                      ['1967-12-31', 215897.0],
                      ['1966-12-31', 211478.0],
                      ['1965-12-31', 207424.0],
                      ['1964-12-31', 203753.0],
                      ['1963-12-31', 200372.0],
                      ['1962-12-31', 197198.0],
                      ['1961-12-31', 194139.0],
                      ['1960-12-31', 191121.0],
                      ['1959-12-31', 188097.0],
                      ['1958-12-31', 185043.0],
                      ['1957-12-31', 181992.0],
                      ['1956-12-31', 178946.0],
                      ['1955-12-31', 175903.0],
                      ['1954-12-31', 172853.0],
                      ['1953-12-31', 169752.0],
                      ['1952-12-31', 166541.0],
                      ['1951-12-31', 163139.0],
                      ['1950-12-31', 159459.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'COM_SP_POP_TOTL',
             'description': 'Population, total - Comoros. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22102483,
             'limit': None,
             'name': 'Population, total - Comoros',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:29:50.056Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
COD
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],

             'data': [['2017-12-31', 81339988.0],
                      ['2016-12-31', 78736153.0],
                      ['2015-12-31', 76196619.0],
                      ['2014-12-31', 73722860.0],
                      ['2013-12-31', 71316033.0],
                      ['2012-12-31', 68978682.0],
                      ['2011-12-31', 66713597.0],
                      ['2010-12-31', 64523263.0],
                      ['2009-12-31', 62409435.0],
                      ['2008-12-31', 60373608.0],
                      ['2007-12-31', 58417562.0],
                      ['2006-12-31', 56543011.0],
                      ['2005-12-31', 54751476.0],
                      ['2004-12-31', 53034217.0],
                      ['2003-12-31', 51390033.0],
                      ['2002-12-31', 49835756.0],
                      ['2001-12-31', 48394338.0],
                      ['2000-12-31', 47076387.0],
                      ['1999-12-31', 45898667.0],
                      ['1998-12-31', 44840529.0],
                      ['1997-12-31', 43830146.0],
                      ['1996-12-31', 42770544.0],
                      ['1995-12-31', 41595744.0],
                      ['1994-12-31', 40273701.0],
                      ['1993-12-31', 38833595.0],
                      ['1992-12-31', 37346147.0],
                      ['1991-12-31', 35914825.0],
                      ['1990-12-31', 34614581.0],
                      ['1989-12-31', 33465441.0],
                      ['1988-12-31', 32444156.0],
                      ['1987-12-31', 31529823.0],
                      ['1986-12-31', 30685824.0],
                      ['1985-12-31', 29883446.0],
                      ['1984-12-31', 29121474.0],
                      ['1983-12-31', 28404876.0],
                      ['1982-12-31', 27717337.0],
                      ['1981-12-31', 27039468.0],
                      ['1980-12-31', 26357462.0],
                      ['1979-12-31', 25661884.0],
                      ['1978-12-31', 24954655.0],
                      ['1977-12-31', 24247550.0],
                      ['1976-12-31', 23559071.0],
                      ['1975-12-31', 22902319.0],
                      ['1974-12-31', 22280923.0],
                      ['1973-12-31', 21689239.0],
                      ['1972-12-31', 21120140.0],
                      ['1971-12-31', 20562865.0],
                      ['1970-12-31', 20009935.0],
                      ['1969-12-31', 19458904.0],
                      ['1968-12-31', 18913203.0],
                      ['1967-12-31', 18378214.0],
                      ['1966-12-31', 17861881.0],
                      ['1965-12-31', 17369883.0],
                      ['1964-12-31', 16903923.0],
                      ['1963-12-31', 16461930.0],
                      ['1962-12-31', 16041263.0],
                      ['1961-12-31', 15637733.0],
                      ['1960-12-31', 15248251.0],
                      ['1959-12-31', 14871772.0],
                      ['1958-12-31', 14508912.0],
                      ['1957-12-31', 14161242.0],
                      ['1956-12-31', 13830440.0],
                      ['1955-12-31', 13517513.0],
                      ['1954-12-31', 13222518.0],
                      ['1953-12-31', 12944385.0],
                      ['1952-12-31', 12680927.0],
                      ['1951-12-31', 12428825.0],
                      ['1950-12-31', 12183659.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'COD_SP_POP_TOTL',
             'description': 'Population, total - Congo, Dem. Rep.. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22096886,
             'limit': None,
             'name': 'Population, total - Congo, Dem. Rep.',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:29:31.124Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
COG
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 5260750.0],
                      ['2016-12-31', 5125821.0],
                      ['2015-12-31', 4995648.0],
                      ['2014-12-31', 4871101.0],
                      ['2013-12-31', 4751393.0],
                      ['2012-12-31', 4633363.0],
                      ['2011-12-31', 4512730.0],
                      ['2010-12-31', 4386693.0],
                      ['2009-12-31', 4253712.0],
                      ['2008-12-31', 4115435.0],
                      ['2007-12-31', 3976246.0],
                      ['2006-12-31', 3842365.0],
                      ['2005-12-31', 3718243.0],
                      ['2004-12-31', 3605439.0],
                      ['2003-12-31', 3502519.0],
                      ['2002-12-31', 3407180.0],
                      ['2001-12-31', 3315806.0],
                      ['2000-12-31', 3225727.0],
                      ['1999-12-31', 3136344.0],
                      ['1998-12-31', 3048453.0],
                      ['1997-12-31', 2962470.0],
                      ['1996-12-31', 2879222.0],
                      ['1995-12-31', 2799255.0],
                      ['1994-12-31', 2722497.0],
                      ['1993-12-31', 2648507.0],
                      ['1992-12-31', 2577035.0],
                      ['1991-12-31', 2507772.0],
                      ['1990-12-31', 2440457.0],
                      ['1989-12-31', 2375008.0],
                      ['1988-12-31', 2311348.0],
                      ['1987-12-31', 2249146.0],
                      ['1986-12-31', 2188046.0],
                      ['1985-12-31', 2127770.0],
                      ['1984-12-31', 2068132.0],
                      ['1983-12-31', 2009165.0],
                      ['1982-12-31', 1951195.0],
                      ['1981-12-31', 1894676.0],
                      ['1980-12-31', 1839935.0],
                      ['1979-12-31', 1787129.0],
                      ['1978-12-31', 1736099.0],
                      ['1977-12-31', 1686524.0],
                      ['1976-12-31', 1637941.0],
                      ['1975-12-31', 1590039.0],
                      ['1974-12-31', 1542690.0],
                      ['1973-12-31', 1496047.0],
                      ['1972-12-31', 1450518.0],
                      ['1971-12-31', 1406643.0],
                      ['1970-12-31', 1364812.0],
                      ['1969-12-31', 1325147.0],
                      ['1968-12-31', 1287516.0],
                      ['1967-12-31', 1251703.0],
                      ['1966-12-31', 1217391.0],
                      ['1965-12-31', 1184316.0],
                      ['1964-12-31', 1152412.0],
                      ['1963-12-31', 1121735.0],
                      ['1962-12-31', 1092292.0],
                      ['1961-12-31', 1064111.0],
                      ['1960-12-31', 1037220.0],
                      ['1959-12-31', 1011584.0],
                      ['1958-12-31', 987142.0],
                      ['1957-12-31', 963824.0],
                      ['1956-12-31', 941536.0],
                      ['1955-12-31', 920218.0],
                      ['1954-12-31', 899822.0],
                      ['1953-12-31', 880318.0],
                      ['1952-12-31', 861706.0],
                      ['1951-12-31', 844004.0],
                      ['1950-12-31', 827252.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'COG_SP_POP_TOTL',
             'description': 'Population, total - Congo, Rep.. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22098887,
             'limit': None,
             'name': 'Population, total - Congo, Rep.',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:29:37.793Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
CRI

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 4905769.0],
                      ['2016-12-31', 4857274.0],
                      ['2015-12-31', 4807852.0],
                      ['2014-12-31', 4757575.0],
                      ['2013-12-31', 4706401.0],
                      ['2012-12-31', 4654122.0],
                      ['2011-12-31', 4600474.0],
                      ['2010-12-31', 4545280.0],
                      ['2009-12-31', 4488263.0],
                      ['2008-12-31', 4429508.0],
                      ['2007-12-31', 4369469.0],
                      ['2006-12-31', 4308794.0],
                      ['2005-12-31', 4247841.0],
                      ['2004-12-31', 4187038.0],
                      ['2003-12-31', 4125971.0],
                      ['2002-12-31', 4063204.0],
                      ['2001-12-31', 3996798.0],
                      ['2000-12-31', 3925443.0],
                      ['1999-12-31', 3848723.0],
                      ['1998-12-31', 3767373.0],
                      ['1997-12-31', 3682725.0],
                      ['1996-12-31', 3596732.0],
                      ['1995-12-31', 3510926.0],
                      ['1994-12-31', 3425690.0],
                      ['1993-12-31', 3341004.0],
                      ['1992-12-31', 3257466.0],
                      ['1991-12-31', 3175649.0],
                      ['1990-12-31', 3095995.0],
                      ['1989-12-31', 3018955.0],
                      ['1988-12-31', 2944557.0],
                      ['1987-12-31', 2872211.0],
                      ['1986-12-31', 2800986.0],
                      ['1985-12-31', 2730233.0],
                      ['1984-12-31', 2659781.0],
                      ['1983-12-31', 2589930.0],
                      ['1982-12-31', 2521168.0],
                      ['1981-12-31', 2454129.0],
                      ['1980-12-31', 2389310.0],
                      ['1979-12-31', 2326704.0],
                      ['1978-12-31', 2266154.0],
                      ['1977-12-31', 2207725.0],
                      ['1976-12-31', 2151497.0],
                      ['1975-12-31', 2097407.0],
                      ['1974-12-31', 2045580.0],
                      ['1973-12-31', 1995743.0],
                      ['1972-12-31', 1947048.0],
                      ['1971-12-31', 1898360.0],
                      ['1970-12-31', 1848866.0],
                      ['1969-12-31', 1798311.0],
                      ['1968-12-31', 1746869.0],
                      ['1967-12-31', 1694710.0],
                      ['1966-12-31', 1642186.0],
                      ['1965-12-31', 1589621.0],
                      ['1964-12-31', 1537041.0],
                      ['1963-12-31', 1484510.0],
                      ['1962-12-31', 1432585.0],
                      ['1961-12-31', 1381917.0],
                      ['1960-12-31', 1333040.0],
                      ['1959-12-31', 1286229.0],
                      ['1958-12-31', 1241553.0],
                      ['1957-12-31', 1198942.0],
                      ['1956-12-31', 1158318.0],
                      ['1955-12-31', 1119617.0],
                      ['1954-12-31', 1082877.0],
                      ['1953-12-31', 1048214.0],
                      ['1952-12-31', 1015879.0],
                      ['1951-12-31', 986156.0],
                      ['1950-12-31', 959495.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'CRI_SP_POP_TOTL',
             'description': 'Population, total - Costa Rica. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22105896,
             'limit': None,
             'name': 'Population, total - Costa Rica',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:30:02.249Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
CIV
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 24294750.0],
                      ['2016-12-31', 23695919.0],
                      ['2015-12-31', 23108472.0],
                      ['2014-12-31', 22531350.0],
                      ['2013-12-31', 21966312.0],
                      ['2012-12-31', 21418603.0],
                      ['2011-12-31', 20895311.0],
                      ['2010-12-31', 20401331.0],
                      ['2009-12-31', 19936366.0],
                      ['2008-12-31', 19497986.0],
                      ['2007-12-31', 19085941.0],
                      ['2006-12-31', 18699435.0],
                      ['2005-12-31', 18336303.0],
                      ['2004-12-31', 17997738.0],
                      ['2003-12-31', 17679355.0],
                      ['2002-12-31', 17366517.0],
                      ['2001-12-31', 17040152.0],
                      ['2000-12-31', 16686561.0],
                      ['1999-12-31', 16300233.0],
                      ['1998-12-31', 15884552.0],
                      ['1997-12-31', 15445986.0],
                      ['1996-12-31', 14995249.0],
                      ['1995-12-31', 14540820.0],
                      ['1994-12-31', 14083611.0],
                      ['1993-12-31', 13622731.0],
                      ['1992-12-31', 13163019.0],
                      ['1991-12-31', 12710008.0],
                      ['1990-12-31', 12267754.0],
                      ['1989-12-31', 11839243.0],
                      ['1988-12-31', 11424260.0],
                      ['1987-12-31', 11019651.0],
                      ['1986-12-31', 10620267.0],
                      ['1985-12-31', 10222558.0],
                      ['1984-12-31', 9826055.0],
                      ['1983-12-31', 9432731.0],
                      ['1982-12-31', 9044473.0],
                      ['1981-12-31', 8664057.0],
                      ['1980-12-31', 8293675.0],
                      ['1979-12-31', 7934279.0],
                      ['1978-12-31', 7585914.0],
                      ['1977-12-31', 7248828.0],
                      ['1976-12-31', 6922982.0],
                      ['1975-12-31', 6608609.0],
                      ['1974-12-31', 6305287.0],
                      ['1973-12-31', 6013862.0],
                      ['1972-12-31', 5737281.0],
                      ['1971-12-31', 5479338.0],
                      ['1970-12-31', 5242395.0],
                      ['1969-12-31', 5027971.0],
                      ['1968-12-31', 4834279.0],
                      ['1967-12-31', 4656353.0],
                      ['1966-12-31', 4487204.0],
                      ['1965-12-31', 4321791.0],
                      ['1964-12-31', 4157965.0],
                      ['1963-12-31', 3996941.0],
                      ['1962-12-31', 3841071.0],
                      ['1961-12-31', 3694205.0],
                      ['1960-12-31', 3558988.0],
                      ['1959-12-31', 3435930.0],
                      ['1958-12-31', 3323761.0],
                      ['1957-12-31', 3220159.0],
                      ['1956-12-31', 3122628.0],
                      ['1955-12-31', 3029303.0],
                      ['1954-12-31', 2939219.0],
                      ['1953-12-31', 2852498.0],
                      ['1952-12-31', 2770362.0],
                      ['1951-12-31', 2695115.0],
                      ['1950-12-31', 2630131.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'CIV_SP_POP_TOTL',
             'description': "Population, total - Cote d'Ivoire. ",
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22093029,
             'limit': None,
             'name': "Population, total - Cote d'Ivoire",
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:29:17.856Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
HRV

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 4125700.0],
                      ['2016-12-31', 4174349.0],
                      ['2015-12-31', 4203604.0],
                      ['2014-12-31', 4238389.0],
                      ['2013-12-31', 4255689.0],
                      ['2012-12-31', 4267558.0],
                      ['2011-12-31', 4280622.0],
                      ['2010-12-31', 4417781.0],
                      ['2009-12-31', 4429078.0],
                      ['2008-12-31', 4434508.0],
                      ['2007-12-31', 4436000.0],
                      ['2006-12-31', 4440000.0],
                      ['2005-12-31', 4442000.0],
                      ['2004-12-31', 4439000.0],
                      ['2003-12-31', 4440000.0],
                      ['2002-12-31', 4440000.0],
                      ['2001-12-31', 4440000.0],
                      ['2000-12-31', 4426000.0],
                      ['1999-12-31', 4554000.0],
                      ['1998-12-31', 4501000.0],
                      ['1997-12-31', 4572000.0],
                      ['1996-12-31', 4494000.0],
                      ['1995-12-31', 4669000.0],
                      ['1994-12-31', 4650000.0],
                      ['1993-12-31', 4640000.0],
                      ['1992-12-31', 4470000.0],
                      ['1991-12-31', 4510000.0],
                      ['1990-12-31', 4780000.0],
                      ['1989-12-31', 4767000.0],
                      ['1988-12-31', 4757000.0],
                      ['1987-12-31', 4740000.0],
                      ['1986-12-31', 4722000.0],
                      ['1985-12-31', 4701000.0],
                      ['1984-12-31', 4680000.0],
                      ['1983-12-31', 4659000.0],
                      ['1982-12-31', 4635000.0],
                      ['1981-12-31', 4608000.0],
                      ['1980-12-31', 4588000.0],
                      ['1979-12-31', 4571000.0],
                      ['1978-12-31', 4556000.0],
                      ['1977-12-31', 4532000.0],
                      ['1976-12-31', 4530000.0],
                      ['1975-12-31', 4514000.0],
                      ['1974-12-31', 4497000.0],
                      ['1973-12-31', 4478000.0],
                      ['1972-12-31', 4457000.0],
                      ['1971-12-31', 4435000.0],
                      ['1970-12-31', 4411000.0],
                      ['1969-12-31', 4387000.0],
                      ['1968-12-31', 4364000.0],
                      ['1967-12-31', 4339000.0],
                      ['1966-12-31', 4313000.0],
                      ['1965-12-31', 4287000.0],
                      ['1964-12-31', 4259680.0],
                      ['1963-12-31', 4231408.0],
                      ['1962-12-31', 4202104.0],
                      ['1961-12-31', 4171672.0],
                      ['1960-12-31', 4140000.0],
                      ['1959-12-31', 4114282.0],
                      ['1958-12-31', 4088725.0],
                      ['1957-12-31', 4063326.0],
                      ['1956-12-31', 4038084.0],
                      ['1955-12-31', 4013000.0],
                      ['1954-12-31', 3980064.0],
                      ['1953-12-31', 3947398.0],
                      ['1952-12-31', 3915000.0],
                      ['1951-12-31', 3882868.0],
                      ['1950-12-31', 3851000.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'HRV_SP_POP_TOTL',
             'description': 'Population, total - Croatia. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22177230,
             'limit': None,
             'name': 'Population, total - Croatia',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:33:59.357Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
CUB
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 11484636.0],
                      ['2016-12-31', 11475982.0],
                      ['2015-12-31', 11461432.0],
                      ['2014-12-31', 11439767.0],
                      ['2013-12-31', 11412167.0],
                      ['2012-12-31', 11382146.0],
                      ['2011-12-31', 11354651.0],
                      ['2010-12-31', 11333051.0],
                      ['2009-12-31', 11318602.0],
                      ['2008-12-31', 11309754.0],
                      ['2007-12-31', 11303687.0],
                      ['2006-12-31', 11296233.0],
                      ['2005-12-31', 11284253.0],
                      ['2004-12-31', 11266941.0],
                      ['2003-12-31', 11244885.0],
                      ['2002-12-31', 11217998.0],
                      ['2001-12-31', 11186542.0],
                      ['2000-12-31', 11150736.0],
                      ['1999-12-31', 11110004.0],
                      ['1998-12-31', 11064097.0],
                      ['1997-12-31', 11013983.0],
                      ['1996-12-31', 10961012.0],
                      ['1995-12-31', 10906043.0],
                      ['1994-12-31', 10850585.0],
                      ['1993-12-31', 10794135.0],
                      ['1992-12-31', 10733363.0],
                      ['1991-12-31', 10663585.0],
                      ['1990-12-31', 10582081.0],
                      ['1989-12-31', 10486509.0],
                      ['1988-12-31', 10379548.0],
                      ['1987-12-31', 10269567.0],
                      ['1986-12-31', 10168087.0],
                      ['1985-12-31', 10082989.0],
                      ['1984-12-31', 10017059.0],
                      ['1983-12-31', 9966733.0],
                      ['1982-12-31', 9925623.0],
                      ['1981-12-31', 9884213.0],
                      ['1980-12-31', 9835177.0],
                      ['1979-12-31', 9777290.0],
                      ['1978-12-31', 9711392.0],
                      ['1977-12-31', 9634680.0],
                      ['1976-12-31', 9544271.0],
                      ['1975-12-31', 9438442.0],
                      ['1974-12-31', 9315373.0],
                      ['1973-12-31', 9176052.0],
                      ['1972-12-31', 9025300.0],
                      ['1971-12-31', 8869961.0],
                      ['1970-12-31', 8715123.0],
                      ['1969-12-31', 8563193.0],
                      ['1968-12-31', 8413327.0],
                      ['1967-12-31', 8263546.0],
                      ['1966-12-31', 8110430.0],
                      ['1965-12-31', 7951933.0],
                      ['1964-12-31', 7787146.0],
                      ['1963-12-31', 7618354.0],
                      ['1962-12-31', 7450402.0],
                      ['1961-12-31', 7289826.0],
                      ['1960-12-31', 7141135.0],
                      ['1959-12-31', 7005481.0],
                      ['1958-12-31', 6881210.0],
                      ['1957-12-31', 6764786.0],
                      ['1956-12-31', 6652090.0],
                      ['1955-12-31', 6539469.0],
                      ['1954-12-31', 6424172.0],
                      ['1953-12-31', 6304523.0],
                      ['1952-12-31', 6180031.0],
                      ['1951-12-31', 6051291.0],
                      ['1950-12-31', 5919993.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'CUB_SP_POP_TOTL',
             'description': 'Population, total - Cuba. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22108799,
             'limit': None,
             'name': 'Population, total - Cuba',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:30:11.196Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
CUW

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 161014.0],
                      ['2016-12-31', 159663.0],
                      ['2015-12-31', 157980.0],
                      ['2014-12-31', 155909.0],
                      ['2013-12-31', 153822.0],
                      ['2012-12-31', 152088.0],
                      ['2011-12-31', 150831.0],
                      ['2010-12-31', 148703.0],
                      ['2009-12-31', 146833.0],
                      ['2008-12-31', 145880.0],
                      ['2007-12-31', 144056.0],
                      ['2006-12-31', 141239.0],
                      ['2005-12-31', 137658.0],
                      ['2004-12-31', 134192.0],
                      ['2003-12-31', 131897.0],
                      ['2002-12-31', 129205.0],
                      ['2001-12-31', 129047.0],
                      ['2000-12-31', 133860.0],
                      ['1999-12-31', 139428.0],
                      ['1998-12-31', 144472.0],
                      ['1997-12-31', 146956.0],
                      ['1996-12-31', 146306.0],
                      ['1995-12-31', 145139.0],
                      ['1994-12-31', 144630.0],
                      ['1993-12-31', 144299.0],
                      ['1992-12-31', 143912.0],
                      ['1991-12-31', 144403.0],
                      ['1990-12-31', 145400.0],
                      ['1989-12-31', 146937.0],
                      ['1988-12-31', 149254.0],
                      ['1987-12-31', 151456.0],
                      ['1986-12-31', 152662.0],
                      ['1985-12-31', 152711.0],
                      ['1984-12-31', 151940.0],
                      ['1983-12-31', 151159.0],
                      ['1982-12-31', 150101.0],
                      ['1981-12-31', 148629.0],
                      ['1980-12-31', 148041.0],
                      ['1979-12-31', 147851.0],
                      ['1978-12-31', 148341.0],
                      ['1977-12-31', 149459.0],
                      ['1976-12-31', 149399.0],
                      ['1975-12-31', 149129.0],
                      ['1974-12-31', 148351.0],
                      ['1973-12-31', 146912.0],
                      ['1972-12-31', 147710.0],
                      ['1971-12-31', 147389.0],
                      ['1970-12-31', 144739.0],
                      ['1969-12-31', 142581.0],
                      ['1968-12-31', 140298.0],
                      ['1967-12-31', 138140.0],
                      ['1966-12-31', 136682.0],
                      ['1965-12-31', 135266.0],
                      ['1964-12-31', 133148.0],
                      ['1963-12-31', 130860.0],
                      ['1962-12-31', 128414.0],
                      ['1961-12-31', 126125.0],
                      ['1960-12-31', 124826.0],
                      ['1959-12-31', 123911.0],
                      ['1958-12-31', 121842.0],
                      ['1957-12-31', 118871.0],
                      ['1956-12-31', 118091.0],
                      ['1955-12-31', 117384.0],
                      ['1954-12-31', 115304.0],
                      ['1953-12-31', 112604.0],
                      ['1952-12-31', 108206.0],
                      ['1951-12-31', 104036.0],
                      ['1950-12-31', 100163.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'CUW_SP_POP_TOTL',
             'description': 'Population, total - Curacao. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22109228,
             'limit': None,
             'name': 'Population, total - Curacao',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:30:13.152Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
CYP
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 1179551.0],
                      ['2016-12-31', 1170125.0],
                      ['2015-12-31', 1160985.0],
                      ['2014-12-31', 1152309.0],
                      ['2013-12-31', 1143896.0],
                      ['2012-12-31', 1135062.0],
                      ['2011-12-31', 1124835.0],
                      ['2010-12-31', 1112607.0],
                      ['2009-12-31', 1098076.0],
                      ['2008-12-31', 1081563.0],
                      ['2007-12-31', 1063712.0],
                      ['2006-12-31', 1045509.0],
                      ['2005-12-31', 1027658.0],
                      ['2004-12-31', 1010410.0],
                      ['2003-12-31', 993563.0],
                      ['2002-12-31', 976966.0],
                      ['2001-12-31', 960282.0],
                      ['2000-12-31', 943286.0],
                      ['1999-12-31', 926050.0],
                      ['1998-12-31', 908704.0],
                      ['1997-12-31', 891192.0],
                      ['1996-12-31', 873423.0],
                      ['1995-12-31', 855384.0],
                      ['1994-12-31', 837110.0],
                      ['1993-12-31', 818751.0],
                      ['1992-12-31', 800609.0],
                      ['1991-12-31', 783129.0],
                      ['1990-12-31', 766614.0],
                      ['1989-12-31', 751044.0],
                      ['1988-12-31', 736479.0],
                      ['1987-12-31', 723380.0],
                      ['1986-12-31', 712341.0],
                      ['1985-12-31', 703687.0],
                      ['1984-12-31', 697717.0],
                      ['1983-12-31', 694077.0],
                      ['1982-12-31', 691702.0],
                      ['1981-12-31', 689173.0],
                      ['1980-12-31', 685406.0],
                      ['1979-12-31', 680011.0],
                      ['1978-12-31', 673251.0],
                      ['1977-12-31', 665528.0],
                      ['1976-12-31', 657534.0],
                      ['1975-12-31', 649755.0],
                      ['1974-12-31', 642339.0],
                      ['1973-12-31', 635111.0],
                      ['1972-12-31', 628002.0],
                      ['1971-12-31', 620859.0],
                      ['1970-12-31', 613621.0],
                      ['1969-12-31', 606113.0],
                      ['1968-12-31', 598493.0],
                      ['1967-12-31', 591308.0],
                      ['1966-12-31', 585308.0],
                      ['1965-12-31', 580966.0],
                      ['1964-12-31', 578627.0],
                      ['1963-12-31', 577913.0],
                      ['1962-12-31', 577691.0],
                      ['1961-12-31', 576395.0],
                      ['1960-12-31', 572930.0],
                      ['1959-12-31', 566982.0],
                      ['1958-12-31', 558895.0],
                      ['1957-12-31', 549461.0],
                      ['1956-12-31', 539565.0],
                      ['1955-12-31', 529972.0],
                      ['1954-12-31', 521184.0],
                      ['1953-12-31', 513434.0],
                      ['1952-12-31', 506627.0],
                      ['1951-12-31', 500381.0],
                      ['1950-12-31', 494015.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'CYP_SP_POP_TOTL',
             'description': 'Population, total - Cyprus. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22111141,
             'limit': None,
             'name': 'Population, total - Cyprus',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:30:19.198Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
CZE
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 10591323.0],
                      ['2016-12-31', 10566332.0],
                      ['2015-12-31', 10546059.0],
                      ['2014-12-31', 10525347.0],
                      ['2013-12-31', 10514272.0],
                      ['2012-12-31', 10510785.0],
                      ['2011-12-31', 10496088.0],
                      ['2010-12-31', 10474410.0],
                      ['2009-12-31', 10443936.0],
                      ['2008-12-31', 10384603.0],
                      ['2007-12-31', 10298828.0],
                      ['2006-12-31', 10238905.0],
                      ['2005-12-31', 10211216.0],
                      ['2004-12-31', 10197101.0],
                      ['2003-12-31', 10193998.0],
                      ['2002-12-31', 10196916.0],
                      ['2001-12-31', 10216605.0],
                      ['2000-12-31', 10255063.0],
                      ['1999-12-31', 10283860.0],
                      ['1998-12-31', 10294373.0],
                      ['1997-12-31', 10304131.0],
                      ['1996-12-31', 10315241.0],
                      ['1995-12-31', 10327253.0],
                      ['1994-12-31', 10333587.0],
                      ['1993-12-31', 10329855.0],
                      ['1992-12-31', 10319123.0],
                      ['1991-12-31', 10308578.0],
                      ['1990-12-31', 10333355.0],
                      ['1989-12-31', 10361068.0],
                      ['1988-12-31', 10355276.0],
                      ['1987-12-31', 10347318.0],
                      ['1986-12-31', 10342227.0],
                      ['1985-12-31', 10337118.0],
                      ['1984-12-31', 10330213.0],
                      ['1983-12-31', 10323856.0],
                      ['1982-12-31', 10314826.0],
                      ['1981-12-31', 10300591.0],
                      ['1980-12-31', 10304193.0],
                      ['1979-12-31', 10292341.0],
                      ['1978-12-31', 10242098.0],
                      ['1977-12-31', 10186755.0],
                      ['1976-12-31', 10125939.0],
                      ['1975-12-31', 10058620.0],
                      ['1974-12-31', 9988459.0],
                      ['1973-12-31', 9922266.0],
                      ['1972-12-31', 9867632.0],
                      ['1971-12-31', 9826815.0],
                      ['1970-12-31', 9858071.0],
                      ['1969-12-31', 9896580.0],
                      ['1968-12-31', 9876346.0],
                      ['1967-12-31', 9852899.0],
                      ['1966-12-31', 9821040.0],
                      ['1965-12-31', 9779358.0],
                      ['1964-12-31', 9727804.0],
                      ['1963-12-31', 9670685.0],
                      ['1962-12-31', 9624660.0],
                      ['1961-12-31', 9586651.0],
                      ['1960-12-31', 9602006.0],
                      ['1959-12-31', 9477371.0],
                      ['1958-12-31', 9428668.0],
                      ['1957-12-31', 9375356.0],
                      ['1956-12-31', 9317119.0],
                      ['1955-12-31', 9253842.0],
                      ['1954-12-31', 9185663.0],
                      ['1953-12-31', 9112988.0],
                      ['1952-12-31', 9036508.0],
                      ['1951-12-31', 8957188.0],
                      ['1950-12-31', 8876260.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'CZE_SP_POP_TOTL',
             'description': 'Population, total - Czech Republic. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22112966,
             'limit': None,
             'name': 'Population, total - Czech Republic',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:30:24.439Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
DNK

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 5769603.0],
                      ['2016-12-31', 5728010.0],
                      ['2015-12-31', 5683483.0],
                      ['2014-12-31', 5643475.0],
                      ['2013-12-31', 5614932.0],
                      ['2012-12-31', 5591572.0],
                      ['2011-12-31', 5570572.0],
                      ['2010-12-31', 5547683.0],
                      ['2009-12-31', 5523095.0],
                      ['2008-12-31', 5493621.0],
                      ['2007-12-31', 5461438.0],
                      ['2006-12-31', 5437272.0],
                      ['2005-12-31', 5419432.0],
                      ['2004-12-31', 5404523.0],
                      ['2003-12-31', 5390574.0],
                      ['2002-12-31', 5375931.0],
                      ['2001-12-31', 5358783.0],
                      ['2000-12-31', 5339616.0],
                      ['1999-12-31', 5321799.0],
                      ['1998-12-31', 5304219.0],
                      ['1997-12-31', 5284991.0],
                      ['1996-12-31', 5263074.0],
                      ['1995-12-31', 5233373.0],
                      ['1994-12-31', 5206180.0],
                      ['1993-12-31', 5188628.0],
                      ['1992-12-31', 5171370.0],
                      ['1991-12-31', 5154298.0],
                      ['1990-12-31', 5140939.0],
                      ['1989-12-31', 5132594.0],
                      ['1988-12-31', 5129516.0],
                      ['1987-12-31', 5127024.0],
                      ['1986-12-31', 5120534.0],
                      ['1985-12-31', 5113691.0],
                      ['1984-12-31', 5111619.0],
                      ['1983-12-31', 5114297.0],
                      ['1982-12-31', 5117810.0],
                      ['1981-12-31', 5121572.0],
                      ['1980-12-31', 5123027.0],
                      ['1979-12-31', 5116801.0],
                      ['1978-12-31', 5104248.0],
                      ['1977-12-31', 5088419.0],
                      ['1976-12-31', 5072596.0],
                      ['1975-12-31', 5059862.0],
                      ['1974-12-31', 5045297.0],
                      ['1973-12-31', 5021861.0],
                      ['1972-12-31', 4991596.0],
                      ['1971-12-31', 4963126.0],
                      ['1970-12-31', 4928757.0],
                      ['1969-12-31', 4891860.0],
                      ['1968-12-31', 4864883.0],
                      ['1967-12-31', 4835354.0],
                      ['1966-12-31', 4797381.0],
                      ['1965-12-31', 4759012.0],
                      ['1964-12-31', 4722072.0],
                      ['1963-12-31', 4684483.0],
                      ['1962-12-31', 4647727.0],
                      ['1961-12-31', 4611687.0],
                      ['1960-12-31', 4579603.0],
                      ['1959-12-31', 4549237.0],
                      ['1958-12-31', 4520755.0],
                      ['1957-12-31', 4493517.0],
                      ['1956-12-31', 4466552.0],
                      ['1955-12-31', 4438935.0],
                      ['1954-12-31', 4409858.0],
                      ['1953-12-31', 4378663.0],
                      ['1952-12-31', 4344863.0],
                      ['1951-12-31', 4308125.0],
                      ['1950-12-31', 4268270.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'DNK_SP_POP_TOTL',
             'description': 'Population, total - Denmark. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22119510,
             'limit': None,
             'name': 'Population, total - Denmark',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:30:44.832Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
DJI
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 956985.0],
                      ['2016-12-31', 942333.0],
                      ['2015-12-31', 927414.0],
                      ['2014-12-31', 912164.0],
                      ['2013-12-31', 896688.0],
                      ['2012-12-31', 881185.0],
                      ['2011-12-31', 865937.0],
                      ['2010-12-31', 851146.0],
                      ['2009-12-31', 836840.0],
                      ['2008-12-31', 822934.0],
                      ['2007-12-31', 809402.0],
                      ['2006-12-31', 796208.0],
                      ['2005-12-31', 783254.0],
                      ['2004-12-31', 770752.0],
                      ['2003-12-31', 758615.0],
                      ['2002-12-31', 746221.0],
                      ['2001-12-31', 732711.0],
                      ['2000-12-31', 717584.0],
                      ['1999-12-31', 700099.0],
                      ['1998-12-31', 680612.0],
                      ['1997-12-31', 660953.0],
                      ['1996-12-31', 643682.0],
                      ['1995-12-31', 630388.0],
                      ['1994-12-31', 622366.0],
                      ['1993-12-31', 618495.0],
                      ['1992-12-31', 615054.0],
                      ['1991-12-31', 606844.0],
                      ['1990-12-31', 590398.0],
                      ['1989-12-31', 563864.0],
                      ['1988-12-31', 528999.0],
                      ['1987-12-31', 490330.0],
                      ['1986-12-31', 454361.0],
                      ['1985-12-31', 425613.0],
                      ['1984-12-31', 406017.0],
                      ['1983-12-31', 393802.0],
                      ['1982-12-31', 385271.0],
                      ['1981-12-31', 374937.0],
                      ['1980-12-31', 358960.0],
                      ['1979-12-31', 336085.0],
                      ['1978-12-31', 308008.0],
                      ['1977-12-31', 277479.0],
                      ['1976-12-31', 248556.0],
                      ['1975-12-31', 224183.0],
                      ['1974-12-31', 205181.0],
                      ['1973-12-31', 190568.0],
                      ['1972-12-31', 179224.0],
                      ['1971-12-31', 169372.0],
                      ['1970-12-31', 159659.0],
                      ['1969-12-31', 149887.0],
                      ['1968-12-31', 140462.0],
                      ['1967-12-31', 131397.0],
                      ['1966-12-31', 122866.0],
                      ['1965-12-31', 114963.0],
                      ['1964-12-31', 107583.0],
                      ['1963-12-31', 100628.0],
                      ['1962-12-31', 94204.0],
                      ['1961-12-31', 88498.0],
                      ['1960-12-31', 83636.0],
                      ['1959-12-31', 79612.0],
                      ['1958-12-31', 76353.0],
                      ['1957-12-31', 73702.0],
                      ['1956-12-31', 71497.0],
                      ['1955-12-31', 69589.0],
                      ['1954-12-31', 67872.0],
                      ['1953-12-31', 66269.0],
                      ['1952-12-31', 64750.0],
                      ['1951-12-31', 63306.0],
                      ['1950-12-31', 62001.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'DJI_SP_POP_TOTL',
             'description': 'Population, total - Djibouti. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22116389,
             'limit': None,
             'name': 'Population, total - Djibouti',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:30:35.096Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
DOM

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 10766998.0],
                      ['2016-12-31', 10648791.0],
                      ['2015-12-31', 10528394.0],
                      ['2014-12-31', 10405844.0],
                      ['2013-12-31', 10281296.0],
                      ['2012-12-31', 10154950.0],
                      ['2011-12-31', 10027095.0],
                      ['2010-12-31', 9897985.0],
                      ['2009-12-31', 9767758.0],
                      ['2008-12-31', 9636520.0],
                      ['2007-12-31', 9504353.0],
                      ['2006-12-31', 9371338.0],
                      ['2005-12-31', 9237566.0],
                      ['2004-12-31', 9102998.0],
                      ['2003-12-31', 8967760.0],
                      ['2002-12-31', 8832285.0],
                      ['2001-12-31', 8697126.0],
                      ['2000-12-31', 8562622.0],
                      ['1999-12-31', 8429112.0],
                      ['1998-12-31', 8296375.0],
                      ['1997-12-31', 8163472.0],
                      ['1996-12-31', 8029113.0],
                      ['1995-12-31', 7892423.0],
                      ['1994-12-31', 7753052.0],
                      ['1993-12-31', 7611465.0],
                      ['1992-12-31', 7468551.0],
                      ['1991-12-31', 7325622.0],
                      ['1990-12-31', 7183647.0],
                      ['1989-12-31', 7042937.0],
                      ['1988-12-31', 6903316.0],
                      ['1987-12-31', 6764624.0],
                      ['1986-12-31', 6626542.0],
                      ['1985-12-31', 6488856.0],
                      ['1984-12-31', 6351572.0],
                      ['1983-12-31', 6214857.0],
                      ['1982-12-31', 6078820.0],
                      ['1981-12-31', 5943591.0],
                      ['1980-12-31', 5809269.0],
                      ['1979-12-31', 5675931.0],
                      ['1978-12-31', 5543517.0],
                      ['1977-12-31', 5411865.0],
                      ['1976-12-31', 5280723.0],
                      ['1975-12-31', 5149935.0],
                      ['1974-12-31', 5019473.0],
                      ['1973-12-31', 4889436.0],
                      ['1972-12-31', 4759934.0],
                      ['1971-12-31', 4631114.0],
                      ['1970-12-31', 4503114.0],
                      ['1969-12-31', 4376054.0],
                      ['1968-12-31', 4250025.0],
                      ['1967-12-31', 4125109.0],
                      ['1966-12-31', 4001375.0],
                      ['1965-12-31', 3878948.0],
                      ['1964-12-31', 3757956.0],
                      ['1963-12-31', 3638628.0],
                      ['1962-12-31', 3521278.0],
                      ['1961-12-31', 3406299.0],
                      ['1960-12-31', 3294042.0],
                      ['1959-12-31', 3184757.0],
                      ['1958-12-31', 3078629.0],
                      ['1957-12-31', 2975807.0],
                      ['1956-12-31', 2876428.0],
                      ['1955-12-31', 2780652.0],
                      ['1954-12-31', 2688698.0],
                      ['1953-12-31', 2600798.0],
                      ['1952-12-31', 2517259.0],
                      ['1951-12-31', 2438405.0],
                      ['1950-12-31', 2364654.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'DOM_SP_POP_TOTL',
             'description': 'Population, total - Dominican Republic. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22121433,
             'limit': None,
             'name': 'Population, total - Dominican Republic',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:30:50.777Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
DMA
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 73925.0],
                      ['2016-12-31', 73543.0],
                      ['2015-12-31', 73162.0],
                      ['2014-12-31', 72778.0],
                      ['2013-12-31', 72400.0],
                      ['2012-12-31', 72044.0],
                      ['2011-12-31', 71718.0],
                      ['2010-12-31', 71440.0],
                      ['2009-12-31', 71229.0],
                      ['2008-12-31', 71074.0],
                      ['2007-12-31', 70950.0],
                      ['2006-12-31', 70807.0],
                      ['2005-12-31', 70627.0],
                      ['2004-12-31', 70379.0],
                      ['2003-12-31', 70093.0],
                      ['2002-12-31', 69824.0],
                      ['2001-12-31', 69670.0],
                      ['2000-12-31', 69676.0],
                      ['1999-12-31', 69903.0],
                      ['1998-12-31', 70290.0],
                      ['1997-12-31', 70753.0],
                      ['1996-12-31', 71145.0],
                      ['1995-12-31', 71368.0],
                      ['1994-12-31', 71373.0],
                      ['1993-12-31', 71210.0],
                      ['1992-12-31', 70970.0],
                      ['1991-12-31', 70842.0],
                      ['1990-12-31', 70926.0],
                      ['1989-12-31', 71242.0],
                      ['1988-12-31', 71742.0],
                      ['1987-12-31', 72370.0],
                      ['1986-12-31', 73025.0],
                      ['1985-12-31', 73643.0],
                      ['1984-12-31', 74213.0],
                      ['1983-12-31', 74747.0],
                      ['1982-12-31', 75170.0],
                      ['1981-12-31', 75375.0],
                      ['1980-12-31', 75314.0],
                      ['1979-12-31', 74925.0],
                      ['1978-12-31', 74242.0],
                      ['1977-12-31', 73411.0],
                      ['1976-12-31', 72642.0],
                      ['1975-12-31', 72094.0],
                      ['1974-12-31', 71807.0],
                      ['1973-12-31', 71744.0],
                      ['1972-12-31', 71734.0],
                      ['1971-12-31', 71569.0],
                      ['1970-12-31', 71073.0],
                      ['1969-12-31', 70213.0],
                      ['1968-12-31', 69040.0],
                      ['1967-12-31', 67686.0],
                      ['1966-12-31', 66311.0],
                      ['1965-12-31', 65038.0],
                      ['1964-12-31', 63926.0],
                      ['1963-12-31', 62918.0],
                      ['1962-12-31', 61982.0],
                      ['1961-12-31', 61032.0],
                      ['1960-12-31', 60011.0],
                      ['1959-12-31', 58922.0],
                      ['1958-12-31', 57772.0],
                      ['1957-12-31', 56630.0],
                      ['1956-12-31', 55547.0],
                      ['1955-12-31', 54560.0],
                      ['1954-12-31', 53688.0],
                      ['1953-12-31', 52947.0],
                      ['1952-12-31', 52301.0],
                      ['1951-12-31', 51706.0],
                      ['1950-12-31', 51100.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'DMA_SP_POP_TOTL',
             'description': 'Population, total - Dominica. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22117878,
             'limit': None,
             'name': 'Population, total - Dominica',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:30:39.872Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
EAS
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 2314364990.0],
                      ['2016-12-31', 2298726779.0],
                      ['2015-12-31', 2283108073.0],
                      ['2014-12-31', 2267745366.0],
                      ['2013-12-31', 2252311022.0],
                      ['2012-12-31', 2237082761.0],
                      ['2011-12-31', 2221934584.0],
                      ['2010-12-31', 2207154641.0],
                      ['2009-12-31', 2192352319.0],
                      ['2008-12-31', 2177421759.0],
                      ['2007-12-31', 2162104019.0],
                      ['2006-12-31', 2147029631.0],
                      ['2005-12-31', 2131363078.0],
                      ['2004-12-31', 2115557365.0],
                      ['2003-12-31', 2099545576.0],
                      ['2002-12-31', 2082953527.0],
                      ['2001-12-31', 2065521836.0],
                      ['2000-12-31', 2047150745.0],
                      ['1999-12-31', 2028095314.0],
                      ['1998-12-31', 2008140141.0],
                      ['1997-12-31', 1986799861.0],
                      ['1996-12-31', 1964635058.0],
                      ['1995-12-31', 1941918800.0],
                      ['1994-12-31', 1918771287.0],
                      ['1993-12-31', 1895356643.0],
                      ['1992-12-31', 1871898268.0],
                      ['1991-12-31', 1847530233.0],
                      ['1990-12-31', 1821481246.0],
                      ['1989-12-31', 1794408755.0],
                      ['1988-12-31', 1766656203.0],
                      ['1987-12-31', 1738276268.0],
                      ['1986-12-31', 1710171170.0],
                      ['1985-12-31', 1683448851.0],
                      ['1984-12-31', 1658253758.0],
                      ['1983-12-31', 1633628203.0],
                      ['1982-12-31', 1607731269.0],
                      ['1981-12-31', 1581806986.0],
                      ['1980-12-31', 1558178982.0],
                      ['1979-12-31', 1535391301.0],
                      ['1978-12-31', 1512159741.0],
                      ['1977-12-31', 1489361661.0],
                      ['1976-12-31', 1466464716.0],
                      ['1975-12-31', 1442241325.0],
                      ['1974-12-31', 1415128313.0],
                      ['1973-12-31', 1385052014.0],
                      ['1972-12-31', 1354794332.0],
                      ['1971-12-31', 1322942750.0],
                      ['1970-12-31', 1289258962.0],
                      ['1969-12-31', 1256501008.0],
                      ['1968-12-31', 1223721283.0],
                      ['1967-12-31', 1194424326.0],
                      ['1966-12-31', 1165517894.0],
                      ['1965-12-31', 1135650895.0],
                      ['1964-12-31', 1109204182.0],
                      ['1963-12-31', 1083802299.0],
                      ['1962-12-31', 1058028199.0],
                      ['1961-12-31', 1043546747.0],
                      ['1960-12-31', 1039944591.0],
                      ['1959-12-31', 1008998973.0],
                      ['1958-12-31', 989058307.0],
                      ['1957-12-31', 969557379.0],
                      ['1956-12-31', 950528665.0],
                      ['1955-12-31', 940920120.0],
                      ['1954-12-31', 912152694.0],
                      ['1953-12-31', 892908557.0],
                      ['1952-12-31', 874278030.0],
                      ['1951-12-31', 856275893.0],
                      ['1950-12-31', 846378225.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'EAS_SP_POP_TOTL',
             'description': 'Population, total - East Asia & Pacific (all '
                            'income levels). ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22126436,
             'limit': None,
             'name': 'Population, total - East Asia & Pacific (all income '
                     'levels)',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:31:07.218Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
EAP

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 2068308373.0],
                      ['2016-12-31', 2053299126.0],
                      ['2015-12-31', 2038410865.0],
                      ['2014-12-31', 2023837097.0],
                      ['2013-12-31', 2009173000.0],
                      ['2012-12-31', 1994651365.0],
                      ['2011-12-31', 1980303926.0],
                      ['2010-12-31', 1966231608.0],
                      ['2009-12-31', 1952308448.0],
                      ['2008-12-31', 1938363936.0],
                      ['2007-12-31', 1924328623.0],
                      ['2006-12-31', 1910175419.0],
                      ['2005-12-31', 1895491197.0],
                      ['2004-12-31', 1880346879.0],
                      ['2003-12-31', 1865072190.0],
                      ['2002-12-31', 1849372898.0],
                      ['2001-12-31', 1833033752.0],
                      ['2000-12-31', 1815956211.0],
                      ['1999-12-31', 1798083668.0],
                      ['1998-12-31', 1779221736.0],
                      ['1997-12-31', 1759201938.0],
                      ['1996-12-31', 1738422945.0],
                      ['1995-12-31', 1717381821.0],
                      ['1994-12-31', 1695931765.0],
                      ['1993-12-31', 1674021645.0],
                      ['1992-12-31', 1651934416.0],
                      ['1991-12-31', 1629001649.0],
                      ['1990-12-31', 1604526529.0],
                      ['1989-12-31', 1578979764.0],
                      ['1988-12-31', 1552839428.0],
                      ['1987-12-31', 1526044403.0],
                      ['1986-12-31', 1499557430.0],
                      ['1985-12-31', 1474560143.0],
                      ['1984-12-31', 1451090680.0],
                      ['1983-12-31', 1428333976.0],
                      ['1982-12-31', 1404508191.0],
                      ['1981-12-31', 1380818022.0],
                      ['1980-12-31', 1359492990.0],
                      ['1979-12-31', 1338905404.0],
                      ['1978-12-31', 1317994414.0],
                      ['1977-12-31', 1297394581.0],
                      ['1976-12-31', 1276763432.0],
                      ['1975-12-31', 1254532835.0],
                      ['1974-12-31', 1230436635.0],
                      ['1973-12-31', 1203905200.0],
                      ['1972-12-31', 1175854628.0],
                      ['1971-12-31', 1146850519.0],
                      ['1970-12-31', 1116105178.0],
                      ['1969-12-31', 1085996628.0],
                      ['1968-12-31', 1056791462.0],
                      ['1967-12-31', 1029286493.0],
                      ['1966-12-31', 1002752091.0],
                      ['1965-12-31', 975325710.0],
                      ['1964-12-31', 951477683.0],
                      ['1963-12-31', 928641158.0],
                      ['1962-12-31', 905445960.0],
                      ['1961-12-31', 893537036.0],
                      ['1960-12-31', 893956327.0],
                      ['1959-12-31', 875675365.0],
                      ['1958-12-31', 857792833.0],
                      ['1957-12-31', 840339062.0],
                      ['1956-12-31', 823348171.0],
                      ['1955-12-31', 806851475.0],
                      ['1954-12-31', 789025848.0],
                      ['1953-12-31', 771813394.0],
                      ['1952-12-31', 755225225.0],
                      ['1951-12-31', 739265998.0],
                      ['1950-12-31', 723934135.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'EAP_SP_POP_TOTL',
             'description': 'Population, total - East Asia & Pacific '
                            '(developing only). ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22124986,
             'limit': None,
             'name': 'Population, total - East Asia & Pacific (developing '
                     'only)',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:31:02.595Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
CEA
{'quandl_error': {'code': 'QECx02',
                  'message': 'You have submitted an incorrect Quandl code. '
                             'Please check your Quandl codes and try again.'}}
ECU
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 16624858.0],
                      ['2016-12-31', 16385068.0],
                      ['2015-12-31', 16144368.0],
                      ['2014-12-31', 15903112.0],
                      ['2013-12-31', 15661547.0],
                      ['2012-12-31', 15419666.0],
                      ['2011-12-31', 15177355.0],
                      ['2010-12-31', 14934690.0],
                      ['2009-12-31', 14691275.0],
                      ['2008-12-31', 14447562.0],
                      ['2007-12-31', 14205453.0],
                      ['2006-12-31', 13967480.0],
                      ['2005-12-31', 13735233.0],
                      ['2004-12-31', 13509647.0],
                      ['2003-12-31', 13289601.0],
                      ['2002-12-31', 13072060.0],
                      ['2001-12-31', 12852755.0],
                      ['2000-12-31', 12628596.0],
                      ['1999-12-31', 12398691.0],
                      ['1998-12-31', 12163885.0],
                      ['1997-12-31', 11924993.0],
                      ['1996-12-31', 11683479.0],
                      ['1995-12-31', 11440583.0],
                      ['1994-12-31', 11196479.0],
                      ['1993-12-31', 10951202.0],
                      ['1992-12-31', 10705667.0],
                      ['1991-12-31', 10460990.0],
                      ['1990-12-31', 10218091.0],
                      ['1989-12-31', 9977377.0],
                      ['1988-12-31', 9739176.0],
                      ['1987-12-31', 9504129.0],
                      ['1986-12-31', 9272906.0],
                      ['1985-12-31', 9045979.0],
                      ['1984-12-31', 8823751.0],
                      ['1983-12-31', 8606213.0],
                      ['1982-12-31', 8392940.0],
                      ['1981-12-31', 8183194.0],
                      ['1980-12-31', 7976445.0],
                      ['1979-12-31', 7772653.0],
                      ['1978-12-31', 7571959.0],
                      ['1977-12-31', 7374234.0],
                      ['1976-12-31', 7179399.0],
                      ['1975-12-31', 6987391.0],
                      ['1974-12-31', 6798206.0],
                      ['1973-12-31', 6611916.0],
                      ['1972-12-31', 6428711.0],
                      ['1971-12-31', 6248835.0],
                      ['1970-12-31', 6072527.0],
                      ['1969-12-31', 5899845.0],
                      ['1968-12-31', 5730906.0],
                      ['1967-12-31', 5566057.0],
                      ['1966-12-31', 5405685.0],
                      ['1965-12-31', 5250119.0],
                      ['1964-12-31', 5099468.0],
                      ['1963-12-31', 4953733.0],
                      ['1962-12-31', 4812890.0],
                      ['1961-12-31', 4676859.0],
                      ['1960-12-31', 4545550.0],
                      ['1959-12-31', 4418892.0],
                      ['1958-12-31', 4296833.0],
                      ['1957-12-31', 4179319.0],
                      ['1956-12-31', 4066239.0],
                      ['1955-12-31', 3957485.0],
                      ['1954-12-31', 3852859.0],
                      ['1953-12-31', 3752135.0],
                      ['1952-12-31', 3655014.0],
                      ['1951-12-31', 3561154.0],
                      ['1950-12-31', 3470159.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'ECU_SP_POP_TOTL',
             'description': 'Population, total - Ecuador. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22130995,
             'limit': None,
             'name': 'Population, total - Ecuador',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:31:22.096Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
EGY

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 97553151.0],
                      ['2016-12-31', 95688681.0],
                      ['2015-12-31', 93778172.0],
                      ['2014-12-31', 91812566.0],
                      ['2013-12-31', 89807433.0],
                      ['2012-12-31', 87813257.0],
                      ['2011-12-31', 85897561.0],
                      ['2010-12-31', 84107606.0],
                      ['2009-12-31', 82465022.0],
                      ['2008-12-31', 80953881.0],
                      ['2007-12-31', 79537253.0],
                      ['2006-12-31', 78159048.0],
                      ['2005-12-31', 76778149.0],
                      ['2004-12-31', 75381899.0],
                      ['2003-12-31', 73981942.0],
                      ['2002-12-31', 72590118.0],
                      ['2001-12-31', 71226940.0],
                      ['2000-12-31', 69905988.0],
                      ['1999-12-31', 68626664.0],
                      ['1998-12-31', 67378056.0],
                      ['1997-12-31', 66151117.0],
                      ['1996-12-31', 64933456.0],
                      ['1995-12-31', 63714386.0],
                      ['1994-12-31', 62495745.0],
                      ['1993-12-31', 61275601.0],
                      ['1992-12-31', 60035536.0],
                      ['1991-12-31', 58752390.0],
                      ['1990-12-31', 57412215.0],
                      ['1989-12-31', 56006573.0],
                      ['1988-12-31', 54547296.0],
                      ['1987-12-31', 53066229.0],
                      ['1986-12-31', 51607703.0],
                      ['1985-12-31', 50204985.0],
                      ['1984-12-31', 48868951.0],
                      ['1983-12-31', 47594556.0],
                      ['1982-12-31', 46379620.0],
                      ['1981-12-31', 45216506.0],
                      ['1980-12-31', 44099142.0],
                      ['1979-12-31', 43027816.0],
                      ['1978-12-31', 42004655.0],
                      ['1977-12-31', 41026477.0],
                      ['1976-12-31', 40089032.0],
                      ['1975-12-31', 39187702.0],
                      ['1974-12-31', 38322022.0],
                      ['1973-12-31', 37488067.0],
                      ['1972-12-31', 36673642.0],
                      ['1971-12-31', 35863382.0],
                      ['1970-12-31', 35046273.0],
                      ['1969-12-31', 34216826.0],
                      ['1968-12-31', 33377259.0],
                      ['1967-12-31', 32534021.0],
                      ['1966-12-31', 31697616.0],
                      ['1965-12-31', 30875964.0],
                      ['1964-12-31', 30071102.0],
                      ['1963-12-31', 29281250.0],
                      ['1962-12-31', 28506176.0],
                      ['1961-12-31', 27744712.0],
                      ['1960-12-31', 26996533.0],
                      ['1959-12-31', 26262697.0],
                      ['1958-12-31', 25545476.0],
                      ['1957-12-31', 24847822.0],
                      ['1956-12-31', 24172872.0],
                      ['1955-12-31', 23523384.0],
                      ['1954-12-31', 22901598.0],
                      ['1953-12-31', 22309098.0],
                      ['1952-12-31', 21746808.0],
                      ['1951-12-31', 21215014.0],
                      ['1950-12-31', 20713331.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'EGY_SP_POP_TOTL',
             'description': 'Population, total - Egypt, Arab Rep.. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22132165,
             'limit': None,
             'name': 'Population, total - Egypt, Arab Rep.',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:31:28.722Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
SLV
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 6377853.0],
                      ['2016-12-31', 6344722.0],
                      ['2015-12-31', 6312478.0],
                      ['2014-12-31', 6281189.0],
                      ['2013-12-31', 6250777.0],
                      ['2012-12-31', 6221246.0],
                      ['2011-12-31', 6192560.0],
                      ['2010-12-31', 6164626.0],
                      ['2009-12-31', 6137276.0],
                      ['2008-12-31', 6110301.0],
                      ['2007-12-31', 6083475.0],
                      ['2006-12-31', 6056478.0],
                      ['2005-12-31', 6028961.0],
                      ['2004-12-31', 6000775.0],
                      ['2003-12-31', 5971535.0],
                      ['2002-12-31', 5940303.0],
                      ['2001-12-31', 5905962.0],
                      ['2000-12-31', 5867626.0],
                      ['1999-12-31', 5825187.0],
                      ['1998-12-31', 5778706.0],
                      ['1997-12-31', 5727755.0],
                      ['1996-12-31', 5671925.0],
                      ['1995-12-31', 5611115.0],
                      ['1994-12-31', 5544945.0],
                      ['1993-12-31', 5474000.0],
                      ['1992-12-31', 5400331.0],
                      ['1991-12-31', 5326657.0],
                      ['1990-12-31', 5254984.0],
                      ['1989-12-31', 5185943.0],
                      ['1988-12-31', 5119035.0],
                      ['1987-12-31', 5053714.0],
                      ['1986-12-31', 4988943.0],
                      ['1985-12-31', 4923860.0],
                      ['1984-12-31', 4858532.0],
                      ['1983-12-31', 4792903.0],
                      ['1982-12-31', 4725720.0],
                      ['1981-12-31', 4655364.0],
                      ['1980-12-31', 4580704.0],
                      ['1979-12-31', 4501316.0],
                      ['1978-12-31', 4417516.0],
                      ['1977-12-31', 4329964.0],
                      ['1976-12-31', 4239675.0],
                      ['1975-12-31', 4147525.0],
                      ['1974-12-31', 4053713.0],
                      ['1973-12-31', 3958323.0],
                      ['1972-12-31', 3861931.0],
                      ['1971-12-31', 3765166.0],
                      ['1970-12-31', 3668595.0],
                      ['1969-12-31', 3572707.0],
                      ['1968-12-31', 3477742.0],
                      ['1967-12-31', 3383701.0],
                      ['1966-12-31', 3290411.0],
                      ['1965-12-31', 3197863.0],
                      ['1964-12-31', 3106186.0],
                      ['1963-12-31', 3015887.0],
                      ['1962-12-31', 2927857.0],
                      ['1961-12-31', 2843240.0],
                      ['1960-12-31', 2762899.0],
                      ['1959-12-31', 2687233.0],
                      ['1958-12-31', 2616277.0],
                      ['1957-12-31', 2549826.0],
                      ['1956-12-31', 2487586.0],
                      ['1955-12-31', 2429333.0],
                      ['1954-12-31', 2374972.0],
                      ['1953-12-31', 2324559.0],
                      ['1952-12-31', 2278307.0],
                      ['1951-12-31', 2236576.0],
                      ['1950-12-31', 2199898.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'SLV_SP_POP_TOTL',
             'description': 'Population, total - El Salvador. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22244412,
             'limit': None,
             'name': 'Population, total - El Salvador',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:43:25.933Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
GNQ

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 1267689.0],
                      ['2016-12-31', 1221490.0],
                      ['2015-12-31', 1175389.0],
                      ['2014-12-31', 1129424.0],
                      ['2013-12-31', 1083746.0],
                      ['2012-12-31', 1038593.0],
                      ['2011-12-31', 994290.0],
                      ['2010-12-31', 951104.0],
                      ['2009-12-31', 909111.0],
                      ['2008-12-31', 868418.0],
                      ['2007-12-31', 829327.0],
                      ['2006-12-31', 792217.0],
                      ['2005-12-31', 757317.0],
                      ['2004-12-31', 724817.0],
                      ['2003-12-31', 694611.0],
                      ['2002-12-31', 666407.0],
                      ['2001-12-31', 639762.0],
                      ['2000-12-31', 614323.0],
                      ['1999-12-31', 589938.0],
                      ['1998-12-31', 566673.0],
                      ['1997-12-31', 544636.0],
                      ['1996-12-31', 523999.0],
                      ['1995-12-31', 504871.0],
                      ['1994-12-31', 487140.0],
                      ['1993-12-31', 470610.0],
                      ['1992-12-31', 455148.0],
                      ['1991-12-31', 440624.0],
                      ['1990-12-31', 426846.0],
                      ['1989-12-31', 414138.0],
                      ['1988-12-31', 402326.0],
                      ['1987-12-31', 390173.0],
                      ['1986-12-31', 376024.0],
                      ['1985-12-31', 358896.0],
                      ['1984-12-31', 338086.0],
                      ['1983-12-31', 314475.0],
                      ['1982-12-31', 290617.0],
                      ['1981-12-31', 270063.0],
                      ['1980-12-31', 255325.0],
                      ['1979-12-31', 247078.0],
                      ['1978-12-31', 244485.0],
                      ['1977-12-31', 246677.0],
                      ['1976-12-31', 252194.0],
                      ['1975-12-31', 259747.0],
                      ['1974-12-31', 269426.0],
                      ['1973-12-31', 281021.0],
                      ['1972-12-31', 292585.0],
                      ['1971-12-31', 301666.0],
                      ['1970-12-31', 306515.0],
                      ['1969-12-31', 306233.0],
                      ['1968-12-31', 301353.0],
                      ['1967-12-31', 293440.0],
                      ['1966-12-31', 284868.0],
                      ['1965-12-31', 277396.0],
                      ['1964-12-31', 271457.0],
                      ['1963-12-31', 266598.0],
                      ['1962-12-31', 262590.0],
                      ['1961-12-31', 258947.0],
                      ['1960-12-31', 255323.0],
                      ['1959-12-31', 251601.0],
                      ['1958-12-31', 247932.0],
                      ['1957-12-31', 244553.0],
                      ['1956-12-31', 241670.0],
                      ['1955-12-31', 239375.0],
                      ['1954-12-31', 237547.0],
                      ['1953-12-31', 235883.0],
                      ['1952-12-31', 233853.0],
                      ['1951-12-31', 230717.0],
                      ['1950-12-31', 225537.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'GNQ_SP_POP_TOTL',
             'description': 'Population, total - Equatorial Guinea. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22162144,
             'limit': None,
             'name': 'Population, total - Equatorial Guinea',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:33:09.731Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
ERI
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2015-12-31', 5228000.0],
                      ['2014-12-31', 5110444.0],
                      ['2013-12-31', 4998824.0],
                      ['2012-12-31', 4892233.0],
                      ['2011-12-31', 4474690.0],
                      ['2010-12-31', 4390840.0],
                      ['2009-12-31', 4310334.0],
                      ['2008-12-31', 4232636.0],
                      ['2007-12-31', 4153332.0],
                      ['2006-12-31', 4066648.0],
                      ['2005-12-31', 3969007.0],
                      ['2004-12-31', 3858623.0],
                      ['2003-12-31', 3738265.0],
                      ['2002-12-31', 3614639.0],
                      ['2001-12-31', 3497124.0],
                      ['2000-12-31', 3392801.0],
                      ['1999-12-31', 3302263.0],
                      ['1998-12-31', 3224223.0],
                      ['1997-12-31', 3161350.0],
                      ['1996-12-31', 3116379.0],
                      ['1995-12-31', 3090159.0],
                      ['1994-12-31', 3085443.0],
                      ['1993-12-31', 3099047.0],
                      ['1992-12-31', 3118582.0],
                      ['1991-12-31', 3127297.0],
                      ['1990-12-31', 3113311.0],
                      ['1989-12-31', 3071771.0],
                      ['1988-12-31', 3006361.0],
                      ['1987-12-31', 2924349.0],
                      ['1986-12-31', 2837111.0],
                      ['1985-12-31', 2753151.0],
                      ['1984-12-31', 2674289.0],
                      ['1983-12-31', 2598410.0],
                      ['1982-12-31', 2525521.0],
                      ['1981-12-31', 2454766.0],
                      ['1980-12-31', 2385540.0],
                      ['1979-12-31', 2318495.0],
                      ['1978-12-31', 2254450.0],
                      ['1977-12-31', 2193068.0],
                      ['1976-12-31', 2133723.0],
                      ['1975-12-31', 2075965.0],
                      ['1974-12-31', 2019717.0],
                      ['1973-12-31', 1965160.0],
                      ['1972-12-31', 1912302.0],
                      ['1971-12-31', 1861199.0],
                      ['1970-12-31', 1811878.0],
                      ['1969-12-31', 1764343.0],
                      ['1968-12-31', 1718525.0],
                      ['1967-12-31', 1674204.0],
                      ['1966-12-31', 1631147.0],
                      ['1965-12-31', 1589179.0],
                      ['1964-12-31', 1548187.0],
                      ['1963-12-31', 1508273.0],
                      ['1962-12-31', 1469645.0],
                      ['1961-12-31', 1432640.0],
                      ['1960-12-31', 1397491.0],
                      ['1959-12-31', 1364276.0],
                      ['1958-12-31', 1332953.0],
                      ['1957-12-31', 1303420.0],
                      ['1956-12-31', 1275534.0],
                      ['1955-12-31', 1249193.0],
                      ['1954-12-31', 1224384.0],
                      ['1953-12-31', 1201124.0],
                      ['1952-12-31', 1179537.0],
                      ['1951-12-31', 1159798.0],
                      ['1950-12-31', 1142148.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'ERI_SP_POP_TOTL',
             'description': 'Population, total - Eritrea. ',
             'end_date': '2015-12-31',
             'frequency': 'annual',
             'id': 22135109,
             'limit': None,
             'name': 'Population, total - Eritrea',
             'newest_available_date': '2015-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:31:39.154Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
EST
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 1315480.0],
                      ['2016-12-31', 1315790.0],
                      ['2015-12-31', 1315407.0],
                      ['2014-12-31', 1314545.0],
                      ['2013-12-31', 1317997.0],
                      ['2012-12-31', 1322696.0],
                      ['2011-12-31', 1327439.0],
                      ['2010-12-31', 1331475.0],
                      ['2009-12-31', 1334515.0],
                      ['2008-12-31', 1337090.0],
                      ['2007-12-31', 1340680.0],
                      ['2006-12-31', 1346810.0],
                      ['2005-12-31', 1354775.0],
                      ['2004-12-31', 1362550.0],
                      ['2003-12-31', 1370720.0],
                      ['2002-12-31', 1379350.0],
                      ['2001-12-31', 1388115.0],
                      ['2000-12-31', 1396985.0],
                      ['1999-12-31', 1390244.0],
                      ['1998-12-31', 1386156.0],
                      ['1997-12-31', 1399535.0],
                      ['1996-12-31', 1415594.0],
                      ['1995-12-31', 1436634.0],
                      ['1994-12-31', 1462514.0],
                      ['1993-12-31', 1494128.0],
                      ['1992-12-31', 1533091.0],
                      ['1991-12-31', 1561314.0],
                      ['1990-12-31', 1569174.0],
                      ['1989-12-31', 1568131.0],
                      ['1988-12-31', 1561900.0],
                      ['1987-12-31', 1552221.0],
                      ['1986-12-31', 1540190.0],
                      ['1985-12-31', 1528781.0],
                      ['1984-12-31', 1518617.0],
                      ['1983-12-31', 1508745.0],
                      ['1982-12-31', 1498414.0],
                      ['1981-12-31', 1487666.0],
                      ['1980-12-31', 1477219.0],
                      ['1979-12-31', 1468333.0],
                      ['1978-12-31', 1460188.0],
                      ['1977-12-31', 1450211.0],
                      ['1976-12-31', 1439576.0],
                      ['1975-12-31', 1429352.0],
                      ['1974-12-31', 1418169.0],
                      ['1973-12-31', 1405951.0],
                      ['1972-12-31', 1392518.0],
                      ['1971-12-31', 1376955.0],
                      ['1970-12-31', 1360076.0],
                      ['1969-12-31', 1345249.0],
                      ['1968-12-31', 1331214.0],
                      ['1967-12-31', 1318946.0],
                      ['1966-12-31', 1308597.0],
                      ['1965-12-31', 1294566.0],
                      ['1964-12-31', 1277086.0],
                      ['1963-12-31', 1258857.0],
                      ['1962-12-31', 1241623.0],
                      ['1961-12-31', 1225077.0],
                      ['1960-12-31', 1211537.0],
                      ['1959-12-31', 1203467.0],
                      ['1958-12-31', 1191912.0],
                      ['1957-12-31', 1181044.0],
                      ['1956-12-31', 1170514.0],
                      ['1955-12-31', 1160002.0],
                      ['1954-12-31', 1149241.0],
                      ['1953-12-31', 1138038.0],
                      ['1952-12-31', 1126280.0],
                      ['1951-12-31', 1113922.0],
                      ['1950-12-31', 1100998.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'EST_SP_POP_TOTL',
             'description': 'Population, total - Estonia. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22138352,
             'limit': None,
             'name': 'Population, total - Estonia',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:31:49.566Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
ETH

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 104957438.0],
                      ['2016-12-31', 102403196.0],
                      ['2015-12-31', 99873033.0],
                      ['2014-12-31', 97366774.0],
                      ['2013-12-31', 94887724.0],
                      ['2012-12-31', 92444183.0],
                      ['2011-12-31', 90046756.0],
                      ['2010-12-31', 87702670.0],
                      ['2009-12-31', 85416253.0],
                      ['2008-12-31', 83184892.0],
                      ['2007-12-31', 81000409.0],
                      ['2006-12-31', 78850689.0],
                      ['2005-12-31', 76727083.0],
                      ['2004-12-31', 74624405.0],
                      ['2003-12-31', 72545144.0],
                      ['2002-12-31', 70497192.0],
                      ['2001-12-31', 68492257.0],
                      ['2000-12-31', 66537331.0],
                      ['1999-12-31', 64640054.0],
                      ['1998-12-31', 62794151.0],
                      ['1997-12-31', 60976450.0],
                      ['1996-12-31', 59155148.0],
                      ['1995-12-31', 57309880.0],
                      ['1994-12-31', 55431123.0],
                      ['1993-12-31', 53532956.0],
                      ['1992-12-31', 51647768.0],
                      ['1991-12-31', 49821083.0],
                      ['1990-12-31', 48086516.0],
                      ['1989-12-31', 46458913.0],
                      ['1988-12-31', 44932064.0],
                      ['1987-12-31', 43493283.0],
                      ['1986-12-31', 42120730.0],
                      ['1985-12-31', 40800343.0],
                      ['1984-12-31', 39518801.0],
                      ['1983-12-31', 38285883.0],
                      ['1982-12-31', 37136848.0],
                      ['1981-12-31', 36120288.0],
                      ['1980-12-31', 35264898.0],
                      ['1979-12-31', 34590226.0],
                      ['1978-12-31', 34068316.0],
                      ['1977-12-31', 33622390.0],
                      ['1976-12-31', 33146891.0],
                      ['1975-12-31', 32566821.0],
                      ['1974-12-31', 31851708.0],
                      ['1973-12-31', 31025115.0],
                      ['1972-12-31', 30132580.0],
                      ['1971-12-31', 29245207.0],
                      ['1970-12-31', 28415077.0],
                      ['1969-12-31', 27654161.0],
                      ['1968-12-31', 26946079.0],
                      ['1967-12-31', 26281208.0],
                      ['1966-12-31', 25641376.0],
                      ['1965-12-31', 25013626.0],
                      ['1964-12-31', 24397024.0],
                      ['1963-12-31', 23798429.0],
                      ['1962-12-31', 23221389.0],
                      ['1961-12-31', 22671190.0],
                      ['1960-12-31', 22151278.0],
                      ['1959-12-31', 21661996.0],
                      ['1958-12-31', 21201034.0],
                      ['1957-12-31', 20764450.0],
                      ['1956-12-31', 20347813.0],
                      ['1955-12-31', 19947292.0],
                      ['1954-12-31', 19560016.0],
                      ['1953-12-31', 19184292.0],
                      ['1952-12-31', 18819700.0],
                      ['1951-12-31', 18466968.0],
                      ['1950-12-31', 18128034.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'ETH_SP_POP_TOTL',
             'description': 'Population, total - Ethiopia. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22140309,
             'limit': None,
             'name': 'Population, total - Ethiopia',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:31:55.902Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
EMU
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 341465149.0],
                      ['2016-12-31', 340617355.0],
                      ['2015-12-31', 339533474.0],
                      ['2014-12-31', 338466271.0],
                      ['2013-12-31', 337325526.0],
                      ['2012-12-31', 336180504.0],
                      ['2011-12-31', 335429120.0],
                      ['2010-12-31', 336151474.0],
                      ['2009-12-31', 335360887.0],
                      ['2008-12-31', 334274730.0],
                      ['2007-12-31', 332645166.0],
                      ['2006-12-31', 330922791.0],
                      ['2005-12-31', 329380413.0],
                      ['2004-12-31', 327682507.0],
                      ['2003-12-31', 325885964.0],
                      ['2002-12-31', 324125338.0],
                      ['2001-12-31', 322547880.0],
                      ['2000-12-31', 321310787.0],
                      ['1999-12-31', 320258902.0],
                      ['1998-12-31', 319433983.0],
                      ['1997-12-31', 318761764.0],
                      ['1996-12-31', 318003015.0],
                      ['1995-12-31', 317181449.0],
                      ['1994-12-31', 316366779.0],
                      ['1993-12-31', 315449104.0],
                      ['1992-12-31', 314162056.0],
                      ['1991-12-31', 312708142.0],
                      ['1990-12-31', 311539698.0],
                      ['1989-12-31', 310080079.0],
                      ['1988-12-31', 308725859.0],
                      ['1987-12-31', 307668322.0],
                      ['1986-12-31', 306797207.0],
                      ['1985-12-31', 306018719.0],
                      ['1984-12-31', 305432240.0],
                      ['1983-12-31', 304920007.0],
                      ['1982-12-31', 304314034.0],
                      ['1981-12-31', 303498663.0],
                      ['1980-12-31', 302363486.0],
                      ['1979-12-31', 301099972.0],
                      ['1978-12-31', 299908948.0],
                      ['1977-12-31', 298738608.0],
                      ['1976-12-31', 297573002.0],
                      ['1975-12-31', 296244715.0],
                      ['1974-12-31', 294689415.0],
                      ['1973-12-31', 292961768.0],
                      ['1972-12-31', 291040689.0],
                      ['1971-12-31', 289032499.0],
                      ['1970-12-31', 287416205.0],
                      ['1969-12-31', 285855058.0],
                      ['1968-12-31', 283966953.0],
                      ['1967-12-31', 282114545.0],
                      ['1966-12-31', 280147494.0],
                      ['1965-12-31', 277856703.0],
                      ['1964-12-31', 275382197.0],
                      ['1963-12-31', 272876447.0],
                      ['1962-12-31', 270324828.0],
                      ['1961-12-31', 267825309.0],
                      ['1960-12-31', 265396502.0],
                      ['1959-12-31', 262381673.0],
                      ['1958-12-31', 260269879.0],
                      ['1957-12-31', 258265860.0],
                      ['1956-12-31', 256322755.0],
                      ['1955-12-31', 254406557.0],
                      ['1954-12-31', 252502542.0],
                      ['1953-12-31', 250619201.0],
                      ['1952-12-31', 248789510.0],
                      ['1951-12-31', 247069642.0],
                      ['1950-12-31', 245538973.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'EMU_SP_POP_TOTL',
             'description': 'Population, total - Euro area. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22133652,
             'limit': None,
             'name': 'Population, total - Euro area',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:31:33.663Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
ECS

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 915545801.0],
                      ['2016-12-31', 911686319.0],
                      ['2015-12-31', 907426233.0],
                      ['2014-12-31', 903123160.0],
                      ['2013-12-31', 898881448.0],
                      ['2012-12-31', 894679968.0],
                      ['2011-12-31', 891098854.0],
                      ['2010-12-31', 889016507.0],
                      ['2009-12-31', 885591814.0],
                      ['2008-12-31', 881965815.0],
                      ['2007-12-31', 878465990.0],
                      ['2006-12-31', 875343235.0],
                      ['2005-12-31', 872661616.0],
                      ['2004-12-31', 870030756.0],
                      ['2003-12-31', 867457664.0],
                      ['2002-12-31', 865196877.0],
                      ['2001-12-31', 863615632.0],
                      ['2000-12-31', 862304086.0],
                      ['1999-12-31', 861380108.0],
                      ['1998-12-31', 860236341.0],
                      ['1997-12-31', 859112733.0],
                      ['1996-12-31', 857652705.0],
                      ['1995-12-31', 856352860.0],
                      ['1994-12-31', 854723055.0],
                      ['1993-12-31', 852762016.0],
                      ['1992-12-31', 849656745.0],
                      ['1991-12-31', 846178276.0],
                      ['1990-12-31', 842848473.0],
                      ['1989-12-31', 838462813.0],
                      ['1988-12-31', 833315236.0],
                      ['1987-12-31', 828213790.0],
                      ['1986-12-31', 823155058.0],
                      ['1985-12-31', 818146882.0],
                      ['1984-12-31', 813281381.0],
                      ['1983-12-31', 808524728.0],
                      ['1982-12-31', 803972967.0],
                      ['1981-12-31', 799215272.0],
                      ['1980-12-31', 793937090.0],
                      ['1979-12-31', 788525199.0],
                      ['1978-12-31', 783298994.0],
                      ['1977-12-31', 778094845.0],
                      ['1976-12-31', 772838318.0],
                      ['1975-12-31', 767332578.0],
                      ['1974-12-31', 761701324.0],
                      ['1973-12-31', 755867961.0],
                      ['1972-12-31', 749815857.0],
                      ['1971-12-31', 743607439.0],
                      ['1970-12-31', 737948178.0],
                      ['1969-12-31', 732317863.0],
                      ['1968-12-31', 726161895.0],
                      ['1967-12-31', 719879789.0],
                      ['1966-12-31', 713341112.0],
                      ['1965-12-31', 706609007.0],
                      ['1964-12-31', 698905664.0],
                      ['1963-12-31', 690962675.0],
                      ['1962-12-31', 682938669.0],
                      ['1961-12-31', 674972972.0],
                      ['1960-12-31', 667246384.0],
                      ['1959-12-31', 658050139.0],
                      ['1958-12-31', 650430999.0],
                      ['1957-12-31', 643032485.0],
                      ['1956-12-31', 635769182.0],
                      ['1955-12-31', 628579915.0],
                      ['1954-12-31', 621342717.0],
                      ['1953-12-31', 614165198.0],
                      ['1952-12-31', 607171048.0],
                      ['1951-12-31', 600498522.0],
                      ['1950-12-31', 594314531.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'ECS_SP_POP_TOTL',
             'description': 'Population, total - Europe & Central Asia (all '
                            'income levels). ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22129471,
             'limit': None,
             'name': 'Population, total - Europe & Central Asia (all income '
                     'levels)',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:31:16.455Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
ECA
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 415546194.0],
                      ['2016-12-31', 413234935.0],
                      ['2015-12-31', 410770813.0],
                      ['2014-12-31', 408271623.0],
                      ['2013-12-31', 405871230.0],
                      ['2012-12-31', 403439691.0],
                      ['2011-12-31', 401241932.0],
                      ['2010-12-31', 399053204.0],
                      ['2009-12-31', 397043992.0],
                      ['2008-12-31', 395304586.0],
                      ['2007-12-31', 394257705.0],
                      ['2006-12-31', 393571334.0],
                      ['2005-12-31', 393027492.0],
                      ['2004-12-31', 392625999.0],
                      ['2003-12-31', 392280391.0],
                      ['2002-12-31', 392134307.0],
                      ['2001-12-31', 392446165.0],
                      ['2000-12-31', 392657969.0],
                      ['1999-12-31', 392517924.0],
                      ['1998-12-31', 392498014.0],
                      ['1997-12-31', 392200932.0],
                      ['1996-12-31', 391791161.0],
                      ['1995-12-31', 391384579.0],
                      ['1994-12-31', 390918548.0],
                      ['1993-12-31', 390265543.0],
                      ['1992-12-31', 389011005.0],
                      ['1991-12-31', 387397109.0],
                      ['1990-12-31', 385427446.0],
                      ['1989-12-31', 382860353.0],
                      ['1988-12-31', 379389656.0],
                      ['1987-12-31', 375756651.0],
                      ['1986-12-31', 372008350.0],
                      ['1985-12-31', 368248384.0],
                      ['1984-12-31', 364461750.0],
                      ['1983-12-31', 360691752.0],
                      ['1982-12-31', 357167765.0],
                      ['1981-12-31', 353625804.0],
                      ['1980-12-31', 349906056.0],
                      ['1979-12-31', 346252401.0],
                      ['1978-12-31', 342694227.0],
                      ['1977-12-31', 339114223.0],
                      ['1976-12-31', 335494688.0],
                      ['1975-12-31', 331816171.0],
                      ['1974-12-31', 328292612.0],
                      ['1973-12-31', 324789807.0],
                      ['1972-12-31', 321305116.0],
                      ['1971-12-31', 317799890.0],
                      ['1970-12-31', 314288628.0],
                      ['1969-12-31', 310775240.0],
                      ['1968-12-31', 307272189.0],
                      ['1967-12-31', 303700772.0],
                      ['1966-12-31', 300043201.0],
                      ['1965-12-31', 296453822.0],
                      ['1964-12-31', 292203393.0],
                      ['1963-12-31', 287888914.0],
                      ['1962-12-31', 283559690.0],
                      ['1961-12-31', 279245314.0],
                      ['1960-12-31', 274947938.0],
                      ['1959-12-31', 274430968.0],
                      ['1958-12-31', 269817783.0],
                      ['1957-12-31', 265277425.0],
                      ['1956-12-31', 260802226.0],
                      ['1955-12-31', 256390739.0],
                      ['1954-12-31', 251952959.0],
                      ['1953-12-31', 247595178.0],
                      ['1952-12-31', 243404200.0],
                      ['1951-12-31', 239447865.0],
                      ['1950-12-31', 235789129.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'ECA_SP_POP_TOTL',
             'description': 'Population, total - Europe & Central Asia '
                            '(developing only). ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22127911,
             'limit': None,
             'name': 'Population, total - Europe & Central Asia (developing '
                     'only)',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:31:11.861Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
CEU

{'quandl_error': {'code': 'QECx02',
                  'message': 'You have submitted an incorrect Quandl code. '
                             'Please check your Quandl codes and try again.'}}
EUU
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 512461290.0],
                      ['2016-12-31', 511218960.0],
                      ['2015-12-31', 509717579.0],
                      ['2014-12-31', 508193872.0],
                      ['2013-12-31', 506621110.0],
                      ['2012-12-31', 505117542.0],
                      ['2011-12-31', 504015371.0],
                      ['2010-12-31', 504421126.0],
                      ['2009-12-31', 503317964.0],
                      ['2008-12-31', 501808477.0],
                      ['2007-12-31', 499916647.0],
                      ['2006-12-31', 497973712.0],
                      ['2005-12-31', 496115006.0],
                      ['2004-12-31', 494162543.0],
                      ['2003-12-31', 492200117.0],
                      ['2002-12-31', 490390251.0],
                      ['2001-12-31', 489155665.0],
                      ['2000-12-31', 488178832.0],
                      ['1999-12-31', 487539366.0],
                      ['1998-12-31', 486565871.0],
                      ['1997-12-31', 485892094.0],
                      ['1996-12-31', 485000716.0],
                      ['1995-12-31', 484271344.0],
                      ['1994-12-31', 483262845.0],
                      ['1993-12-31', 482099286.0],
                      ['1992-12-31', 480438474.0],
                      ['1991-12-31', 478976405.0],
                      ['1990-12-31', 478005307.0],
                      ['1989-12-31', 476392094.0],
                      ['1988-12-31', 474792549.0],
                      ['1987-12-31', 473284093.0],
                      ['1986-12-31', 471937316.0],
                      ['1985-12-31', 470637754.0],
                      ['1984-12-31', 469501597.0],
                      ['1983-12-31', 468468840.0],
                      ['1982-12-31', 467389436.0],
                      ['1981-12-31', 466099879.0],
                      ['1980-12-31', 464392913.0],
                      ['1979-12-31', 462488540.0],
                      ['1978-12-31', 460699315.0],
                      ['1977-12-31', 458888174.0],
                      ['1976-12-31', 457001001.0],
                      ['1975-12-31', 454865483.0],
                      ['1974-12-31', 452475893.0],
                      ['1973-12-31', 449960637.0],
                      ['1972-12-31', 447253578.0],
                      ['1971-12-31', 444400996.0],
                      ['1970-12-31', 442062266.0],
                      ['1969-12-31', 439730656.0],
                      ['1968-12-31', 436916059.0],
                      ['1967-12-31', 434001556.0],
                      ['1966-12-31', 430868372.0],
                      ['1965-12-31', 427592605.0],
                      ['1964-12-31', 424075858.0],
                      ['1963-12-31', 420393293.0],
                      ['1962-12-31', 416670637.0],
                      ['1961-12-31', 413007006.0],
                      ['1960-12-31', 409498463.0],
                      ['1959-12-31', 404845878.0],
                      ['1958-12-31', 401671494.0],
                      ['1957-12-31', 398620153.0],
                      ['1956-12-31', 395628731.0],
                      ['1955-12-31', 392648346.0],
                      ['1954-12-31', 389644183.0],
                      ['1953-12-31', 386624348.0],
                      ['1952-12-31', 383617190.0],
                      ['1951-12-31', 380677848.0],
                      ['1950-12-31', 377888249.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'EUU_SP_POP_TOTL',
             'description': 'Population, total - European Union. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22141885,
             'limit': None,
             'name': 'Population, total - European Union',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:32:00.932Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
FRO
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 49290.0],
                      ['2016-12-31', 49117.0],
                      ['2015-12-31', 48965.0],
                      ['2014-12-31', 48842.0],
                      ['2013-12-31', 48747.0],
                      ['2012-12-31', 48666.0],
                      ['2011-12-31', 48608.0],
                      ['2010-12-31', 48550.0],
                      ['2009-12-31', 48517.0],
                      ['2008-12-31', 48485.0],
                      ['2007-12-31', 48448.0],
                      ['2006-12-31', 48383.0],
                      ['2005-12-31', 48285.0],
                      ['2004-12-31', 48143.0],
                      ['2003-12-31', 47974.0],
                      ['2002-12-31', 47769.0],
                      ['2001-12-31', 47526.0],
                      ['2000-12-31', 47258.0],
                      ['1999-12-31', 46937.0],
                      ['1998-12-31', 46580.0],
                      ['1997-12-31', 46251.0],
                      ['1996-12-31', 46058.0],
                      ['1995-12-31', 46040.0],
                      ['1994-12-31', 46250.0],
                      ['1993-12-31', 46640.0],
                      ['1992-12-31', 47101.0],
                      ['1991-12-31', 47457.0],
                      ['1990-12-31', 47594.0],
                      ['1989-12-31', 47466.0],
                      ['1988-12-31', 47117.0],
                      ['1987-12-31', 46621.0],
                      ['1986-12-31', 46077.0],
                      ['1985-12-31', 45573.0],
                      ['1984-12-31', 45122.0],
                      ['1983-12-31', 44700.0],
                      ['1982-12-31', 44307.0],
                      ['1981-12-31', 43917.0],
                      ['1980-12-31', 43514.0],
                      ['1979-12-31', 43101.0],
                      ['1978-12-31', 42693.0],
                      ['1977-12-31', 42275.0],
                      ['1976-12-31', 41848.0],
                      ['1975-12-31', 41407.0],
                      ['1974-12-31', 40955.0],
                      ['1973-12-31', 40486.0],
                      ['1972-12-31', 40009.0],
                      ['1971-12-31', 39537.0],
                      ['1970-12-31', 39083.0],
                      ['1969-12-31', 38646.0],
                      ['1968-12-31', 38200.0],
                      ['1967-12-31', 37768.0],
                      ['1966-12-31', 37334.0],
                      ['1965-12-31', 36900.0],
                      ['1964-12-31', 36454.0],
                      ['1963-12-31', 36014.0],
                      ['1962-12-31', 35570.0],
                      ['1961-12-31', 35115.0],
                      ['1960-12-31', 34661.0],
                      ['1959-12-31', 34192.0],
                      ['1958-12-31', 33743.0],
                      ['1957-12-31', 33295.0],
                      ['1956-12-31', 32882.0],
                      ['1955-12-31', 32496.0],
                      ['1954-12-31', 32159.0],
                      ['1953-12-31', 31881.0],
                      ['1952-12-31', 31672.0],
                      ['1951-12-31', 31538.0],
                      ['1950-12-31', 31503.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'FRO_SP_POP_TOTL',
             'description': 'Population, total - Faeroe Islands. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22147703,
             'limit': None,
             'name': 'Population, total - Faeroe Islands',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:32:19.217Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
FJI

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 905502.0],
                      ['2016-12-31', 898760.0],
                      ['2015-12-31', 892149.0],
                      ['2014-12-31', 885806.0],
                      ['2013-12-31', 879715.0],
                      ['2012-12-31', 873596.0],
                      ['2011-12-31', 867086.0],
                      ['2010-12-31', 859950.0],
                      ['2009-12-31', 851967.0],
                      ['2008-12-31', 843340.0],
                      ['2007-12-31', 834812.0],
                      ['2006-12-31', 827411.0],
                      ['2005-12-31', 821817.0],
                      ['2004-12-31', 818354.0],
                      ['2003-12-31', 816628.0],
                      ['2002-12-31', 815691.0],
                      ['2001-12-31', 814218.0],
                      ['2000-12-31', 811223.0],
                      ['1999-12-31', 806494.0],
                      ['1998-12-31', 800315.0],
                      ['1997-12-31', 792860.0],
                      ['1996-12-31', 784476.0],
                      ['1995-12-31', 775498.0],
                      ['1994-12-31', 765667.0],
                      ['1993-12-31', 755026.0],
                      ['1992-12-31', 744531.0],
                      ['1991-12-31', 735473.0],
                      ['1990-12-31', 728628.0],
                      ['1989-12-31', 724624.0],
                      ['1988-12-31', 722917.0],
                      ['1987-12-31', 721725.0],
                      ['1986-12-31', 718548.0],
                      ['1985-12-31', 711661.0],
                      ['1984-12-31', 700366.0],
                      ['1983-12-31', 685391.0],
                      ['1982-12-31', 668198.0],
                      ['1981-12-31', 650955.0],
                      ['1980-12-31', 635255.0],
                      ['1979-12-31', 621538.0],
                      ['1978-12-31', 609345.0],
                      ['1977-12-31', 598259.0],
                      ['1976-12-31', 587520.0],
                      ['1975-12-31', 576595.0],
                      ['1974-12-31', 565388.0],
                      ['1973-12-31', 554107.0],
                      ['1972-12-31', 542814.0],
                      ['1971-12-31', 531601.0],
                      ['1970-12-31', 520529.0],
                      ['1969-12-31', 509658.0],
                      ['1968-12-31', 498892.0],
                      ['1967-12-31', 487913.0],
                      ['1966-12-31', 476324.0],
                      ['1965-12-31', 463883.0],
                      ['1964-12-31', 450450.0],
                      ['1963-12-31', 436208.0],
                      ['1962-12-31', 421577.0],
                      ['1961-12-31', 407156.0],
                      ['1960-12-31', 393386.0],
                      ['1959-12-31', 380451.0],
                      ['1958-12-31', 368319.0],
                      ['1957-12-31', 356820.0],
                      ['1956-12-31', 345744.0],
                      ['1955-12-31', 334976.0],
                      ['1954-12-31', 324482.0],
                      ['1953-12-31', 314351.0],
                      ['1952-12-31', 304814.0],
                      ['1951-12-31', 296209.0],
                      ['1950-12-31', 288988.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'FJI_SP_POP_TOTL',
             'description': 'Population, total - Fiji. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22145229,
             'limit': None,
             'name': 'Population, total - Fiji',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:32:11.185Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
FIN
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 5511303.0],
                      ['2016-12-31', 5495303.0],
                      ['2015-12-31', 5479531.0],
                      ['2014-12-31', 5461512.0],
                      ['2013-12-31', 5438972.0],
                      ['2012-12-31', 5413971.0],
                      ['2011-12-31', 5388272.0],
                      ['2010-12-31', 5363352.0],
                      ['2009-12-31', 5338871.0],
                      ['2008-12-31', 5313399.0],
                      ['2007-12-31', 5288720.0],
                      ['2006-12-31', 5266268.0],
                      ['2005-12-31', 5246096.0],
                      ['2004-12-31', 5228172.0],
                      ['2003-12-31', 5213014.0],
                      ['2002-12-31', 5200598.0],
                      ['2001-12-31', 5188008.0],
                      ['2000-12-31', 5176209.0],
                      ['1999-12-31', 5165474.0],
                      ['1998-12-31', 5153498.0],
                      ['1997-12-31', 5139835.0],
                      ['1996-12-31', 5124573.0],
                      ['1995-12-31', 5107790.0],
                      ['1994-12-31', 5088333.0],
                      ['1993-12-31', 5066447.0],
                      ['1992-12-31', 5041992.0],
                      ['1991-12-31', 5013740.0],
                      ['1990-12-31', 4986431.0],
                      ['1989-12-31', 4964371.0],
                      ['1988-12-31', 4946481.0],
                      ['1987-12-31', 4932123.0],
                      ['1986-12-31', 4918154.0],
                      ['1985-12-31', 4902206.0],
                      ['1984-12-31', 4881803.0],
                      ['1983-12-31', 4855787.0],
                      ['1982-12-31', 4826933.0],
                      ['1981-12-31', 4799964.0],
                      ['1980-12-31', 4779535.0],
                      ['1979-12-31', 4764690.0],
                      ['1978-12-31', 4752528.0],
                      ['1977-12-31', 4738902.0],
                      ['1976-12-31', 4725664.0],
                      ['1975-12-31', 4711440.0],
                      ['1974-12-31', 4690574.0],
                      ['1973-12-31', 4666081.0],
                      ['1972-12-31', 4639657.0],
                      ['1971-12-31', 4612124.0],
                      ['1970-12-31', 4606307.0],
                      ['1969-12-31', 4623785.0],
                      ['1968-12-31', 4626469.0],
                      ['1967-12-31', 4605744.0],
                      ['1966-12-31', 4580869.0],
                      ['1965-12-31', 4563732.0],
                      ['1964-12-31', 4548543.0],
                      ['1963-12-31', 4523309.0],
                      ['1962-12-31', 4491443.0],
                      ['1961-12-31', 4461005.0],
                      ['1960-12-31', 4429634.0],
                      ['1959-12-31', 4395188.0],
                      ['1958-12-31', 4358612.0],
                      ['1957-12-31', 4319898.0],
                      ['1956-12-31', 4278702.0],
                      ['1955-12-31', 4235002.0],
                      ['1954-12-31', 4189185.0],
                      ['1953-12-31', 4142102.0],
                      ['1952-12-31', 4095096.0],
                      ['1951-12-31', 4049971.0],
                      ['1950-12-31', 4009003.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'FIN_SP_POP_TOTL',
             'description': 'Population, total - Finland. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22143558,
             'limit': None,
             'name': 'Population, total - Finland',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:32:05.885Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
FRA

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 67118648.0],
                      ['2016-12-31', 66859768.0],
                      ['2015-12-31', 66593366.0],
                      ['2014-12-31', 66316092.0],
                      ['2013-12-31', 65998660.0],
                      ['2012-12-31', 65659789.0],
                      ['2011-12-31', 65342775.0],
                      ['2010-12-31', 65027507.0],
                      ['2009-12-31', 64707044.0],
                      ['2008-12-31', 64374989.0],
                      ['2007-12-31', 64016227.0],
                      ['2006-12-31', 63621381.0],
                      ['2005-12-31', 63179351.0],
                      ['2004-12-31', 62704895.0],
                      ['2003-12-31', 62244886.0],
                      ['2002-12-31', 61805267.0],
                      ['2001-12-31', 61357430.0],
                      ['2000-12-31', 60912500.0],
                      ['1999-12-31', 60496718.0],
                      ['1998-12-31', 60186288.0],
                      ['1997-12-31', 59964851.0],
                      ['1996-12-31', 59753100.0],
                      ['1995-12-31', 59541899.0],
                      ['1994-12-31', 59327192.0],
                      ['1993-12-31', 59106768.0],
                      ['1992-12-31', 58851217.0],
                      ['1991-12-31', 58559311.0],
                      ['1990-12-31', 58512808.0],
                      ['1989-12-31', 58182702.0],
                      ['1988-12-31', 57836486.0],
                      ['1987-12-31', 57482591.0],
                      ['1986-12-31', 57132691.0],
                      ['1985-12-31', 56795686.0],
                      ['1984-12-31', 56470769.0],
                      ['1983-12-31', 56156284.0],
                      ['1982-12-31', 55858727.0],
                      ['1981-12-31', 55585824.0],
                      ['1980-12-31', 55340782.0],
                      ['1979-12-31', 55130594.0],
                      ['1978-12-31', 54947975.0],
                      ['1977-12-31', 54764462.0],
                      ['1976-12-31', 54541493.0],
                      ['1975-12-31', 54252574.0],
                      ['1974-12-31', 53882416.0],
                      ['1973-12-31', 53441264.0],
                      ['1972-12-31', 52959228.0],
                      ['1971-12-31', 52480421.0],
                      ['1970-12-31', 52035095.0],
                      ['1969-12-31', 51638260.0],
                      ['1968-12-31', 51276054.0],
                      ['1967-12-31', 50915456.0],
                      ['1966-12-31', 50508717.0],
                      ['1965-12-31', 50023774.0],
                      ['1964-12-31', 49449403.0],
                      ['1963-12-31', 48803680.0],
                      ['1962-12-31', 48119649.0],
                      ['1961-12-31', 47444751.0],
                      ['1960-12-31', 46814237.0],
                      ['1959-12-31', 46242129.0],
                      ['1958-12-31', 45724403.0],
                      ['1957-12-31', 45246453.0],
                      ['1956-12-31', 44791572.0],
                      ['1955-12-31', 44348943.0],
                      ['1954-12-31', 43916298.0],
                      ['1953-12-31', 43501503.0],
                      ['1952-12-31', 43123100.0],
                      ['1951-12-31', 42809772.0],
                      ['1950-12-31', 42600338.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'FRA_SP_POP_TOTL',
             'description': 'Population, total - France. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22146927,
             'limit': None,
             'name': 'Population, total - France',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:32:16.315Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
PYF
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 283007.0],
                      ['2016-12-31', 280208.0],
                      ['2015-12-31', 277690.0],
                      ['2014-12-31', 275484.0],
                      ['2013-12-31', 273528.0],
                      ['2012-12-31', 271703.0],
                      ['2011-12-31', 269843.0],
                      ['2010-12-31', 267820.0],
                      ['2009-12-31', 265581.0],
                      ['2008-12-31', 263179.0],
                      ['2007-12-31', 260594.0],
                      ['2006-12-31', 257832.0],
                      ['2005-12-31', 254886.0],
                      ['2004-12-31', 251775.0],
                      ['2003-12-31', 248499.0],
                      ['2002-12-31', 245006.0],
                      ['2001-12-31', 241273.0],
                      ['2000-12-31', 237258.0],
                      ['1999-12-31', 232952.0],
                      ['1998-12-31', 228376.0],
                      ['1997-12-31', 223731.0],
                      ['1996-12-31', 219283.0],
                      ['1995-12-31', 215196.0],
                      ['1994-12-31', 211579.0],
                      ['1993-12-31', 208345.0],
                      ['1992-12-31', 205266.0],
                      ['1991-12-31', 202016.0],
                      ['1990-12-31', 198375.0],
                      ['1989-12-31', 194252.0],
                      ['1988-12-31', 189738.0],
                      ['1987-12-31', 184950.0],
                      ['1986-12-31', 180075.0],
                      ['1985-12-31', 175204.0],
                      ['1984-12-31', 170396.0],
                      ['1983-12-31', 165613.0],
                      ['1982-12-31', 160888.0],
                      ['1981-12-31', 156243.0],
                      ['1980-12-31', 151708.0],
                      ['1979-12-31', 147296.0],
                      ['1978-12-31', 143032.0],
                      ['1977-12-31', 138864.0],
                      ['1976-12-31', 134748.0],
                      ['1975-12-31', 130619.0],
                      ['1974-12-31', 126486.0],
                      ['1973-12-31', 122356.0],
                      ['1972-12-31', 118279.0],
                      ['1971-12-31', 114313.0],
                      ['1970-12-31', 110495.0],
                      ['1969-12-31', 106857.0],
                      ['1968-12-31', 103386.0],
                      ['1967-12-31', 100029.0],
                      ['1966-12-31', 96732.0],
                      ['1965-12-31', 93438.0],
                      ['1964-12-31', 90132.0],
                      ['1963-12-31', 86837.0],
                      ['1962-12-31', 83651.0],
                      ['1961-12-31', 80703.0],
                      ['1960-12-31', 78076.0],
                      ['1959-12-31', 75806.0],
                      ['1958-12-31', 73827.0],
                      ['1957-12-31', 72060.0],
                      ['1956-12-31', 70429.0],
                      ['1955-12-31', 68854.0],
                      ['1954-12-31', 67252.0],
                      ['1953-12-31', 65593.0],
                      ['1952-12-31', 63870.0],
                      ['1951-12-31', 62085.0],
                      ['1950-12-31', 60266.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'PYF_SP_POP_TOTL',
             'description': 'Population, total - French Polynesia. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22221208,
             'limit': None,
             'name': 'Population, total - French Polynesia',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:42:17.634Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
GAB

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 2025137.0],
                      ['2016-12-31', 1979786.0],
                      ['2015-12-31', 1930175.0],
                      ['2014-12-31', 1875713.0],
                      ['2013-12-31', 1817271.0],
                      ['2012-12-31', 1756817.0],
                      ['2011-12-31', 1697101.0],
                      ['2010-12-31', 1640210.0],
                      ['2009-12-31', 1586754.0],
                      ['2008-12-31', 1536411.0],
                      ['2007-12-31', 1489193.0],
                      ['2006-12-31', 1444844.0],
                      ['2005-12-31', 1403126.0],
                      ['2004-12-31', 1364205.0],
                      ['2003-12-31', 1328146.0],
                      ['2002-12-31', 1294409.0],
                      ['2001-12-31', 1262259.0],
                      ['2000-12-31', 1231122.0],
                      ['1999-12-31', 1200773.0],
                      ['1998-12-31', 1171224.0],
                      ['1997-12-31', 1142324.0],
                      ['1996-12-31', 1113994.0],
                      ['1995-12-31', 1086137.0],
                      ['1994-12-31', 1058663.0],
                      ['1993-12-31', 1031504.0],
                      ['1992-12-31', 1004676.0],
                      ['1991-12-31', 978223.0],
                      ['1990-12-31', 952212.0],
                      ['1989-12-31', 926622.0],
                      ['1988-12-31', 901458.0],
                      ['1987-12-31', 876863.0],
                      ['1986-12-31', 853027.0],
                      ['1985-12-31', 830085.0],
                      ['1984-12-31', 808083.0],
                      ['1983-12-31', 787013.0],
                      ['1982-12-31', 766855.0],
                      ['1981-12-31', 747587.0],
                      ['1980-12-31', 729159.0],
                      ['1979-12-31', 711533.0],
                      ['1978-12-31', 694732.0],
                      ['1977-12-31', 678774.0],
                      ['1976-12-31', 663770.0],
                      ['1975-12-31', 649716.0],
                      ['1974-12-31', 636696.0],
                      ['1973-12-31', 624621.0],
                      ['1972-12-31', 613123.0],
                      ['1971-12-31', 601731.0],
                      ['1970-12-31', 590118.0],
                      ['1969-12-31', 578108.0],
                      ['1968-12-31', 565873.0],
                      ['1967-12-31', 553823.0],
                      ['1966-12-31', 542557.0],
                      ['1965-12-31', 532511.0],
                      ['1964-12-31', 523789.0],
                      ['1963-12-31', 516265.0],
                      ['1962-12-31', 509806.0],
                      ['1961-12-31', 504167.0],
                      ['1960-12-31', 499184.0],
                      ['1959-12-31', 494751.0],
                      ['1958-12-31', 490870.0],
                      ['1957-12-31', 487536.0],
                      ['1956-12-31', 484782.0],
                      ['1955-12-31', 482560.0],
                      ['1954-12-31', 480767.0],
                      ['1953-12-31', 479237.0],
                      ['1952-12-31', 477711.0],
                      ['1951-12-31', 475865.0],
                      ['1950-12-31', 473298.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'GAB_SP_POP_TOTL',
             'description': 'Population, total - Gabon. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22149850,
             'limit': None,
             'name': 'Population, total - Gabon',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:32:27.698Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
GMB
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 2100568.0],
                      ['2016-12-31', 2038501.0],
                      ['2015-12-31', 1977590.0],
                      ['2014-12-31', 1917852.0],
                      ['2013-12-31', 1859324.0],
                      ['2012-12-31', 1802125.0],
                      ['2011-12-31', 1746363.0],
                      ['2010-12-31', 1692149.0],
                      ['2009-12-31', 1639560.0],
                      ['2008-12-31', 1588572.0],
                      ['2007-12-31', 1539116.0],
                      ['2006-12-31', 1491021.0],
                      ['2005-12-31', 1444204.0],
                      ['2004-12-31', 1398573.0],
                      ['2003-12-31', 1354194.0],
                      ['2002-12-31', 1311349.0],
                      ['2001-12-31', 1270495.0],
                      ['2000-12-31', 1231844.0],
                      ['1999-12-31', 1195420.0],
                      ['1998-12-31', 1160944.0],
                      ['1997-12-31', 1128169.0],
                      ['1996-12-31', 1096708.0],
                      ['1995-12-31', 1066223.0],
                      ['1994-12-31', 1036829.0],
                      ['1993-12-31', 1008358.0],
                      ['1992-12-31', 979718.0],
                      ['1991-12-31', 949493.0],
                      ['1990-12-31', 916808.0],
                      ['1989-12-31', 881138.0],
                      ['1988-12-31', 843050.0],
                      ['1987-12-31', 804125.0],
                      ['1986-12-31', 766589.0],
                      ['1985-12-31', 732096.0],
                      ['1984-12-31', 701104.0],
                      ['1983-12-31', 673238.0],
                      ['1982-12-31', 648210.0],
                      ['1981-12-31', 625411.0],
                      ['1980-12-31', 604369.0],
                      ['1979-12-31', 585157.0],
                      ['1978-12-31', 567831.0],
                      ['1977-12-31', 551817.0],
                      ['1976-12-31', 536409.0],
                      ['1975-12-31', 521070.0],
                      ['1974-12-31', 505512.0],
                      ['1973-12-31', 489861.0],
                      ['1972-12-31', 474539.0],
                      ['1971-12-31', 460194.0],
                      ['1970-12-31', 447285.0],
                      ['1969-12-31', 435798.0],
                      ['1968-12-31', 425510.0],
                      ['1967-12-31', 416339.0],
                      ['1966-12-31', 408180.0],
                      ['1965-12-31', 400861.0],
                      ['1964-12-31', 394553.0],
                      ['1963-12-31', 389072.0],
                      ['1962-12-31', 383523.0],
                      ['1961-12-31', 376737.0],
                      ['1960-12-31', 367928.0],
                      ['1959-12-31', 356968.0],
                      ['1958-12-31', 344265.0],
                      ['1957-12-31', 330600.0],
                      ['1956-12-31', 316907.0],
                      ['1955-12-31', 304029.0],
                      ['1954-12-31', 292713.0],
                      ['1953-12-31', 283505.0],
                      ['1952-12-31', 276773.0],
                      ['1951-12-31', 272720.0],
                      ['1950-12-31', 271377.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'GMB_SP_POP_TOTL',
             'description': 'Population, total - Gambia, The. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22159209,
             'limit': None,
             'name': 'Population, total - Gambia, The',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:32:58.382Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
GEO

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 3717100.0],
                      ['2016-12-31', 3719300.0],
                      ['2015-12-31', 3717100.0],
                      ['2014-12-31', 3727000.0],
                      ['2013-12-31', 3776000.0],
                      ['2012-12-31', 3825000.0],
                      ['2011-12-31', 3875000.0],
                      ['2010-12-31', 3926000.0],
                      ['2009-12-31', 3978000.0],
                      ['2008-12-31', 4030000.0],
                      ['2007-12-31', 4082000.0],
                      ['2006-12-31', 4136000.0],
                      ['2005-12-31', 4190000.0],
                      ['2004-12-31', 4245000.0],
                      ['2003-12-31', 4301000.0],
                      ['2002-12-31', 4357000.0],
                      ['2001-12-31', 4386400.0],
                      ['2000-12-31', 4418300.0],
                      ['1999-12-31', 4452500.0],
                      ['1998-12-31', 4487300.0],
                      ['1997-12-31', 4531600.0],
                      ['1996-12-31', 4616100.0],
                      ['1995-12-31', 4734000.0],
                      ['1994-12-31', 4861600.0],
                      ['1993-12-31', 4911100.0],
                      ['1992-12-31', 4873500.0],
                      ['1991-12-31', 4835900.0],
                      ['1990-12-31', 4802000.0],
                      ['1989-12-31', 4803300.0],
                      ['1988-12-31', 4790700.0],
                      ['1987-12-31', 4743500.0],
                      ['1986-12-31', 4704500.0],
                      ['1985-12-31', 4662900.0],
                      ['1984-12-31', 4622200.0],
                      ['1983-12-31', 4582900.0],
                      ['1982-12-31', 4542800.0],
                      ['1981-12-31', 4504500.0],
                      ['1980-12-31', 4467700.0],
                      ['1979-12-31', 4430200.0],
                      ['1978-12-31', 4397700.0],
                      ['1977-12-31', 4372100.0],
                      ['1976-12-31', 4342400.0],
                      ['1975-12-31', 4311200.0],
                      ['1974-12-31', 4279500.0],
                      ['1973-12-31', 4242500.0],
                      ['1972-12-31', 4205300.0],
                      ['1971-12-31', 4163000.0],
                      ['1970-12-31', 4119900.0],
                      ['1969-12-31', 4080300.0],
                      ['1968-12-31', 4042300.0],
                      ['1967-12-31', 4005800.0],
                      ['1966-12-31', 3966700.0],
                      ['1965-12-31', 3921600.0],
                      ['1964-12-31', 3870300.0],
                      ['1963-12-31', 3816100.0],
                      ['1962-12-31', 3760300.0],
                      ['1961-12-31', 3703600.0],
                      ['1960-12-31', 3645600.0],
                      ['1959-12-31', 3579000.0],
                      ['1958-12-31', 3512200.0],
                      ['1957-12-31', 3463800.0],
                      ['1956-12-31', 3419800.0],
                      ['1955-12-31', 3366300.0],
                      ['1954-12-31', 3308800.0],
                      ['1953-12-31', 3239600.0],
                      ['1952-12-31', 3188500.0],
                      ['1951-12-31', 3150900.0],
                      ['1950-12-31', 3099700.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'GEO_SP_POP_TOTL',
             'description': 'Population, total - Georgia. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22153459,
             'limit': None,
             'name': 'Population, total - Georgia',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:32:38.875Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
DEU
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 82695000.0],
                      ['2016-12-31', 82348669.0],
                      ['2015-12-31', 81686611.0],
                      ['2014-12-31', 80982500.0],
                      ['2013-12-31', 80645605.0],
                      ['2012-12-31', 80425823.0],
                      ['2011-12-31', 80274983.0],
                      ['2010-12-31', 81776930.0],
                      ['2009-12-31', 81902307.0],
                      ['2008-12-31', 82110097.0],
                      ['2007-12-31', 82266372.0],
                      ['2006-12-31', 82376451.0],
                      ['2005-12-31', 82469422.0],
                      ['2004-12-31', 82516260.0],
                      ['2003-12-31', 82534176.0],
                      ['2002-12-31', 82488495.0],
                      ['2001-12-31', 82349925.0],
                      ['2000-12-31', 82211508.0],
                      ['1999-12-31', 82100243.0],
                      ['1998-12-31', 82047195.0],
                      ['1997-12-31', 82034771.0],
                      ['1996-12-31', 81914831.0],
                      ['1995-12-31', 81678051.0],
                      ['1994-12-31', 81438348.0],
                      ['1993-12-31', 81156363.0],
                      ['1992-12-31', 80624598.0],
                      ['1991-12-31', 80013896.0],
                      ['1990-12-31', 79433029.0],
                      ['1989-12-31', 78751283.0],
                      ['1988-12-31', 78144619.0],
                      ['1987-12-31', 77839920.0],
                      ['1986-12-31', 77720436.0],
                      ['1985-12-31', 77684873.0],
                      ['1984-12-31', 77858685.0],
                      ['1983-12-31', 78128282.0],
                      ['1982-12-31', 78333366.0],
                      ['1981-12-31', 78407907.0],
                      ['1980-12-31', 78288576.0],
                      ['1979-12-31', 78126350.0],
                      ['1978-12-31', 78091820.0],
                      ['1977-12-31', 78159814.0],
                      ['1976-12-31', 78336950.0],
                      ['1975-12-31', 78673554.0],
                      ['1974-12-31', 78967433.0],
                      ['1973-12-31', 78936666.0],
                      ['1972-12-31', 78688452.0],
                      ['1971-12-31', 78312842.0],
                      ['1970-12-31', 78169289.0],
                      ['1969-12-31', 77909682.0],
                      ['1968-12-31', 77294314.0],
                      ['1967-12-31', 76951336.0],
                      ['1966-12-31', 76600311.0],
                      ['1965-12-31', 75963695.0],
                      ['1964-12-31', 75318337.0],
                      ['1963-12-31', 74714353.0],
                      ['1962-12-31', 74025784.0],
                      ['1961-12-31', 73377632.0],
                      ['1960-12-31', 72814900.0],
                      ['1959-12-31', 72247225.0],
                      ['1958-12-31', 71721922.0],
                      ['1957-12-31', 71232304.0],
                      ['1956-12-31', 70769436.0],
                      ['1955-12-31', 70325997.0],
                      ['1954-12-31', 69897556.0],
                      ['1953-12-31', 69483349.0],
                      ['1952-12-31', 69086530.0],
                      ['1951-12-31', 68713920.0],
                      ['1950-12-31', 68376002.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'DEU_SP_POP_TOTL',
             'description': 'Population, total - Germany. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22114747,
             'limit': None,
             'name': 'Population, total - Germany',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:30:29.509Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
GHA

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 28833629.0],
                      ['2016-12-31', 28206728.0],
                      ['2015-12-31', 27582821.0],
                      ['2014-12-31', 26962563.0],
                      ['2013-12-31', 26346251.0],
                      ['2012-12-31', 25733049.0],
                      ['2011-12-31', 25121796.0],
                      ['2010-12-31', 24512104.0],
                      ['2009-12-31', 23903831.0],
                      ['2008-12-31', 23298640.0],
                      ['2007-12-31', 22700212.0],
                      ['2006-12-31', 22113425.0],
                      ['2005-12-31', 21542009.0],
                      ['2004-12-31', 20986536.0],
                      ['2003-12-31', 20446782.0],
                      ['2002-12-31', 19924522.0],
                      ['2001-12-31', 19421605.0],
                      ['2000-12-31', 18938762.0],
                      ['1999-12-31', 18477612.0],
                      ['1998-12-31', 18036494.0],
                      ['1997-12-31', 17608812.0],
                      ['1996-12-31', 17185608.0],
                      ['1995-12-31', 16760467.0],
                      ['1994-12-31', 16330174.0],
                      ['1993-12-31', 15896432.0],
                      ['1992-12-31', 15463854.0],
                      ['1991-12-31', 15039514.0],
                      ['1990-12-31', 14628260.0],
                      ['1989-12-31', 14233874.0],
                      ['1988-12-31', 13854214.0],
                      ['1987-12-31', 13481406.0],
                      ['1986-12-31', 13104296.0],
                      ['1985-12-31', 12716228.0],
                      ['1984-12-31', 12311158.0],
                      ['1983-12-31', 11895125.0],
                      ['1982-12-31', 11488106.0],
                      ['1981-12-31', 11117605.0],
                      ['1980-12-31', 10802028.0],
                      ['1979-12-31', 10550777.0],
                      ['1978-12-31', 10354499.0],
                      ['1977-12-31', 10189890.0],
                      ['1976-12-31', 10023472.0],
                      ['1975-12-31', 9831407.0],
                      ['1974-12-31', 9604276.0],
                      ['1973-12-31', 9350111.0],
                      ['1972-12-31', 9083573.0],
                      ['1971-12-31', 8827273.0],
                      ['1970-12-31', 8596983.0],
                      ['1969-12-31', 8397347.0],
                      ['1968-12-31', 8221020.0],
                      ['1967-12-31', 8057444.0],
                      ['1966-12-31', 7890992.0],
                      ['1965-12-31', 7710549.0],
                      ['1964-12-31', 7513289.0],
                      ['1963-12-31', 7303432.0],
                      ['1962-12-31', 7085464.0],
                      ['1961-12-31', 6866539.0],
                      ['1960-12-31', 6652287.0],
                      ['1959-12-31', 6445283.0],
                      ['1958-12-31', 6245646.0],
                      ['1957-12-31', 6052159.0],
                      ['1956-12-31', 5863686.0],
                      ['1955-12-31', 5680410.0],
                      ['1954-12-31', 5504254.0],
                      ['1953-12-31', 5339182.0],
                      ['1952-12-31', 5191219.0],
                      ['1951-12-31', 5068436.0],
                      ['1950-12-31', 4980875.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'GHA_SP_POP_TOTL',
             'description': 'Population, total - Ghana. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22155471,
             'limit': None,
             'name': 'Population, total - Ghana',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:32:45.628Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
GRC
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 10760421.0],
                      ['2016-12-31', 10775971.0],
                      ['2015-12-31', 10820883.0],
                      ['2014-12-31', 10892413.0],
                      ['2013-12-31', 10965211.0],
                      ['2012-12-31', 11045011.0],
                      ['2011-12-31', 11104899.0],
                      ['2010-12-31', 11121341.0],
                      ['2009-12-31', 11107017.0],
                      ['2008-12-31', 11077841.0],
                      ['2007-12-31', 11048473.0],
                      ['2006-12-31', 11020362.0],
                      ['2005-12-31', 10987314.0],
                      ['2004-12-31', 10955141.0],
                      ['2003-12-31', 10928070.0],
                      ['2002-12-31', 10902022.0],
                      ['2001-12-31', 10862132.0],
                      ['2000-12-31', 10805808.0],
                      ['1999-12-31', 10761698.0],
                      ['1998-12-31', 10720509.0],
                      ['1997-12-31', 10661259.0],
                      ['1996-12-31', 10608800.0],
                      ['1995-12-31', 10562153.0],
                      ['1994-12-31', 10512922.0],
                      ['1993-12-31', 10460415.0],
                      ['1992-12-31', 10399061.0],
                      ['1991-12-31', 10319927.0],
                      ['1990-12-31', 10196792.0],
                      ['1989-12-31', 10089498.0],
                      ['1988-12-31', 10036983.0],
                      ['1987-12-31', 10000595.0],
                      ['1986-12-31', 9967213.0],
                      ['1985-12-31', 9934300.0],
                      ['1984-12-31', 9895801.0],
                      ['1983-12-31', 9846627.0],
                      ['1982-12-31', 9789513.0],
                      ['1981-12-31', 9729350.0],
                      ['1980-12-31', 9642505.0],
                      ['1979-12-31', 9548258.0],
                      ['1978-12-31', 9429959.0],
                      ['1977-12-31', 9308479.0],
                      ['1976-12-31', 9188150.0],
                      ['1975-12-31', 9046541.0],
                      ['1974-12-31', 8962022.0],
                      ['1973-12-31', 8929086.0],
                      ['1972-12-31', 8888628.0],
                      ['1971-12-31', 8831036.0],
                      ['1970-12-31', 8792806.0],
                      ['1969-12-31', 8772764.0],
                      ['1968-12-31', 8740765.0],
                      ['1967-12-31', 8684088.0],
                      ['1966-12-31', 8613651.0],
                      ['1965-12-31', 8550333.0],
                      ['1964-12-31', 8510429.0],
                      ['1963-12-31', 8479625.0],
                      ['1962-12-31', 8448233.0],
                      ['1961-12-31', 8398050.0],
                      ['1960-12-31', 8331725.0],
                      ['1959-12-31', 8271724.0],
                      ['1958-12-31', 8201917.0],
                      ['1957-12-31', 8126135.0],
                      ['1956-12-31', 8046802.0],
                      ['1955-12-31', 7965998.0],
                      ['1954-12-31', 7885213.0],
                      ['1953-12-31', 7805207.0],
                      ['1952-12-31', 7725959.0],
                      ['1951-12-31', 7646718.0],
                      ['1950-12-31', 7566002.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'GRC_SP_POP_TOTL',
             'description': 'Population, total - Greece. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22163741,
             'limit': None,
             'name': 'Population, total - Greece',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:33:14.862Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
GRL

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 56171.0],
                      ['2016-12-31', 56186.0],
                      ['2015-12-31', 56114.0],
                      ['2014-12-31', 56295.0],
                      ['2013-12-31', 56483.0],
                      ['2012-12-31', 56810.0],
                      ['2011-12-31', 56890.0],
                      ['2010-12-31', 56905.0],
                      ['2009-12-31', 56323.0],
                      ['2008-12-31', 56328.0],
                      ['2007-12-31', 56555.0],
                      ['2006-12-31', 56774.0],
                      ['2005-12-31', 56935.0],
                      ['2004-12-31', 56911.0],
                      ['2003-12-31', 56765.0],
                      ['2002-12-31', 56609.0],
                      ['2001-12-31', 56350.0],
                      ['2000-12-31', 56200.0],
                      ['1999-12-31', 56100.0],
                      ['1998-12-31', 56100.0],
                      ['1997-12-31', 56000.0],
                      ['1996-12-31', 55900.0],
                      ['1995-12-31', 55800.0],
                      ['1994-12-31', 55500.0],
                      ['1993-12-31', 55200.0],
                      ['1992-12-31', 55300.0],
                      ['1991-12-31', 55500.0],
                      ['1990-12-31', 55600.0],
                      ['1989-12-31', 55300.0],
                      ['1988-12-31', 54800.0],
                      ['1987-12-31', 54100.0],
                      ['1986-12-31', 53500.0],
                      ['1985-12-31', 53200.0],
                      ['1984-12-31', 52700.0],
                      ['1983-12-31', 52100.0],
                      ['1982-12-31', 51500.0],
                      ['1981-12-31', 51000.0],
                      ['1980-12-31', 50200.0],
                      ['1979-12-31', 49600.0],
                      ['1978-12-31', 49200.0],
                      ['1977-12-31', 49400.0],
                      ['1976-12-31', 49700.0],
                      ['1975-12-31', 49600.0],
                      ['1974-12-31', 49500.0],
                      ['1973-12-31', 49000.0],
                      ['1972-12-31', 48300.0],
                      ['1971-12-31', 47200.0],
                      ['1970-12-31', 46400.0],
                      ['1969-12-31', 44900.0],
                      ['1968-12-31', 43400.0],
                      ['1967-12-31', 41900.0],
                      ['1966-12-31', 40500.0],
                      ['1965-12-31', 39200.0],
                      ['1964-12-31', 37600.0],
                      ['1963-12-31', 36400.0],
                      ['1962-12-31', 35000.0],
                      ['1961-12-31', 33700.0],
                      ['1960-12-31', 32500.0],
                      ['1959-12-31', 31224.0],
                      ['1958-12-31', 29997.0],
                      ['1957-12-31', 28819.0],
                      ['1956-12-31', 27687.0],
                      ['1955-12-31', 26600.0],
                      ['1954-12-31', 25678.0],
                      ['1953-12-31', 24789.0],
                      ['1952-12-31', 23930.0],
                      ['1951-12-31', 23100.0],
                      ['1950-12-31', 22300.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'GRL_SP_POP_TOTL',
             'description': 'Population, total - Greenland. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22166028,
             'limit': None,
             'name': 'Population, total - Greenland',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:33:22.376Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
GRD
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 107825.0],
                      ['2016-12-31', 107317.0],
                      ['2015-12-31', 106823.0],
                      ['2014-12-31', 106360.0],
                      ['2013-12-31', 105909.0],
                      ['2012-12-31', 105481.0],
                      ['2011-12-31', 105075.0],
                      ['2010-12-31', 104677.0],
                      ['2009-12-31', 104296.0],
                      ['2008-12-31', 103930.0],
                      ['2007-12-31', 103586.0],
                      ['2006-12-31', 103259.0],
                      ['2005-12-31', 102949.0],
                      ['2004-12-31', 102656.0],
                      ['2003-12-31', 102375.0],
                      ['2002-12-31', 102100.0],
                      ['2001-12-31', 101849.0],
                      ['2000-12-31', 101619.0],
                      ['1999-12-31', 101442.0],
                      ['1998-12-31', 101309.0],
                      ['1997-12-31', 101122.0],
                      ['1996-12-31', 100796.0],
                      ['1995-12-31', 100255.0],
                      ['1994-12-31', 99405.0],
                      ['1993-12-31', 98305.0],
                      ['1992-12-31', 97198.0],
                      ['1991-12-31', 96454.0],
                      ['1990-12-31', 96283.0],
                      ['1989-12-31', 96869.0],
                      ['1988-12-31', 98062.0],
                      ['1987-12-31', 99380.0],
                      ['1986-12-31', 100143.0],
                      ['1985-12-31', 99906.0],
                      ['1984-12-31', 98439.0],
                      ['1983-12-31', 95985.0],
                      ['1982-12-31', 93091.0],
                      ['1981-12-31', 90572.0],
                      ['1980-12-31', 89005.0],
                      ['1979-12-31', 88568.0],
                      ['1978-12-31', 89073.0],
                      ['1977-12-31', 90184.0],
                      ['1976-12-31', 91437.0],
                      ['1975-12-31', 92448.0],
                      ['1974-12-31', 93152.0],
                      ['1973-12-31', 93630.0],
                      ['1972-12-31', 93934.0],
                      ['1971-12-31', 94185.0],
                      ['1970-12-31', 94426.0],
                      ['1969-12-31', 94682.0],
                      ['1968-12-31', 94868.0],
                      ['1967-12-31', 94961.0],
                      ['1966-12-31', 94875.0],
                      ['1965-12-31', 94581.0],
                      ['1964-12-31', 94066.0],
                      ['1963-12-31', 93350.0],
                      ['1962-12-31', 92425.0],
                      ['1961-12-31', 91260.0],
                      ['1960-12-31', 89869.0],
                      ['1959-12-31', 88252.0],
                      ['1958-12-31', 86493.0],
                      ['1957-12-31', 84648.0],
                      ['1956-12-31', 82800.0],
                      ['1955-12-31', 81024.0],
                      ['1954-12-31', 79432.0],
                      ['1953-12-31', 78103.0],
                      ['1952-12-31', 77137.0],
                      ['1951-12-31', 76624.0],
                      ['1950-12-31', 76681.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'GRD_SP_POP_TOTL',
             'description': 'Population, total - Grenada. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22165317,
             'limit': None,
             'name': 'Population, total - Grenada',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:33:19.538Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
GUM
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 164229.0],
                      ['2016-12-31', 162896.0],
                      ['2015-12-31', 161797.0],
                      ['2014-12-31', 160967.0],
                      ['2013-12-31', 160375.0],
                      ['2012-12-31', 159973.0],
                      ['2011-12-31', 159678.0],
                      ['2010-12-31', 159444.0],
                      ['2009-12-31', 159231.0],
                      ['2008-12-31', 159035.0],
                      ['2007-12-31', 158855.0],
                      ['2006-12-31', 158648.0],
                      ['2005-12-31', 158402.0],
                      ['2004-12-31', 158099.0],
                      ['2003-12-31', 157714.0],
                      ['2002-12-31', 157175.0],
                      ['2001-12-31', 156401.0],
                      ['2000-12-31', 155329.0],
                      ['1999-12-31', 153953.0],
                      ['1998-12-31', 152277.0],
                      ['1997-12-31', 150303.0],
                      ['1996-12-31', 148060.0],
                      ['1995-12-31', 145561.0],
                      ['1994-12-31', 142802.0],
                      ['1993-12-31', 139818.0],
                      ['1992-12-31', 136692.0],
                      ['1991-12-31', 133558.0],
                      ['1990-12-31', 130482.0],
                      ['1989-12-31', 127522.0],
                      ['1988-12-31', 124673.0],
                      ['1987-12-31', 121919.0],
                      ['1986-12-31', 119232.0],
                      ['1985-12-31', 116572.0],
                      ['1984-12-31', 113961.0],
                      ['1983-12-31', 111402.0],
                      ['1982-12-31', 108906.0],
                      ['1981-12-31', 106485.0],
                      ['1980-12-31', 104133.0],
                      ['1979-12-31', 101844.0],
                      ['1978-12-31', 99630.0],
                      ['1977-12-31', 97477.0],
                      ['1976-12-31', 95385.0],
                      ['1975-12-31', 93352.0],
                      ['1974-12-31', 91377.0],
                      ['1973-12-31', 89464.0],
                      ['1972-12-31', 87587.0],
                      ['1971-12-31', 85726.0],
                      ['1970-12-31', 83877.0],
                      ['1969-12-31', 82040.0],
                      ['1968-12-31', 80217.0],
                      ['1967-12-31', 78404.0],
                      ['1966-12-31', 76607.0],
                      ['1965-12-31', 74830.0],
                      ['1964-12-31', 73051.0],
                      ['1963-12-31', 71286.0],
                      ['1962-12-31', 69604.0],
                      ['1961-12-31', 68072.0],
                      ['1960-12-31', 66742.0],
                      ['1959-12-31', 65619.0],
                      ['1958-12-31', 64697.0],
                      ['1957-12-31', 63926.0],
                      ['1956-12-31', 63258.0],
                      ['1955-12-31', 62641.0],
                      ['1954-12-31', 62053.0],
                      ['1953-12-31', 61471.0],
                      ['1952-12-31', 60877.0],
                      ['1951-12-31', 60262.0],
                      ['1950-12-31', 59651.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'GUM_SP_POP_TOTL',
             'description': 'Population, total - Guam. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22167953,
             'limit': None,
             'name': 'Population, total - Guam',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:33:30.034Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
GTM

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 16913503.0],
                      ['2016-12-31', 16582469.0],
                      ['2015-12-31', 16252429.0],
                      ['2014-12-31', 15923559.0],
                      ['2013-12-31', 15596214.0],
                      ['2012-12-31', 15271056.0],
                      ['2011-12-31', 14948919.0],
                      ['2010-12-31', 14630417.0],
                      ['2009-12-31', 14316208.0],
                      ['2008-12-31', 14006366.0],
                      ['2007-12-31', 13700286.0],
                      ['2006-12-31', 13397008.0],
                      ['2005-12-31', 13096028.0],
                      ['2004-12-31', 12796925.0],
                      ['2003-12-31', 12500478.0],
                      ['2002-12-31', 12208848.0],
                      ['2001-12-31', 11924946.0],
                      ['2000-12-31', 11650743.0],
                      ['1999-12-31', 11387203.0],
                      ['1998-12-31', 11133501.0],
                      ['1997-12-31', 10887634.0],
                      ['1996-12-31', 10646674.0],
                      ['1995-12-31', 10408489.0],
                      ['1994-12-31', 10172297.0],
                      ['1993-12-31', 9938692.0],
                      ['1992-12-31', 9708544.0],
                      ['1991-12-31', 9483270.0],
                      ['1990-12-31', 9263813.0],
                      ['1989-12-31', 9050465.0],
                      ['1988-12-31', 8842575.0],
                      ['1987-12-31', 8639108.0],
                      ['1986-12-31', 8438604.0],
                      ['1985-12-31', 8240060.0],
                      ['1984-12-31', 8042897.0],
                      ['1983-12-31', 7847472.0],
                      ['1982-12-31', 7654819.0],
                      ['1981-12-31', 7466488.0],
                      ['1980-12-31', 7283459.0],
                      ['1979-12-31', 7106145.0],
                      ['1978-12-31', 6933906.0],
                      ['1977-12-31', 6765516.0],
                      ['1976-12-31', 6599214.0],
                      ['1975-12-31', 6433728.0],
                      ['1974-12-31', 6268707.0],
                      ['1973-12-31', 6104530.0],
                      ['1972-12-31', 5941567.0],
                      ['1971-12-31', 5780480.0],
                      ['1970-12-31', 5621792.0],
                      ['1969-12-31', 5465512.0],
                      ['1968-12-31', 5311615.0],
                      ['1967-12-31', 5160609.0],
                      ['1966-12-31', 5013153.0],
                      ['1965-12-31', 4869716.0],
                      ['1964-12-31', 4730540.0],
                      ['1963-12-31', 4595510.0],
                      ['1962-12-31', 4464249.0],
                      ['1961-12-31', 4336143.0],
                      ['1960-12-31', 4210747.0],
                      ['1959-12-31', 4087923.0],
                      ['1958-12-31', 3967745.0],
                      ['1957-12-31', 3850434.0],
                      ['1956-12-31', 3736236.0],
                      ['1955-12-31', 3625300.0],
                      ['1954-12-31', 3517653.0],
                      ['1953-12-31', 3413165.0],
                      ['1952-12-31', 3311537.0],
                      ['1951-12-31', 3212331.0],
                      ['1950-12-31', 3114957.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'GTM_SP_POP_TOTL',
             'description': 'Population, total - Guatemala. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22167354,
             'limit': None,
             'name': 'Population, total - Guatemala',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:33:27.175Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
GNB
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 1861283.0],
                      ['2016-12-31', 1815698.0],
                      ['2015-12-31', 1770526.0],
                      ['2014-12-31', 1725744.0],
                      ['2013-12-31', 1681495.0],
                      ['2012-12-31', 1638139.0],
                      ['2011-12-31', 1596154.0],
                      ['2010-12-31', 1555880.0],
                      ['2009-12-31', 1517448.0],
                      ['2008-12-31', 1480841.0],
                      ['2007-12-31', 1445958.0],
                      ['2006-12-31', 1412669.0],
                      ['2005-12-31', 1380838.0],
                      ['2004-12-31', 1350345.0],
                      ['2003-12-31', 1321202.0],
                      ['2002-12-31', 1293523.0],
                      ['2001-12-31', 1267512.0],
                      ['2000-12-31', 1243229.0],
                      ['1999-12-31', 1220794.0],
                      ['1998-12-31', 1199915.0],
                      ['1997-12-31', 1179727.0],
                      ['1996-12-31', 1159060.0],
                      ['1995-12-31', 1137122.0],
                      ['1994-12-31', 1113541.0],
                      ['1993-12-31', 1088569.0],
                      ['1992-12-31', 1062800.0],
                      ['1991-12-31', 1037155.0],
                      ['1990-12-31', 1012280.0],
                      ['1989-12-31', 988520.0],
                      ['1988-12-31', 965742.0],
                      ['1987-12-31', 943617.0],
                      ['1986-12-31', 921626.0],
                      ['1985-12-31', 899509.0],
                      ['1984-12-31', 876873.0],
                      ['1983-12-31', 854113.0],
                      ['1982-12-31', 832668.0],
                      ['1981-12-31', 814507.0],
                      ['1980-12-31', 800854.0],
                      ['1979-12-31', 792462.0],
                      ['1978-12-31', 788495.0],
                      ['1977-12-31', 786754.0],
                      ['1976-12-31', 784156.0],
                      ['1975-12-31', 778470.0],
                      ['1974-12-31', 768945.0],
                      ['1973-12-31', 756280.0],
                      ['1972-12-31', 741490.0],
                      ['1971-12-31', 726256.0],
                      ['1970-12-31', 711827.0],
                      ['1969-12-31', 698338.0],
                      ['1968-12-31', 685476.0],
                      ['1967-12-31', 673462.0],
                      ['1966-12-31', 662463.0],
                      ['1965-12-31', 652562.0],
                      ['1964-12-31', 643961.0],
                      ['1963-12-31', 636586.0],
                      ['1962-12-31', 629969.0],
                      ['1961-12-31', 623415.0],
                      ['1960-12-31', 616409.0],
                      ['1959-12-31', 608779.0],
                      ['1958-12-31', 600597.0],
                      ['1957-12-31', 592130.0],
                      ['1956-12-31', 583648.0],
                      ['1955-12-31', 575382.0],
                      ['1954-12-31', 567404.0],
                      ['1953-12-31', 559692.0],
                      ['1952-12-31', 552029.0],
                      ['1951-12-31', 544106.0],
                      ['1950-12-31', 535430.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'GNB_SP_POP_TOTL',
             'description': 'Population, total - Guinea-Bissau. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22160786,
             'limit': None,
             'name': 'Population, total - Guinea-Bissau',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:33:04.526Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
GIN

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 12717176.0],
                      ['2016-12-31', 12395924.0],
                      ['2015-12-31', 12091533.0],
                      ['2014-12-31', 11805509.0],
                      ['2013-12-31', 11536615.0],
                      ['2012-12-31', 11281469.0],
                      ['2011-12-31', 11035170.0],
                      ['2010-12-31', 10794170.0],
                      ['2009-12-31', 10556524.0],
                      ['2008-12-31', 10323142.0],
                      ['2007-12-31', 10096727.0],
                      ['2006-12-31', 9881428.0],
                      ['2005-12-31', 9679745.0],
                      ['2004-12-31', 9490229.0],
                      ['2003-12-31', 9309848.0],
                      ['2002-12-31', 9137345.0],
                      ['2001-12-31', 8971139.0],
                      ['2000-12-31', 8808546.0],
                      ['1999-12-31', 8653769.0],
                      ['1998-12-31', 8503297.0],
                      ['1997-12-31', 8337988.0],
                      ['1996-12-31', 8132552.0],
                      ['1995-12-31', 7871173.0],
                      ['1994-12-31', 7544291.0],
                      ['1993-12-31', 7163236.0],
                      ['1992-12-31', 6758838.0],
                      ['1991-12-31', 6374329.0],
                      ['1990-12-31', 6041094.0],
                      ['1989-12-31', 5770652.0],
                      ['1988-12-31', 5554882.0],
                      ['1987-12-31', 5381483.0],
                      ['1986-12-31', 5229797.0],
                      ['1985-12-31', 5084767.0],
                      ['1984-12-31', 4943144.0],
                      ['1983-12-31', 4810496.0],
                      ['1982-12-31', 4690605.0],
                      ['1981-12-31', 4589784.0],
                      ['1980-12-31', 4511902.0],
                      ['1979-12-31', 4457078.0],
                      ['1978-12-31', 4421134.0],
                      ['1977-12-31', 4398484.0],
                      ['1976-12-31', 4381601.0],
                      ['1975-12-31', 4364514.0],
                      ['1974-12-31', 4345545.0],
                      ['1973-12-31', 4324360.0],
                      ['1972-12-31', 4298091.0],
                      ['1971-12-31', 4263840.0],
                      ['1970-12-31', 4219770.0],
                      ['1969-12-31', 4164003.0],
                      ['1968-12-31', 4097191.0],
                      ['1967-12-31', 4023486.0],
                      ['1966-12-31', 3948869.0],
                      ['1965-12-31', 3877806.0],
                      ['1964-12-31', 3811659.0],
                      ['1963-12-31', 3749505.0],
                      ['1962-12-31', 3690664.0],
                      ['1961-12-31', 3633652.0],
                      ['1960-12-31', 3577409.0],
                      ['1959-12-31', 3521704.0],
                      ['1958-12-31', 3466990.0],
                      ['1957-12-31', 3414053.0],
                      ['1956-12-31', 3363660.0],
                      ['1955-12-31', 3316135.0],
                      ['1954-12-31', 3271313.0],
                      ['1953-12-31', 3228381.0],
                      ['1952-12-31', 3185909.0],
                      ['1951-12-31', 3141879.0],
                      ['1950-12-31', 3093654.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'GIN_SP_POP_TOTL',
             'description': 'Population, total - Guinea. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22157366,
             'limit': None,
             'name': 'Population, total - Guinea',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:32:52.075Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
GUY
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 777859.0],
                      ['2016-12-31', 773303.0],
                      ['2015-12-31', 768514.0],
                      ['2014-12-31', 763393.0],
                      ['2013-12-31', 758081.0],
                      ['2012-12-31', 753091.0],
                      ['2011-12-31', 749100.0],
                      ['2010-12-31', 746556.0],
                      ['2009-12-31', 745693.0],
                      ['2008-12-31', 746314.0],
                      ['2007-12-31', 747869.0],
                      ['2006-12-31', 749601.0],
                      ['2005-12-31', 750946.0],
                      ['2004-12-31', 751652.0],
                      ['2003-12-31', 751857.0],
                      ['2002-12-31', 751884.0],
                      ['2001-12-31', 752263.0],
                      ['2000-12-31', 753301.0],
                      ['1999-12-31', 755278.0],
                      ['1998-12-31', 757952.0],
                      ['1997-12-31', 760510.0],
                      ['1996-12-31', 761861.0],
                      ['1995-12-31', 761291.0],
                      ['1994-12-31', 758342.0],
                      ['1993-12-31', 753484.0],
                      ['1992-12-31', 748134.0],
                      ['1991-12-31', 744289.0],
                      ['1990-12-31', 743309.0],
                      ['1989-12-31', 745665.0],
                      ['1988-12-31', 750731.0],
                      ['1987-12-31', 757506.0],
                      ['1986-12-31', 764459.0],
                      ['1985-12-31', 770435.0],
                      ['1984-12-31', 775219.0],
                      ['1983-12-31', 778948.0],
                      ['1982-12-31', 781246.0],
                      ['1981-12-31', 781732.0],
                      ['1980-12-31', 780153.0],
                      ['1979-12-31', 776254.0],
                      ['1978-12-31', 770125.0],
                      ['1977-12-31', 762424.0],
                      ['1976-12-31', 754101.0],
                      ['1975-12-31', 745841.0],
                      ['1974-12-31', 737847.0],
                      ['1973-12-31', 729916.0],
                      ['1972-12-31', 721948.0],
                      ['1971-12-31', 713684.0],
                      ['1970-12-31', 704934.0],
                      ['1969-12-31', 695745.0],
                      ['1968-12-31', 686146.0],
                      ['1967-12-31', 675871.0],
                      ['1966-12-31', 664521.0],
                      ['1965-12-31', 651868.0],
                      ['1964-12-31', 637845.0],
                      ['1963-12-31', 622575.0],
                      ['1962-12-31', 606285.0],
                      ['1961-12-31', 589274.0],
                      ['1960-12-31', 571819.0],
                      ['1959-12-31', 554092.0],
                      ['1958-12-31', 536218.0],
                      ['1957-12-31', 518259.0],
                      ['1956-12-31', 500324.0],
                      ['1955-12-31', 482555.0],
                      ['1954-12-31', 465172.0],
                      ['1953-12-31', 448464.0],
                      ['1952-12-31', 432818.0],
                      ['1951-12-31', 418674.0],
                      ['1950-12-31', 406559.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'GUY_SP_POP_TOTL',
             'description': 'Population, total - Guyana. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22169118,
             'limit': None,
             'name': 'Population, total - Guyana',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:33:34.266Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
HTI

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 10981229.0],
                      ['2016-12-31', 10847334.0],
                      ['2015-12-31', 10711061.0],
                      ['2014-12-31', 10572466.0],
                      ['2013-12-31', 10431776.0],
                      ['2012-12-31', 10289210.0],
                      ['2011-12-31', 10145054.0],
                      ['2010-12-31', 9999617.0],
                      ['2009-12-31', 9852870.0],
                      ['2008-12-31', 9705029.0],
                      ['2007-12-31', 9556889.0],
                      ['2006-12-31', 9409457.0],
                      ['2005-12-31', 9263404.0],
                      ['2004-12-31', 9119178.0],
                      ['2003-12-31', 8976552.0],
                      ['2002-12-31', 8834733.0],
                      ['2001-12-31', 8692567.0],
                      ['2000-12-31', 8549200.0],
                      ['1999-12-31', 8404398.0],
                      ['1998-12-31', 8258483.0],
                      ['1997-12-31', 8111951.0],
                      ['1996-12-31', 7965553.0],
                      ['1995-12-31', 7819806.0],
                      ['1994-12-31', 7674911.0],
                      ['1993-12-31', 7530705.0],
                      ['1992-12-31', 7386975.0],
                      ['1991-12-31', 7243391.0],
                      ['1990-12-31', 7099732.0],
                      ['1989-12-31', 6956300.0],
                      ['1988-12-31', 6813348.0],
                      ['1987-12-31', 6670568.0],
                      ['1986-12-31', 6527543.0],
                      ['1985-12-31', 6384195.0],
                      ['1984-12-31', 6240329.0],
                      ['1983-12-31', 6096692.0],
                      ['1982-12-31', 5955267.0],
                      ['1981-12-31', 5818671.0],
                      ['1980-12-31', 5688836.0],
                      ['1979-12-31', 5566266.0],
                      ['1978-12-31', 5450549.0],
                      ['1977-12-31', 5341419.0],
                      ['1976-12-31', 5238245.0],
                      ['1975-12-31', 5140357.0],
                      ['1974-12-31', 5047944.0],
                      ['1973-12-31', 4960657.0],
                      ['1972-12-31', 4876560.0],
                      ['1971-12-31', 4793155.0],
                      ['1970-12-31', 4708642.0],
                      ['1969-12-31', 4622208.0],
                      ['1968-12-31', 4534234.0],
                      ['1967-12-31', 4445530.0],
                      ['1966-12-31', 4357484.0],
                      ['1965-12-31', 4271133.0],
                      ['1964-12-31', 4186640.0],
                      ['1963-12-31', 4103730.0],
                      ['1962-12-31', 4022593.0],
                      ['1961-12-31', 3943364.0],
                      ['1960-12-31', 3866159.0],
                      ['1959-12-31', 3791097.0],
                      ['1958-12-31', 3718283.0],
                      ['1957-12-31', 3647809.0],
                      ['1956-12-31', 3579725.0],
                      ['1955-12-31', 3514074.0],
                      ['1954-12-31', 3450850.0],
                      ['1953-12-31', 3390050.0],
                      ['1952-12-31', 3331580.0],
                      ['1951-12-31', 3275366.0],
                      ['1950-12-31', 3221283.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'HTI_SP_POP_TOTL',
             'description': 'Population, total - Haiti. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22178910,
             'limit': None,
             'name': 'Population, total - Haiti',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:34:05.087Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
HPC
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 765112280.0],
                      ['2016-12-31', 744602976.0],
                      ['2015-12-31', 724482652.0],
                      ['2014-12-31', 704745420.0],
                      ['2013-12-31', 685401960.0],
                      ['2012-12-31', 666488623.0],
                      ['2011-12-31', 648053253.0],
                      ['2010-12-31', 630127436.0],
                      ['2009-12-31', 612731524.0],
                      ['2008-12-31', 595849807.0],
                      ['2007-12-31', 579434057.0],
                      ['2006-12-31', 563415107.0],
                      ['2005-12-31', 547744433.0],
                      ['2004-12-31', 532385197.0],
                      ['2003-12-31', 517352559.0],
                      ['2002-12-31', 502710676.0],
                      ['2001-12-31', 488553040.0],
                      ['2000-12-31', 474935556.0],
                      ['1999-12-31', 461899663.0],
                      ['1998-12-31', 449393754.0],
                      ['1997-12-31', 437269757.0],
                      ['1996-12-31', 425324425.0],
                      ['1995-12-31', 413418810.0],
                      ['1994-12-31', 401488248.0],
                      ['1993-12-31', 389594161.0],
                      ['1992-12-31', 377879250.0],
                      ['1991-12-31', 366551884.0],
                      ['1990-12-31', 355762200.0],
                      ['1989-12-31', 345544609.0],
                      ['1988-12-31', 335847788.0],
                      ['1987-12-31', 326631480.0],
                      ['1986-12-31', 317825339.0],
                      ['1985-12-31', 309370058.0],
                      ['1984-12-31', 301260428.0],
                      ['1983-12-31', 293492340.0],
                      ['1982-12-31', 286006012.0],
                      ['1981-12-31', 278728186.0],
                      ['1980-12-31', 271603169.0],
                      ['1979-12-31', 264602415.0],
                      ['1978-12-31', 257725573.0],
                      ['1977-12-31', 250981876.0],
                      ['1976-12-31', 244394102.0],
                      ['1975-12-31', 237979218.0],
                      ['1974-12-31', 231732881.0],
                      ['1973-12-31', 225645580.0],
                      ['1972-12-31', 219724282.0],
                      ['1971-12-31', 213978472.0],
                      ['1970-12-31', 208415064.0],
                      ['1969-12-31', 203035027.0],
                      ['1968-12-31', 197836081.0],
                      ['1967-12-31', 192817243.0],
                      ['1966-12-31', 187976481.0],
                      ['1965-12-31', 183311108.0],
                      ['1964-12-31', 178820615.0],
                      ['1963-12-31', 174502178.0],
                      ['1962-12-31', 170348129.0],
                      ['1961-12-31', 166348536.0],
                      ['1960-12-31', 162495580.0],
                      ['1959-12-31', 158784566.0],
                      ['1958-12-31', 155213799.0],
                      ['1957-12-31', 151783138.0],
                      ['1956-12-31', 148492981.0],
                      ['1955-12-31', 145342841.0],
                      ['1954-12-31', 142331083.0],
                      ['1953-12-31', 139454449.0],
                      ['1952-12-31', 136708435.0],
                      ['1951-12-31', 134086788.0],
                      ['1950-12-31', 131581995.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'HPC_SP_POP_TOTL',
             'description': 'Population, total - Heavily indebted poor '
                            'countries (HIPC). ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22175589,
             'limit': None,
             'name': 'Population, total - Heavily indebted poor countries '
                     '(HIPC)',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:33:54.219Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
NOC

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2015-12-31', 330858000.0],
                      ['2014-12-31', 328773073.0],
                      ['2013-12-31', 326137349.0],
                      ['2012-12-31', 323348755.0],
                      ['2011-12-31', 320397030.0],
                      ['2010-12-31', 317681268.0],
                      ['2009-12-31', 314698228.0],
                      ['2008-12-31', 311513627.0],
                      ['2007-12-31', 308252723.0],
                      ['2006-12-31', 305315015.0],
                      ['2005-12-31', 302878992.0],
                      ['2004-12-31', 300817188.0],
                      ['2003-12-31', 299016104.0],
                      ['2002-12-31', 297623324.0],
                      ['2001-12-31', 296194874.0],
                      ['2000-12-31', 294642775.0],
                      ['1999-12-31', 293296765.0],
                      ['1998-12-31', 291694158.0],
                      ['1997-12-31', 289904210.0],
                      ['1996-12-31', 288040690.0],
                      ['1995-12-31', 286202907.0],
                      ['1994-12-31', 282394875.0],
                      ['1993-12-31', 280529131.0],
                      ['1992-12-31', 278453583.0],
                      ['1991-12-31', 278295732.0],
                      ['1990-12-31', 276140110.0],
                      ['1989-12-31', 273342929.0],
                      ['1988-12-31', 270168709.0],
                      ['1987-12-31', 266853986.0],
                      ['1986-12-31', 263460489.0],
                      ['1985-12-31', 260062512.0],
                      ['1984-12-31', 256549836.0],
                      ['1983-12-31', 253015702.0],
                      ['1982-12-31', 249695520.0],
                      ['1981-12-31', 246276870.0],
                      ['1980-12-31', 242853368.0],
                      ['1979-12-31', 239533579.0],
                      ['1978-12-31', 236180318.0],
                      ['1977-12-31', 233083282.0],
                      ['1976-12-31', 230076609.0],
                      ['1975-12-31', 227123524.0],
                      ['1974-12-31', 224356476.0],
                      ['1973-12-31', 221683016.0],
                      ['1972-12-31', 219034450.0],
                      ['1971-12-31', 216468801.0],
                      ['1970-12-31', 213932884.0],
                      ['1969-12-31', 211459827.0],
                      ['1968-12-31', 209075991.0],
                      ['1967-12-31', 206694312.0],
                      ['1966-12-31', 204307185.0],
                      ['1965-12-31', 201980369.0],
                      ['1964-12-31', 198896794.0],
                      ['1963-12-31', 195817810.0],
                      ['1962-12-31', 192729589.0],
                      ['1961-12-31', 189656817.0],
                      ['1960-12-31', 186676748.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'NOC_SP_POP_TOTL',
             'description': 'Population, total - High income; nonOECD. ',
             'end_date': '2015-12-31',
             'frequency': 'annual',
             'id': 22188615,
             'limit': None,
             'name': 'Population, total - High income; nonOECD',
             'newest_available_date': '2015-12-31',
             'oldest_available_date': '1960-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2016-06-25T10:15:20.560Z',
             'start_date': '1960-12-31',
             'transform': None,
             'type': 'Time Series'}}
OEC
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2015-12-31', 1073822000.0],
                      ['2014-12-31', 1069655987.0],
                      ['2013-12-31', 1065863269.0],
                      ['2012-12-31', 1059077354.0],
                      ['2011-12-31', 1055666125.0],
                      ['2010-12-31', 1050524925.0],
                      ['2009-12-31', 1045091869.0],
                      ['2008-12-31', 1039025517.0],
                      ['2007-12-31', 1032134098.0],
                      ['2006-12-31', 1025640526.0],
                      ['2005-12-31', 1019353722.0],
                      ['2004-12-31', 1013314403.0],
                      ['2003-12-31', 1007211338.0],
                      ['2002-12-31', 1001135680.0],
                      ['2001-12-31', 994995553.0],
                      ['2000-12-31', 988844311.0],
                      ['1999-12-31', 983140866.0],
                      ['1998-12-31', 977434526.0],
                      ['1997-12-31', 971845436.0],
                      ['1996-12-31', 966001758.0],
                      ['1995-12-31', 960143730.0],
                      ['1994-12-31', 954093985.0],
                      ['1993-12-31', 947891762.0],
                      ['1992-12-31', 941211429.0],
                      ['1991-12-31', 934074915.0],
                      ['1990-12-31', 927034726.0],
                      ['1989-12-31', 920547191.0],
                      ['1988-12-31', 914618033.0],
                      ['1987-12-31', 909202842.0],
                      ['1986-12-31', 903940836.0],
                      ['1985-12-31', 898643236.0],
                      ['1984-12-31', 893672565.0],
                      ['1983-12-31', 888793354.0],
                      ['1982-12-31', 883588067.0],
                      ['1981-12-31', 878037163.0],
                      ['1980-12-31', 871995822.0],
                      ['1979-12-31', 865921808.0],
                      ['1978-12-31', 859653791.0],
                      ['1977-12-31', 853369201.0],
                      ['1976-12-31', 847181502.0],
                      ['1975-12-31', 841216563.0],
                      ['1974-12-31', 833799306.0],
                      ['1973-12-31', 825904055.0],
                      ['1972-12-31', 819052501.0],
                      ['1971-12-31', 811265587.0],
                      ['1970-12-31', 803572643.0],
                      ['1969-12-31', 796437970.0],
                      ['1968-12-31', 788256445.0],
                      ['1967-12-31', 781788178.0],
                      ['1966-12-31', 774349071.0],
                      ['1965-12-31', 766464800.0],
                      ['1964-12-31', 758024731.0],
                      ['1963-12-31', 749200097.0],
                      ['1962-12-31', 740295817.0],
                      ['1961-12-31', 731314090.0],
                      ['1960-12-31', 720920759.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'OEC_SP_POP_TOTL',
             'description': 'Population, total - High income; OECD. ',
             'end_date': '2015-12-31',
             'frequency': 'annual',
             'id': 22195401,
             'limit': None,
             'name': 'Population, total - High income; OECD',
             'newest_available_date': '2015-12-31',
             'oldest_available_date': '1960-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2016-06-25T10:15:55.217Z',
             'start_date': '1960-12-31',
             'transform': None,
             'type': 'Time Series'}}
HIC
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 1249066228.0],
                      ['2016-12-31', 1242137612.0],
                      ['2015-12-31', 1234714041.0],
                      ['2014-12-31', 1227211897.0],
                      ['2013-12-31', 1219556921.0],
                      ['2012-12-31', 1212058100.0],
                      ['2011-12-31', 1204631343.0],
                      ['2010-12-31', 1198787232.0],
                      ['2009-12-31', 1190790909.0],
                      ['2008-12-31', 1181962982.0],
                      ['2007-12-31', 1172156434.0],
                      ['2006-12-31', 1162908282.0],
                      ['2005-12-31', 1154156034.0],
                      ['2004-12-31', 1145971873.0],
                      ['2003-12-31', 1137953182.0],
                      ['2002-12-31', 1130299527.0],
                      ['2001-12-31', 1122635089.0],
                      ['2000-12-31', 1115010208.0],
                      ['1999-12-31', 1108002668.0],
                      ['1998-12-31', 1100763765.0],
                      ['1997-12-31', 1093603568.0],
                      ['1996-12-31', 1086071661.0],
                      ['1995-12-31', 1078558586.0],
                      ['1994-12-31', 1069147445.0],
                      ['1993-12-31', 1061248480.0],
                      ['1992-12-31', 1052656811.0],
                      ['1991-12-31', 1045799408.0],
                      ['1990-12-31', 1037334467.0],
                      ['1989-12-31', 1029042492.0],
                      ['1988-12-31', 1021209656.0],
                      ['1987-12-31', 1013806386.0],
                      ['1986-12-31', 1006551028.0],
                      ['1985-12-31', 999278230.0],
                      ['1984-12-31', 992295742.0],
                      ['1983-12-31', 985349949.0],
                      ['1982-12-31', 978056271.0],
                      ['1981-12-31', 970338016.0],
                      ['1980-12-31', 962228266.0],
                      ['1979-12-31', 954142946.0],
                      ['1978-12-31', 945879993.0],
                      ['1977-12-31', 937990304.0],
                      ['1976-12-31', 930171314.0],
                      ['1975-12-31', 922573384.0],
                      ['1974-12-31', 913510969.0],
                      ['1973-12-31', 903912425.0],
                      ['1972-12-31', 895387452.0],
                      ['1971-12-31', 886003787.0],
                      ['1970-12-31', 876786721.0],
                      ['1969-12-31', 868224174.0],
                      ['1968-12-31', 858706694.0],
                      ['1967-12-31', 850904554.0],
                      ['1966-12-31', 842127682.0],
                      ['1965-12-31', 832959686.0],
                      ['1964-12-31', 823154587.0],
                      ['1963-12-31', 812955277.0],
                      ['1962-12-31', 802642237.0],
                      ['1961-12-31', 792246929.0],
                      ['1960-12-31', 780501923.0],
                      ['1959-12-31', 733387755.0],
                      ['1958-12-31', 724412195.0],
                      ['1957-12-31', 715650907.0],
                      ['1956-12-31', 707031462.0],
                      ['1955-12-31', 707448747.0],
                      ['1954-12-31', 689996344.0],
                      ['1953-12-31', 681536477.0],
                      ['1952-12-31', 673147602.0],
                      ['1951-12-31', 664905967.0],
                      ['1950-12-31', 664421072.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'HIC_SP_POP_TOTL',
             'description': 'Population, total - High income. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22170489,
             'limit': None,
             'name': 'Population, total - High income',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:33:38.762Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
HND

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 9265067.0],
                      ['2016-12-31', 9112867.0],
                      ['2015-12-31', 8960829.0],
                      ['2014-12-31', 8809216.0],
                      ['2013-12-31', 8657785.0],
                      ['2012-12-31', 8505646.0],
                      ['2011-12-31', 8351600.0],
                      ['2010-12-31', 8194778.0],
                      ['2009-12-31', 8035021.0],
                      ['2008-12-31', 7872658.0],
                      ['2007-12-31', 7707972.0],
                      ['2006-12-31', 7541406.0],
                      ['2005-12-31', 7373430.0],
                      ['2004-12-31', 7204153.0],
                      ['2003-12-31', 7033821.0],
                      ['2002-12-31', 6863157.0],
                      ['2001-12-31', 6693061.0],
                      ['2000-12-31', 6524283.0],
                      ['1999-12-31', 6357221.0],
                      ['1998-12-31', 6192026.0],
                      ['1997-12-31', 6028882.0],
                      ['1996-12-31', 5867849.0],
                      ['1995-12-31', 5709051.0],
                      ['1994-12-31', 5552625.0],
                      ['1993-12-31', 5398805.0],
                      ['1992-12-31', 5247836.0],
                      ['1991-12-31', 5099951.0],
                      ['1990-12-31', 4955328.0],
                      ['1989-12-31', 4814137.0],
                      ['1988-12-31', 4676361.0],
                      ['1987-12-31', 4541804.0],
                      ['1986-12-31', 4410158.0],
                      ['1985-12-31', 4281189.0],
                      ['1984-12-31', 4154887.0],
                      ['1983-12-31', 4031349.0],
                      ['1982-12-31', 3910657.0],
                      ['1981-12-31', 3792938.0],
                      ['1980-12-31', 3678286.0],
                      ['1979-12-31', 3566665.0],
                      ['1978-12-31', 3458104.0],
                      ['1977-12-31', 3352835.0],
                      ['1976-12-31', 3251158.0],
                      ['1975-12-31', 3153261.0],
                      ['1974-12-31', 3059254.0],
                      ['1973-12-31', 2968994.0],
                      ['1972-12-31', 2882113.0],
                      ['1971-12-31', 2798125.0],
                      ['1970-12-31', 2716659.0],
                      ['1969-12-31', 2637517.0],
                      ['1968-12-31', 2560727.0],
                      ['1967-12-31', 2486414.0],
                      ['1966-12-31', 2414807.0],
                      ['1965-12-31', 2346010.0],
                      ['1964-12-31', 2280045.0],
                      ['1963-12-31', 2216707.0],
                      ['1962-12-31', 2155652.0],
                      ['1961-12-31', 2096407.0],
                      ['1960-12-31', 2038637.0],
                      ['1959-12-31', 1982192.0],
                      ['1958-12-31', 1927104.0],
                      ['1957-12-31', 1873498.0],
                      ['1956-12-31', 1821538.0],
                      ['1955-12-31', 1771351.0],
                      ['1954-12-31', 1723010.0],
                      ['1953-12-31', 1676502.0],
                      ['1952-12-31', 1631734.0],
                      ['1951-12-31', 1588561.0],
                      ['1950-12-31', 1546724.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'HND_SP_POP_TOTL',
             'description': 'Population, total - Honduras. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22174072,
             'limit': None,
             'name': 'Population, total - Honduras',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:33:49.352Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
HKG
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 7391700.0],
                      ['2016-12-31', 7336600.0],
                      ['2015-12-31', 7291300.0],
                      ['2014-12-31', 7229500.0],
                      ['2013-12-31', 7178900.0],
                      ['2012-12-31', 7150100.0],
                      ['2011-12-31', 7071600.0],
                      ['2010-12-31', 7024200.0],
                      ['2009-12-31', 6972800.0],
                      ['2008-12-31', 6957800.0],
                      ['2007-12-31', 6916300.0],
                      ['2006-12-31', 6857100.0],
                      ['2005-12-31', 6813200.0],
                      ['2004-12-31', 6783500.0],
                      ['2003-12-31', 6730800.0],
                      ['2002-12-31', 6744100.0],
                      ['2001-12-31', 6714300.0],
                      ['2000-12-31', 6665000.0],
                      ['1999-12-31', 6606500.0],
                      ['1998-12-31', 6543700.0],
                      ['1997-12-31', 6489300.0],
                      ['1996-12-31', 6435500.0],
                      ['1995-12-31', 6156100.0],
                      ['1994-12-31', 6035400.0],
                      ['1993-12-31', 5901000.0],
                      ['1992-12-31', 5800500.0],
                      ['1991-12-31', 5752000.0],
                      ['1990-12-31', 5704500.0],
                      ['1989-12-31', 5686200.0],
                      ['1988-12-31', 5627600.0],
                      ['1987-12-31', 5580500.0],
                      ['1986-12-31', 5524600.0],
                      ['1985-12-31', 5456200.0],
                      ['1984-12-31', 5397900.0],
                      ['1983-12-31', 5345100.0],
                      ['1982-12-31', 5264500.0],
                      ['1981-12-31', 5183400.0],
                      ['1980-12-31', 5063100.0],
                      ['1979-12-31', 4929700.0],
                      ['1978-12-31', 4667500.0],
                      ['1977-12-31', 4583700.0],
                      ['1976-12-31', 4518000.0],
                      ['1975-12-31', 4461600.0],
                      ['1974-12-31', 4377800.0],
                      ['1973-12-31', 4241600.0],
                      ['1972-12-31', 4123600.0],
                      ['1971-12-31', 4045300.0],
                      ['1970-12-31', 3959000.0],
                      ['1969-12-31', 3863900.0],
                      ['1968-12-31', 3802700.0],
                      ['1967-12-31', 3722800.0],
                      ['1966-12-31', 3629900.0],
                      ['1965-12-31', 3597900.0],
                      ['1964-12-31', 3504600.0],
                      ['1963-12-31', 3420900.0],
                      ['1962-12-31', 3305200.0],
                      ['1961-12-31', 3168100.0],
                      ['1960-12-31', 3075605.0],
                      ['1959-12-31', 2941712.0],
                      ['1958-12-31', 2823161.0],
                      ['1957-12-31', 2713041.0],
                      ['1956-12-31', 2603651.0],
                      ['1955-12-31', 2489955.0],
                      ['1954-12-31', 2370729.0],
                      ['1953-12-31', 2249255.0],
                      ['1952-12-31', 2133544.0],
                      ['1951-12-31', 2036119.0],
                      ['1950-12-31', 1973998.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'HKG_SP_POP_TOTL',
             'description': 'Population, total - Hong Kong SAR, China. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22172057,
             'limit': None,
             'name': 'Population, total - Hong Kong SAR, China',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:33:43.409Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
HUN

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 9781127.0],
                      ['2016-12-31', 9814023.0],
                      ['2015-12-31', 9843028.0],
                      ['2014-12-31', 9866468.0],
                      ['2013-12-31', 9893082.0],
                      ['2012-12-31', 9920362.0],
                      ['2011-12-31', 9971727.0],
                      ['2010-12-31', 10000023.0],
                      ['2009-12-31', 10022650.0],
                      ['2008-12-31', 10038188.0],
                      ['2007-12-31', 10055780.0],
                      ['2006-12-31', 10071370.0],
                      ['2005-12-31', 10087065.0],
                      ['2004-12-31', 10107146.0],
                      ['2003-12-31', 10129552.0],
                      ['2002-12-31', 10158608.0],
                      ['2001-12-31', 10187576.0],
                      ['2000-12-31', 10210971.0],
                      ['1999-12-31', 10237530.0],
                      ['1998-12-31', 10266570.0],
                      ['1997-12-31', 10290486.0],
                      ['1996-12-31', 10311238.0],
                      ['1995-12-31', 10328965.0],
                      ['1994-12-31', 10343355.0],
                      ['1993-12-31', 10357523.0],
                      ['1992-12-31', 10369341.0],
                      ['1991-12-31', 10373400.0],
                      ['1990-12-31', 10373988.0],
                      ['1989-12-31', 10481719.0],
                      ['1988-12-31', 10596487.0],
                      ['1987-12-31', 10612741.0],
                      ['1986-12-31', 10630564.0],
                      ['1985-12-31', 10648713.0],
                      ['1984-12-31', 10668095.0],
                      ['1983-12-31', 10689463.0],
                      ['1982-12-31', 10705535.0],
                      ['1981-12-31', 10711848.0],
                      ['1980-12-31', 10711122.0],
                      ['1979-12-31', 10704152.0],
                      ['1978-12-31', 10684822.0],
                      ['1977-12-31', 10648031.0],
                      ['1976-12-31', 10598677.0],
                      ['1975-12-31', 10540525.0],
                      ['1974-12-31', 10478720.0],
                      ['1973-12-31', 10432055.0],
                      ['1972-12-31', 10398489.0],
                      ['1971-12-31', 10367537.0],
                      ['1970-12-31', 10337910.0],
                      ['1969-12-31', 10298723.0],
                      ['1968-12-31', 10255815.0],
                      ['1967-12-31', 10216604.0],
                      ['1966-12-31', 10178653.0],
                      ['1965-12-31', 10147935.0],
                      ['1964-12-31', 10119835.0],
                      ['1963-12-31', 10087947.0],
                      ['1962-12-31', 10061734.0],
                      ['1961-12-31', 10029321.0],
                      ['1960-12-31', 9983967.0],
                      ['1959-12-31', 9957295.0],
                      ['1958-12-31', 9932015.0],
                      ['1957-12-31', 9903650.0],
                      ['1956-12-31', 9868650.0],
                      ['1955-12-31', 9823485.0],
                      ['1954-12-31', 9764807.0],
                      ['1953-12-31', 9689536.0],
                      ['1952-12-31', 9594893.0],
                      ['1951-12-31', 9478369.0],
                      ['1950-12-31', 9337723.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'HUN_SP_POP_TOTL',
             'description': 'Population, total - Hungary. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22180640,
             'limit': None,
             'name': 'Population, total - Hungary',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:34:10.224Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
ISL
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 341284.0],
                      ['2016-12-31', 335439.0],
                      ['2015-12-31', 330815.0],
                      ['2014-12-31', 327386.0],
                      ['2013-12-31', 323764.0],
                      ['2012-12-31', 320716.0],
                      ['2011-12-31', 319014.0],
                      ['2010-12-31', 318041.0],
                      ['2009-12-31', 318499.0],
                      ['2008-12-31', 317414.0],
                      ['2007-12-31', 311566.0],
                      ['2006-12-31', 303782.0],
                      ['2005-12-31', 296734.0],
                      ['2004-12-31', 292074.0],
                      ['2003-12-31', 289521.0],
                      ['2002-12-31', 287523.0],
                      ['2001-12-31', 284968.0],
                      ['2000-12-31', 281205.0],
                      ['1999-12-31', 277381.0],
                      ['1998-12-31', 274047.0],
                      ['1997-12-31', 271128.0],
                      ['1996-12-31', 268916.0],
                      ['1995-12-31', 267468.0],
                      ['1994-12-31', 266021.0],
                      ['1993-12-31', 263725.0],
                      ['1992-12-31', 261057.0],
                      ['1991-12-31', 257797.0],
                      ['1990-12-31', 254826.0],
                      ['1989-12-31', 252852.0],
                      ['1988-12-31', 249740.0],
                      ['1987-12-31', 245859.0],
                      ['1986-12-31', 243180.0],
                      ['1985-12-31', 241405.0],
                      ['1984-12-31', 239511.0],
                      ['1983-12-31', 236977.0],
                      ['1982-12-31', 233860.0],
                      ['1981-12-31', 230755.0],
                      ['1980-12-31', 228138.0],
                      ['1979-12-31', 225735.0],
                      ['1978-12-31', 223537.0],
                      ['1977-12-31', 221799.0],
                      ['1976-12-31', 220154.0],
                      ['1975-12-31', 217979.0],
                      ['1974-12-31', 215209.0],
                      ['1973-12-31', 212317.0],
                      ['1972-12-31', 209137.0],
                      ['1971-12-31', 206098.0],
                      ['1970-12-31', 204438.0],
                      ['1969-12-31', 203369.0],
                      ['1968-12-31', 201488.0],
                      ['1967-12-31', 198751.0],
                      ['1966-12-31', 195570.0],
                      ['1965-12-31', 192286.0],
                      ['1964-12-31', 188983.0],
                      ['1963-12-31', 185653.0],
                      ['1962-12-31', 182378.0],
                      ['1961-12-31', 179029.0],
                      ['1960-12-31', 175574.0],
                      ['1959-12-31', 172450.0],
                      ['1958-12-31', 168853.0],
                      ['1957-12-31', 165227.0],
                      ['1956-12-31', 161597.0],
                      ['1955-12-31', 158002.0],
                      ['1954-12-31', 154496.0],
                      ['1953-12-31', 151148.0],
                      ['1952-12-31', 148044.0],
                      ['1951-12-31', 145288.0],
                      ['1950-12-31', 142998.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'ISL_SP_POP_TOTL',
             'description': 'Population, total - Iceland. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22141766,
             'limit': None,
             'name': 'Population, total - Iceland',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:34:44.700Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
IND

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 1339180127.0],
                      ['2016-12-31', 1324171354.0],
                      ['2015-12-31', 1309053980.0],
                      ['2014-12-31', 1293859294.0],
                      ['2013-12-31', 1278562207.0],
                      ['2012-12-31', 1263065852.0],
                      ['2011-12-31', 1247236029.0],
                      ['2010-12-31', 1230980691.0],
                      ['2009-12-31', 1214270132.0],
                      ['2008-12-31', 1197146906.0],
                      ['2007-12-31', 1179681239.0],
                      ['2006-12-31', 1161977719.0],
                      ['2005-12-31', 1144118674.0],
                      ['2004-12-31', 1126135777.0],
                      ['2003-12-31', 1108027848.0],
                      ['2002-12-31', 1089807112.0],
                      ['2001-12-31', 1071477855.0],
                      ['2000-12-31', 1053050912.0],
                      ['1999-12-31', 1034539214.0],
                      ['1998-12-31', 1015974042.0],
                      ['1997-12-31', 997405318.0],
                      ['1996-12-31', 978893217.0],
                      ['1995-12-31', 960482795.0],
                      ['1994-12-31', 942204249.0],
                      ['1993-12-31', 924057817.0],
                      ['1992-12-31', 906021106.0],
                      ['1991-12-31', 888054875.0],
                      ['1990-12-31', 870133480.0],
                      ['1989-12-31', 852270034.0],
                      ['1988-12-31', 834489322.0],
                      ['1987-12-31', 816792741.0],
                      ['1986-12-31', 799181436.0],
                      ['1985-12-31', 781666671.0],
                      ['1984-12-31', 764245202.0],
                      ['1983-12-31', 746949067.0],
                      ['1982-12-31', 729868013.0],
                      ['1981-12-31', 713118032.0],
                      ['1980-12-31', 696783517.0],
                      ['1979-12-31', 680915804.0],
                      ['1978-12-31', 665502284.0],
                      ['1977-12-31', 650485030.0],
                      ['1976-12-31', 635771734.0],
                      ['1975-12-31', 621301720.0],
                      ['1974-12-31', 607050255.0],
                      ['1973-12-31', 593058926.0],
                      ['1972-12-31', 579411513.0],
                      ['1971-12-31', 566224812.0],
                      ['1970-12-31', 553578513.0],
                      ['1969-12-31', 541505076.0],
                      ['1968-12-31', 529967317.0],
                      ['1967-12-31', 518889779.0],
                      ['1966-12-31', 508161935.0],
                      ['1965-12-31', 497702365.0],
                      ['1964-12-31', 487484535.0],
                      ['1963-12-31', 477527970.0],
                      ['1962-12-31', 467852537.0],
                      ['1961-12-31', 458494963.0],
                      ['1960-12-31', 449480608.0],
                      ['1959-12-31', 440813896.0],
                      ['1958-12-31', 432481663.0],
                      ['1957-12-31', 424461108.0],
                      ['1956-12-31', 416728771.0],
                      ['1955-12-31', 409269055.0],
                      ['1954-12-31', 402077026.0],
                      ['1953-12-31', 395160091.0],
                      ['1952-12-31', 388538620.0],
                      ['1951-12-31', 382245303.0],
                      ['1950-12-31', 376325200.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'IND_SP_POP_TOTL',
             'description': 'Population, total - India. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22134890,
             'limit': None,
             'name': 'Population, total - India',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:34:23.321Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
IDN
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 263991379.0],
                      ['2016-12-31', 261115456.0],
                      ['2015-12-31', 258162113.0],
                      ['2014-12-31', 255131116.0],
                      ['2013-12-31', 252032263.0],
                      ['2012-12-31', 248883232.0],
                      ['2011-12-31', 245707511.0],
                      ['2010-12-31', 242524123.0],
                      ['2009-12-31', 239340478.0],
                      ['2008-12-31', 236159276.0],
                      ['2007-12-31', 232989141.0],
                      ['2006-12-31', 229838202.0],
                      ['2005-12-31', 226712730.0],
                      ['2004-12-31', 223614649.0],
                      ['2003-12-31', 220545214.0],
                      ['2002-12-31', 217508059.0],
                      ['2001-12-31', 214506502.0],
                      ['2000-12-31', 211540429.0],
                      ['1999-12-31', 208612556.0],
                      ['1998-12-31', 205715544.0],
                      ['1997-12-31', 202826465.0],
                      ['1996-12-31', 199914831.0],
                      ['1995-12-31', 196957849.0],
                      ['1994-12-31', 193945272.0],
                      ['1993-12-31', 190879523.0],
                      ['1992-12-31', 187766086.0],
                      ['1991-12-31', 184615979.0],
                      ['1990-12-31', 181436821.0],
                      ['1989-12-31', 178233223.0],
                      ['1988-12-31', 175000916.0],
                      ['1987-12-31', 171728917.0],
                      ['1986-12-31', 168402025.0],
                      ['1985-12-31', 165012196.0],
                      ['1984-12-31', 161555583.0],
                      ['1983-12-31', 158044343.0],
                      ['1982-12-31', 154506265.0],
                      ['1981-12-31', 150978840.0],
                      ['1980-12-31', 147490365.0],
                      ['1979-12-31', 144053518.0],
                      ['1978-12-31', 140665856.0],
                      ['1977-12-31', 137322118.0],
                      ['1976-12-31', 134010690.0],
                      ['1975-12-31', 130724115.0],
                      ['1974-12-31', 127465231.0],
                      ['1973-12-31', 124242298.0],
                      ['1972-12-31', 121059513.0],
                      ['1971-12-31', 117921998.0],
                      ['1970-12-31', 114834780.0],
                      ['1969-12-31', 111800091.0],
                      ['1968-12-31', 108821564.0],
                      ['1967-12-31', 105907403.0],
                      ['1966-12-31', 103067354.0],
                      ['1965-12-31', 100308894.0],
                      ['1964-12-31', 97638029.0],
                      ['1963-12-31', 95055665.0],
                      ['1962-12-31', 92558005.0],
                      ['1961-12-31', 90138235.0],
                      ['1960-12-31', 87792515.0],
                      ['1959-12-31', 85521979.0],
                      ['1958-12-31', 83332050.0],
                      ['1957-12-31', 81230747.0],
                      ['1956-12-31', 79226787.0],
                      ['1955-12-31', 77327794.0],
                      ['1954-12-31', 75539737.0],
                      ['1953-12-31', 73866521.0],
                      ['1952-12-31', 72309900.0],
                      ['1951-12-31', 70869609.0],
                      ['1950-12-31', 69543316.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'IDN_SP_POP_TOTL',
             'description': 'Population, total - Indonesia. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22132636,
             'limit': None,
             'name': 'Population, total - Indonesia',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:34:16.458Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
IRN

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 81162788.0],
                      ['2016-12-31', 80277428.0],
                      ['2015-12-31', 79360487.0],
                      ['2014-12-31', 78411092.0],
                      ['2013-12-31', 77435384.0],
                      ['2012-12-31', 76453574.0],
                      ['2011-12-31', 75491582.0],
                      ['2010-12-31', 74567511.0],
                      ['2009-12-31', 73687565.0],
                      ['2008-12-31', 72845542.0],
                      ['2007-12-31', 72031103.0],
                      ['2006-12-31', 71227880.0],
                      ['2005-12-31', 70421811.0],
                      ['2004-12-31', 69617100.0],
                      ['2003-12-31', 68812713.0],
                      ['2002-12-31', 67983330.0],
                      ['2001-12-31', 67096414.0],
                      ['2000-12-31', 66131854.0],
                      ['1999-12-31', 65062660.0],
                      ['1998-12-31', 63900630.0],
                      ['1997-12-31', 62710557.0],
                      ['1996-12-31', 61583089.0],
                      ['1995-12-31', 60575644.0],
                      ['1994-12-31', 59725125.0],
                      ['1993-12-31', 58991218.0],
                      ['1992-12-31', 58260738.0],
                      ['1991-12-31', 57375584.0],
                      ['1990-12-31', 56226185.0],
                      ['1989-12-31', 54777114.0],
                      ['1988-12-31', 53075618.0],
                      ['1987-12-31', 51197482.0],
                      ['1986-12-31', 49256842.0],
                      ['1985-12-31', 47342702.0],
                      ['1984-12-31', 45474708.0],
                      ['1983-12-31', 43645092.0],
                      ['1982-12-31', 41883332.0],
                      ['1981-12-31', 40217629.0],
                      ['1980-12-31', 38668220.0],
                      ['1979-12-31', 37252659.0],
                      ['1978-12-31', 35972652.0],
                      ['1977-12-31', 34810723.0],
                      ['1976-12-31', 33737768.0],
                      ['1975-12-31', 32730554.0],
                      ['1974-12-31', 31785500.0],
                      ['1973-12-31', 30904271.0],
                      ['1972-12-31', 30074298.0],
                      ['1971-12-31', 29281268.0],
                      ['1970-12-31', 28514010.0],
                      ['1969-12-31', 27765243.0],
                      ['1968-12-31', 27032943.0],
                      ['1967-12-31', 26318119.0],
                      ['1966-12-31', 25624656.0],
                      ['1965-12-31', 24955115.0],
                      ['1964-12-31', 24308085.0],
                      ['1963-12-31', 23680432.0],
                      ['1962-12-31', 23071429.0],
                      ['1961-12-31', 22480418.0],
                      ['1960-12-31', 21906903.0],
                      ['1959-12-31', 21350524.0],
                      ['1958-12-31', 20811061.0],
                      ['1957-12-31', 20288436.0],
                      ['1956-12-31', 19782701.0],
                      ['1955-12-31', 19293999.0],
                      ['1954-12-31', 18822603.0],
                      ['1953-12-31', 18368896.0],
                      ['1952-12-31', 17933356.0],
                      ['1951-12-31', 17516575.0],
                      ['1950-12-31', 17119268.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'IRN_SP_POP_TOTL',
             'description': 'Population, total - Iran, Islamic Rep.. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22138597,
             'limit': None,
             'name': 'Population, total - Iran, Islamic Rep.',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:34:34.390Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
IRQ
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 38274618.0],
                      ['2016-12-31', 37202572.0],
                      ['2015-12-31', 36115649.0],
                      ['2014-12-31', 35006080.0],
                      ['2013-12-31', 33883145.0],
                      ['2012-12-31', 32776571.0],
                      ['2011-12-31', 31727053.0],
                      ['2010-12-31', 30762701.0],
                      ['2009-12-31', 29894652.0],
                      ['2008-12-31', 29111417.0],
                      ['2007-12-31', 28390433.0],
                      ['2006-12-31', 27697912.0],
                      ['2005-12-31', 27008426.0],
                      ['2004-12-31', 26316609.0],
                      ['2003-12-31', 25627626.0],
                      ['2002-12-31', 24939299.0],
                      ['2001-12-31', 24251649.0],
                      ['2000-12-31', 23565413.0],
                      ['1999-12-31', 22878156.0],
                      ['1998-12-31', 22190250.0],
                      ['1997-12-31', 21509291.0],
                      ['1996-12-31', 20845893.0],
                      ['1995-12-31', 20208387.0],
                      ['1994-12-31', 19597239.0],
                      ['1993-12-31', 19011917.0],
                      ['1992-12-31', 18458187.0],
                      ['1991-12-31', 17942715.0],
                      ['1990-12-31', 17469005.0],
                      ['1989-12-31', 17040190.0],
                      ['1988-12-31', 16651807.0],
                      ['1987-12-31', 16290149.0],
                      ['1986-12-31', 15936375.0],
                      ['1985-12-31', 15576395.0],
                      ['1984-12-31', 15205501.0],
                      ['1983-12-31', 14825789.0],
                      ['1982-12-31', 14438309.0],
                      ['1981-12-31', 14046540.0],
                      ['1980-12-31', 13653356.0],
                      ['1979-12-31', 13257799.0],
                      ['1978-12-31', 12859094.0],
                      ['1977-12-31', 12460914.0],
                      ['1976-12-31', 12068168.0],
                      ['1975-12-31', 11684589.0],
                      ['1974-12-31', 11312305.0],
                      ['1973-12-31', 10951166.0],
                      ['1972-12-31', 10599845.0],
                      ['1971-12-31', 10255903.0],
                      ['1970-12-31', 9917983.0],
                      ['1969-12-31', 9585576.0],
                      ['1968-12-31', 9260682.0],
                      ['1967-12-31', 8947404.0],
                      ['1966-12-31', 8651164.0],
                      ['1965-12-31', 8375793.0],
                      ['1964-12-31', 8122199.0],
                      ['1963-12-31', 7888914.0],
                      ['1962-12-31', 7674223.0],
                      ['1961-12-31', 7475352.0],
                      ['1960-12-31', 7289761.0],
                      ['1959-12-31', 7115511.0],
                      ['1958-12-31', 6951161.0],
                      ['1957-12-31', 6795397.0],
                      ['1956-12-31', 6646643.0],
                      ['1955-12-31', 6502657.0],
                      ['1954-12-31', 6360439.0],
                      ['1953-12-31', 6216131.0],
                      ['1952-12-31', 6065010.0],
                      ['1951-12-31', 5901505.0],
                      ['1950-12-31', 5719192.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'IRQ_SP_POP_TOTL',
             'description': 'Population, total - Iraq. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22140213,
             'limit': None,
             'name': 'Population, total - Iraq',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:34:39.823Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
IRL

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 4813608.0],
                      ['2016-12-31', 4755335.0],
                      ['2015-12-31', 4701957.0],
                      ['2014-12-31', 4657740.0],
                      ['2013-12-31', 4623816.0],
                      ['2012-12-31', 4599533.0],
                      ['2011-12-31', 4580084.0],
                      ['2010-12-31', 4560155.0],
                      ['2009-12-31', 4535375.0],
                      ['2008-12-31', 4489544.0],
                      ['2007-12-31', 4398942.0],
                      ['2006-12-31', 4273591.0],
                      ['2005-12-31', 4159914.0],
                      ['2004-12-31', 4070262.0],
                      ['2003-12-31', 3996521.0],
                      ['2002-12-31', 3931947.0],
                      ['2001-12-31', 3866243.0],
                      ['2000-12-31', 3805174.0],
                      ['1999-12-31', 3754786.0],
                      ['1998-12-31', 3712696.0],
                      ['1997-12-31', 3674171.0],
                      ['1996-12-31', 3637510.0],
                      ['1995-12-31', 3608841.0],
                      ['1994-12-31', 3590386.0],
                      ['1993-12-31', 3576261.0],
                      ['1992-12-31', 3558430.0],
                      ['1991-12-31', 3534235.0],
                      ['1990-12-31', 3513974.0],
                      ['1989-12-31', 3511009.0],
                      ['1988-12-31', 3524949.0],
                      ['1987-12-31', 3540057.0],
                      ['1986-12-31', 3539690.0],
                      ['1985-12-31', 3538082.0],
                      ['1984-12-31', 3532423.0],
                      ['1983-12-31', 3510600.0],
                      ['1982-12-31', 3485800.0],
                      ['1981-12-31', 3453000.0],
                      ['1980-12-31', 3412800.0],
                      ['1979-12-31', 3373750.0],
                      ['1978-12-31', 3329100.0],
                      ['1977-12-31', 3282200.0],
                      ['1976-12-31', 3238050.0],
                      ['1975-12-31', 3189550.0],
                      ['1974-12-31', 3137500.0],
                      ['1973-12-31', 3085950.0],
                      ['1972-12-31', 3036850.0],
                      ['1971-12-31', 2992050.0],
                      ['1970-12-31', 2957250.0],
                      ['1969-12-31', 2932650.0],
                      ['1968-12-31', 2915550.0],
                      ['1967-12-31', 2902450.0],
                      ['1966-12-31', 2888800.0],
                      ['1965-12-31', 2877300.0],
                      ['1964-12-31', 2866550.0],
                      ['1963-12-31', 2852650.0],
                      ['1962-12-31', 2836050.0],
                      ['1961-12-31', 2824400.0],
                      ['1960-12-31', 2828600.0],
                      ['1959-12-31', 2836551.0],
                      ['1958-12-31', 2850125.0],
                      ['1957-12-31', 2867181.0],
                      ['1956-12-31', 2884992.0],
                      ['1955-12-31', 2901135.0],
                      ['1954-12-31', 2913706.0],
                      ['1953-12-31', 2921444.0],
                      ['1952-12-31', 2923770.0],
                      ['1951-12-31', 2920750.0],
                      ['1950-12-31', 2913093.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'IRL_SP_POP_TOTL',
             'description': 'Population, total - Ireland. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22136772,
             'limit': None,
             'name': 'Population, total - Ireland',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:34:28.734Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
IMN
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 84287.0],
                      ['2016-12-31', 83737.0],
                      ['2015-12-31', 83167.0],
                      ['2014-12-31', 82590.0],
                      ['2013-12-31', 82013.0],
                      ['2012-12-31', 81406.0],
                      ['2011-12-31', 80759.0],
                      ['2010-12-31', 80072.0],
                      ['2009-12-31', 79325.0],
                      ['2008-12-31', 78534.0],
                      ['2007-12-31', 77727.0],
                      ['2006-12-31', 76914.0],
                      ['2005-12-31', 76118.0],
                      ['2004-12-31', 75341.0],
                      ['2003-12-31', 74587.0],
                      ['2002-12-31', 73870.0],
                      ['2001-12-31', 73192.0],
                      ['2000-12-31', 72554.0],
                      ['1999-12-31', 71952.0],
                      ['1998-12-31', 71390.0],
                      ['1997-12-31', 70869.0],
                      ['1996-12-31', 70431.0],
                      ['1995-12-31', 70070.0],
                      ['1994-12-31', 69818.0],
                      ['1993-12-31', 69656.0],
                      ['1992-12-31', 69475.0],
                      ['1991-12-31', 69096.0],
                      ['1990-12-31', 68429.0],
                      ['1989-12-31', 67388.0],
                      ['1988-12-31', 66047.0],
                      ['1987-12-31', 64630.0],
                      ['1986-12-31', 63441.0],
                      ['1985-12-31', 62696.0],
                      ['1984-12-31', 62487.0],
                      ['1983-12-31', 62730.0],
                      ['1982-12-31', 63191.0],
                      ['1981-12-31', 63540.0],
                      ['1980-12-31', 63551.0],
                      ['1979-12-31', 63151.0],
                      ['1978-12-31', 62406.0],
                      ['1977-12-31', 61443.0],
                      ['1976-12-31', 60428.0],
                      ['1975-12-31', 59478.0],
                      ['1974-12-31', 58655.0],
                      ['1973-12-31', 57900.0],
                      ['1972-12-31', 57154.0],
                      ['1971-12-31', 56352.0],
                      ['1970-12-31', 55425.0],
                      ['1969-12-31', 54376.0],
                      ['1968-12-31', 53254.0],
                      ['1967-12-31', 52118.0],
                      ['1966-12-31', 51049.0],
                      ['1965-12-31', 50141.0],
                      ['1964-12-31', 49391.0],
                      ['1963-12-31', 48800.0],
                      ['1962-12-31', 48418.0],
                      ['1961-12-31', 48281.0],
                      ['1960-12-31', 48442.0],
                      ['1959-12-31', 48883.0],
                      ['1958-12-31', 49566.0],
                      ['1957-12-31', 50429.0],
                      ['1956-12-31', 51401.0],
                      ['1955-12-31', 52408.0],
                      ['1954-12-31', 53367.0],
                      ['1953-12-31', 54208.0],
                      ['1952-12-31', 54852.0],
                      ['1951-12-31', 55222.0],
                      ['1950-12-31', 55254.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'IMN_SP_POP_TOTL',
             'description': 'Population, total - Isle of Man. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22133292,
             'limit': None,
             'name': 'Population, total - Isle of Man',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:34:18.576Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
ISR
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 8712400.0],
                      ['2016-12-31', 8546000.0],
                      ['2015-12-31', 8380100.0],
                      ['2014-12-31', 8215700.0],
                      ['2013-12-31', 8059500.0],
                      ['2012-12-31', 7910500.0],
                      ['2011-12-31', 7765800.0],
                      ['2010-12-31', 7623600.0],
                      ['2009-12-31', 7485600.0],
                      ['2008-12-31', 7308800.0],
                      ['2007-12-31', 7180100.0],
                      ['2006-12-31', 7053700.0],
                      ['2005-12-31', 6930100.0],
                      ['2004-12-31', 6809000.0],
                      ['2003-12-31', 6689700.0],
                      ['2002-12-31', 6570000.0],
                      ['2001-12-31', 6439000.0],
                      ['2000-12-31', 6289000.0],
                      ['1999-12-31', 6125000.0],
                      ['1998-12-31', 5971000.0],
                      ['1997-12-31', 5836000.0],
                      ['1996-12-31', 5692000.0],
                      ['1995-12-31', 5545000.0],
                      ['1994-12-31', 5399000.0],
                      ['1993-12-31', 5261000.0],
                      ['1992-12-31', 5123000.0],
                      ['1991-12-31', 4949000.0],
                      ['1990-12-31', 4660000.0],
                      ['1989-12-31', 4518000.0],
                      ['1988-12-31', 4442000.0],
                      ['1987-12-31', 4369000.0],
                      ['1986-12-31', 4299000.0],
                      ['1985-12-31', 4233000.0],
                      ['1984-12-31', 4159000.0],
                      ['1983-12-31', 4105000.0],
                      ['1982-12-31', 4031000.0],
                      ['1981-12-31', 3956000.0],
                      ['1980-12-31', 3878000.0],
                      ['1979-12-31', 3786000.0],
                      ['1978-12-31', 3690000.0],
                      ['1977-12-31', 3613000.0],
                      ['1976-12-31', 3533000.0],
                      ['1975-12-31', 3455000.0],
                      ['1974-12-31', 3377000.0],
                      ['1973-12-31', 3278000.0],
                      ['1972-12-31', 3148000.0],
                      ['1971-12-31', 3069000.0],
                      ['1970-12-31', 2974000.0],
                      ['1969-12-31', 2877000.0],
                      ['1968-12-31', 2803000.0],
                      ['1967-12-31', 2745000.0],
                      ['1966-12-31', 2629000.0],
                      ['1965-12-31', 2563000.0],
                      ['1964-12-31', 2475000.0],
                      ['1963-12-31', 2379000.0],
                      ['1962-12-31', 2293000.0],
                      ['1961-12-31', 2185000.0],
                      ['1960-12-31', 2114020.0],
                      ['1959-12-31', 2036279.0],
                      ['1958-12-31', 1964694.0],
                      ['1957-12-31', 1895494.0],
                      ['1956-12-31', 1824427.0],
                      ['1955-12-31', 1748020.0],
                      ['1954-12-31', 1664004.0],
                      ['1953-12-31', 1571554.0],
                      ['1952-12-31', 1471382.0],
                      ['1951-12-31', 1365652.0],
                      ['1950-12-31', 1257971.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'ISR_SP_POP_TOTL',
             'description': 'Population, total - Israel. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22143470,
             'limit': None,
             'name': 'Population, total - Israel',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:34:50.206Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
ITA

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 60551416.0],
                      ['2016-12-31', 60627498.0],
                      ['2015-12-31', 60730582.0],
                      ['2014-12-31', 60789140.0],
                      ['2013-12-31', 60233948.0],
                      ['2012-12-31', 59539717.0],
                      ['2011-12-31', 59379449.0],
                      ['2010-12-31', 59277417.0],
                      ['2009-12-31', 59095365.0],
                      ['2008-12-31', 58826731.0],
                      ['2007-12-31', 58438310.0],
                      ['2006-12-31', 58143979.0],
                      ['2005-12-31', 57969484.0],
                      ['2004-12-31', 57685327.0],
                      ['2003-12-31', 57313203.0],
                      ['2002-12-31', 57059007.0],
                      ['2001-12-31', 56974100.0],
                      ['2000-12-31', 56942108.0],
                      ['1999-12-31', 56916317.0],
                      ['1998-12-31', 56906744.0],
                      ['1997-12-31', 56890372.0],
                      ['1996-12-31', 56860281.0],
                      ['1995-12-31', 56844303.0],
                      ['1994-12-31', 56843400.0],
                      ['1993-12-31', 56831821.0],
                      ['1992-12-31', 56797087.0],
                      ['1991-12-31', 56758521.0],
                      ['1990-12-31', 56719240.0],
                      ['1989-12-31', 56671781.0],
                      ['1988-12-31', 56629288.0],
                      ['1987-12-31', 56601931.0],
                      ['1986-12-31', 56596155.0],
                      ['1985-12-31', 56593071.0],
                      ['1984-12-31', 56576718.0],
                      ['1983-12-31', 56564074.0],
                      ['1982-12-31', 56543548.0],
                      ['1981-12-31', 56501675.0],
                      ['1980-12-31', 56433883.0],
                      ['1979-12-31', 56317749.0],
                      ['1978-12-31', 56155143.0],
                      ['1977-12-31', 55955411.0],
                      ['1976-12-31', 55718260.0],
                      ['1975-12-31', 55441001.0],
                      ['1974-12-31', 55110868.0],
                      ['1973-12-31', 54751406.0],
                      ['1972-12-31', 54381345.0],
                      ['1971-12-31', 54073490.0],
                      ['1970-12-31', 53821850.0],
                      ['1969-12-31', 53537950.0],
                      ['1968-12-31', 53235750.0],
                      ['1967-12-31', 52900500.0],
                      ['1966-12-31', 52519000.0],
                      ['1965-12-31', 52112350.0],
                      ['1964-12-31', 51675350.0],
                      ['1963-12-31', 51252000.0],
                      ['1962-12-31', 50879450.0],
                      ['1961-12-31', 50536350.0],
                      ['1960-12-31', 50199700.0],
                      ['1959-12-31', 49208667.0],
                      ['1958-12-31', 48927140.0],
                      ['1957-12-31', 48662851.0],
                      ['1956-12-31', 48401893.0],
                      ['1955-12-31', 48131479.0],
                      ['1954-12-31', 47841004.0],
                      ['1953-12-31', 47522671.0],
                      ['1952-12-31', 47171699.0],
                      ['1951-12-31', 46786118.0],
                      ['1950-12-31', 46366767.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'ITA_SP_POP_TOTL',
             'description': 'Population, total - Italy. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22145158,
             'limit': None,
             'name': 'Population, total - Italy',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:34:55.459Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
JAM
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 2890299.0],
                      ['2016-12-31', 2881355.0],
                      ['2015-12-31', 2871934.0],
                      ['2014-12-31', 2862087.0],
                      ['2013-12-31', 2851807.0],
                      ['2012-12-31', 2840992.0],
                      ['2011-12-31', 2829493.0],
                      ['2010-12-31', 2817210.0],
                      ['2009-12-31', 2804082.0],
                      ['2008-12-31', 2790122.0],
                      ['2007-12-31', 2775467.0],
                      ['2006-12-31', 2760279.0],
                      ['2005-12-31', 2744673.0],
                      ['2004-12-31', 2728777.0],
                      ['2003-12-31', 2712511.0],
                      ['2002-12-31', 2695446.0],
                      ['2001-12-31', 2677011.0],
                      ['2000-12-31', 2656864.0],
                      ['1999-12-31', 2634882.0],
                      ['1998-12-31', 2611367.0],
                      ['1997-12-31', 2586827.0],
                      ['1996-12-31', 2561993.0],
                      ['1995-12-31', 2537440.0],
                      ['1994-12-31', 2513049.0],
                      ['1993-12-31', 2488782.0],
                      ['1992-12-31', 2465362.0],
                      ['1991-12-31', 2443689.0],
                      ['1990-12-31', 2424242.0],
                      ['1989-12-31', 2407720.0],
                      ['1988-12-31', 2393534.0],
                      ['1987-12-31', 2379279.0],
                      ['1986-12-31', 2361720.0],
                      ['1985-12-31', 2338638.0],
                      ['1984-12-31', 2308947.0],
                      ['1983-12-31', 2273666.0],
                      ['1982-12-31', 2235327.0],
                      ['1981-12-31', 2197583.0],
                      ['1980-12-31', 2163045.0],
                      ['1979-12-31', 2132690.0],
                      ['1978-12-31', 2105664.0],
                      ['1977-12-31', 2080538.0],
                      ['1976-12-31', 2055085.0],
                      ['1975-12-31', 2027737.0],
                      ['1974-12-31', 1998034.0],
                      ['1973-12-31', 1966700.0],
                      ['1972-12-31', 1934828.0],
                      ['1971-12-31', 1904016.0],
                      ['1970-12-31', 1875381.0],
                      ['1969-12-31', 1849414.0],
                      ['1968-12-31', 1825633.0],
                      ['1967-12-31', 1803064.0],
                      ['1966-12-31', 1780264.0],
                      ['1965-12-31', 1756266.0],
                      ['1964-12-31', 1730486.0],
                      ['1963-12-31', 1703395.0],
                      ['1962-12-31', 1676250.0],
                      ['1961-12-31', 1650806.0],
                      ['1960-12-31', 1628252.0],
                      ['1959-12-31', 1608723.0],
                      ['1958-12-31', 1591514.0],
                      ['1957-12-31', 1575359.0],
                      ['1956-12-31', 1558819.0],
                      ['1955-12-31', 1540623.0],
                      ['1954-12-31', 1519786.0],
                      ['1953-12-31', 1495670.0],
                      ['1952-12-31', 1468018.0],
                      ['1951-12-31', 1436944.0],
                      ['1950-12-31', 1402899.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'JAM_SP_POP_TOTL',
             'description': 'Population, total - Jamaica. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22147082,
             'limit': None,
             'name': 'Population, total - Jamaica',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:35:01.365Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
JPN

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 126785797.0],
                      ['2016-12-31', 126994511.0],
                      ['2015-12-31', 127141000.0],
                      ['2014-12-31', 127276000.0],
                      ['2013-12-31', 127445000.0],
                      ['2012-12-31', 127629000.0],
                      ['2011-12-31', 127833000.0],
                      ['2010-12-31', 128070000.0],
                      ['2009-12-31', 128047000.0],
                      ['2008-12-31', 128063000.0],
                      ['2007-12-31', 128001000.0],
                      ['2006-12-31', 127854000.0],
                      ['2005-12-31', 127773000.0],
                      ['2004-12-31', 127761000.0],
                      ['2003-12-31', 127718000.0],
                      ['2002-12-31', 127445000.0],
                      ['2001-12-31', 127149000.0],
                      ['2000-12-31', 126843000.0],
                      ['1999-12-31', 126631000.0],
                      ['1998-12-31', 126400000.0],
                      ['1997-12-31', 126057000.0],
                      ['1996-12-31', 125757000.0],
                      ['1995-12-31', 125439000.0],
                      ['1994-12-31', 124961000.0],
                      ['1993-12-31', 124536000.0],
                      ['1992-12-31', 124229000.0],
                      ['1991-12-31', 123921000.0],
                      ['1990-12-31', 123537000.0],
                      ['1989-12-31', 123116000.0],
                      ['1988-12-31', 122613000.0],
                      ['1987-12-31', 122091000.0],
                      ['1986-12-31', 121492000.0],
                      ['1985-12-31', 120754000.0],
                      ['1984-12-31', 120018000.0],
                      ['1983-12-31', 119259000.0],
                      ['1982-12-31', 118449000.0],
                      ['1981-12-31', 117648000.0],
                      ['1980-12-31', 116782000.0],
                      ['1979-12-31', 115870000.0],
                      ['1978-12-31', 114898000.0],
                      ['1977-12-31', 113863000.0],
                      ['1976-12-31', 112771000.0],
                      ['1975-12-31', 111940000.0],
                      ['1974-12-31', 110162000.0],
                      ['1973-12-31', 108079000.0],
                      ['1972-12-31', 107188000.0],
                      ['1971-12-31', 105697000.0],
                      ['1970-12-31', 104345000.0],
                      ['1969-12-31', 103172000.0],
                      ['1968-12-31', 101061000.0],
                      ['1967-12-31', 100725000.0],
                      ['1966-12-31', 99790000.0],
                      ['1965-12-31', 98883000.0],
                      ['1964-12-31', 97826000.0],
                      ['1963-12-31', 96812000.0],
                      ['1962-12-31', 95832000.0],
                      ['1961-12-31', 94943000.0],
                      ['1960-12-31', 92500572.0],
                      ['1959-12-31', 91681328.0],
                      ['1958-12-31', 90882709.0],
                      ['1957-12-31', 90084066.0],
                      ['1956-12-31', 89261611.0],
                      ['1955-12-31', 88389061.0],
                      ['1954-12-31', 87437837.0],
                      ['1953-12-31', 86377203.0],
                      ['1952-12-31', 85174302.0],
                      ['1951-12-31', 83794117.0],
                      ['1950-12-31', 82199470.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'JPN_SP_POP_TOTL',
             'description': 'Population, total - Japan. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22150828,
             'limit': None,
             'name': 'Population, total - Japan',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:35:12.832Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
JOR
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 9702353.0],
                      ['2016-12-31', 9455802.0],
                      ['2015-12-31', 9159302.0],
                      ['2014-12-31', 8809306.0],
                      ['2013-12-31', 8413464.0],
                      ['2012-12-31', 7992573.0],
                      ['2011-12-31', 7574943.0],
                      ['2010-12-31', 7182390.0],
                      ['2009-12-31', 6821116.0],
                      ['2008-12-31', 6489822.0],
                      ['2007-12-31', 6193191.0],
                      ['2006-12-31', 5934232.0],
                      ['2005-12-31', 5714111.0],
                      ['2004-12-31', 5535595.0],
                      ['2003-12-31', 5396774.0],
                      ['2002-12-31', 5287488.0],
                      ['2001-12-31', 5193482.0],
                      ['2000-12-31', 5103130.0],
                      ['1999-12-31', 5014899.0],
                      ['1998-12-31', 4927912.0],
                      ['1997-12-31', 4832267.0],
                      ['1996-12-31', 4716373.0],
                      ['1995-12-31', 4572904.0],
                      ['1994-12-31', 4395953.0],
                      ['1993-12-31', 4189431.0],
                      ['1992-12-31', 3968198.0],
                      ['1991-12-31', 3753433.0],
                      ['1990-12-31', 3560582.0],
                      ['1989-12-31', 3395023.0],
                      ['1988-12-31', 3252672.0],
                      ['1987-12-31', 3127917.0],
                      ['1986-12-31', 3011300.0],
                      ['1985-12-31', 2895985.0],
                      ['1984-12-31', 2780428.0],
                      ['1983-12-31', 2667470.0],
                      ['1982-12-31', 2559718.0],
                      ['1981-12-31', 2461193.0],
                      ['1980-12-31', 2374422.0],
                      ['1979-12-31', 2299655.0],
                      ['1978-12-31', 2234594.0],
                      ['1977-12-31', 2176135.0],
                      ['1976-12-31', 2120069.0],
                      ['1975-12-31', 2062918.0],
                      ['1974-12-31', 2004833.0],
                      ['1973-12-31', 1945626.0],
                      ['1972-12-31', 1881214.0],
                      ['1971-12-31', 1806605.0],
                      ['1970-12-31', 1718913.0],
                      ['1969-12-31', 1615277.0],
                      ['1968-12-31', 1498309.0],
                      ['1967-12-31', 1377465.0],
                      ['1966-12-31', 1265806.0],
                      ['1965-12-31', 1172550.0],
                      ['1964-12-31', 1101459.0],
                      ['1963-12-31', 1049302.0],
                      ['1962-12-31', 1009733.0],
                      ['1961-12-31', 973083.0],
                      ['1960-12-31', 932257.0],
                      ['1959-12-31', 884864.0],
                      ['1958-12-31', 832428.0],
                      ['1957-12-31', 778771.0],
                      ['1956-12-31', 728040.0],
                      ['1955-12-31', 682952.0],
                      ['1954-12-31', 644196.0],
                      ['1953-12-31', 610079.0],
                      ['1952-12-31', 576367.0],
                      ['1951-12-31', 536446.0],
                      ['1950-12-31', 481321.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'JOR_SP_POP_TOTL',
             'description': 'Population, total - Jordan. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22149111,
             'limit': None,
             'name': 'Population, total - Jordan',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:35:07.453Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
KAZ

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 18037646.0],
                      ['2016-12-31', 17794055.0],
                      ['2015-12-31', 17542806.0],
                      ['2014-12-31', 17288285.0],
                      ['2013-12-31', 17035550.0],
                      ['2012-12-31', 16792089.0],
                      ['2011-12-31', 16557201.0],
                      ['2010-12-31', 16321872.0],
                      ['2009-12-31', 16092822.0],
                      ['2008-12-31', 15674000.0],
                      ['2007-12-31', 15484192.0],
                      ['2006-12-31', 15308084.0],
                      ['2005-12-31', 15147029.0],
                      ['2004-12-31', 15012985.0],
                      ['2003-12-31', 14909018.0],
                      ['2002-12-31', 14858948.0],
                      ['2001-12-31', 14858335.0],
                      ['2000-12-31', 14883626.0],
                      ['1999-12-31', 14928426.0],
                      ['1998-12-31', 15071300.0],
                      ['1997-12-31', 15333703.0],
                      ['1996-12-31', 15577894.0],
                      ['1995-12-31', 15815626.0],
                      ['1994-12-31', 16095199.0],
                      ['1993-12-31', 16330419.0],
                      ['1992-12-31', 16439095.0],
                      ['1991-12-31', 16450500.0],
                      ['1990-12-31', 16348000.0],
                      ['1989-12-31', 16249500.0],
                      ['1988-12-31', 15982510.0],
                      ['1987-12-31', 15801753.0],
                      ['1986-12-31', 15600928.0],
                      ['1985-12-31', 15403006.0],
                      ['1984-12-31', 15214051.0],
                      ['1983-12-31', 15030495.0],
                      ['1982-12-31', 14853993.0],
                      ['1981-12-31', 14683789.0],
                      ['1980-12-31', 14518924.0],
                      ['1979-12-31', 14362417.0],
                      ['1978-12-31', 14215111.0],
                      ['1977-12-31', 14070681.0],
                      ['1976-12-31', 13920105.0],
                      ['1975-12-31', 13756789.0],
                      ['1974-12-31', 13577049.0],
                      ['1973-12-31', 13382211.0],
                      ['1972-12-31', 13176584.0],
                      ['1971-12-31', 12966920.0],
                      ['1970-12-31', 12757245.0],
                      ['1969-12-31', 12550121.0],
                      ['1968-12-31', 12341412.0],
                      ['1967-12-31', 12120504.0],
                      ['1966-12-31', 11872939.0],
                      ['1965-12-31', 11588870.0],
                      ['1964-12-31', 11267329.0],
                      ['1963-12-31', 10913552.0],
                      ['1962-12-31', 10532062.0],
                      ['1961-12-31', 10129861.0],
                      ['1960-12-31', 9714260.0],
                      ['1959-12-31', 9292148.0],
                      ['1958-12-31', 8870252.0],
                      ['1957-12-31', 8455736.0],
                      ['1956-12-31', 8056903.0],
                      ['1955-12-31', 7683837.0],
                      ['1954-12-31', 7348624.0],
                      ['1953-12-31', 7065480.0],
                      ['1952-12-31', 6850793.0],
                      ['1951-12-31', 6723082.0],
                      ['1950-12-31', 6702996.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'KAZ_SP_POP_TOTL',
             'description': 'Population, total - Kazakhstan. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22152647,
             'limit': None,
             'name': 'Population, total - Kazakhstan',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:35:18.532Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
KEN
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 49699862.0],
                      ['2016-12-31', 48461567.0],
                      ['2015-12-31', 47236259.0],
                      ['2014-12-31', 46024250.0],
                      ['2013-12-31', 44826849.0],
                      ['2012-12-31', 43646629.0],
                      ['2011-12-31', 42486839.0],
                      ['2010-12-31', 41350152.0],
                      ['2009-12-31', 40237204.0],
                      ['2008-12-31', 39148416.0],
                      ['2007-12-31', 38085909.0],
                      ['2006-12-31', 37052050.0],
                      ['2005-12-31', 36048288.0],
                      ['2004-12-31', 35074931.0],
                      ['2003-12-31', 34130852.0],
                      ['2002-12-31', 33214009.0],
                      ['2001-12-31', 32321482.0],
                      ['2000-12-31', 31450483.0],
                      ['1999-12-31', 30600397.0],
                      ['1998-12-31', 29769803.0],
                      ['1997-12-31', 28954114.0],
                      ['1996-12-31', 28147734.0],
                      ['1995-12-31', 27346456.0],
                      ['1994-12-31', 26548486.0],
                      ['1993-12-31', 25754114.0],
                      ['1992-12-31', 24963953.0],
                      ['1991-12-31', 24179598.0],
                      ['1990-12-31', 23402507.0],
                      ['1989-12-31', 22633022.0],
                      ['1988-12-31', 21871442.0],
                      ['1987-12-31', 21119318.0],
                      ['1986-12-31', 20378626.0],
                      ['1985-12-31', 19651225.0],
                      ['1984-12-31', 18937738.0],
                      ['1983-12-31', 18239404.0],
                      ['1982-12-31', 17559430.0],
                      ['1981-12-31', 16901677.0],
                      ['1980-12-31', 16268990.0],
                      ['1979-12-31', 15662852.0],
                      ['1978-12-31', 15082994.0],
                      ['1977-12-31', 14528293.0],
                      ['1976-12-31', 13996704.0],
                      ['1975-12-31', 13486629.0],
                      ['1974-12-31', 12997595.0],
                      ['1973-12-31', 12529852.0],
                      ['1972-12-31', 12083188.0],
                      ['1971-12-31', 11657514.0],
                      ['1970-12-31', 11252492.0],
                      ['1969-12-31', 10867716.0],
                      ['1968-12-31', 10502245.0],
                      ['1967-12-31', 10154484.0],
                      ['1966-12-31', 9822499.0],
                      ['1965-12-31', 9504703.0],
                      ['1964-12-31', 9200157.0],
                      ['1963-12-31', 8908422.0],
                      ['1962-12-31', 8628972.0],
                      ['1961-12-31', 8361441.0],
                      ['1960-12-31', 8105440.0],
                      ['1959-12-31', 7860475.0],
                      ['1958-12-31', 7625995.0],
                      ['1957-12-31', 7401421.0],
                      ['1956-12-31', 7186211.0],
                      ['1955-12-31', 6979931.0],
                      ['1954-12-31', 6782287.0],
                      ['1953-12-31', 6593109.0],
                      ['1952-12-31', 6412363.0],
                      ['1951-12-31', 6240163.0],
                      ['1950-12-31', 6076758.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'KEN_SP_POP_TOTL',
             'description': 'Population, total - Kenya. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22154686,
             'limit': None,
             'name': 'Population, total - Kenya',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:35:25.855Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
KIR

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 116398.0],
                      ['2016-12-31', 114395.0],
                      ['2015-12-31', 112407.0],
                      ['2014-12-31', 110458.0],
                      ['2013-12-31', 108535.0],
                      ['2012-12-31', 106613.0],
                      ['2011-12-31', 104656.0],
                      ['2010-12-31', 102652.0],
                      ['2009-12-31', 100568.0],
                      ['2008-12-31', 98440.0],
                      ['2007-12-31', 96311.0],
                      ['2006-12-31', 94260.0],
                      ['2005-12-31', 92325.0],
                      ['2004-12-31', 90542.0],
                      ['2003-12-31', 88895.0],
                      ['2002-12-31', 87343.0],
                      ['2001-12-31', 85858.0],
                      ['2000-12-31', 84406.0],
                      ['1999-12-31', 82966.0],
                      ['1998-12-31', 81550.0],
                      ['1997-12-31', 80184.0],
                      ['1996-12-31', 78907.0],
                      ['1995-12-31', 77730.0],
                      ['1994-12-31', 76671.0],
                      ['1993-12-31', 75719.0],
                      ['1992-12-31', 74769.0],
                      ['1991-12-31', 73700.0],
                      ['1990-12-31', 72412.0],
                      ['1989-12-31', 70860.0],
                      ['1988-12-31', 69098.0],
                      ['1987-12-31', 67261.0],
                      ['1986-12-31', 65518.0],
                      ['1985-12-31', 64003.0],
                      ['1984-12-31', 62765.0],
                      ['1983-12-31', 61768.0],
                      ['1982-12-31', 60920.0],
                      ['1981-12-31', 60133.0],
                      ['1980-12-31', 59339.0],
                      ['1979-12-31', 58506.0],
                      ['1978-12-31', 57662.0],
                      ['1977-12-31', 56810.0],
                      ['1976-12-31', 55977.0],
                      ['1975-12-31', 55169.0],
                      ['1974-12-31', 54380.0],
                      ['1973-12-31', 53604.0],
                      ['1972-12-31', 52824.0],
                      ['1971-12-31', 52025.0],
                      ['1970-12-31', 51178.0],
                      ['1969-12-31', 50294.0],
                      ['1968-12-31', 49388.0],
                      ['1967-12-31', 48437.0],
                      ['1966-12-31', 47459.0],
                      ['1965-12-31', 46453.0],
                      ['1964-12-31', 45425.0],
                      ['1963-12-31', 44363.0],
                      ['1962-12-31', 43302.0],
                      ['1961-12-31', 42257.0],
                      ['1960-12-31', 41233.0],
                      ['1959-12-31', 40240.0],
                      ['1958-12-31', 39268.0],
                      ['1957-12-31', 38346.0],
                      ['1956-12-31', 37455.0],
                      ['1955-12-31', 36596.0],
                      ['1954-12-31', 35777.0],
                      ['1953-12-31', 35007.0],
                      ['1952-12-31', 34286.0],
                      ['1951-12-31', 33623.0],
                      ['1950-12-31', 33048.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'KIR_SP_POP_TOTL',
             'description': 'Population, total - Kiribati. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22159931,
             'limit': None,
             'name': 'Population, total - Kiribati',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:35:44.801Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
PRK
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 25490965.0],
                      ['2016-12-31', 25368620.0],
                      ['2015-12-31', 25243917.0],
                      ['2014-12-31', 25116363.0],
                      ['2013-12-31', 24985976.0],
                      ['2012-12-31', 24854034.0],
                      ['2011-12-31', 24722298.0],
                      ['2010-12-31', 24591599.0],
                      ['2009-12-31', 24463021.0],
                      ['2008-12-31', 24335146.0],
                      ['2007-12-31', 24203289.0],
                      ['2006-12-31', 24061097.0],
                      ['2005-12-31', 23904167.0],
                      ['2004-12-31', 23729498.0],
                      ['2003-12-31', 23538540.0],
                      ['2002-12-31', 23336681.0],
                      ['2001-12-31', 23131810.0],
                      ['2000-12-31', 22929075.0],
                      ['1999-12-31', 22731985.0],
                      ['1998-12-31', 22537336.0],
                      ['1997-12-31', 22335638.0],
                      ['1996-12-31', 22113548.0],
                      ['1995-12-31', 21862299.0],
                      ['1994-12-31', 21577982.0],
                      ['1993-12-31', 21265834.0],
                      ['1992-12-31', 20937404.0],
                      ['1991-12-31', 20609150.0],
                      ['1990-12-31', 20293054.0],
                      ['1989-12-31', 19993755.0],
                      ['1988-12-31', 19708323.0],
                      ['1987-12-31', 19431986.0],
                      ['1986-12-31', 19156795.0],
                      ['1985-12-31', 18877238.0],
                      ['1984-12-31', 18590138.0],
                      ['1983-12-31', 18298214.0],
                      ['1982-12-31', 18008564.0],
                      ['1981-12-31', 17731230.0],
                      ['1980-12-31', 17472140.0],
                      ['1979-12-31', 17235666.0],
                      ['1978-12-31', 17015983.0],
                      ['1977-12-31', 16796578.0],
                      ['1976-12-31', 16554746.0],
                      ['1975-12-31', 16274740.0],
                      ['1974-12-31', 15952078.0],
                      ['1973-12-31', 15593351.0],
                      ['1972-12-31', 15207771.0],
                      ['1971-12-31', 14809521.0],
                      ['1970-12-31', 14410400.0],
                      ['1969-12-31', 14010339.0],
                      ['1968-12-31', 13609982.0],
                      ['1967-12-31', 13222694.0],
                      ['1966-12-31', 12864954.0],
                      ['1965-12-31', 12547525.0],
                      ['1964-12-31', 12282419.0],
                      ['1963-12-31', 12065468.0],
                      ['1962-12-31', 11871712.0],
                      ['1961-12-31', 11665595.0],
                      ['1960-12-31', 11424176.0],
                      ['1959-12-31', 11145152.0],
                      ['1958-12-31', 10843979.0],
                      ['1957-12-31', 10547389.0],
                      ['1956-12-31', 10285940.0],
                      ['1955-12-31', 10086991.0],
                      ['1954-12-31', 9972436.0],
                      ['1953-12-31', 9957242.0],
                      ['1952-12-31', 10049029.0],
                      ['1951-12-31', 10248496.0],
                      ['1950-12-31', 10549472.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'PRK_SP_POP_TOTL',
             'description': 'Population, total - Korea, Dem. Rep.. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22214277,
             'limit': None,
             'name': 'Population, total - Korea, Dem. Rep.',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:41:55.494Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
KOR

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 51466201.0],
                      ['2016-12-31', 51245707.0],
                      ['2015-12-31', 51014947.0],
                      ['2014-12-31', 50746659.0],
                      ['2013-12-31', 50428893.0],
                      ['2012-12-31', 50199853.0],
                      ['2011-12-31', 49936638.0],
                      ['2010-12-31', 49554112.0],
                      ['2009-12-31', 49307835.0],
                      ['2008-12-31', 49054708.0],
                      ['2007-12-31', 48683638.0],
                      ['2006-12-31', 48438292.0],
                      ['2005-12-31', 48184561.0],
                      ['2004-12-31', 48082519.0],
                      ['2003-12-31', 47892330.0],
                      ['2002-12-31', 47644736.0],
                      ['2001-12-31', 47370164.0],
                      ['2000-12-31', 47008111.0],
                      ['1999-12-31', 46616677.0],
                      ['1998-12-31', 46286503.0],
                      ['1997-12-31', 45953580.0],
                      ['1996-12-31', 45524681.0],
                      ['1995-12-31', 45092991.0],
                      ['1994-12-31', 44641540.0],
                      ['1993-12-31', 44194628.0],
                      ['1992-12-31', 43747962.0],
                      ['1991-12-31', 43295704.0],
                      ['1990-12-31', 42869283.0],
                      ['1989-12-31', 42449038.0],
                      ['1988-12-31', 42031247.0],
                      ['1987-12-31', 41621690.0],
                      ['1986-12-31', 41213674.0],
                      ['1985-12-31', 40805744.0],
                      ['1984-12-31', 40405956.0],
                      ['1983-12-31', 39910403.0],
                      ['1982-12-31', 39326352.0],
                      ['1981-12-31', 38723248.0],
                      ['1980-12-31', 38123775.0],
                      ['1979-12-31', 37534236.0],
                      ['1978-12-31', 36969185.0],
                      ['1977-12-31', 36411795.0],
                      ['1976-12-31', 35848523.0],
                      ['1975-12-31', 35280725.0],
                      ['1974-12-31', 34692266.0],
                      ['1973-12-31', 34103149.0],
                      ['1972-12-31', 33505406.0],
                      ['1971-12-31', 32882704.0],
                      ['1970-12-31', 32240827.0],
                      ['1969-12-31', 31544266.0],
                      ['1968-12-31', 30838302.0],
                      ['1967-12-31', 30130983.0],
                      ['1966-12-31', 29435571.0],
                      ['1965-12-31', 28704674.0],
                      ['1964-12-31', 27984155.0],
                      ['1963-12-31', 27261747.0],
                      ['1962-12-31', 26513030.0],
                      ['1961-12-31', 25765673.0],
                      ['1960-12-31', 25012374.0],
                      ['1959-12-31', 24295670.0],
                      ['1958-12-31', 23489746.0],
                      ['1957-12-31', 22680855.0],
                      ['1956-12-31', 21897498.0],
                      ['1955-12-31', 21168216.0],
                      ['1954-12-31', 20520266.0],
                      ['1953-12-31', 19978822.0],
                      ['1952-12-31', 19566709.0],
                      ['1951-12-31', 19304677.0],
                      ['1950-12-31', 19211386.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'KOR_SP_POP_TOTL',
             'description': 'Population, total - Korea, Rep.. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22162967,
             'limit': None,
             'name': 'Population, total - Korea, Rep.',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:35:53.580Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
KSV
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 1830700.0],
                      ['2016-12-31', 1816200.0],
                      ['2015-12-31', 1801800.0],
                      ['2014-12-31', 1821800.0],
                      ['2013-12-31', 1824100.0],
                      ['2012-12-31', 1805200.0],
                      ['2011-12-31', 1791000.0],
                      ['2010-12-31', 1775680.0],
                      ['2009-12-31', 1761474.0],
                      ['2008-12-31', 1747383.0],
                      ['2007-12-31', 1733404.0],
                      ['2006-12-31', 1719536.0],
                      ['2005-12-31', 1705780.0],
                      ['2004-12-31', 1704622.0],
                      ['2003-12-31', 1703466.0],
                      ['2002-12-31', 1702310.0],
                      ['2001-12-31', 1701154.0],
                      ['2000-12-31', 1700000.0],
                      ['1999-12-31', 1762000.0],
                      ['1998-12-31', 1966000.0],
                      ['1997-12-31', 2086000.0],
                      ['1996-12-31', 2059000.0],
                      ['1995-12-31', 2029000.0],
                      ['1994-12-31', 1997000.0],
                      ['1993-12-31', 1965000.0],
                      ['1992-12-31', 1932000.0],
                      ['1991-12-31', 1898000.0],
                      ['1990-12-31', 1862000.0],
                      ['1989-12-31', 1827000.0],
                      ['1988-12-31', 1791000.0],
                      ['1987-12-31', 1753000.0],
                      ['1986-12-31', 1717000.0],
                      ['1985-12-31', 1682000.0],
                      ['1984-12-31', 1647000.0],
                      ['1983-12-31', 1614000.0],
                      ['1982-12-31', 1582000.0],
                      ['1981-12-31', 1552000.0],
                      ['1980-12-31', 1521000.0],
                      ['1979-12-31', 1491000.0],
                      ['1978-12-31', 1460000.0],
                      ['1977-12-31', 1430000.0],
                      ['1976-12-31', 1400000.0],
                      ['1975-12-31', 1369000.0],
                      ['1974-12-31', 1339000.0],
                      ['1973-12-31', 1308000.0],
                      ['1972-12-31', 1278000.0],
                      ['1971-12-31', 1247000.0],
                      ['1970-12-31', 1219000.0],
                      ['1969-12-31', 1191000.0],
                      ['1968-12-31', 1163000.0],
                      ['1967-12-31', 1135000.0],
                      ['1966-12-31', 1106000.0],
                      ['1965-12-31', 1078000.0],
                      ['1964-12-31', 1050000.0],
                      ['1963-12-31', 1022000.0],
                      ['1962-12-31', 994000.0],
                      ['1961-12-31', 966000.0],
                      ['1960-12-31', 947000.0],
                      ['1959-12-31', 928000.0],
                      ['1958-12-31', 910000.0],
                      ['1957-12-31', 891000.0],
                      ['1956-12-31', 872000.0],
                      ['1955-12-31', 854000.0],
                      ['1954-12-31', 835000.0],
                      ['1953-12-31', 816000.0],
                      ['1952-12-31', 798000.0],
                      ['1951-12-31', 779000.0],
                      ['1950-12-31', 761000.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'KSV_SP_POP_TOTL',
             'description': 'Population, total - Kosovo. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22164153,
             'limit': None,
             'name': 'Population, total - Kosovo',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:35:57.675Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
KWT

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 4136528.0],
                      ['2016-12-31', 4052584.0],
                      ['2015-12-31', 3935794.0],
                      ['2014-12-31', 3782450.0],
                      ['2013-12-31', 3598385.0],
                      ['2012-12-31', 3395556.0],
                      ['2011-12-31', 3191051.0],
                      ['2010-12-31', 2998083.0],
                      ['2009-12-31', 2818939.0],
                      ['2008-12-31', 2652340.0],
                      ['2007-12-31', 2503410.0],
                      ['2006-12-31', 2377258.0],
                      ['2005-12-31', 2276623.0],
                      ['2004-12-31', 2207939.0],
                      ['2003-12-31', 2169118.0],
                      ['2002-12-31', 2143833.0],
                      ['2001-12-31', 2109355.0],
                      ['2000-12-31', 2050741.0],
                      ['1999-12-31', 1957066.0],
                      ['1998-12-31', 1836353.0],
                      ['1997-12-31', 1715314.0],
                      ['1996-12-31', 1631740.0],
                      ['1995-12-31', 1610651.0],
                      ['1991-12-31', 2035661.0],
                      ['1990-12-31', 2099615.0],
                      ['1989-12-31', 2096932.0],
                      ['1988-12-31', 2038885.0],
                      ['1987-12-31', 1942810.0],
                      ['1986-12-31', 1836105.0],
                      ['1985-12-31', 1738994.0],
                      ['1984-12-31', 1655833.0],
                      ['1983-12-31', 1580638.0],
                      ['1982-12-31', 1511314.0],
                      ['1981-12-31', 1442991.0],
                      ['1980-12-31', 1372318.0],
                      ['1979-12-31', 1299683.0],
                      ['1978-12-31', 1227601.0],
                      ['1977-12-31', 1157033.0],
                      ['1976-12-31', 1089209.0],
                      ['1975-12-31', 1024940.0],
                      ['1974-12-31', 964834.0],
                      ['1973-12-31', 908520.0],
                      ['1972-12-31', 854604.0],
                      ['1971-12-31', 801142.0],
                      ['1970-12-31', 746767.0],
                      ['1969-12-31', 691129.0],
                      ['1968-12-31', 634897.0],
                      ['1967-12-31', 579007.0],
                      ['1966-12-31', 524856.0],
                      ['1965-12-31', 473554.0],
                      ['1964-12-31', 425235.0],
                      ['1963-12-31', 379891.0],
                      ['1962-12-31', 338296.0],
                      ['1961-12-31', 301336.0],
                      ['1960-12-31', 269618.0],
                      ['1959-12-31', 243235.0],
                      ['1958-12-31', 221911.0],
                      ['1957-12-31', 205065.0],
                      ['1956-12-31', 191975.0],
                      ['1955-12-31', 181888.0],
                      ['1954-12-31', 174091.0],
                      ['1953-12-31', 167896.0],
                      ['1952-12-31', 162696.0],
                      ['1951-12-31', 157932.0],
                      ['1950-12-31', 153096.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'KWT_SP_POP_TOTL',
             'description': 'Population, total - Kuwait. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22165580,
             'limit': None,
             'name': 'Population, total - Kuwait',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:36:02.076Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
KGZ
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 6201500.0],
                      ['2016-12-31', 6079500.0],
                      ['2015-12-31', 5956900.0],
                      ['2014-12-31', 5835500.0],
                      ['2013-12-31', 5719600.0],
                      ['2012-12-31', 5607200.0],
                      ['2011-12-31', 5514600.0],
                      ['2010-12-31', 5447900.0],
                      ['2009-12-31', 5383300.0],
                      ['2008-12-31', 5318700.0],
                      ['2007-12-31', 5268400.0],
                      ['2006-12-31', 5218400.0],
                      ['2005-12-31', 5162600.0],
                      ['2004-12-31', 5104700.0],
                      ['2003-12-31', 5043300.0],
                      ['2002-12-31', 4990700.0],
                      ['2001-12-31', 4945100.0],
                      ['2000-12-31', 4898400.0],
                      ['1999-12-31', 4840400.0],
                      ['1998-12-31', 4769000.0],
                      ['1997-12-31', 4696400.0],
                      ['1996-12-31', 4628400.0],
                      ['1995-12-31', 4560400.0],
                      ['1994-12-31', 4515100.0],
                      ['1993-12-31', 4516700.0],
                      ['1992-12-31', 4515400.0],
                      ['1991-12-31', 4463600.0],
                      ['1990-12-31', 4391200.0],
                      ['1989-12-31', 4307500.0],
                      ['1988-12-31', 4218400.0],
                      ['1987-12-31', 4144600.0],
                      ['1986-12-31', 4066500.0],
                      ['1985-12-31', 3990300.0],
                      ['1984-12-31', 3916400.0],
                      ['1983-12-31', 3838300.0],
                      ['1982-12-31', 3759300.0],
                      ['1981-12-31', 3685800.0],
                      ['1980-12-31', 3617400.0],
                      ['1979-12-31', 3552000.0],
                      ['1978-12-31', 3487100.0],
                      ['1977-12-31', 3423900.0],
                      ['1976-12-31', 3358700.0],
                      ['1975-12-31', 3292400.0],
                      ['1974-12-31', 3223900.0],
                      ['1973-12-31', 3153800.0],
                      ['1972-12-31', 3088200.0],
                      ['1971-12-31', 3022300.0],
                      ['1970-12-31', 2959900.0],
                      ['1969-12-31', 2894800.0],
                      ['1968-12-31', 2818300.0],
                      ['1967-12-31', 2736500.0],
                      ['1966-12-31', 2655300.0],
                      ['1965-12-31', 2573300.0],
                      ['1964-12-31', 2495300.0],
                      ['1963-12-31', 2413700.0],
                      ['1962-12-31', 2333400.0],
                      ['1961-12-31', 2255900.0],
                      ['1960-12-31', 2172300.0],
                      ['1959-12-31', 2106792.0],
                      ['1958-12-31', 2047784.0],
                      ['1957-12-31', 1994697.0],
                      ['1956-12-31', 1946540.0],
                      ['1955-12-31', 1902499.0],
                      ['1954-12-31', 1862068.0],
                      ['1953-12-31', 1825123.0],
                      ['1952-12-31', 1791952.0],
                      ['1951-12-31', 1763226.0],
                      ['1950-12-31', 1740000.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'KGZ_SP_POP_TOTL',
             'description': 'Population, total - Kyrgyz Republic. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22156685,
             'limit': None,
             'name': 'Population, total - Kyrgyz Republic',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:35:34.132Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
LAO
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 6858160.0],
                      ['2016-12-31', 6758353.0],
                      ['2015-12-31', 6663967.0],
                      ['2014-12-31', 6576397.0],
                      ['2013-12-31', 6494557.0],
                      ['2012-12-31', 6415169.0],
                      ['2011-12-31', 6333487.0],
                      ['2010-12-31', 6246274.0],
                      ['2009-12-31', 6152036.0],
                      ['2008-12-31', 6052190.0],
                      ['2007-12-31', 5949787.0],
                      ['2006-12-31', 5849356.0],
                      ['2005-12-31', 5754026.0],
                      ['2004-12-31', 5664605.0],
                      ['2003-12-31', 5579656.0],
                      ['2002-12-31', 5497273.0],
                      ['2001-12-31', 5414568.0],
                      ['2000-12-31', 5329304.0],
                      ['1999-12-31', 5241284.0],
                      ['1998-12-31', 5150763.0],
                      ['1997-12-31', 5056519.0],
                      ['1996-12-31', 4957180.0],
                      ['1995-12-31', 4851923.0],
                      ['1994-12-31', 4740380.0],
                      ['1993-12-31', 4623280.0],
                      ['1992-12-31', 4502363.0],
                      ['1991-12-31', 4380073.0],
                      ['1990-12-31', 4258472.0],
                      ['1989-12-31', 4138408.0],
                      ['1988-12-31', 4020295.0],
                      ['1987-12-31', 3905163.0],
                      ['1986-12-31', 3794043.0],
                      ['1985-12-31', 3687898.0],
                      ['1984-12-31', 3586381.0],
                      ['1983-12-31', 3489977.0],
                      ['1982-12-31', 3401242.0],
                      ['1981-12-31', 3323377.0],
                      ['1980-12-31', 3258144.0],
                      ['1979-12-31', 3207328.0],
                      ['1978-12-31', 3168843.0],
                      ['1977-12-31', 3135842.0],
                      ['1976-12-31', 3098973.0],
                      ['1975-12-31', 3051577.0],
                      ['1974-12-31', 2990965.0],
                      ['1973-12-31', 2919287.0],
                      ['1972-12-31', 2840841.0],
                      ['1971-12-31', 2762265.0],
                      ['1970-12-31', 2688428.0],
                      ['1969-12-31', 2620434.0],
                      ['1968-12-31', 2556852.0],
                      ['1967-12-31', 2496920.0],
                      ['1966-12-31', 2439196.0],
                      ['1965-12-31', 2382594.0],
                      ['1964-12-31', 2327137.0],
                      ['1963-12-31', 2273349.0],
                      ['1962-12-31', 2221122.0],
                      ['1961-12-31', 2170343.0],
                      ['1960-12-31', 2120896.0],
                      ['1959-12-31', 2072699.0],
                      ['1958-12-31', 2025666.0],
                      ['1957-12-31', 1979729.0],
                      ['1956-12-31', 1934812.0],
                      ['1955-12-31', 1890852.0],
                      ['1954-12-31', 1847775.0],
                      ['1953-12-31', 1805515.0],
                      ['1952-12-31', 1764007.0],
                      ['1951-12-31', 1723162.0],
                      ['1950-12-31', 1682915.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'LAO_SP_POP_TOTL',
             'description': 'Population, total - Lao PDR. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22169356,
             'limit': None,
             'name': 'Population, total - Lao PDR',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:36:12.709Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
LCN

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 644137666.0],
                      ['2016-12-31', 637663890.0],
                      ['2015-12-31', 631062657.0],
                      ['2014-12-31', 624335544.0],
                      ['2013-12-31', 617495658.0],
                      ['2012-12-31', 610547919.0],
                      ['2011-12-31', 603537118.0],
                      ['2010-12-31', 596478519.0],
                      ['2009-12-31', 589349327.0],
                      ['2008-12-31', 582179826.0],
                      ['2007-12-31', 574994397.0],
                      ['2006-12-31', 567821716.0],
                      ['2005-12-31', 560673962.0],
                      ['2004-12-31', 553563090.0],
                      ['2003-12-31', 546478662.0],
                      ['2002-12-31', 539372044.0],
                      ['2001-12-31', 532172709.0],
                      ['2000-12-31', 524829251.0],
                      ['1999-12-31', 517324344.0],
                      ['1998-12-31', 509664957.0],
                      ['1997-12-31', 501837820.0],
                      ['1996-12-31', 493920488.0],
                      ['1995-12-31', 485913138.0],
                      ['1994-12-31', 477832467.0],
                      ['1993-12-31', 469673465.0],
                      ['1992-12-31', 461466819.0],
                      ['1991-12-31', 453251622.0],
                      ['1990-12-31', 445044474.0],
                      ['1989-12-31', 436857131.0],
                      ['1988-12-31', 428701267.0],
                      ['1987-12-31', 420560827.0],
                      ['1986-12-31', 412413602.0],
                      ['1985-12-31', 404246768.0],
                      ['1984-12-31', 396059351.0],
                      ['1983-12-31', 387868173.0],
                      ['1982-12-31', 379697683.0],
                      ['1981-12-31', 371580994.0],
                      ['1980-12-31', 363543431.0],
                      ['1979-12-31', 355593111.0],
                      ['1978-12-31', 347735305.0],
                      ['1977-12-31', 339956419.0],
                      ['1976-12-31', 332247800.0],
                      ['1975-12-31', 324590837.0],
                      ['1974-12-31', 316987646.0],
                      ['1973-12-31', 309446959.0],
                      ['1972-12-31', 301984430.0],
                      ['1971-12-31', 294620137.0],
                      ['1970-12-31', 287361389.0],
                      ['1969-12-31', 280225795.0],
                      ['1968-12-31', 273209036.0],
                      ['1967-12-31', 266295880.0],
                      ['1966-12-31', 259468669.0],
                      ['1965-12-31', 252710310.0],
                      ['1964-12-31', 246016368.0],
                      ['1963-12-31', 239401268.0],
                      ['1962-12-31', 232897323.0],
                      ['1961-12-31', 226564469.0],
                      ['1960-12-31', 220434662.0],
                      ['1959-12-31', 214529909.0],
                      ['1958-12-31', 208821851.0],
                      ['1957-12-31', 203291970.0],
                      ['1956-12-31', 197920194.0],
                      ['1955-12-31', 192685947.0],
                      ['1954-12-31', 187589780.0],
                      ['1953-12-31', 182611242.0],
                      ['1952-12-31', 177752158.0],
                      ['1951-12-31', 173021009.0],
                      ['1950-12-31', 168434655.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'LCN_SP_POP_TOTL',
             'description': 'Population, total - Latin America & Caribbean '
                            '(all income levels). ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22177522,
             'limit': None,
             'name': 'Population, total - Latin America & Caribbean (all '
                     'income levels)',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:36:39.703Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
LAC
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 568136842.0],
                      ['2016-12-31', 562254848.0],
                      ['2015-12-31', 556257851.0],
                      ['2014-12-31', 550149862.0],
                      ['2013-12-31', 543940758.0],
                      ['2012-12-31', 537645733.0],
                      ['2011-12-31', 531283625.0],
                      ['2010-12-31', 524870761.0],
                      ['2009-12-31', 518406797.0],
                      ['2008-12-31', 511896377.0],
                      ['2007-12-31', 505365856.0],
                      ['2006-12-31', 498847473.0],
                      ['2005-12-31', 492360617.0],
                      ['2004-12-31', 485921455.0],
                      ['2003-12-31', 479514487.0],
                      ['2002-12-31', 473087978.0],
                      ['2001-12-31', 466569961.0],
                      ['2000-12-31', 459908706.0],
                      ['1999-12-31', 453089523.0],
                      ['1998-12-31', 446128863.0],
                      ['1997-12-31', 439044994.0],
                      ['1996-12-31', 431868811.0],
                      ['1995-12-31', 424626030.0],
                      ['1994-12-31', 417319166.0],
                      ['1993-12-31', 409949382.0],
                      ['1992-12-31', 402540526.0],
                      ['1991-12-31', 395121495.0],
                      ['1990-12-31', 387713894.0],
                      ['1989-12-31', 380333859.0],
                      ['1988-12-31', 372981462.0],
                      ['1987-12-31', 365642644.0],
                      ['1986-12-31', 358294111.0],
                      ['1985-12-31', 350921427.0],
                      ['1984-12-31', 343523088.0],
                      ['1983-12-31', 336113781.0],
                      ['1982-12-31', 328714848.0],
                      ['1981-12-31', 321354880.0],
                      ['1980-12-31', 314056110.0],
                      ['1979-12-31', 306827996.0],
                      ['1978-12-31', 299670407.0],
                      ['1977-12-31', 292584153.0],
                      ['1976-12-31', 285566670.0],
                      ['1975-12-31', 278616831.0],
                      ['1974-12-31', 271738582.0],
                      ['1973-12-31', 264937350.0],
                      ['1972-12-31', 258215063.0],
                      ['1971-12-31', 251573313.0],
                      ['1970-12-31', 245013878.0],
                      ['1969-12-31', 238543508.0],
                      ['1968-12-31', 232165931.0],
                      ['1967-12-31', 225877250.0],
                      ['1966-12-31', 219670768.0],
                      ['1965-12-31', 213545018.0],
                      ['1964-12-31', 207496532.0],
                      ['1963-12-31', 201536793.0],
                      ['1962-12-31', 195697709.0],
                      ['1961-12-31', 190021046.0],
                      ['1960-12-31', 184536470.0],
                      ['1959-12-31', 200639440.0],
                      ['1958-12-31', 195185689.0],
                      ['1957-12-31', 189907529.0],
                      ['1956-12-31', 184781523.0],
                      ['1955-12-31', 179787658.0],
                      ['1954-12-31', 174912031.0],
                      ['1953-12-31', 170147964.0],
                      ['1952-12-31', 165496645.0],
                      ['1951-12-31', 160966632.0],
                      ['1950-12-31', 156573892.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'LAC_SP_POP_TOTL',
             'description': 'Population, total - Latin America & Caribbean '
                            '(developing only). ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22167335,
             'limit': None,
             'name': 'Population, total - Latin America & Caribbean '
                     '(developing only)',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:36:07.148Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
CLA
{'quandl_error': {'code': 'QECx02',
                  'message': 'You have submitted an incorrect Quandl code. '
                             'Please check your Quandl codes and try again.'}}
LVA

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 1940740.0],
                      ['2016-12-31', 1959537.0],
                      ['2015-12-31', 1977527.0],
                      ['2014-12-31', 1993782.0],
                      ['2013-12-31', 2012647.0],
                      ['2012-12-31', 2034319.0],
                      ['2011-12-31', 2059709.0],
                      ['2010-12-31', 2097555.0],
                      ['2009-12-31', 2141669.0],
                      ['2008-12-31', 2177322.0],
                      ['2007-12-31', 2200325.0],
                      ['2006-12-31', 2218357.0],
                      ['2005-12-31', 2238799.0],
                      ['2004-12-31', 2263122.0],
                      ['2003-12-31', 2287955.0],
                      ['2002-12-31', 2310173.0],
                      ['2001-12-31', 2337170.0],
                      ['2000-12-31', 2367550.0],
                      ['1999-12-31', 2390482.0],
                      ['1998-12-31', 2410019.0],
                      ['1997-12-31', 2432851.0],
                      ['1996-12-31', 2457222.0],
                      ['1995-12-31', 2485056.0],
                      ['1994-12-31', 2520742.0],
                      ['1993-12-31', 2563290.0],
                      ['1992-12-31', 2614338.0],
                      ['1991-12-31', 2650581.0],
                      ['1990-12-31', 2663151.0],
                      ['1989-12-31', 2666955.0],
                      ['1988-12-31', 2653434.0],
                      ['1987-12-31', 2626583.0],
                      ['1986-12-31', 2599892.0],
                      ['1985-12-31', 2578873.0],
                      ['1984-12-31', 2562047.0],
                      ['1983-12-31', 2546011.0],
                      ['1982-12-31', 2531080.0],
                      ['1981-12-31', 2519421.0],
                      ['1980-12-31', 2511701.0],
                      ['1979-12-31', 2505953.0],
                      ['1978-12-31', 2497921.0],
                      ['1977-12-31', 2485073.0],
                      ['1976-12-31', 2470989.0],
                      ['1975-12-31', 2456130.0],
                      ['1974-12-31', 2437186.0],
                      ['1973-12-31', 2415819.0],
                      ['1972-12-31', 2395674.0],
                      ['1971-12-31', 2376389.0],
                      ['1970-12-31', 2359164.0],
                      ['1969-12-31', 2343173.0],
                      ['1968-12-31', 2323619.0],
                      ['1967-12-31', 2301220.0],
                      ['1966-12-31', 2283217.0],
                      ['1965-12-31', 2265919.0],
                      ['1964-12-31', 2240623.0],
                      ['1963-12-31', 2210919.0],
                      ['1962-12-31', 2181586.0],
                      ['1961-12-31', 2152681.0],
                      ['1960-12-31', 2120979.0],
                      ['1959-12-31', 2106392.0],
                      ['1958-12-31', 2081785.0],
                      ['1957-12-31', 2058224.0],
                      ['1956-12-31', 2035877.0],
                      ['1955-12-31', 2014992.0],
                      ['1954-12-31', 1995922.0],
                      ['1953-12-31', 1979138.0],
                      ['1952-12-31', 1965231.0],
                      ['1951-12-31', 1954910.0],
                      ['1950-12-31', 1949000.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'LVA_SP_POP_TOTL',
             'description': 'Population, total - Latvia. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22192188,
             'limit': None,
             'name': 'Population, total - Latvia',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:37:29.983Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
LDC
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 1002485957.0],
                      ['2016-12-31', 979387925.0],
                      ['2015-12-31', 956631108.0],
                      ['2014-12-31', 934192321.0],
                      ['2013-12-31', 912093996.0],
                      ['2012-12-31', 890423474.0],
                      ['2011-12-31', 869298106.0],
                      ['2010-12-31', 848791962.0],
                      ['2009-12-31', 828953320.0],
                      ['2008-12-31', 809730997.0],
                      ['2007-12-31', 790978141.0],
                      ['2006-12-31', 772488966.0],
                      ['2005-12-31', 754118072.0],
                      ['2004-12-31', 735796583.0],
                      ['2003-12-31', 717572892.0],
                      ['2002-12-31', 699560739.0],
                      ['2001-12-31', 681932226.0],
                      ['2000-12-31', 664804763.0],
                      ['1999-12-31', 648229112.0],
                      ['1998-12-31', 632146821.0],
                      ['1997-12-31', 616437048.0],
                      ['1996-12-31', 600926162.0],
                      ['1995-12-31', 585496175.0],
                      ['1994-12-31', 570101958.0],
                      ['1993-12-31', 554804181.0],
                      ['1992-12-31', 539720450.0],
                      ['1991-12-31', 525020368.0],
                      ['1990-12-31', 510827576.0],
                      ['1989-12-31', 497176877.0],
                      ['1988-12-31', 484033065.0],
                      ['1987-12-31', 471364938.0],
                      ['1986-12-31', 459115735.0],
                      ['1985-12-31', 447240981.0],
                      ['1984-12-31', 435737690.0],
                      ['1983-12-31', 424613917.0],
                      ['1982-12-31', 413846599.0],
                      ['1981-12-31', 403408681.0],
                      ['1980-12-31', 393279303.0],
                      ['1979-12-31', 383429856.0],
                      ['1978-12-31', 373854416.0],
                      ['1977-12-31', 364581154.0],
                      ['1976-12-31', 355653610.0],
                      ['1975-12-31', 347093126.0],
                      ['1974-12-31', 338920295.0],
                      ['1973-12-31', 331095229.0],
                      ['1972-12-31', 323506502.0],
                      ['1971-12-31', 316004632.0],
                      ['1970-12-31', 308486373.0],
                      ['1969-12-31', 300902584.0],
                      ['1968-12-31', 293292818.0],
                      ['1967-12-31', 285751541.0],
                      ['1966-12-31', 278419926.0],
                      ['1965-12-31', 271400502.0],
                      ['1964-12-31', 264721836.0],
                      ['1963-12-31', 258352723.0],
                      ['1962-12-31', 252264341.0],
                      ['1961-12-31', 246406470.0],
                      ['1960-12-31', 240742196.0],
                      ['1959-12-31', 235259472.0],
                      ['1958-12-31', 229967077.0],
                      ['1957-12-31', 224884923.0],
                      ['1956-12-31', 220033004.0],
                      ['1955-12-31', 215421063.0],
                      ['1954-12-31', 211045058.0],
                      ['1953-12-31', 206885020.0],
                      ['1952-12-31', 202904860.0],
                      ['1951-12-31', 199052136.0],
                      ['1950-12-31', 195259056.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'LDC_SP_POP_TOTL',
             'description': 'Population, total - Least developed countries; UN '
                            'classification. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22178893,
             'limit': None,
             'name': 'Population, total - Least developed countries; UN '
                     'classification',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:36:44.151Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
LBN

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 6082357.0],
                      ['2016-12-31', 6006668.0],
                      ['2015-12-31', 5851479.0],
                      ['2014-12-31', 5603279.0],
                      ['2013-12-31', 5276102.0],
                      ['2012-12-31', 4916404.0],
                      ['2011-12-31', 4588368.0],
                      ['2010-12-31', 4337141.0],
                      ['2009-12-31', 4183156.0],
                      ['2008-12-31', 4111047.0],
                      ['2007-12-31', 4086466.0],
                      ['2006-12-31', 4057350.0],
                      ['2005-12-31', 3986852.0],
                      ['2004-12-31', 3863267.0],
                      ['2003-12-31', 3701464.0],
                      ['2002-12-31', 3522837.0],
                      ['2001-12-31', 3359859.0],
                      ['2000-12-31', 3235366.0],
                      ['1999-12-31', 3156646.0],
                      ['1998-12-31', 3113951.0],
                      ['1997-12-31', 3092670.0],
                      ['1996-12-31', 3070960.0],
                      ['1995-12-31', 3033394.0],
                      ['1994-12-31', 2974640.0],
                      ['1993-12-31', 2900854.0],
                      ['1992-12-31', 2821862.0],
                      ['1991-12-31', 2752462.0],
                      ['1990-12-31', 2703016.0],
                      ['1989-12-31', 2676605.0],
                      ['1988-12-31', 2668585.0],
                      ['1987-12-31', 2672173.0],
                      ['1986-12-31', 2677280.0],
                      ['1985-12-31', 2676583.0],
                      ['1984-12-31', 2667220.0],
                      ['1983-12-31', 2651292.0],
                      ['1982-12-31', 2632276.0],
                      ['1981-12-31', 2615747.0],
                      ['1980-12-31', 2605293.0],
                      ['1979-12-31', 2602566.0],
                      ['1978-12-31', 2604865.0],
                      ['1977-12-31', 2606221.0],
                      ['1976-12-31', 2598354.0],
                      ['1975-12-31', 2575690.0],
                      ['1974-12-31', 2535497.0],
                      ['1973-12-31', 2480419.0],
                      ['1972-12-31', 2416735.0],
                      ['1971-12-31', 2353555.0],
                      ['1970-12-31', 2297389.0],
                      ['1969-12-31', 2250602.0],
                      ['1968-12-31', 2210959.0],
                      ['1967-12-31', 2174845.0],
                      ['1966-12-31', 2136636.0],
                      ['1965-12-31', 2092348.0],
                      ['1964-12-31', 2041207.0],
                      ['1963-12-31', 1984980.0],
                      ['1962-12-31', 1925276.0],
                      ['1961-12-31', 1864605.0],
                      ['1960-12-31', 1804926.0],
                      ['1959-12-31', 1747162.0],
                      ['1958-12-31', 1691361.0],
                      ['1957-12-31', 1637127.0],
                      ['1956-12-31', 1584030.0],
                      ['1955-12-31', 1532109.0],
                      ['1954-12-31', 1481959.0],
                      ['1953-12-31', 1434849.0],
                      ['1952-12-31', 1392725.0],
                      ['1951-12-31', 1358217.0],
                      ['1950-12-31', 1334621.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'LBN_SP_POP_TOTL',
             'description': 'Population, total - Lebanon. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22171303,
             'limit': None,
             'name': 'Population, total - Lebanon',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:36:18.566Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
LSO
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 2233339.0],
                      ['2016-12-31', 2203821.0],
                      ['2015-12-31', 2174645.0],
                      ['2014-12-31', 2145785.0],
                      ['2013-12-31', 2117361.0],
                      ['2012-12-31', 2089928.0],
                      ['2011-12-31', 2064166.0],
                      ['2010-12-31', 2040551.0],
                      ['2009-12-31', 2019209.0],
                      ['2008-12-31', 1999930.0],
                      ['2007-12-31', 1982287.0],
                      ['2006-12-31', 1965662.0],
                      ['2005-12-31', 1949543.0],
                      ['2004-12-31', 1933728.0],
                      ['2003-12-31', 1918097.0],
                      ['2002-12-31', 1902312.0],
                      ['2001-12-31', 1885955.0],
                      ['2000-12-31', 1868699.0],
                      ['1999-12-31', 1850527.0],
                      ['1998-12-31', 1831298.0],
                      ['1997-12-31', 1810453.0],
                      ['1996-12-31', 1787273.0],
                      ['1995-12-31', 1761359.0],
                      ['1994-12-31', 1732257.0],
                      ['1993-12-31', 1700362.0],
                      ['1992-12-31', 1667121.0],
                      ['1991-12-31', 1634517.0],
                      ['1990-12-31', 1603938.0],
                      ['1989-12-31', 1576022.0],
                      ['1988-12-31', 1550262.0],
                      ['1987-12-31', 1525460.0],
                      ['1986-12-31', 1499861.0],
                      ['1985-12-31', 1472192.0],
                      ['1984-12-31', 1442212.0],
                      ['1983-12-31', 1410439.0],
                      ['1982-12-31', 1377346.0],
                      ['1981-12-31', 1343690.0],
                      ['1980-12-31', 1310118.0],
                      ['1979-12-31', 1276663.0],
                      ['1978-12-31', 1243352.0],
                      ['1977-12-31', 1210799.0],
                      ['1976-12-31', 1179723.0],
                      ['1975-12-31', 1150635.0],
                      ['1974-12-31', 1123855.0],
                      ['1973-12-31', 1099235.0],
                      ['1972-12-31', 1076340.0],
                      ['1971-12-31', 1054453.0],
                      ['1970-12-31', 1033050.0],
                      ['1969-12-31', 1012015.0],
                      ['1968-12-31', 991491.0],
                      ['1967-12-31', 971512.0],
                      ['1966-12-31', 952206.0],
                      ['1965-12-31', 933655.0],
                      ['1964-12-31', 915822.0],
                      ['1963-12-31', 898647.0],
                      ['1962-12-31', 882170.0],
                      ['1961-12-31', 866462.0],
                      ['1960-12-31', 851591.0],
                      ['1959-12-31', 837519.0],
                      ['1958-12-31', 824200.0],
                      ['1957-12-31', 811543.0],
                      ['1956-12-31', 799440.0],
                      ['1955-12-31', 787806.0],
                      ['1954-12-31', 776548.0],
                      ['1953-12-31', 765581.0],
                      ['1952-12-31', 754853.0],
                      ['1951-12-31', 744319.0],
                      ['1950-12-31', 733945.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'LSO_SP_POP_TOTL',
             'description': 'Population, total - Lesotho. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22186913,
             'limit': None,
             'name': 'Population, total - Lesotho',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:37:13.502Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
LBR

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 4731906.0],
                      ['2016-12-31', 4613823.0],
                      ['2015-12-31', 4499621.0],
                      ['2014-12-31', 4390737.0],
                      ['2013-12-31', 4286291.0],
                      ['2012-12-31', 4181563.0],
                      ['2011-12-31', 4070167.0],
                      ['2010-12-31', 3948125.0],
                      ['2009-12-31', 3811528.0],
                      ['2008-12-31', 3662993.0],
                      ['2007-12-31', 3512932.0],
                      ['2006-12-31', 3375838.0],
                      ['2005-12-31', 3261230.0],
                      ['2004-12-31', 3176414.0],
                      ['2003-12-31', 3116233.0],
                      ['2002-12-31', 3062863.0],
                      ['2001-12-31', 2991132.0],
                      ['2000-12-31', 2884522.0],
                      ['1999-12-31', 2734518.0],
                      ['1998-12-31', 2551062.0],
                      ['1997-12-31', 2358469.0],
                      ['1996-12-31', 2191179.0],
                      ['1995-12-31', 2073482.0],
                      ['1994-12-31', 2012885.0],
                      ['1993-12-31', 2000248.0],
                      ['1992-12-31', 2022729.0],
                      ['1991-12-31', 2060267.0],
                      ['1990-12-31', 2097232.0],
                      ['1989-12-31', 2131525.0],
                      ['1988-12-31', 2165090.0],
                      ['1987-12-31', 2191023.0],
                      ['1986-12-31', 2201833.0],
                      ['1985-12-31', 2192555.0],
                      ['1984-12-31', 2159089.0],
                      ['1983-12-31', 2102911.0],
                      ['1982-12-31', 2031850.0],
                      ['1981-12-31', 1957456.0],
                      ['1980-12-31', 1888314.0],
                      ['1979-12-31', 1826881.0],
                      ['1978-12-31', 1771256.0],
                      ['1977-12-31', 1720489.0],
                      ['1976-12-31', 1672300.0],
                      ['1975-12-31', 1625013.0],
                      ['1974-12-31', 1578952.0],
                      ['1973-12-31', 1535229.0],
                      ['1972-12-31', 1493711.0],
                      ['1971-12-31', 1454198.0],
                      ['1970-12-31', 1416529.0],
                      ['1969-12-31', 1380637.0],
                      ['1968-12-31', 1346491.0],
                      ['1967-12-31', 1313941.0],
                      ['1966-12-31', 1282814.0],
                      ['1965-12-31', 1252972.0],
                      ['1964-12-31', 1224344.0],
                      ['1963-12-31', 1196890.0],
                      ['1962-12-31', 1170480.0],
                      ['1961-12-31', 1144986.0],
                      ['1960-12-31', 1120313.0],
                      ['1959-12-31', 1096442.0],
                      ['1958-12-31', 1073392.0],
                      ['1957-12-31', 1051250.0],
                      ['1956-12-31', 1030109.0],
                      ['1955-12-31', 1010067.0],
                      ['1954-12-31', 991230.0],
                      ['1953-12-31', 973699.0],
                      ['1952-12-31', 957595.0],
                      ['1951-12-31', 942999.0],
                      ['1950-12-31', 930025.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'LBR_SP_POP_TOTL',
             'description': 'Population, total - Liberia. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22173005,
             'limit': None,
             'name': 'Population, total - Liberia',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:36:24.758Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
LBY
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 6374616.0],
                      ['2016-12-31', 6293253.0],
                      ['2015-12-31', 6234955.0],
                      ['2014-12-31', 6204108.0],
                      ['2013-12-31', 6195970.0],
                      ['2012-12-31', 6198258.0],
                      ['2011-12-31', 6193501.0],
                      ['2010-12-31', 6169140.0],
                      ['2009-12-31', 6121053.0],
                      ['2008-12-31', 6053078.0],
                      ['2007-12-31', 5970362.0],
                      ['2006-12-31', 5881435.0],
                      ['2005-12-31', 5792688.0],
                      ['2004-12-31', 5704759.0],
                      ['2003-12-31', 5615952.0],
                      ['2002-12-31', 5527515.0],
                      ['2001-12-31', 5440566.0],
                      ['2000-12-31', 5355751.0],
                      ['1999-12-31', 5274163.0],
                      ['1998-12-31', 5195502.0],
                      ['1997-12-31', 5117269.0],
                      ['1996-12-31', 5035884.0],
                      ['1995-12-31', 4948798.0],
                      ['1994-12-31', 4855003.0],
                      ['1993-12-31', 4755289.0],
                      ['1992-12-31', 4651004.0],
                      ['1991-12-31', 4544293.0],
                      ['1990-12-31', 4436661.0],
                      ['1989-12-31', 4328914.0],
                      ['1988-12-31', 4220418.0],
                      ['1987-12-31', 4109703.0],
                      ['1986-12-31', 3994591.0],
                      ['1985-12-31', 3873781.0],
                      ['1984-12-31', 3746715.0],
                      ['1983-12-31', 3614689.0],
                      ['1982-12-31', 3480454.0],
                      ['1981-12-31', 3347781.0],
                      ['1980-12-31', 3219466.0],
                      ['1979-12-31', 3096729.0],
                      ['1978-12-31', 2979093.0],
                      ['1977-12-31', 2865637.0],
                      ['1976-12-31', 2754696.0],
                      ['1975-12-31', 2645139.0],
                      ['1974-12-31', 2536888.0],
                      ['1973-12-31', 2430755.0],
                      ['1972-12-31', 2327490.0],
                      ['1971-12-31', 2228146.0],
                      ['1970-12-31', 2133526.0],
                      ['1969-12-31', 2043818.0],
                      ['1968-12-31', 1958914.0],
                      ['1967-12-31', 1878877.0],
                      ['1966-12-31', 1803683.0],
                      ['1965-12-31', 1733306.0],
                      ['1964-12-31', 1667825.0],
                      ['1963-12-31', 1607171.0],
                      ['1962-12-31', 1550813.0],
                      ['1961-12-31', 1498071.0],
                      ['1960-12-31', 1448417.0],
                      ['1959-12-31', 1401620.0],
                      ['1958-12-31', 1357732.0],
                      ['1957-12-31', 1316911.0],
                      ['1956-12-31', 1279406.0],
                      ['1955-12-31', 1245358.0],
                      ['1954-12-31', 1214827.0],
                      ['1953-12-31', 1187734.0],
                      ['1952-12-31', 1163891.0],
                      ['1951-12-31', 1142972.0],
                      ['1950-12-31', 1124515.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'LBY_SP_POP_TOTL',
             'description': 'Population, total - Libya. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22174465,
             'limit': None,
             'name': 'Population, total - Libya',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:36:30.083Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
LIE

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 37922.0],
                      ['2016-12-31', 37666.0],
                      ['2015-12-31', 37403.0],
                      ['2014-12-31', 37127.0],
                      ['2013-12-31', 36834.0],
                      ['2012-12-31', 36545.0],
                      ['2011-12-31', 36264.0],
                      ['2010-12-31', 36003.0],
                      ['2009-12-31', 35766.0],
                      ['2008-12-31', 35541.0],
                      ['2007-12-31', 35322.0],
                      ['2006-12-31', 35095.0],
                      ['2005-12-31', 34852.0],
                      ['2004-12-31', 34596.0],
                      ['2003-12-31', 34321.0],
                      ['2002-12-31', 34018.0],
                      ['2001-12-31', 33671.0],
                      ['2000-12-31', 33286.0],
                      ['1999-12-31', 32842.0],
                      ['1998-12-31', 32355.0],
                      ['1997-12-31', 31838.0],
                      ['1996-12-31', 31325.0],
                      ['1995-12-31', 30833.0],
                      ['1994-12-31', 30365.0],
                      ['1993-12-31', 29919.0],
                      ['1992-12-31', 29497.0],
                      ['1991-12-31', 29108.0],
                      ['1990-12-31', 28747.0],
                      ['1989-12-31', 28407.0],
                      ['1988-12-31', 28095.0],
                      ['1987-12-31', 27802.0],
                      ['1986-12-31', 27524.0],
                      ['1985-12-31', 27257.0],
                      ['1984-12-31', 27011.0],
                      ['1983-12-31', 26765.0],
                      ['1982-12-31', 26515.0],
                      ['1981-12-31', 26224.0],
                      ['1980-12-31', 25866.0],
                      ['1979-12-31', 25447.0],
                      ['1978-12-31', 24962.0],
                      ['1977-12-31', 24440.0],
                      ['1976-12-31', 23926.0],
                      ['1975-12-31', 23432.0],
                      ['1974-12-31', 22981.0],
                      ['1973-12-31', 22563.0],
                      ['1972-12-31', 22151.0],
                      ['1971-12-31', 21726.0],
                      ['1970-12-31', 21265.0],
                      ['1969-12-31', 20765.0],
                      ['1968-12-31', 20236.0],
                      ['1967-12-31', 19691.0],
                      ['1966-12-31', 19153.0],
                      ['1965-12-31', 18649.0],
                      ['1964-12-31', 18170.0],
                      ['1963-12-31', 17718.0],
                      ['1962-12-31', 17290.0],
                      ['1961-12-31', 16894.0],
                      ['1960-12-31', 16495.0],
                      ['1959-12-31', 16126.0],
                      ['1958-12-31', 15767.0],
                      ['1957-12-31', 15431.0],
                      ['1956-12-31', 15112.0],
                      ['1955-12-31', 14831.0],
                      ['1954-12-31', 14568.0],
                      ['1953-12-31', 14338.0],
                      ['1952-12-31', 14128.0],
                      ['1951-12-31', 13942.0],
                      ['1950-12-31', 13758.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'LIE_SP_POP_TOTL',
             'description': 'Population, total - Liechtenstein. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22180904,
             'limit': None,
             'name': 'Population, total - Liechtenstein',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:36:50.726Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
LTU
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 2827721.0],
                      ['2016-12-31', 2868231.0],
                      ['2015-12-31', 2904910.0],
                      ['2014-12-31', 2932367.0],
                      ['2013-12-31', 2957689.0],
                      ['2012-12-31', 2987773.0],
                      ['2011-12-31', 3028115.0],
                      ['2010-12-31', 3097282.0],
                      ['2009-12-31', 3162916.0],
                      ['2008-12-31', 3198231.0],
                      ['2007-12-31', 3231294.0],
                      ['2006-12-31', 3269909.0],
                      ['2005-12-31', 3322528.0],
                      ['2004-12-31', 3377075.0],
                      ['2003-12-31', 3415213.0],
                      ['2002-12-31', 3443067.0],
                      ['2001-12-31', 3470818.0],
                      ['2000-12-31', 3499536.0],
                      ['1999-12-31', 3524238.0],
                      ['1998-12-31', 3549331.0],
                      ['1997-12-31', 3575137.0],
                      ['1996-12-31', 3601613.0],
                      ['1995-12-31', 3629102.0],
                      ['1994-12-31', 3657144.0],
                      ['1993-12-31', 3682613.0],
                      ['1992-12-31', 3700114.0],
                      ['1991-12-31', 3704134.0],
                      ['1990-12-31', 3697838.0],
                      ['1989-12-31', 3684255.0],
                      ['1988-12-31', 3655049.0],
                      ['1987-12-31', 3616367.0],
                      ['1986-12-31', 3578914.0],
                      ['1985-12-31', 3544543.0],
                      ['1984-12-31', 3514205.0],
                      ['1983-12-31', 3485192.0],
                      ['1982-12-31', 3457179.0],
                      ['1981-12-31', 3432947.0],
                      ['1980-12-31', 3413202.0],
                      ['1979-12-31', 3397842.0],
                      ['1978-12-31', 3379514.0],
                      ['1977-12-31', 3355036.0],
                      ['1976-12-31', 3328664.0],
                      ['1975-12-31', 3301652.0],
                      ['1974-12-31', 3273894.0],
                      ['1973-12-31', 3244438.0],
                      ['1972-12-31', 3213622.0],
                      ['1971-12-31', 3179041.0],
                      ['1970-12-31', 3139689.0],
                      ['1969-12-31', 3107321.0],
                      ['1968-12-31', 3078850.0],
                      ['1967-12-31', 3044400.0],
                      ['1966-12-31', 3008050.0],
                      ['1965-12-31', 2971450.0],
                      ['1964-12-31', 2935200.0],
                      ['1963-12-31', 2898950.0],
                      ['1962-12-31', 2863350.0],
                      ['1961-12-31', 2823550.0],
                      ['1960-12-31', 2778550.0],
                      ['1959-12-31', 2735814.0],
                      ['1958-12-31', 2704918.0],
                      ['1957-12-31', 2676930.0],
                      ['1956-12-31', 2651564.0],
                      ['1955-12-31', 2628706.0],
                      ['1954-12-31', 2608493.0],
                      ['1953-12-31', 2591358.0],
                      ['1952-12-31', 2578052.0],
                      ['1951-12-31', 2569619.0],
                      ['1950-12-31', 2567402.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'LTU_SP_POP_TOTL',
             'description': 'Population, total - Lithuania. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22188739,
             'limit': None,
             'name': 'Population, total - Lithuania',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:37:19.230Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
LMY
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 6281293921.0],
                      ['2016-12-31', 6202019744.0],
                      ['2015-12-31', 6122845409.0],
                      ['2014-12-31', 6044110924.0],
                      ['2013-12-31', 5965580605.0],
                      ['2012-12-31', 5887499549.0],
                      ['2011-12-31', 5810352625.0],
                      ['2010-12-31', 5734082511.0],
                      ['2009-12-31', 5658778430.0],
                      ['2008-12-31', 5584333697.0],
                      ['2007-12-31', 5511067338.0],
                      ['2006-12-31', 5438568259.0],
                      ['2005-12-31', 5366142729.0],
                      ['2004-12-31', 5293853508.0],
                      ['2003-12-31', 5221946114.0],
                      ['2002-12-31', 5150230538.0],
                      ['2001-12-31', 5078705169.0],
                      ['2000-12-31', 5006672528.0],
                      ['1999-12-31', 4933815918.0],
                      ['1998-12-31', 4860402272.0],
                      ['1997-12-31', 4785830332.0],
                      ['1996-12-31', 4710560456.0],
                      ['1995-12-31', 4635235786.0],
                      ['1994-12-31', 4559643731.0],
                      ['1993-12-31', 4483624608.0],
                      ['1992-12-31', 4407097054.0],
                      ['1991-12-31', 4329689211.0],
                      ['1990-12-31', 4250768747.0],
                      ['1989-12-31', 4168715794.0],
                      ['1988-12-31', 4087603622.0],
                      ['1987-12-31', 4006194718.0],
                      ['1986-12-31', 3925562597.0],
                      ['1985-12-31', 3847060142.0],
                      ['1984-12-31', 3770747360.0],
                      ['1983-12-31', 3695912147.0],
                      ['1982-12-31', 3621125345.0],
                      ['1981-12-31', 3547464632.0],
                      ['1980-12-31', 3477109502.0],
                      ['1979-12-31', 3408720998.0],
                      ['1978-12-31', 3341275682.0],
                      ['1977-12-31', 3275314891.0],
                      ['1976-12-31', 3210476025.0],
                      ['1975-12-31', 3145167184.0],
                      ['1974-12-31', 3079360312.0],
                      ['1973-12-31', 3012331276.0],
                      ['1972-12-31', 2944882224.0],
                      ['1971-12-31', 2877389252.0],
                      ['1970-12-31', 2808966620.0],
                      ['1969-12-31', 2741954619.0],
                      ['1968-12-31', 2676648622.0],
                      ['1967-12-31', 2613784631.0],
                      ['1966-12-31', 2552655971.0],
                      ['1965-12-31', 2491585633.0],
                      ['1964-12-31', 2434305162.0],
                      ['1963-12-31', 2378831151.0],
                      ['1962-12-31', 2323867572.0],
                      ['1961-12-31', 2281121660.0],
                      ['1960-12-31', 2251658472.0],
                      ['1959-12-31', 2229606433.0],
                      ['1958-12-31', 2183035977.0],
                      ['1957-12-31', 2137874046.0],
                      ['1956-12-31', 2094118825.0],
                      ['1955-12-31', 2051774238.0],
                      ['1954-12-31', 2008906136.0],
                      ['1953-12-31', 1967547566.0],
                      ['1952-12-31', 1927787885.0],
                      ['1951-12-31', 1889696510.0],
                      ['1950-12-31', 1853338222.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'LMY_SP_POP_TOTL',
             'description': 'Population, total - Low & middle income. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22185225,
             'limit': None,
             'name': 'Population, total - Low & middle income',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:37:07.114Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
LIC

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 732448558.0],
                      ['2016-12-31', 714022293.0],
                      ['2015-12-31', 696058453.0],
                      ['2014-12-31', 678572076.0],
                      ['2013-12-31', 661550623.0],
                      ['2012-12-31', 644901894.0],
                      ['2011-12-31', 628504663.0],
                      ['2010-12-31', 612274687.0],
                      ['2009-12-31', 596172925.0],
                      ['2008-12-31', 580229110.0],
                      ['2007-12-31', 564514253.0],
                      ['2006-12-31', 549135479.0],
                      ['2005-12-31', 534172627.0],
                      ['2004-12-31', 519630935.0],
                      ['2003-12-31', 505488618.0],
                      ['2002-12-31', 491764952.0],
                      ['2001-12-31', 478477973.0],
                      ['2000-12-31', 465631330.0],
                      ['1999-12-31', 453254723.0],
                      ['1998-12-31', 441325367.0],
                      ['1997-12-31', 429730581.0],
                      ['1996-12-31', 418317960.0],
                      ['1995-12-31', 406983803.0],
                      ['1994-12-31', 395678396.0],
                      ['1993-12-31', 384447813.0],
                      ['1992-12-31', 373402947.0],
                      ['1991-12-31', 362705618.0],
                      ['1990-12-31', 352473181.0],
                      ['1989-12-31', 342729958.0],
                      ['1988-12-31', 333438165.0],
                      ['1987-12-31', 324577008.0],
                      ['1986-12-31', 316105719.0],
                      ['1985-12-31', 307987034.0],
                      ['1984-12-31', 300220347.0],
                      ['1983-12-31', 292795982.0],
                      ['1982-12-31', 285653497.0],
                      ['1981-12-31', 278716283.0],
                      ['1980-12-31', 271925904.0],
                      ['1979-12-31', 265253926.0],
                      ['1978-12-31', 258700456.0],
                      ['1977-12-31', 252271835.0],
                      ['1976-12-31', 245986989.0],
                      ['1975-12-31', 239859140.0],
                      ['1974-12-31', 233887209.0],
                      ['1973-12-31', 228060405.0],
                      ['1972-12-31', 222372305.0],
                      ['1971-12-31', 216814959.0],
                      ['1970-12-31', 211385069.0],
                      ['1969-12-31', 206074326.0],
                      ['1968-12-31', 200890086.0],
                      ['1967-12-31', 195863148.0],
                      ['1966-12-31', 191035377.0],
                      ['1965-12-31', 186434685.0],
                      ['1964-12-31', 182077594.0],
                      ['1963-12-31', 177950312.0],
                      ['1962-12-31', 174013498.0],
                      ['1961-12-31', 170210778.0],
                      ['1960-12-31', 166502848.0],
                      ['1959-12-31', 151341932.0],
                      ['1958-12-31', 148099273.0],
                      ['1957-12-31', 144972227.0],
                      ['1956-12-31', 141995133.0],
                      ['1955-12-31', 139196080.0],
                      ['1954-12-31', 136593546.0],
                      ['1953-12-31', 134194006.0],
                      ['1952-12-31', 131991799.0],
                      ['1951-12-31', 129969107.0],
                      ['1950-12-31', 128096648.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'LIC_SP_POP_TOTL',
             'description': 'Population, total - Low income. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22180322,
             'limit': None,
             'name': 'Population, total - Low income',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:36:48.550Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
LMC
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 2972642807.0],
                      ['2016-12-31', 2931075528.0],
                      ['2015-12-31', 2889349899.0],
                      ['2014-12-31', 2847559084.0],
                      ['2013-12-31', 2805845772.0],
                      ['2012-12-31', 2764105969.0],
                      ['2011-12-31', 2722672277.0],
                      ['2010-12-31', 2681264749.0],
                      ['2009-12-31', 2640211692.0],
                      ['2008-12-31', 2599821177.0],
                      ['2007-12-31', 2559728298.0],
                      ['2006-12-31', 2519781995.0],
                      ['2005-12-31', 2479864962.0],
                      ['2004-12-31', 2439908661.0],
                      ['2003-12-31', 2399909122.0],
                      ['2002-12-31', 2359924081.0],
                      ['2001-12-31', 2320035800.0],
                      ['2000-12-31', 2280235216.0],
                      ['1999-12-31', 2240561424.0],
                      ['1998-12-31', 2201139625.0],
                      ['1997-12-31', 2161549857.0],
                      ['1996-12-31', 2121803515.0],
                      ['1995-12-31', 2082090008.0],
                      ['1994-12-31', 2042431452.0],
                      ['1993-12-31', 2002605779.0],
                      ['1992-12-31', 1962374702.0],
                      ['1991-12-31', 1921978997.0],
                      ['1990-12-31', 1881674731.0],
                      ['1989-12-31', 1839450536.0],
                      ['1988-12-31', 1799200488.0],
                      ['1987-12-31', 1759107373.0],
                      ['1986-12-31', 1719270442.0],
                      ['1985-12-31', 1679742957.0],
                      ['1984-12-31', 1640549014.0],
                      ['1983-12-31', 1601718966.0],
                      ['1982-12-31', 1563490212.0],
                      ['1981-12-31', 1526127019.0],
                      ['1980-12-31', 1489702291.0],
                      ['1979-12-31', 1454422088.0],
                      ['1978-12-31', 1420226130.0],
                      ['1977-12-31', 1387056884.0],
                      ['1976-12-31', 1354785257.0],
                      ['1975-12-31', 1323320387.0],
                      ['1974-12-31', 1292662974.0],
                      ['1973-12-31', 1262818780.0],
                      ['1972-12-31', 1233747550.0],
                      ['1971-12-31', 1205371089.0],
                      ['1970-12-31', 1177647344.0],
                      ['1969-12-31', 1150552380.0],
                      ['1968-12-31', 1124070988.0],
                      ['1967-12-31', 1098201811.0],
                      ['1966-12-31', 1072942964.0],
                      ['1965-12-31', 1048295050.0],
                      ['1964-12-31', 1024253768.0],
                      ['1963-12-31', 1000820431.0],
                      ['1962-12-31', 978033376.0],
                      ['1961-12-31', 955943402.0],
                      ['1960-12-31', 934586665.0],
                      ['1959-12-31', 932307247.0],
                      ['1958-12-31', 911950177.0],
                      ['1957-12-31', 892381850.0],
                      ['1956-12-31', 873583580.0],
                      ['1955-12-31', 855542777.0],
                      ['1954-12-31', 838270265.0],
                      ['1953-12-31', 821773680.0],
                      ['1952-12-31', 806103714.0],
                      ['1951-12-31', 791282514.0],
                      ['1950-12-31', 777320949.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'LMC_SP_POP_TOTL',
             'description': 'Population, total - Lower middle income. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22183678,
             'limit': None,
             'name': 'Population, total - Lower middle income',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:37:01.835Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
LUX

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 599449.0],
                      ['2016-12-31', 582014.0],
                      ['2015-12-31', 569604.0],
                      ['2014-12-31', 556319.0],
                      ['2013-12-31', 543360.0],
                      ['2012-12-31', 530946.0],
                      ['2011-12-31', 518347.0],
                      ['2010-12-31', 506953.0],
                      ['2009-12-31', 497783.0],
                      ['2008-12-31', 488650.0],
                      ['2007-12-31', 479993.0],
                      ['2006-12-31', 472637.0],
                      ['2005-12-31', 465158.0],
                      ['2004-12-31', 458095.0],
                      ['2003-12-31', 451630.0],
                      ['2002-12-31', 446175.0],
                      ['2001-12-31', 441525.0],
                      ['2000-12-31', 436300.0],
                      ['1999-12-31', 430475.0],
                      ['1998-12-31', 424700.0],
                      ['1997-12-31', 419450.0],
                      ['1996-12-31', 414225.0],
                      ['1995-12-31', 408625.0],
                      ['1994-12-31', 402925.0],
                      ['1993-12-31', 397475.0],
                      ['1992-12-31', 392175.0],
                      ['1991-12-31', 387000.0],
                      ['1990-12-31', 381850.0],
                      ['1989-12-31', 377100.0],
                      ['1988-12-31', 373450.0],
                      ['1987-12-31', 370750.0],
                      ['1986-12-31', 368355.0],
                      ['1985-12-31', 366706.0],
                      ['1984-12-31', 365998.0],
                      ['1983-12-31', 365622.0],
                      ['1982-12-31', 365525.0],
                      ['1981-12-31', 365225.0],
                      ['1980-12-31', 364150.0],
                      ['1979-12-31', 362856.0],
                      ['1978-12-31', 362007.0],
                      ['1977-12-31', 361358.0],
                      ['1976-12-31', 360731.0],
                      ['1975-12-31', 358950.0],
                      ['1974-12-31', 355050.0],
                      ['1973-12-31', 350450.0],
                      ['1972-12-31', 346600.0],
                      ['1971-12-31', 342421.0],
                      ['1970-12-31', 339171.0],
                      ['1969-12-31', 337500.0],
                      ['1968-12-31', 335850.0],
                      ['1967-12-31', 334995.0],
                      ['1966-12-31', 333895.0],
                      ['1965-12-31', 331500.0],
                      ['1964-12-31', 327750.0],
                      ['1963-12-31', 324100.0],
                      ['1962-12-31', 320750.0],
                      ['1961-12-31', 316845.0],
                      ['1960-12-31', 313970.0],
                      ['1959-12-31', 311508.0],
                      ['1958-12-31', 309611.0],
                      ['1957-12-31', 308067.0],
                      ['1956-12-31', 306598.0],
                      ['1955-12-31', 305000.0],
                      ['1954-12-31', 303172.0],
                      ['1953-12-31', 301140.0],
                      ['1952-12-31', 299060.0],
                      ['1951-12-31', 297212.0],
                      ['1950-12-31', 296001.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'LUX_SP_POP_TOTL',
             'description': 'Population, total - Luxembourg. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22190410,
             'limit': None,
             'name': 'Population, total - Luxembourg',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:37:24.593Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
MAC
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 622567.0],
                      ['2016-12-31', 612167.0],
                      ['2015-12-31', 600942.0],
                      ['2014-12-31', 588781.0],
                      ['2013-12-31', 575841.0],
                      ['2012-12-31', 562531.0],
                      ['2011-12-31', 549439.0],
                      ['2010-12-31', 536969.0],
                      ['2009-12-31', 525313.0],
                      ['2008-12-31', 514348.0],
                      ['2007-12-31', 503823.0],
                      ['2006-12-31', 493320.0],
                      ['2005-12-31', 482559.0],
                      ['2004-12-31', 471453.0],
                      ['2003-12-31', 460147.0],
                      ['2002-12-31', 448896.0],
                      ['2001-12-31', 438081.0],
                      ['2000-12-31', 427979.0],
                      ['1999-12-31', 418604.0],
                      ['1998-12-31', 409837.0],
                      ['1997-12-31', 401564.0],
                      ['1996-12-31', 393567.0],
                      ['1995-12-31', 385686.0],
                      ['1994-12-31', 377960.0],
                      ['1993-12-31', 370345.0],
                      ['1992-12-31', 362459.0],
                      ['1991-12-31', 353764.0],
                      ['1990-12-31', 343935.0],
                      ['1989-12-31', 332901.0],
                      ['1988-12-31', 320877.0],
                      ['1987-12-31', 308275.0],
                      ['1986-12-31', 295677.0],
                      ['1985-12-31', 283581.0],
                      ['1984-12-31', 271993.0],
                      ['1983-12-31', 260997.0],
                      ['1982-12-31', 251219.0],
                      ['1981-12-31', 243427.0],
                      ['1980-12-31', 238118.0],
                      ['1979-12-31', 235479.0],
                      ['1978-12-31', 235198.0],
                      ['1977-12-31', 236695.0],
                      ['1976-12-31', 239085.0],
                      ['1975-12-31', 241628.0],
                      ['1974-12-31', 244284.0],
                      ['1973-12-31', 246947.0],
                      ['1972-12-31', 248767.0],
                      ['1971-12-31', 248739.0],
                      ['1970-12-31', 246195.0],
                      ['1969-12-31', 240842.0],
                      ['1968-12-31', 233004.0],
                      ['1967-12-31', 223420.0],
                      ['1966-12-31', 213196.0],
                      ['1965-12-31', 203231.0],
                      ['1964-12-31', 193563.0],
                      ['1963-12-31', 184250.0],
                      ['1962-12-31', 176188.0],
                      ['1961-12-31', 170465.0],
                      ['1960-12-31', 167796.0],
                      ['1959-12-31', 168289.0],
                      ['1958-12-31', 171523.0],
                      ['1957-12-31', 176753.0],
                      ['1956-12-31', 183047.0],
                      ['1955-12-31', 189461.0],
                      ['1954-12-31', 195132.0],
                      ['1953-12-31', 199292.0],
                      ['1952-12-31', 201274.0],
                      ['1951-12-31', 200490.0],
                      ['1950-12-31', 196483.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'MAC_SP_POP_TOTL',
             'description': 'Population, total - Macao SAR, China. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22193524,
             'limit': None,
             'name': 'Population, total - Macao SAR, China',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:37:34.630Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
MKD
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 2083160.0],
                      ['2016-12-31', 2081206.0],
                      ['2015-12-31', 2079308.0],
                      ['2014-12-31', 2077495.0],
                      ['2013-12-31', 2075739.0],
                      ['2012-12-31', 2074036.0],
                      ['2011-12-31', 2072383.0],
                      ['2010-12-31', 2070739.0],
                      ['2009-12-31', 2069093.0],
                      ['2008-12-31', 2067378.0],
                      ['2007-12-31', 2065458.0],
                      ['2006-12-31', 2063145.0],
                      ['2005-12-31', 2060272.0],
                      ['2004-12-31', 2057047.0],
                      ['2003-12-31', 2053426.0],
                      ['2002-12-31', 2048928.0],
                      ['2001-12-31', 2042842.0],
                      ['2000-12-31', 2034819.0],
                      ['1999-12-31', 2024394.0],
                      ['1998-12-31', 2012057.0],
                      ['1997-12-31', 1999599.0],
                      ['1996-12-31', 1989443.0],
                      ['1995-12-31', 1983252.0],
                      ['1994-12-31', 1981703.0],
                      ['1993-12-31', 1984028.0],
                      ['1992-12-31', 1988659.0],
                      ['1991-12-31', 1993302.0],
                      ['1990-12-31', 1996228.0],
                      ['1989-12-31', 1996870.0],
                      ['1988-12-31', 1995513.0],
                      ['1987-12-31', 1992274.0],
                      ['1986-12-31', 1987538.0],
                      ['1985-12-31', 1981534.0],
                      ['1984-12-31', 1974415.0],
                      ['1983-12-31', 1965895.0],
                      ['1982-12-31', 1955243.0],
                      ['1981-12-31', 1941530.0],
                      ['1980-12-31', 1924197.0],
                      ['1979-12-31', 1902719.0],
                      ['1978-12-31', 1877688.0],
                      ['1977-12-31', 1851069.0],
                      ['1976-12-31', 1825552.0],
                      ['1975-12-31', 1803010.0],
                      ['1974-12-31', 1784398.0],
                      ['1973-12-31', 1768992.0],
                      ['1972-12-31', 1754956.0],
                      ['1971-12-31', 1739521.0],
                      ['1970-12-31', 1720800.0],
                      ['1969-12-31', 1698143.0],
                      ['1968-12-31', 1672399.0],
                      ['1967-12-31', 1644943.0],
                      ['1966-12-31', 1617794.0],
                      ['1965-12-31', 1592432.0],
                      ['1964-12-31', 1569141.0],
                      ['1963-12-31', 1547450.0],
                      ['1962-12-31', 1527111.0],
                      ['1961-12-31', 1507654.0],
                      ['1960-12-31', 1488667.0],
                      ['1959-12-31', 1469843.0],
                      ['1958-12-31', 1451015.0],
                      ['1957-12-31', 1432019.0],
                      ['1956-12-31', 1412613.0],
                      ['1955-12-31', 1392449.0],
                      ['1954-12-31', 1370978.0],
                      ['1953-12-31', 1347463.0],
                      ['1952-12-31', 1320981.0],
                      ['1951-12-31', 1290408.0],
                      ['1950-12-31', 1254445.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'MKD_SP_POP_TOTL',
             'description': 'Population, total - Macedonia, FYR. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22208424,
             'limit': None,
             'name': 'Population, total - Macedonia, FYR',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:38:59.917Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
MDG

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 25570895.0],
                      ['2016-12-31', 24894551.0],
                      ['2015-12-31', 24234088.0],
                      ['2014-12-31', 23589801.0],
                      ['2013-12-31', 22961146.0],
                      ['2012-12-31', 22346573.0],
                      ['2011-12-31', 21743949.0],
                      ['2010-12-31', 21151640.0],
                      ['2009-12-31', 20569121.0],
                      ['2008-12-31', 19996469.0],
                      ['2007-12-31', 19433523.0],
                      ['2006-12-31', 18880268.0],
                      ['2005-12-31', 18336724.0],
                      ['2004-12-31', 17802997.0],
                      ['2003-12-31', 17279141.0],
                      ['2002-12-31', 16765117.0],
                      ['2001-12-31', 16260932.0],
                      ['2000-12-31', 15766806.0],
                      ['1999-12-31', 15282521.0],
                      ['1998-12-31', 14808791.0],
                      ['1997-12-31', 14347854.0],
                      ['1996-12-31', 13902688.0],
                      ['1995-12-31', 13475400.0],
                      ['1994-12-31', 13066543.0],
                      ['1993-12-31', 12675460.0],
                      ['1992-12-31', 12301336.0],
                      ['1991-12-31', 11942819.0],
                      ['1990-12-31', 11598633.0],
                      ['1989-12-31', 11268658.0],
                      ['1988-12-31', 10952395.0],
                      ['1987-12-31', 10647754.0],
                      ['1986-12-31', 10352120.0],
                      ['1985-12-31', 10063495.0],
                      ['1984-12-31', 9780872.0],
                      ['1983-12-31', 9504281.0],
                      ['1982-12-31', 9234129.0],
                      ['1981-12-31', 8971345.0],
                      ['1980-12-31', 8716553.0],
                      ['1979-12-31', 8469672.0],
                      ['1978-12-31', 8230218.0],
                      ['1977-12-31', 7998164.0],
                      ['1976-12-31', 7773449.0],
                      ['1975-12-31', 7556026.0],
                      ['1974-12-31', 7345780.0],
                      ['1973-12-31', 7142627.0],
                      ['1972-12-31', 6946620.0],
                      ['1971-12-31', 6757850.0],
                      ['1970-12-31', 6576305.0],
                      ['1969-12-31', 6401921.0],
                      ['1968-12-31', 6234465.0],
                      ['1967-12-31', 6073526.0],
                      ['1966-12-31', 5918595.0],
                      ['1965-12-31', 5769218.0],
                      ['1964-12-31', 5625164.0],
                      ['1963-12-31', 5486319.0],
                      ['1962-12-31', 5352503.0],
                      ['1961-12-31', 5223568.0],
                      ['1960-12-31', 5099373.0],
                      ['1959-12-31', 4979753.0],
                      ['1958-12-31', 4864524.0],
                      ['1957-12-31', 4753523.0],
                      ['1956-12-31', 4646576.0],
                      ['1955-12-31', 4543542.0],
                      ['1954-12-31', 4444288.0],
                      ['1953-12-31', 4348720.0],
                      ['1952-12-31', 4256770.0],
                      ['1951-12-31', 4168386.0],
                      ['1950-12-31', 4083554.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'MDG_SP_POP_TOTL',
             'description': 'Population, total - Madagascar. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22199180,
             'limit': None,
             'name': 'Population, total - Madagascar',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:37:56.223Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
MWI
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 18622104.0],
                      ['2016-12-31', 18091575.0],
                      ['2015-12-31', 17573607.0],
                      ['2014-12-31', 17068838.0],
                      ['2013-12-31', 16577147.0],
                      ['2012-12-31', 16097305.0],
                      ['2011-12-31', 15627618.0],
                      ['2010-12-31', 15167095.0],
                      ['2009-12-31', 14714602.0],
                      ['2008-12-31', 14271234.0],
                      ['2007-12-31', 13840969.0],
                      ['2006-12-31', 13429262.0],
                      ['2005-12-31', 13039711.0],
                      ['2004-12-31', 12676038.0],
                      ['2003-12-31', 12336687.0],
                      ['2002-12-31', 12013711.0],
                      ['2001-12-31', 11695863.0],
                      ['2000-12-31', 11376172.0],
                      ['1999-12-31', 11044356.0],
                      ['1998-12-31', 10704744.0],
                      ['1997-12-31', 10381862.0],
                      ['1996-12-31', 10109789.0],
                      ['1995-12-31', 9909088.0],
                      ['1994-12-31', 9796976.0],
                      ['1993-12-31', 9755857.0],
                      ['1992-12-31', 9729717.0],
                      ['1991-12-31', 9641153.0],
                      ['1990-12-31', 9437553.0],
                      ['1989-12-31', 9094671.0],
                      ['1988-12-31', 8636935.0],
                      ['1987-12-31', 8120093.0],
                      ['1986-12-31', 7625305.0],
                      ['1985-12-31', 7211105.0],
                      ['1984-12-31', 6895928.0],
                      ['1983-12-31', 6661358.0],
                      ['1982-12-31', 6484452.0],
                      ['1981-12-31', 6327569.0],
                      ['1980-12-31', 6163080.0],
                      ['1979-12-31', 5986332.0],
                      ['1978-12-31', 5806845.0],
                      ['1977-12-31', 5627533.0],
                      ['1976-12-31', 5454705.0],
                      ['1975-12-31', 5292808.0],
                      ['1974-12-31', 5141202.0],
                      ['1973-12-31', 4996940.0],
                      ['1972-12-31', 4859610.0],
                      ['1971-12-31', 4728703.0],
                      ['1970-12-31', 4603723.0],
                      ['1969-12-31', 4484439.0],
                      ['1968-12-31', 4370650.0],
                      ['1967-12-31', 4262005.0],
                      ['1966-12-31', 4158124.0],
                      ['1965-12-31', 4058673.0],
                      ['1964-12-31', 3963417.0],
                      ['1963-12-31', 3872118.0],
                      ['1962-12-31', 3784439.0],
                      ['1961-12-31', 3700023.0],
                      ['1960-12-31', 3618595.0],
                      ['1959-12-31', 3539970.0],
                      ['1958-12-31', 3464047.0],
                      ['1957-12-31', 3390797.0],
                      ['1956-12-31', 3320220.0],
                      ['1955-12-31', 3252332.0],
                      ['1954-12-31', 3187173.0],
                      ['1953-12-31', 3124734.0],
                      ['1952-12-31', 3065034.0],
                      ['1951-12-31', 3008067.0],
                      ['1950-12-31', 2953871.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'MWI_SP_POP_TOTL',
             'description': 'Population, total - Malawi. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22226166,
             'limit': None,
             'name': 'Population, total - Malawi',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:39:59.911Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
MYS

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 31624264.0],
                      ['2016-12-31', 31187265.0],
                      ['2015-12-31', 30723155.0],
                      ['2014-12-31', 30228017.0],
                      ['2013-12-31', 29706724.0],
                      ['2012-12-31', 29170456.0],
                      ['2011-12-31', 28635128.0],
                      ['2010-12-31', 28112289.0],
                      ['2009-12-31', 27605383.0],
                      ['2008-12-31', 27111069.0],
                      ['2007-12-31', 26625845.0],
                      ['2006-12-31', 26143566.0],
                      ['2005-12-31', 25659393.0],
                      ['2004-12-31', 25174109.0],
                      ['2003-12-31', 24688703.0],
                      ['2002-12-31', 24198811.0],
                      ['2001-12-31', 23698907.0],
                      ['2000-12-31', 23185608.0],
                      ['1999-12-31', 22656286.0],
                      ['1998-12-31', 22113464.0],
                      ['1997-12-31', 21565325.0],
                      ['1996-12-31', 21023321.0],
                      ['1995-12-31', 20495597.0],
                      ['1994-12-31', 19986894.0],
                      ['1993-12-31', 19494967.0],
                      ['1992-12-31', 19012724.0],
                      ['1991-12-31', 18529454.0],
                      ['1990-12-31', 18038321.0],
                      ['1989-12-31', 17535971.0],
                      ['1988-12-31', 17027588.0],
                      ['1987-12-31', 16525108.0],
                      ['1986-12-31', 16045047.0],
                      ['1985-12-31', 15598942.0],
                      ['1984-12-31', 15191625.0],
                      ['1983-12-31', 14818617.0],
                      ['1982-12-31', 14470633.0],
                      ['1981-12-31', 14133840.0],
                      ['1980-12-31', 13798125.0],
                      ['1979-12-31', 13460201.0],
                      ['1978-12-31', 13123069.0],
                      ['1977-12-31', 12790546.0],
                      ['1976-12-31', 12468893.0],
                      ['1975-12-31', 12162369.0],
                      ['1974-12-31', 11871233.0],
                      ['1973-12-31', 11592698.0],
                      ['1972-12-31', 11324251.0],
                      ['1971-12-31', 11062338.0],
                      ['1970-12-31', 10803978.0],
                      ['1969-12-31', 10549226.0],
                      ['1968-12-31', 10297801.0],
                      ['1967-12-31', 10046172.0],
                      ['1966-12-31', 9789982.0],
                      ['1965-12-31', 9526563.0],
                      ['1964-12-31', 9253963.0],
                      ['1963-12-31', 8974084.0],
                      ['1962-12-31', 8692815.0],
                      ['1961-12-31', 8418460.0],
                      ['1960-12-31', 8157106.0],
                      ['1959-12-31', 7911036.0],
                      ['1958-12-31', 7679270.0],
                      ['1957-12-31', 7458898.0],
                      ['1956-12-31', 7246538.0],
                      ['1955-12-31', 7039719.0],
                      ['1954-12-31', 6837358.0],
                      ['1953-12-31', 6640041.0],
                      ['1952-12-31', 6450083.0],
                      ['1951-12-31', 6271486.0],
                      ['1950-12-31', 6109915.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'MYS_SP_POP_TOTL',
             'description': 'Population, total - Malaysia. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22227943,
             'limit': None,
             'name': 'Population, total - Malaysia',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:40:05.970Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
MDV
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 436330.0],
                      ['2016-12-31', 427756.0],
                      ['2015-12-31', 418403.0],
                      ['2014-12-31', 408247.0],
                      ['2013-12-31', 397397.0],
                      ['2012-12-31', 386203.0],
                      ['2011-12-31', 375131.0],
                      ['2010-12-31', 364511.0],
                      ['2009-12-31', 354501.0],
                      ['2008-12-31', 345054.0],
                      ['2007-12-31', 336070.0],
                      ['2006-12-31', 327371.0],
                      ['2005-12-31', 318836.0],
                      ['2004-12-31', 310423.0],
                      ['2003-12-31', 302209.0],
                      ['2002-12-31', 294341.0],
                      ['2001-12-31', 287027.0],
                      ['2000-12-31', 280384.0],
                      ['1999-12-31', 274484.0],
                      ['1998-12-31', 269206.0],
                      ['1997-12-31', 264275.0],
                      ['1996-12-31', 259327.0],
                      ['1995-12-31', 254082.0],
                      ['1994-12-31', 248433.0],
                      ['1993-12-31', 242459.0],
                      ['1992-12-31', 236190.0],
                      ['1991-12-31', 229754.0],
                      ['1990-12-31', 223215.0],
                      ['1989-12-31', 216595.0],
                      ['1988-12-31', 209885.0],
                      ['1987-12-31', 203124.0],
                      ['1986-12-31', 196357.0],
                      ['1985-12-31', 189637.0],
                      ['1984-12-31', 182953.0],
                      ['1983-12-31', 176356.0],
                      ['1982-12-31', 169960.0],
                      ['1981-12-31', 163935.0],
                      ['1980-12-31', 158385.0],
                      ['1979-12-31', 153386.0],
                      ['1978-12-31', 148892.0],
                      ['1977-12-31', 144736.0],
                      ['1976-12-31', 140665.0],
                      ['1975-12-31', 136519.0],
                      ['1974-12-31', 132195.0],
                      ['1973-12-31', 127791.0],
                      ['1972-12-31', 123441.0],
                      ['1971-12-31', 119378.0],
                      ['1970-12-31', 115768.0],
                      ['1969-12-31', 112651.0],
                      ['1968-12-31', 109959.0],
                      ['1967-12-31', 107538.0],
                      ['1966-12-31', 105190.0],
                      ['1965-12-31', 102766.0],
                      ['1964-12-31', 100214.0],
                      ['1963-12-31', 97584.0],
                      ['1962-12-31', 94938.0],
                      ['1961-12-31', 92350.0],
                      ['1960-12-31', 89887.0],
                      ['1959-12-31', 87590.0],
                      ['1958-12-31', 85451.0],
                      ['1957-12-31', 83435.0],
                      ['1956-12-31', 81520.0],
                      ['1955-12-31', 79714.0],
                      ['1954-12-31', 78016.0],
                      ['1953-12-31', 76486.0],
                      ['1952-12-31', 75194.0],
                      ['1951-12-31', 74223.0],
                      ['1950-12-31', 73714.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'MDV_SP_POP_TOTL',
             'description': 'Population, total - Maldives. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22200487,
             'limit': None,
             'name': 'Population, total - Maldives',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:38:01.992Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
MLI

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 18541980.0],
                      ['2016-12-31', 17994837.0],
                      ['2015-12-31', 17467905.0],
                      ['2014-12-31', 16962846.0],
                      ['2013-12-31', 16477818.0],
                      ['2012-12-31', 16006670.0],
                      ['2011-12-31', 15540989.0],
                      ['2010-12-31', 15075085.0],
                      ['2009-12-31', 14606597.0],
                      ['2008-12-31', 14138216.0],
                      ['2007-12-31', 13675606.0],
                      ['2006-12-31', 13227064.0],
                      ['2005-12-31', 12798763.0],
                      ['2004-12-31', 12391906.0],
                      ['2003-12-31', 12005128.0],
                      ['2002-12-31', 11638929.0],
                      ['2001-12-31', 11293258.0],
                      ['2000-12-31', 10967690.0],
                      ['1999-12-31', 10663723.0],
                      ['1998-12-31', 10380835.0],
                      ['1997-12-31', 10114094.0],
                      ['1996-12-31', 9856810.0],
                      ['1995-12-31', 9604450.0],
                      ['1994-12-31', 9353385.0],
                      ['1993-12-31', 9105472.0],
                      ['1992-12-31', 8868263.0],
                      ['1991-12-31', 8652514.0],
                      ['1990-12-31', 8465188.0],
                      ['1989-12-31', 8309531.0],
                      ['1988-12-31', 8180728.0],
                      ['1987-12-31', 8067758.0],
                      ['1986-12-31', 7955164.0],
                      ['1985-12-31', 7831889.0],
                      ['1984-12-31', 7693667.0],
                      ['1983-12-31', 7543743.0],
                      ['1982-12-31', 7387656.0],
                      ['1981-12-31', 7234303.0],
                      ['1980-12-31', 7090126.0],
                      ['1979-12-31', 6956579.0],
                      ['1978-12-31', 6831295.0],
                      ['1977-12-31', 6712401.0],
                      ['1976-12-31', 6596773.0],
                      ['1975-12-31', 6482278.0],
                      ['1974-12-31', 6368348.0],
                      ['1973-12-31', 6256187.0],
                      ['1972-12-31', 6147458.0],
                      ['1971-12-31', 6044530.0],
                      ['1970-12-31', 5949045.0],
                      ['1969-12-31', 5861412.0],
                      ['1968-12-31', 5780835.0],
                      ['1967-12-31', 5706199.0],
                      ['1966-12-31', 5635859.0],
                      ['1965-12-31', 5568484.0],
                      ['1964-12-31', 5503752.0],
                      ['1963-12-31', 5441613.0],
                      ['1962-12-31', 5381368.0],
                      ['1961-12-31', 5322266.0],
                      ['1960-12-31', 5263733.0],
                      ['1959-12-31', 5205449.0],
                      ['1958-12-31', 5147348.0],
                      ['1957-12-31', 5089509.0],
                      ['1956-12-31', 5032123.0],
                      ['1955-12-31', 4975398.0],
                      ['1954-12-31', 4919547.0],
                      ['1953-12-31', 4864755.0],
                      ['1952-12-31', 4811199.0],
                      ['1951-12-31', 4759036.0],
                      ['1950-12-31', 4708429.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'MLI_SP_POP_TOTL',
             'description': 'Population, total - Mali. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22210276,
             'limit': None,
             'name': 'Population, total - Mali',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:39:06.423Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
MLT
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 465292.0],
                      ['2016-12-31', 455356.0],
                      ['2015-12-31', 445053.0],
                      ['2014-12-31', 434558.0],
                      ['2013-12-31', 425967.0],
                      ['2012-12-31', 420028.0],
                      ['2011-12-31', 416268.0],
                      ['2010-12-31', 414508.0],
                      ['2009-12-31', 412477.0],
                      ['2008-12-31', 409379.0],
                      ['2007-12-31', 406724.0],
                      ['2006-12-31', 405308.0],
                      ['2005-12-31', 403834.0],
                      ['2004-12-31', 401268.0],
                      ['2003-12-31', 398582.0],
                      ['2002-12-31', 395969.0],
                      ['2001-12-31', 393028.0],
                      ['2000-12-31', 390087.0],
                      ['1999-12-31', 387578.0],
                      ['1998-12-31', 385287.0],
                      ['1997-12-31', 382791.0],
                      ['1996-12-31', 379905.0],
                      ['1995-12-31', 377419.0],
                      ['1994-12-31', 374797.0],
                      ['1993-12-31', 371308.0],
                      ['1992-12-31', 367618.0],
                      ['1991-12-31', 363845.0],
                      ['1990-12-31', 354170.0],
                      ['1989-12-31', 350722.0],
                      ['1988-12-31', 347325.0],
                      ['1987-12-31', 344485.0],
                      ['1986-12-31', 342121.0],
                      ['1985-12-31', 336452.0],
                      ['1984-12-31', 330593.0],
                      ['1983-12-31', 330524.0],
                      ['1982-12-31', 325898.0],
                      ['1981-12-31', 318982.0],
                      ['1980-12-31', 316645.0],
                      ['1979-12-31', 313342.0],
                      ['1978-12-31', 310182.0],
                      ['1977-12-31', 306970.0],
                      ['1976-12-31', 305774.0],
                      ['1975-12-31', 304222.0],
                      ['1974-12-31', 301996.0],
                      ['1973-12-31', 302200.0],
                      ['1972-12-31', 302450.0],
                      ['1971-12-31', 302700.0],
                      ['1970-12-31', 302650.0],
                      ['1969-12-31', 304300.0],
                      ['1968-12-31', 307900.0],
                      ['1967-12-31', 311550.0],
                      ['1966-12-31', 315200.0],
                      ['1965-12-31', 318800.0],
                      ['1964-12-31', 321250.0],
                      ['1963-12-31', 322550.0],
                      ['1962-12-31', 323900.0],
                      ['1961-12-31', 325250.0],
                      ['1960-12-31', 326550.0],
                      ['1959-12-31', 313725.0],
                      ['1958-12-31', 314204.0],
                      ['1957-12-31', 314412.0],
                      ['1956-12-31', 314436.0],
                      ['1955-12-31', 314341.0],
                      ['1954-12-31', 314164.0],
                      ['1953-12-31', 313903.0],
                      ['1952-12-31', 313514.0],
                      ['1951-12-31', 312918.0],
                      ['1950-12-31', 311997.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'MLT_SP_POP_TOTL',
             'description': 'Population, total - Malta. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22211884,
             'limit': None,
             'name': 'Population, total - Malta',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:39:11.812Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
MHL

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 53127.0],
                      ['2016-12-31', 53066.0],
                      ['2015-12-31', 52994.0],
                      ['2014-12-31', 52898.0],
                      ['2013-12-31', 52793.0],
                      ['2012-12-31', 52663.0],
                      ['2011-12-31', 52542.0],
                      ['2010-12-31', 52425.0],
                      ['2009-12-31', 52320.0],
                      ['2008-12-31', 52218.0],
                      ['2007-12-31', 52137.0],
                      ['2006-12-31', 52078.0],
                      ['2005-12-31', 52055.0],
                      ['2004-12-31', 52074.0],
                      ['2003-12-31', 52116.0],
                      ['2002-12-31', 52158.0],
                      ['2001-12-31', 52183.0],
                      ['2000-12-31', 52159.0],
                      ['1999-12-31', 52079.0],
                      ['1998-12-31', 51925.0],
                      ['1997-12-31', 51692.0],
                      ['1996-12-31', 51401.0],
                      ['1995-12-31', 51015.0],
                      ['1994-12-31', 50575.0],
                      ['1993-12-31', 50048.0],
                      ['1992-12-31', 49378.0],
                      ['1991-12-31', 48475.0],
                      ['1990-12-31', 47298.0],
                      ['1989-12-31', 45814.0],
                      ['1988-12-31', 44063.0],
                      ['1987-12-31', 42153.0],
                      ['1986-12-31', 40204.0],
                      ['1985-12-31', 38333.0],
                      ['1984-12-31', 36561.0],
                      ['1983-12-31', 34892.0],
                      ['1982-12-31', 33330.0],
                      ['1981-12-31', 31893.0],
                      ['1980-12-31', 30576.0],
                      ['1979-12-31', 29418.0],
                      ['1978-12-31', 28405.0],
                      ['1977-12-31', 27470.0],
                      ['1976-12-31', 26552.0],
                      ['1975-12-31', 25576.0],
                      ['1974-12-31', 24531.0],
                      ['1973-12-31', 23439.0],
                      ['1972-12-31', 22341.0],
                      ['1971-12-31', 21313.0],
                      ['1970-12-31', 20395.0],
                      ['1969-12-31', 19622.0],
                      ['1968-12-31', 18961.0],
                      ['1967-12-31', 18388.0],
                      ['1966-12-31', 17842.0],
                      ['1965-12-31', 17284.0],
                      ['1964-12-31', 16710.0],
                      ['1963-12-31', 16114.0],
                      ['1962-12-31', 15547.0],
                      ['1961-12-31', 15051.0],
                      ['1960-12-31', 14662.0],
                      ['1959-12-31', 14390.0],
                      ['1958-12-31', 14208.0],
                      ['1957-12-31', 14083.0],
                      ['1956-12-31', 13993.0],
                      ['1955-12-31', 13894.0],
                      ['1954-12-31', 13784.0],
                      ['1953-12-31', 13624.0],
                      ['1952-12-31', 13438.0],
                      ['1951-12-31', 13222.0],
                      ['1950-12-31', 13001.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'MHL_SP_POP_TOTL',
             'description': 'Population, total - Marshall Islands. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22204853,
             'limit': None,
             'name': 'Population, total - Marshall Islands',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:38:49.846Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
MRT
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 4420184.0],
                      ['2016-12-31', 4301018.0],
                      ['2015-12-31', 4182341.0],
                      ['2014-12-31', 4063920.0],
                      ['2013-12-31', 3946170.0],
                      ['2012-12-31', 3830239.0],
                      ['2011-12-31', 3717672.0],
                      ['2010-12-31', 3609543.0],
                      ['2009-12-31', 3506288.0],
                      ['2008-12-31', 3407541.0],
                      ['2007-12-31', 3312665.0],
                      ['2006-12-31', 3220653.0],
                      ['2005-12-31', 3130720.0],
                      ['2004-12-31', 3042823.0],
                      ['2003-12-31', 2957117.0],
                      ['2002-12-31', 2873228.0],
                      ['2001-12-31', 2790729.0],
                      ['2000-12-31', 2709359.0],
                      ['1999-12-31', 2628803.0],
                      ['1998-12-31', 2549223.0],
                      ['1997-12-31', 2471598.0],
                      ['1996-12-31', 2397245.0],
                      ['1995-12-31', 2327075.0],
                      ['1994-12-31', 2261403.0],
                      ['1993-12-31', 2199791.0],
                      ['1992-12-31', 2141445.0],
                      ['1991-12-31', 2085202.0],
                      ['1990-12-31', 2030140.0],
                      ['1989-12-31', 1976030.0],
                      ['1988-12-31', 1923002.0],
                      ['1987-12-31', 1870978.0],
                      ['1986-12-31', 1819954.0],
                      ['1985-12-31', 1769942.0],
                      ['1984-12-31', 1720812.0],
                      ['1983-12-31', 1672496.0],
                      ['1982-12-31', 1625124.0],
                      ['1981-12-31', 1578938.0],
                      ['1980-12-31', 1534085.0],
                      ['1979-12-31', 1490603.0],
                      ['1978-12-31', 1448414.0],
                      ['1977-12-31', 1407436.0],
                      ['1976-12-31', 1367563.0],
                      ['1975-12-31', 1328686.0],
                      ['1974-12-31', 1290790.0],
                      ['1973-12-31', 1253874.0],
                      ['1972-12-31', 1217941.0],
                      ['1971-12-31', 1182954.0],
                      ['1970-12-31', 1148908.0],
                      ['1969-12-31', 1115788.0],
                      ['1968-12-31', 1083583.0],
                      ['1967-12-31', 1052286.0],
                      ['1966-12-31', 1021882.0],
                      ['1965-12-31', 992367.0],
                      ['1964-12-31', 963747.0],
                      ['1963-12-31', 936016.0],
                      ['1962-12-31', 909174.0],
                      ['1961-12-31', 883221.0],
                      ['1960-12-31', 858168.0],
                      ['1959-12-31', 834023.0],
                      ['1958-12-31', 810801.0],
                      ['1957-12-31', 788506.0],
                      ['1956-12-31', 767162.0],
                      ['1955-12-31', 746804.0],
                      ['1954-12-31', 727437.0],
                      ['1953-12-31', 709097.0],
                      ['1952-12-31', 691811.0],
                      ['1951-12-31', 675596.0],
                      ['1950-12-31', 660491.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'MRT_SP_POP_TOTL',
             'description': 'Population, total - Mauritania. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22222444,
             'limit': None,
             'name': 'Population, total - Mauritania',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:39:47.111Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
MUS
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 1264613.0],
                      ['2016-12-31', 1263473.0],
                      ['2015-12-31', 1262605.0],
                      ['2014-12-31', 1260934.0],
                      ['2013-12-31', 1258653.0],
                      ['2012-12-31', 1255882.0],
                      ['2011-12-31', 1252404.0],
                      ['2010-12-31', 1250400.0],
                      ['2009-12-31', 1247429.0],
                      ['2008-12-31', 1244121.0],
                      ['2007-12-31', 1239630.0],
                      ['2006-12-31', 1233996.0],
                      ['2005-12-31', 1228254.0],
                      ['2004-12-31', 1221003.0],
                      ['2003-12-31', 1213370.0],
                      ['2002-12-31', 1204621.0],
                      ['2001-12-31', 1196287.0],
                      ['2000-12-31', 1186873.0],
                      ['1999-12-31', 1175267.0],
                      ['1998-12-31', 1160421.0],
                      ['1997-12-31', 1148284.0],
                      ['1996-12-31', 1133996.0],
                      ['1995-12-31', 1122457.0],
                      ['1994-12-31', 1112846.0],
                      ['1993-12-31', 1097374.0],
                      ['1992-12-31', 1084441.0],
                      ['1991-12-31', 1070266.0],
                      ['1990-12-31', 1058775.0],
                      ['1989-12-31', 1051260.0],
                      ['1988-12-31', 1043239.0],
                      ['1987-12-31', 1036082.0],
                      ['1986-12-31', 1028360.0],
                      ['1985-12-31', 1020528.0],
                      ['1984-12-31', 1012221.0],
                      ['1983-12-31', 1001691.0],
                      ['1982-12-31', 992521.0],
                      ['1981-12-31', 980462.0],
                      ['1980-12-31', 966039.0],
                      ['1979-12-31', 949888.0],
                      ['1978-12-31', 933499.0],
                      ['1977-12-31', 921379.0],
                      ['1976-12-31', 906507.0],
                      ['1975-12-31', 892000.0],
                      ['1974-12-31', 878042.0],
                      ['1973-12-31', 864819.0],
                      ['1972-12-31', 852053.0],
                      ['1971-12-31', 839230.0],
                      ['1970-12-31', 826000.0],
                      ['1969-12-31', 812405.0],
                      ['1968-12-31', 798413.0],
                      ['1967-12-31', 783917.0],
                      ['1966-12-31', 768813.0],
                      ['1965-12-31', 753000.0],
                      ['1964-12-31', 736381.0],
                      ['1963-12-31', 718861.0],
                      ['1962-12-31', 700349.0],
                      ['1961-12-31', 680757.0],
                      ['1960-12-31', 659351.0],
                      ['1959-12-31', 640758.0],
                      ['1958-12-31', 622642.0],
                      ['1957-12-31', 604913.0],
                      ['1956-12-31', 587465.0],
                      ['1955-12-31', 570258.0],
                      ['1954-12-31', 553338.0],
                      ['1953-12-31', 536859.0],
                      ['1952-12-31', 521087.0],
                      ['1951-12-31', 506393.0],
                      ['1950-12-31', 493254.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'MUS_SP_POP_TOTL',
             'description': 'Population, total - Mauritius. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22223803,
             'limit': None,
             'name': 'Population, total - Mauritius',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:39:53.437Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
MEX

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 129163276.0],
                      ['2016-12-31', 127540423.0],
                      ['2015-12-31', 125890949.0],
                      ['2014-12-31', 124221600.0],
                      ['2013-12-31', 122535969.0],
                      ['2012-12-31', 120828307.0],
                      ['2011-12-31', 119090017.0],
                      ['2010-12-31', 117318941.0],
                      ['2009-12-31', 115505228.0],
                      ['2008-12-31', 113661809.0],
                      ['2007-12-31', 111836346.0],
                      ['2006-12-31', 110092378.0],
                      ['2005-12-31', 108472228.0],
                      ['2004-12-31', 106995583.0],
                      ['2003-12-31', 105640453.0],
                      ['2002-12-31', 104355608.0],
                      ['2001-12-31', 103067068.0],
                      ['2000-12-31', 101719673.0],
                      ['1999-12-31', 100300579.0],
                      ['1998-12-31', 98821456.0],
                      ['1997-12-31', 97281739.0],
                      ['1996-12-31', 95687452.0],
                      ['1995-12-31', 94045579.0],
                      ['1994-12-31', 92349147.0],
                      ['1993-12-31', 90600453.0],
                      ['1992-12-31', 88828310.0],
                      ['1991-12-31', 87071512.0],
                      ['1990-12-31', 85357874.0],
                      ['1989-12-31', 83697891.0],
                      ['1988-12-31', 82083919.0],
                      ['1987-12-31', 80503052.0],
                      ['1986-12-31', 78934125.0],
                      ['1985-12-31', 77360707.0],
                      ['1984-12-31', 75780605.0],
                      ['1983-12-31', 74196548.0],
                      ['1982-12-31', 72602533.0],
                      ['1981-12-31', 70992195.0],
                      ['1980-12-31', 69360871.0],
                      ['1979-12-31', 67709689.0],
                      ['1978-12-31', 66039488.0],
                      ['1977-12-31', 64345884.0],
                      ['1976-12-31', 62623763.0],
                      ['1975-12-31', 60872399.0],
                      ['1974-12-31', 59088193.0],
                      ['1973-12-31', 57280587.0],
                      ['1972-12-31', 55478151.0],
                      ['1971-12-31', 53718724.0],
                      ['1970-12-31', 52029861.0],
                      ['1969-12-31', 50423481.0],
                      ['1968-12-31', 48894019.0],
                      ['1967-12-31', 47429812.0],
                      ['1966-12-31', 46011038.0],
                      ['1965-12-31', 44623043.0],
                      ['1964-12-31', 43264272.0],
                      ['1963-12-31', 41939880.0],
                      ['1962-12-31', 40649588.0],
                      ['1961-12-31', 39394126.0],
                      ['1960-12-31', 38174112.0],
                      ['1959-12-31', 36989694.0],
                      ['1958-12-31', 35840646.0],
                      ['1957-12-31', 34726719.0],
                      ['1956-12-31', 33647982.0],
                      ['1955-12-31', 32605178.0],
                      ['1954-12-31', 31599801.0],
                      ['1953-12-31', 30634215.0],
                      ['1952-12-31', 29711632.0],
                      ['1951-12-31', 28836114.0],
                      ['1950-12-31', 28012561.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'MEX_SP_POP_TOTL',
             'description': 'Population, total - Mexico. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22203801,
             'limit': None,
             'name': 'Population, total - Mexico',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:38:13.137Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
FSM
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 105544.0],
                      ['2016-12-31', 104937.0],
                      ['2015-12-31', 104433.0],
                      ['2014-12-31', 104015.0],
                      ['2013-12-31', 103702.0],
                      ['2012-12-31', 103503.0],
                      ['2011-12-31', 103468.0],
                      ['2010-12-31', 103616.0],
                      ['2009-12-31', 103960.0],
                      ['2008-12-31', 104478.0],
                      ['2007-12-31', 105078.0],
                      ['2006-12-31', 105684.0],
                      ['2005-12-31', 106196.0],
                      ['2004-12-31', 106577.0],
                      ['2003-12-31', 106816.0],
                      ['2002-12-31', 106983.0],
                      ['2001-12-31', 107165.0],
                      ['2000-12-31', 107432.0],
                      ['1999-12-31', 107816.0],
                      ['1998-12-31', 108238.0],
                      ['1997-12-31', 108502.0],
                      ['1996-12-31', 108344.0],
                      ['1995-12-31', 107556.0],
                      ['1994-12-31', 106057.0],
                      ['1993-12-31', 103934.0],
                      ['1992-12-31', 101413.0],
                      ['1991-12-31', 98799.0],
                      ['1990-12-31', 96331.0],
                      ['1989-12-31', 94091.0],
                      ['1988-12-31', 92021.0],
                      ['1987-12-31', 90020.0],
                      ['1986-12-31', 87948.0],
                      ['1985-12-31', 85686.0],
                      ['1984-12-31', 83240.0],
                      ['1983-12-31', 80678.0],
                      ['1982-12-31', 78059.0],
                      ['1981-12-31', 75462.0],
                      ['1980-12-31', 72964.0],
                      ['1979-12-31', 70550.0],
                      ['1978-12-31', 68222.0],
                      ['1977-12-31', 66105.0],
                      ['1976-12-31', 64386.0],
                      ['1975-12-31', 63144.0],
                      ['1974-12-31', 62476.0],
                      ['1973-12-31', 62290.0],
                      ['1972-12-31', 62298.0],
                      ['1971-12-31', 62108.0],
                      ['1970-12-31', 61431.0],
                      ['1969-12-31', 60170.0],
                      ['1968-12-31', 58403.0],
                      ['1967-12-31', 56319.0],
                      ['1966-12-31', 54199.0],
                      ['1965-12-31', 52242.0],
                      ['1964-12-31', 50487.0],
                      ['1963-12-31', 48876.0],
                      ['1962-12-31', 47388.0],
                      ['1961-12-31', 45955.0],
                      ['1960-12-31', 44537.0],
                      ['1959-12-31', 43126.0],
                      ['1958-12-31', 41727.0],
                      ['1957-12-31', 40373.0],
                      ['1956-12-31', 39093.0],
                      ['1955-12-31', 37893.0],
                      ['1954-12-31', 36777.0],
                      ['1953-12-31', 35693.0],
                      ['1952-12-31', 34600.0],
                      ['1951-12-31', 33408.0],
                      ['1950-12-31', 32001.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'FSM_SP_POP_TOTL',
             'description': 'Population, total - Micronesia, Fed. Sts.. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22148367,
             'limit': None,
             'name': 'Population, total - Micronesia, Fed. Sts.',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:32:22.157Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
MEA

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 444322417.0],
                      ['2016-12-31', 436738031.0],
                      ['2015-12-31', 428974903.0],
                      ['2014-12-31', 421030035.0],
                      ['2013-12-31', 412953000.0],
                      ['2012-12-31', 404783020.0],
                      ['2011-12-31', 396573248.0],
                      ['2010-12-31', 388376106.0],
                      ['2009-12-31', 380192587.0],
                      ['2008-12-31', 371999662.0],
                      ['2007-12-31', 363996317.0],
                      ['2006-12-31', 356287693.0],
                      ['2005-12-31', 348956287.0],
                      ['2004-12-31', 342046777.0],
                      ['2003-12-31', 335522845.0],
                      ['2002-12-31', 329289435.0],
                      ['2001-12-31', 323196354.0],
                      ['2000-12-31', 317129227.0],
                      ['1999-12-31', 311053183.0],
                      ['1998-12-31', 305001541.0],
                      ['1997-12-31', 298982946.0],
                      ['1996-12-31', 292934005.0],
                      ['1995-12-31', 286917385.0],
                      ['1994-12-31', 279279333.0],
                      ['1993-12-31', 273204804.0],
                      ['1992-12-31', 267020622.0],
                      ['1991-12-31', 262659662.0],
                      ['1990-12-31', 255989130.0],
                      ['1989-12-31', 247283550.0],
                      ['1988-12-31', 240367135.0],
                      ['1987-12-31', 233285188.0],
                      ['1986-12-31', 226161475.0],
                      ['1985-12-31', 219095273.0],
                      ['1984-12-31', 212102793.0],
                      ['1983-12-31', 205229901.0],
                      ['1982-12-31', 198499602.0],
                      ['1981-12-31', 192015875.0],
                      ['1980-12-31', 185843847.0],
                      ['1979-12-31', 180000521.0],
                      ['1978-12-31', 174493349.0],
                      ['1977-12-31', 169318424.0],
                      ['1976-12-31', 164407528.0],
                      ['1975-12-31', 159722643.0],
                      ['1974-12-31', 155259901.0],
                      ['1973-12-31', 150999871.0],
                      ['1972-12-31', 146887303.0],
                      ['1971-12-31', 142950993.0],
                      ['1970-12-31', 139083819.0],
                      ['1969-12-31', 135279930.0],
                      ['1968-12-31', 131566224.0],
                      ['1967-12-31', 127947266.0],
                      ['1966-12-31', 124374455.0],
                      ['1965-12-31', 120973578.0],
                      ['1964-12-31', 117671617.0],
                      ['1963-12-31', 114471415.0],
                      ['1962-12-31', 111385940.0],
                      ['1961-12-31', 108374227.0],
                      ['1960-12-31', 105488678.0],
                      ['1959-12-31', 102668517.0],
                      ['1958-12-31', 99954457.0],
                      ['1957-12-31', 97331494.0],
                      ['1956-12-31', 94798079.0],
                      ['1955-12-31', 92352298.0],
                      ['1954-12-31', 89991990.0],
                      ['1953-12-31', 87714415.0],
                      ['1952-12-31', 85516426.0],
                      ['1951-12-31', 83394420.0],
                      ['1950-12-31', 81344462.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'MEA_SP_POP_TOTL',
             'description': 'Population, total - Middle East & North Africa '
                            '(all income levels). ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22201942,
             'limit': None,
             'name': 'Population, total - Middle East & North Africa (all '
                     'income levels)',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:38:07.090Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
MNA
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 379901782.0],
                      ['2016-12-31', 373719055.0],
                      ['2015-12-31', 367449306.0],
                      ['2014-12-31', 361077997.0],
                      ['2013-12-31', 354641044.0],
                      ['2012-12-31', 348195697.0],
                      ['2011-12-31', 341822043.0],
                      ['2010-12-31', 335581557.0],
                      ['2009-12-31', 329488935.0],
                      ['2008-12-31', 323531149.0],
                      ['2007-12-31', 317721161.0],
                      ['2006-12-31', 312079307.0],
                      ['2005-12-31', 306595214.0],
                      ['2004-12-31', 301278295.0],
                      ['2003-12-31', 296114536.0],
                      ['2002-12-31', 291051001.0],
                      ['2001-12-31', 286016125.0],
                      ['2000-12-31', 280955290.0],
                      ['1999-12-31', 275840061.0],
                      ['1998-12-31', 270672291.0],
                      ['1997-12-31', 265463944.0],
                      ['1996-12-31', 260190124.0],
                      ['1995-12-31', 254918217.0],
                      ['1994-12-31', 249660649.0],
                      ['1993-12-31', 244395451.0],
                      ['1992-12-31', 239062651.0],
                      ['1991-12-31', 233582274.0],
                      ['1990-12-31', 227903820.0],
                      ['1989-12-31', 220121789.0],
                      ['1988-12-31', 214140741.0],
                      ['1987-12-31', 208051337.0],
                      ['1986-12-31', 201950420.0],
                      ['1985-12-31', 195917732.0],
                      ['1984-12-31', 189974163.0],
                      ['1983-12-31', 184129812.0],
                      ['1982-12-31', 178440308.0],
                      ['1981-12-31', 172967490.0],
                      ['1980-12-31', 167755859.0],
                      ['1979-12-31', 162829871.0],
                      ['1978-12-31', 158185098.0],
                      ['1977-12-31', 153798274.0],
                      ['1976-12-31', 149628962.0],
                      ['1975-12-31', 145642454.0],
                      ['1974-12-31', 141837810.0],
                      ['1973-12-31', 138211123.0],
                      ['1972-12-31', 134719523.0],
                      ['1971-12-31', 131309640.0],
                      ['1970-12-31', 127942543.0],
                      ['1969-12-31', 124596411.0],
                      ['1968-12-31', 121276296.0],
                      ['1967-12-31', 118004103.0],
                      ['1966-12-31', 114816087.0],
                      ['1965-12-31', 111738154.0],
                      ['1964-12-31', 108774858.0],
                      ['1963-12-31', 105914391.0],
                      ['1962-12-31', 103147177.0],
                      ['1961-12-31', 100458479.0],
                      ['1960-12-31', 97837766.0],
                      ['1959-12-31', 95281870.0],
                      ['1958-12-31', 92793879.0],
                      ['1957-12-31', 90380550.0],
                      ['1956-12-31', 88049216.0],
                      ['1955-12-31', 85805049.0],
                      ['1954-12-31', 83650112.0],
                      ['1953-12-31', 81582826.0],
                      ['1952-12-31', 79597662.0],
                      ['1951-12-31', 77685467.0],
                      ['1950-12-31', 75833442.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'MNA_SP_POP_TOTL',
             'description': 'Population, total - Middle East & North Africa '
                            '(developing only). ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22214970,
             'limit': None,
             'name': 'Population, total - Middle East & North Africa '
                     '(developing only)',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:39:22.464Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
CME
{'quandl_error': {'code': 'QECx02',
                  'message': 'You have submitted an incorrect Quandl code. '
                             'Please check your Quandl codes and try again.'}}
MIC

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 5548845363.0],
                      ['2016-12-31', 5487997451.0],
                      ['2015-12-31', 5426786956.0],
                      ['2014-12-31', 5365538848.0],
                      ['2013-12-31', 5304029982.0],
                      ['2012-12-31', 5242597655.0],
                      ['2011-12-31', 5181847962.0],
                      ['2010-12-31', 5121807824.0],
                      ['2009-12-31', 5062605505.0],
                      ['2008-12-31', 5004104587.0],
                      ['2007-12-31', 4946553085.0],
                      ['2006-12-31', 4889432780.0],
                      ['2005-12-31', 4831970102.0],
                      ['2004-12-31', 4774222573.0],
                      ['2003-12-31', 4716457496.0],
                      ['2002-12-31', 4658465586.0],
                      ['2001-12-31', 4600227196.0],
                      ['2000-12-31', 4541041198.0],
                      ['1999-12-31', 4480561195.0],
                      ['1998-12-31', 4419076905.0],
                      ['1997-12-31', 4356099751.0],
                      ['1996-12-31', 4292242496.0],
                      ['1995-12-31', 4228251983.0],
                      ['1994-12-31', 4163965335.0],
                      ['1993-12-31', 4099176795.0],
                      ['1992-12-31', 4033694107.0],
                      ['1991-12-31', 3966983593.0],
                      ['1990-12-31', 3898295566.0],
                      ['1989-12-31', 3825985836.0],
                      ['1988-12-31', 3754165457.0],
                      ['1987-12-31', 3681617710.0],
                      ['1986-12-31', 3609456878.0],
                      ['1985-12-31', 3539073108.0],
                      ['1984-12-31', 3470527013.0],
                      ['1983-12-31', 3403116165.0],
                      ['1982-12-31', 3335471848.0],
                      ['1981-12-31', 3268748349.0],
                      ['1980-12-31', 3205183598.0],
                      ['1979-12-31', 3143467072.0],
                      ['1978-12-31', 3082575226.0],
                      ['1977-12-31', 3023043056.0],
                      ['1976-12-31', 2964489036.0],
                      ['1975-12-31', 2905308044.0],
                      ['1974-12-31', 2845473103.0],
                      ['1973-12-31', 2784270871.0],
                      ['1972-12-31', 2722509919.0],
                      ['1971-12-31', 2660574293.0],
                      ['1970-12-31', 2597581551.0],
                      ['1969-12-31', 2535880293.0],
                      ['1968-12-31', 2475758536.0],
                      ['1967-12-31', 2417921483.0],
                      ['1966-12-31', 2361620594.0],
                      ['1965-12-31', 2305150948.0],
                      ['1964-12-31', 2252227568.0],
                      ['1963-12-31', 2200880839.0],
                      ['1962-12-31', 2149854074.0],
                      ['1961-12-31', 2110910882.0],
                      ['1960-12-31', 2085155624.0],
                      ['1959-12-31', 2078264501.0],
                      ['1958-12-31', 2034936704.0],
                      ['1957-12-31', 1992901819.0],
                      ['1956-12-31', 1952123692.0],
                      ['1955-12-31', 1912578158.0],
                      ['1954-12-31', 1872312590.0],
                      ['1953-12-31', 1833353560.0],
                      ['1952-12-31', 1795796086.0],
                      ['1951-12-31', 1759727403.0],
                      ['1950-12-31', 1725241574.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'MIC_SP_POP_TOTL',
             'description': 'Population, total - Middle income. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22206794,
             'limit': None,
             'name': 'Population, total - Middle income',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:38:54.340Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
MDA
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 3549750.0],
                      ['2016-12-31', 3551954.0],
                      ['2015-12-31', 3554108.0],
                      ['2014-12-31', 3556397.0],
                      ['2013-12-31', 3558566.0],
                      ['2012-12-31', 3559519.0],
                      ['2011-12-31', 3559986.0],
                      ['2010-12-31', 3562045.0],
                      ['2009-12-31', 3565604.0],
                      ['2008-12-31', 3570108.0],
                      ['2007-12-31', 3576910.0],
                      ['2006-12-31', 3585209.0],
                      ['2005-12-31', 3595187.0],
                      ['2004-12-31', 3603945.0],
                      ['2003-12-31', 3612874.0],
                      ['2002-12-31', 3623062.0],
                      ['2001-12-31', 3631462.0],
                      ['2000-12-31', 3639592.0],
                      ['1999-12-31', 3647001.0],
                      ['1998-12-31', 3652732.0],
                      ['1997-12-31', 3654208.0],
                      ['1996-12-31', 3667748.0],
                      ['1995-12-31', 3675099.0],
                      ['1994-12-31', 3691000.0],
                      ['1993-12-31', 3701000.0],
                      ['1992-12-31', 3706000.0],
                      ['1991-12-31', 3704000.0],
                      ['1990-12-31', 3696000.0],
                      ['1989-12-31', 3681000.0],
                      ['1988-12-31', 3660000.0],
                      ['1987-12-31', 3633000.0],
                      ['1986-12-31', 3602000.0],
                      ['1985-12-31', 3570000.0],
                      ['1984-12-31', 3536000.0],
                      ['1983-12-31', 3500000.0],
                      ['1982-12-31', 3464000.0],
                      ['1981-12-31', 3429000.0],
                      ['1980-12-31', 3396000.0],
                      ['1979-12-31', 3366000.0],
                      ['1978-12-31', 3339000.0],
                      ['1977-12-31', 3312000.0],
                      ['1976-12-31', 3284000.0],
                      ['1975-12-31', 3251000.0],
                      ['1974-12-31', 3215000.0],
                      ['1973-12-31', 3174000.0],
                      ['1972-12-31', 3131000.0],
                      ['1971-12-31', 3088000.0],
                      ['1970-12-31', 3044000.0],
                      ['1969-12-31', 3002000.0],
                      ['1968-12-31', 2960000.0],
                      ['1967-12-31', 2918000.0],
                      ['1966-12-31', 2873000.0],
                      ['1965-12-31', 2825000.0],
                      ['1964-12-31', 2774000.0],
                      ['1963-12-31', 2721000.0],
                      ['1962-12-31', 2664000.0],
                      ['1961-12-31', 2605000.0],
                      ['1960-12-31', 2544000.0],
                      ['1959-12-31', 2481000.0],
                      ['1958-12-31', 2416000.0],
                      ['1957-12-31', 2352000.0],
                      ['1956-12-31', 2288000.0],
                      ['1955-12-31', 2225000.0],
                      ['1954-12-31', 2165000.0],
                      ['1953-12-31', 2110000.0],
                      ['1952-12-31', 2060000.0],
                      ['1951-12-31', 2017000.0],
                      ['1950-12-31', 1983000.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'MDA_SP_POP_TOTL',
             'description': 'Population, total - Moldova. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22197608,
             'limit': None,
             'name': 'Population, total - Moldova',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:37:49.224Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
MCO

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 38695.0],
                      ['2016-12-31', 38499.0],
                      ['2015-12-31', 38307.0],
                      ['2014-12-31', 38132.0],
                      ['2013-12-31', 37971.0],
                      ['2012-12-31', 37783.0],
                      ['2011-12-31', 37497.0],
                      ['2010-12-31', 37094.0],
                      ['2009-12-31', 36534.0],
                      ['2008-12-31', 35853.0],
                      ['2007-12-31', 35111.0],
                      ['2006-12-31', 34408.0],
                      ['2005-12-31', 33793.0],
                      ['2004-12-31', 33314.0],
                      ['2003-12-31', 32933.0],
                      ['2002-12-31', 32629.0],
                      ['2001-12-31', 32360.0],
                      ['2000-12-31', 32082.0],
                      ['1999-12-31', 31800.0],
                      ['1998-12-31', 31523.0],
                      ['1997-12-31', 31251.0],
                      ['1996-12-31', 30967.0],
                      ['1995-12-31', 30691.0],
                      ['1994-12-31', 30427.0],
                      ['1993-12-31', 30138.0],
                      ['1992-12-31', 29863.0],
                      ['1991-12-31', 29624.0],
                      ['1990-12-31', 29439.0],
                      ['1989-12-31', 29312.0],
                      ['1988-12-31', 29235.0],
                      ['1987-12-31', 29172.0],
                      ['1986-12-31', 29041.0],
                      ['1985-12-31', 28835.0],
                      ['1984-12-31', 28512.0],
                      ['1983-12-31', 28095.0],
                      ['1982-12-31', 27624.0],
                      ['1981-12-31', 27164.0],
                      ['1980-12-31', 26745.0],
                      ['1979-12-31', 26395.0],
                      ['1978-12-31', 26087.0],
                      ['1977-12-31', 25809.0],
                      ['1976-12-31', 25523.0],
                      ['1975-12-31', 25197.0],
                      ['1974-12-31', 24835.0],
                      ['1973-12-31', 24439.0],
                      ['1972-12-31', 24051.0],
                      ['1971-12-31', 23720.0],
                      ['1970-12-31', 23484.0],
                      ['1969-12-31', 23346.0],
                      ['1968-12-31', 23304.0],
                      ['1967-12-31', 23292.0],
                      ['1966-12-31', 23305.0],
                      ['1965-12-31', 23282.0],
                      ['1964-12-31', 23236.0],
                      ['1963-12-31', 23168.0],
                      ['1962-12-31', 23039.0],
                      ['1961-12-31', 22808.0],
                      ['1960-12-31', 22452.0],
                      ['1959-12-31', 21974.0],
                      ['1958-12-31', 21399.0],
                      ['1957-12-31', 20791.0],
                      ['1956-12-31', 20182.0],
                      ['1955-12-31', 19655.0],
                      ['1954-12-31', 19264.0],
                      ['1953-12-31', 19053.0],
                      ['1952-12-31', 19073.0],
                      ['1951-12-31', 19377.0],
                      ['1950-12-31', 19996.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'MCO_SP_POP_TOTL',
             'description': 'Population, total - Monaco. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22196150,
             'limit': None,
             'name': 'Population, total - Monaco',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:37:44.096Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
MNG
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 3075647.0],
                      ['2016-12-31', 3027398.0],
                      ['2015-12-31', 2976877.0],
                      ['2014-12-31', 2923896.0],
                      ['2013-12-31', 2869107.0],
                      ['2012-12-31', 2814226.0],
                      ['2011-12-31', 2761516.0],
                      ['2010-12-31', 2712650.0],
                      ['2009-12-31', 2668289.0],
                      ['2008-12-31', 2628131.0],
                      ['2007-12-31', 2591670.0],
                      ['2006-12-31', 2558012.0],
                      ['2005-12-31', 2526446.0],
                      ['2004-12-31', 2496832.0],
                      ['2003-12-31', 2469286.0],
                      ['2002-12-31', 2443659.0],
                      ['2001-12-31', 2419776.0],
                      ['2000-12-31', 2397436.0],
                      ['1999-12-31', 2376162.0],
                      ['1998-12-31', 2355590.0],
                      ['1997-12-31', 2335695.0],
                      ['1996-12-31', 2316567.0],
                      ['1995-12-31', 2298039.0],
                      ['1994-12-31', 2280496.0],
                      ['1993-12-31', 2263200.0],
                      ['1992-12-31', 2243502.0],
                      ['1991-12-31', 2217918.0],
                      ['1990-12-31', 2184145.0],
                      ['1989-12-31', 2141008.0],
                      ['1988-12-31', 2089714.0],
                      ['1987-12-31', 2033343.0],
                      ['1986-12-31', 1976309.0],
                      ['1985-12-31', 1921881.0],
                      ['1984-12-31', 1871090.0],
                      ['1983-12-31', 1823216.0],
                      ['1982-12-31', 1777727.0],
                      ['1981-12-31', 1733475.0],
                      ['1980-12-31', 1689622.0],
                      ['1979-12-31', 1646291.0],
                      ['1978-12-31', 1603906.0],
                      ['1977-12-31', 1562209.0],
                      ['1976-12-31', 1520865.0],
                      ['1975-12-31', 1479651.0],
                      ['1974-12-31', 1438425.0],
                      ['1973-12-31', 1397304.0],
                      ['1972-12-31', 1356670.0],
                      ['1971-12-31', 1317050.0],
                      ['1970-12-31', 1278825.0],
                      ['1969-12-31', 1242214.0],
                      ['1968-12-31', 1207104.0],
                      ['1967-12-31', 1173191.0],
                      ['1966-12-31', 1139961.0],
                      ['1965-12-31', 1107124.0],
                      ['1964-12-31', 1074514.0],
                      ['1963-12-31', 1042383.0],
                      ['1962-12-31', 1011324.0],
                      ['1961-12-31', 982178.0],
                      ['1960-12-31', 955505.0],
                      ['1959-12-31', 931481.0],
                      ['1958-12-31', 909890.0],
                      ['1957-12-31', 890274.0],
                      ['1956-12-31', 872156.0],
                      ['1955-12-31', 855103.0],
                      ['1954-12-31', 838785.0],
                      ['1953-12-31', 823060.0],
                      ['1952-12-31', 807921.0],
                      ['1951-12-31', 793538.0],
                      ['1950-12-31', 780199.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'MNG_SP_POP_TOTL',
             'description': 'Population, total - Mongolia. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22218890,
             'limit': None,
             'name': 'Population, total - Mongolia',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:39:33.327Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
MNE
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 622471.0],
                      ['2016-12-31', 622303.0],
                      ['2015-12-31', 622159.0],
                      ['2014-12-31', 621810.0],
                      ['2013-12-31', 621207.0],
                      ['2012-12-31', 620601.0],
                      ['2011-12-31', 620079.0],
                      ['2010-12-31', 619428.0],
                      ['2009-12-31', 618294.0],
                      ['2008-12-31', 616969.0],
                      ['2007-12-31', 615875.0],
                      ['2006-12-31', 615025.0],
                      ['2005-12-31', 614261.0],
                      ['2004-12-31', 613353.0],
                      ['2003-12-31', 612267.0],
                      ['2002-12-31', 609828.0],
                      ['2001-12-31', 607389.0],
                      ['2000-12-31', 604950.0],
                      ['1999-12-31', 606001.0],
                      ['1998-12-31', 607662.0],
                      ['1997-12-31', 609520.0],
                      ['1996-12-31', 611003.0],
                      ['1995-12-31', 611712.0],
                      ['1994-12-31', 611389.0],
                      ['1993-12-31', 610170.0],
                      ['1992-12-31', 608516.0],
                      ['1991-12-31', 607105.0],
                      ['1990-12-31', 606372.0],
                      ['1989-12-31', 606571.0],
                      ['1988-12-31', 607413.0],
                      ['1987-12-31', 608144.0],
                      ['1986-12-31', 607711.0],
                      ['1985-12-31', 605398.0],
                      ['1984-12-31', 600884.0],
                      ['1983-12-31', 594506.0],
                      ['1982-12-31', 587001.0],
                      ['1981-12-31', 579445.0],
                      ['1980-12-31', 572608.0],
                      ['1979-12-31', 566888.0],
                      ['1978-12-31', 562065.0],
                      ['1977-12-31', 557576.0],
                      ['1976-12-31', 552562.0],
                      ['1975-12-31', 546487.0],
                      ['1974-12-31', 538902.0],
                      ['1973-12-31', 530220.0],
                      ['1972-12-31', 521785.0],
                      ['1971-12-31', 515449.0],
                      ['1970-12-31', 512407.0],
                      ['1969-12-31', 513340.0],
                      ['1968-12-31', 517481.0],
                      ['1967-12-31', 522796.0],
                      ['1966-12-31', 526419.0],
                      ['1965-12-31', 526327.0],
                      ['1964-12-31', 521753.0],
                      ['1963-12-31', 513409.0],
                      ['1962-12-31', 502558.0],
                      ['1961-12-31', 491140.0],
                      ['1960-12-31', 480579.0],
                      ['1959-12-31', 471363.0],
                      ['1958-12-31', 463196.0],
                      ['1957-12-31', 455333.0],
                      ['1956-12-31', 446963.0],
                      ['1955-12-31', 437570.0],
                      ['1954-12-31', 427059.0],
                      ['1953-12-31', 415819.0],
                      ['1952-12-31', 404752.0],
                      ['1951-12-31', 395252.0],
                      ['1950-12-31', 389201.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'MNE_SP_POP_TOTL',
             'description': 'Population, total - Montenegro. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22216958,
             'limit': None,
             'name': 'Population, total - Montenegro',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:39:27.485Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
MAR

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 35739580.0],
                      ['2016-12-31', 35276786.0],
                      ['2015-12-31', 34803322.0],
                      ['2014-12-31', 34318082.0],
                      ['2013-12-31', 33824769.0],
                      ['2012-12-31', 33333789.0],
                      ['2011-12-31', 32858823.0],
                      ['2010-12-31', 32409639.0],
                      ['2009-12-31', 31989897.0],
                      ['2008-12-31', 31596855.0],
                      ['2007-12-31', 31225881.0],
                      ['2006-12-31', 30869346.0],
                      ['2005-12-31', 30521070.0],
                      ['2004-12-31', 30179285.0],
                      ['2003-12-31', 29843937.0],
                      ['2002-12-31', 29512368.0],
                      ['2001-12-31', 29181832.0],
                      ['2000-12-31', 28849621.0],
                      ['1999-12-31', 28514798.0],
                      ['1998-12-31', 28175263.0],
                      ['1997-12-31', 27825901.0],
                      ['1996-12-31', 27460603.0],
                      ['1995-12-31', 27075232.0],
                      ['1994-12-31', 26667048.0],
                      ['1993-12-31', 26237417.0],
                      ['1992-12-31', 25791494.0],
                      ['1991-12-31', 25336862.0],
                      ['1990-12-31', 24879136.0],
                      ['1989-12-31', 24421191.0],
                      ['1988-12-31', 23961820.0],
                      ['1987-12-31', 23497766.0],
                      ['1986-12-31', 23023935.0],
                      ['1985-12-31', 22537376.0],
                      ['1984-12-31', 22037610.0],
                      ['1983-12-31', 21528502.0],
                      ['1982-12-31', 21016818.0],
                      ['1981-12-31', 20511601.0],
                      ['1980-12-31', 20019847.0],
                      ['1979-12-31', 19543347.0],
                      ['1978-12-31', 19081718.0],
                      ['1977-12-31', 18636977.0],
                      ['1976-12-31', 18210754.0],
                      ['1975-12-31', 17803698.0],
                      ['1974-12-31', 17416964.0],
                      ['1973-12-31', 17049165.0],
                      ['1972-12-31', 16695003.0],
                      ['1971-12-31', 16347198.0],
                      ['1970-12-31', 16000008.0],
                      ['1969-12-31', 15651924.0],
                      ['1968-12-31', 15302947.0],
                      ['1967-12-31', 14950803.0],
                      ['1966-12-31', 14593284.0],
                      ['1965-12-31', 14229044.0],
                      ['1964-12-31', 13857142.0],
                      ['1963-12-31', 13478232.0],
                      ['1962-12-31', 13094818.0],
                      ['1961-12-31', 12710547.0],
                      ['1960-12-31', 12328532.0],
                      ['1959-12-31', 11950826.0],
                      ['1958-12-31', 11578559.0],
                      ['1957-12-31', 11212449.0],
                      ['1956-12-31', 10853333.0],
                      ['1955-12-31', 10502666.0],
                      ['1954-12-31', 10162684.0],
                      ['1953-12-31', 9836534.0],
                      ['1952-12-31', 9528256.0],
                      ['1951-12-31', 9242797.0],
                      ['1950-12-31', 8985989.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'MAR_SP_POP_TOTL',
             'description': 'Population, total - Morocco. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22195403,
             'limit': None,
             'name': 'Population, total - Morocco',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:37:41.466Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
MOZ
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 29668834.0],
                      ['2016-12-31', 28829476.0],
                      ['2015-12-31', 28010691.0],
                      ['2014-12-31', 27212382.0],
                      ['2013-12-31', 26434372.0],
                      ['2012-12-31', 25676606.0],
                      ['2011-12-31', 24939005.0],
                      ['2010-12-31', 24221405.0],
                      ['2009-12-31', 23524063.0],
                      ['2008-12-31', 22846758.0],
                      ['2007-12-31', 22188387.0],
                      ['2006-12-31', 21547463.0],
                      ['2005-12-31', 20923070.0],
                      ['2004-12-31', 20312705.0],
                      ['2003-12-31', 19716598.0],
                      ['2002-12-31', 19139658.0],
                      ['2001-12-31', 18588758.0],
                      ['2000-12-31', 18067687.0],
                      ['1999-12-31', 17584869.0],
                      ['1998-12-31', 17136780.0],
                      ['1997-12-31', 16701351.0],
                      ['1996-12-31', 16248232.0],
                      ['1995-12-31', 15759132.0],
                      ['1994-12-31', 15217044.0],
                      ['1993-12-31', 14636995.0],
                      ['1992-12-31', 14071231.0],
                      ['1991-12-31', 13591970.0],
                      ['1990-12-31', 13247649.0],
                      ['1989-12-31', 13059613.0],
                      ['1988-12-31', 13002553.0],
                      ['1987-12-31', 13020861.0],
                      ['1986-12-31', 13034385.0],
                      ['1985-12-31', 12984405.0],
                      ['1984-12-31', 12853780.0],
                      ['1983-12-31', 12657708.0],
                      ['1982-12-31', 12409243.0],
                      ['1981-12-31', 12133074.0],
                      ['1980-12-31', 11848331.0],
                      ['1979-12-31', 11554979.0],
                      ['1978-12-31', 11248046.0],
                      ['1977-12-31', 10936936.0],
                      ['1976-12-31', 10632932.0],
                      ['1975-12-31', 10344494.0],
                      ['1974-12-31', 10076172.0],
                      ['1973-12-31', 9827580.0],
                      ['1972-12-31', 9595762.0],
                      ['1971-12-31', 9375144.0],
                      ['1970-12-31', 9161534.0],
                      ['1969-12-31', 8954809.0],
                      ['1968-12-31', 8756481.0],
                      ['1967-12-31', 8565674.0],
                      ['1966-12-31', 8381455.0],
                      ['1965-12-31', 8203076.0],
                      ['1964-12-31', 8030025.0],
                      ['1963-12-31', 7862072.0],
                      ['1962-12-31', 7699139.0],
                      ['1961-12-31', 7541325.0],
                      ['1960-12-31', 7388695.0],
                      ['1959-12-31', 7241232.0],
                      ['1958-12-31', 7098859.0],
                      ['1957-12-31', 6961486.0],
                      ['1956-12-31', 6829092.0],
                      ['1955-12-31', 6701749.0],
                      ['1954-12-31', 6579634.0],
                      ['1953-12-31', 6463088.0],
                      ['1952-12-31', 6352584.0],
                      ['1951-12-31', 6248717.0],
                      ['1950-12-31', 6152237.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'MOZ_SP_POP_TOTL',
             'description': 'Population, total - Mozambique. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22220656,
             'limit': None,
             'name': 'Population, total - Mozambique',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:39:40.896Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
MMR

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 53370609.0],
                      ['2016-12-31', 52885223.0],
                      ['2015-12-31', 52403669.0],
                      ['2014-12-31', 51924182.0],
                      ['2013-12-31', 51448196.0],
                      ['2012-12-31', 50986514.0],
                      ['2011-12-31', 50553031.0],
                      ['2010-12-31', 50155896.0],
                      ['2009-12-31', 49800690.0],
                      ['2008-12-31', 49479752.0],
                      ['2007-12-31', 49171586.0],
                      ['2006-12-31', 48846474.0],
                      ['2005-12-31', 48482614.0],
                      ['2004-12-31', 48073707.0],
                      ['2003-12-31', 47624894.0],
                      ['2002-12-31', 47140220.0],
                      ['2001-12-31', 46627994.0],
                      ['2000-12-31', 46095462.0],
                      ['1999-12-31', 45539435.0],
                      ['1998-12-31', 44959935.0],
                      ['1997-12-31', 44371525.0],
                      ['1996-12-31', 43793310.0],
                      ['1995-12-31', 43237792.0],
                      ['1994-12-31', 42712223.0],
                      ['1993-12-31', 42209778.0],
                      ['1992-12-31', 41711465.0],
                      ['1991-12-31', 41190156.0],
                      ['1990-12-31', 40626250.0],
                      ['1989-12-31', 40014862.0],
                      ['1988-12-31', 39362142.0],
                      ['1987-12-31', 38673241.0],
                      ['1986-12-31', 37957332.0],
                      ['1985-12-31', 37222296.0],
                      ['1984-12-31', 36468888.0],
                      ['1983-12-31', 35697943.0],
                      ['1982-12-31', 34917895.0],
                      ['1981-12-31', 34139130.0],
                      ['1980-12-31', 33369712.0],
                      ['1979-12-31', 32613888.0],
                      ['1978-12-31', 31872230.0],
                      ['1977-12-31', 31144324.0],
                      ['1976-12-31', 30428034.0],
                      ['1975-12-31', 29721967.0],
                      ['1974-12-31', 29027734.0],
                      ['1973-12-31', 28347341.0],
                      ['1972-12-31', 27680144.0],
                      ['1971-12-31', 27024985.0],
                      ['1970-12-31', 26381431.0],
                      ['1969-12-31', 25748643.0],
                      ['1968-12-31', 25128116.0],
                      ['1967-12-31', 24524548.0],
                      ['1966-12-31', 23944178.0],
                      ['1965-12-31', 23391145.0],
                      ['1964-12-31', 22867741.0],
                      ['1963-12-31', 22371902.0],
                      ['1962-12-31', 21898020.0],
                      ['1961-12-31', 21438025.0],
                      ['1960-12-31', 20986123.0],
                      ['1959-12-31', 20540399.0],
                      ['1958-12-31', 20102248.0],
                      ['1957-12-31', 19675044.0],
                      ['1956-12-31', 19262647.0],
                      ['1955-12-31', 18867968.0],
                      ['1954-12-31', 18492475.0],
                      ['1953-12-31', 18135962.0],
                      ['1952-12-31', 17796400.0],
                      ['1951-12-31', 17470060.0],
                      ['1950-12-31', 17151510.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'MMR_SP_POP_TOTL',
             'description': 'Population, total - Myanmar. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22213463,
             'limit': None,
             'name': 'Population, total - Myanmar',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:39:17.326Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
NAM
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 2533794.0],
                      ['2016-12-31', 2479713.0],
                      ['2015-12-31', 2425561.0],
                      ['2014-12-31', 2370992.0],
                      ['2013-12-31', 2316520.0],
                      ['2012-12-31', 2263934.0],
                      ['2011-12-31', 2215621.0],
                      ['2010-12-31', 2173170.0],
                      ['2009-12-31', 2137040.0],
                      ['2008-12-31', 2106375.0],
                      ['2007-12-31', 2079915.0],
                      ['2006-12-31', 2055734.0],
                      ['2005-12-31', 2032196.0],
                      ['2004-12-31', 2009228.0],
                      ['2003-12-31', 1986535.0],
                      ['2002-12-31', 1962147.0],
                      ['2001-12-31', 1933596.0],
                      ['2000-12-31', 1899257.0],
                      ['1999-12-31', 1858042.0],
                      ['1998-12-31', 1810566.0],
                      ['1997-12-31', 1758994.0],
                      ['1996-12-31', 1706489.0],
                      ['1995-12-31', 1655359.0],
                      ['1994-12-31', 1606718.0],
                      ['1993-12-31', 1559983.0],
                      ['1992-12-31', 1513721.0],
                      ['1991-12-31', 1465740.0],
                      ['1990-12-31', 1414692.0],
                      ['1989-12-31', 1359933.0],
                      ['1988-12-31', 1302741.0],
                      ['1987-12-31', 1245990.0],
                      ['1986-12-31', 1193592.0],
                      ['1985-12-31', 1148302.0],
                      ['1984-12-31', 1111132.0],
                      ['1983-12-31', 1081081.0],
                      ['1982-12-31', 1056366.0],
                      ['1981-12-31', 1034264.0],
                      ['1980-12-31', 1012672.0],
                      ['1979-12-31', 991226.0],
                      ['1978-12-31', 970258.0],
                      ['1977-12-31', 949193.0],
                      ['1976-12-31', 927503.0],
                      ['1975-12-31', 904839.0],
                      ['1974-12-31', 880785.0],
                      ['1973-12-31', 855380.0],
                      ['1972-12-31', 829441.0],
                      ['1971-12-31', 804157.0],
                      ['1970-12-31', 780384.0],
                      ['1969-12-31', 758377.0],
                      ['1968-12-31', 737886.0],
                      ['1967-12-31', 718685.0],
                      ['1966-12-31', 700341.0],
                      ['1965-12-31', 682551.0],
                      ['1964-12-31', 665282.0],
                      ['1963-12-31', 648661.0],
                      ['1962-12-31', 632654.0],
                      ['1961-12-31', 617277.0],
                      ['1960-12-31', 602544.0],
                      ['1959-12-31', 588426.0],
                      ['1958-12-31', 574904.0],
                      ['1957-12-31', 561932.0],
                      ['1956-12-31', 549479.0],
                      ['1955-12-31', 537514.0],
                      ['1954-12-31', 526042.0],
                      ['1953-12-31', 515058.0],
                      ['1952-12-31', 504578.0],
                      ['1951-12-31', 494631.0],
                      ['1950-12-31', 485274.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'NAM_SP_POP_TOTL',
             'description': 'Population, total - Namibia. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22229390,
             'limit': None,
             'name': 'Population, total - Namibia',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:40:12.934Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
NPL

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 29304998.0],
                      ['2016-12-31', 28982771.0],
                      ['2015-12-31', 28656282.0],
                      ['2014-12-31', 28323241.0],
                      ['2013-12-31', 27985310.0],
                      ['2012-12-31', 27649925.0],
                      ['2011-12-31', 27327147.0],
                      ['2010-12-31', 27023137.0],
                      ['2009-12-31', 26741103.0],
                      ['2008-12-31', 26475859.0],
                      ['2007-12-31', 26214847.0],
                      ['2006-12-31', 25940618.0],
                      ['2005-12-31', 25640287.0],
                      ['2004-12-31', 25309449.0],
                      ['2003-12-31', 24950623.0],
                      ['2002-12-31', 24566342.0],
                      ['2001-12-31', 24161777.0],
                      ['2000-12-31', 23740911.0],
                      ['1999-12-31', 23305994.0],
                      ['1998-12-31', 22856305.0],
                      ['1997-12-31', 22389803.0],
                      ['1996-12-31', 21903379.0],
                      ['1995-12-31', 21396384.0],
                      ['1994-12-31', 20867130.0],
                      ['1993-12-31', 20321175.0],
                      ['1992-12-31', 19773772.0],
                      ['1991-12-31', 19245054.0],
                      ['1990-12-31', 18749406.0],
                      ['1989-12-31', 18293514.0],
                      ['1988-12-31', 17873667.0],
                      ['1987-12-31', 17480921.0],
                      ['1986-12-31', 17101136.0],
                      ['1985-12-31', 16723956.0],
                      ['1984-12-31', 16347242.0],
                      ['1983-12-31', 15974420.0],
                      ['1982-12-31', 15607236.0],
                      ['1981-12-31', 15249010.0],
                      ['1980-12-31', 14902163.0],
                      ['1979-12-31', 14566691.0],
                      ['1978-12-31', 14241403.0],
                      ['1977-12-31', 13926260.0],
                      ['1976-12-31', 13621110.0],
                      ['1975-12-31', 13325814.0],
                      ['1974-12-31', 13040404.0],
                      ['1973-12-31', 12764957.0],
                      ['1972-12-31', 12499429.0],
                      ['1971-12-31', 12243768.0],
                      ['1970-12-31', 11997929.0],
                      ['1969-12-31', 11761473.0],
                      ['1968-12-31', 11534264.0],
                      ['1967-12-31', 11316826.0],
                      ['1966-12-31', 11109884.0],
                      ['1965-12-31', 10913724.0],
                      ['1964-12-31', 10728197.0],
                      ['1963-12-31', 10552267.0],
                      ['1962-12-31', 10384204.0],
                      ['1961-12-31', 10221759.0],
                      ['1960-12-31', 10063011.0],
                      ['1959-12-31', 9906689.0],
                      ['1958-12-31', 9752049.0],
                      ['1957-12-31', 9598630.0],
                      ['1956-12-31', 9446009.0],
                      ['1955-12-31', 9293493.0],
                      ['1954-12-31', 9140059.0],
                      ['1953-12-31', 8984311.0],
                      ['1952-12-31', 8824455.0],
                      ['1951-12-31', 8658310.0],
                      ['1950-12-31', 8483325.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'NPL_SP_POP_TOTL',
             'description': 'Population, total - Nepal. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22192165,
             'limit': None,
             'name': 'Population, total - Nepal',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:40:51.454Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
NLD
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 17132854.0],
                      ['2016-12-31', 17030314.0],
                      ['2015-12-31', 16939923.0],
                      ['2014-12-31', 16865008.0],
                      ['2013-12-31', 16804432.0],
                      ['2012-12-31', 16754962.0],
                      ['2011-12-31', 16693074.0],
                      ['2010-12-31', 16615394.0],
                      ['2009-12-31', 16530388.0],
                      ['2008-12-31', 16445593.0],
                      ['2007-12-31', 16381696.0],
                      ['2006-12-31', 16346101.0],
                      ['2005-12-31', 16319868.0],
                      ['2004-12-31', 16281779.0],
                      ['2003-12-31', 16225302.0],
                      ['2002-12-31', 16148929.0],
                      ['2001-12-31', 16046180.0],
                      ['2000-12-31', 15925513.0],
                      ['1999-12-31', 15812088.0],
                      ['1998-12-31', 15707209.0],
                      ['1997-12-31', 15610650.0],
                      ['1996-12-31', 15530498.0],
                      ['1995-12-31', 15459006.0],
                      ['1994-12-31', 15382838.0],
                      ['1993-12-31', 15290368.0],
                      ['1992-12-31', 15184166.0],
                      ['1991-12-31', 15069798.0],
                      ['1990-12-31', 14951510.0],
                      ['1989-12-31', 14848907.0],
                      ['1988-12-31', 14760094.0],
                      ['1987-12-31', 14665037.0],
                      ['1986-12-31', 14572278.0],
                      ['1985-12-31', 14491632.0],
                      ['1984-12-31', 14424211.0],
                      ['1983-12-31', 14367070.0],
                      ['1982-12-31', 14312690.0],
                      ['1981-12-31', 14247208.0],
                      ['1980-12-31', 14149800.0],
                      ['1979-12-31', 14038270.0],
                      ['1978-12-31', 13941700.0],
                      ['1977-12-31', 13856185.0],
                      ['1976-12-31', 13774037.0],
                      ['1975-12-31', 13666335.0],
                      ['1974-12-31', 13545056.0],
                      ['1973-12-31', 13439322.0],
                      ['1972-12-31', 13328593.0],
                      ['1971-12-31', 13194497.0],
                      ['1970-12-31', 13038526.0],
                      ['1969-12-31', 12877984.0],
                      ['1968-12-31', 12729721.0],
                      ['1967-12-31', 12598201.0],
                      ['1966-12-31', 12456251.0],
                      ['1965-12-31', 12294732.0],
                      ['1964-12-31', 12127120.0],
                      ['1963-12-31', 11965966.0],
                      ['1962-12-31', 11805689.0],
                      ['1961-12-31', 11638712.0],
                      ['1960-12-31', 11486631.0],
                      ['1959-12-31', 11264566.0],
                      ['1958-12-31', 11114008.0],
                      ['1957-12-31', 10966682.0],
                      ['1956-12-31', 10822380.0],
                      ['1955-12-31', 10680990.0],
                      ['1954-12-31', 10542570.0],
                      ['1953-12-31', 10407381.0],
                      ['1952-12-31', 10275906.0],
                      ['1951-12-31', 10148830.0],
                      ['1950-12-31', 10027047.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'NLD_SP_POP_TOTL',
             'description': 'Population, total - Netherlands. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22187166,
             'limit': None,
             'name': 'Population, total - Netherlands',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:40:40.280Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
NCL

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 280460.0],
                      ['2016-12-31', 276550.0],
                      ['2015-12-31', 272400.0],
                      ['2014-12-31', 268050.0],
                      ['2013-12-31', 263650.0],
                      ['2012-12-31', 259000.0],
                      ['2011-12-31', 254350.0],
                      ['2010-12-31', 249750.0],
                      ['2009-12-31', 245950.0],
                      ['2008-12-31', 242750.0],
                      ['2007-12-31', 239250.0],
                      ['2006-12-31', 235750.0],
                      ['2005-12-31', 232250.0],
                      ['2004-12-31', 228750.0],
                      ['2003-12-31', 225296.0],
                      ['2002-12-31', 221490.0],
                      ['2001-12-31', 217324.0],
                      ['2000-12-31', 213230.0],
                      ['1999-12-31', 209214.0],
                      ['1998-12-31', 205279.0],
                      ['1997-12-31', 201418.0],
                      ['1996-12-31', 197564.0],
                      ['1995-12-31', 193816.0],
                      ['1994-12-31', 189482.0],
                      ['1993-12-31', 184496.0],
                      ['1992-12-31', 179799.0],
                      ['1991-12-31', 175362.0],
                      ['1990-12-31', 170899.0],
                      ['1989-12-31', 166898.0],
                      ['1988-12-31', 163650.0],
                      ['1987-12-31', 160500.0],
                      ['1986-12-31', 157350.0],
                      ['1985-12-31', 154450.0],
                      ['1984-12-31', 151650.0],
                      ['1983-12-31', 148700.0],
                      ['1982-12-31', 145700.0],
                      ['1981-12-31', 142650.0],
                      ['1980-12-31', 140050.0],
                      ['1979-12-31', 138500.0],
                      ['1978-12-31', 137500.0],
                      ['1977-12-31', 136000.0],
                      ['1976-12-31', 134000.0],
                      ['1975-12-31', 132500.0],
                      ['1974-12-31', 131000.0],
                      ['1973-12-31', 128500.0],
                      ['1972-12-31', 125500.0],
                      ['1971-12-31', 120000.0],
                      ['1970-12-31', 112000.0],
                      ['1969-12-31', 104000.0],
                      ['1968-12-31', 99500.0],
                      ['1967-12-31', 96500.0],
                      ['1966-12-31', 93500.0],
                      ['1965-12-31', 90500.0],
                      ['1964-12-31', 88100.0],
                      ['1963-12-31', 85700.0],
                      ['1962-12-31', 83400.0],
                      ['1961-12-31', 81200.0],
                      ['1960-12-31', 79000.0],
                      ['1959-12-31', 75977.0],
                      ['1958-12-31', 73070.0],
                      ['1957-12-31', 70275.0],
                      ['1956-12-31', 67586.0],
                      ['1955-12-31', 65000.0],
                      ['1954-12-31', 62864.0],
                      ['1953-12-31', 60799.0],
                      ['1952-12-31', 58801.0],
                      ['1951-12-31', 56869.0],
                      ['1950-12-31', 55000.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'NCL_SP_POP_TOTL',
             'description': 'Population, total - New Caledonia. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22230490,
             'limit': None,
             'name': 'Population, total - New Caledonia',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:40:16.641Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
NZL
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 4793900.0],
                      ['2016-12-31', 4693200.0],
                      ['2015-12-31', 4595700.0],
                      ['2014-12-31', 4509700.0],
                      ['2013-12-31', 4442100.0],
                      ['2012-12-31', 4408100.0],
                      ['2011-12-31', 4384000.0],
                      ['2010-12-31', 4350700.0],
                      ['2009-12-31', 4302600.0],
                      ['2008-12-31', 4259800.0],
                      ['2007-12-31', 4223800.0],
                      ['2006-12-31', 4184600.0],
                      ['2005-12-31', 4133900.0],
                      ['2004-12-31', 4087500.0],
                      ['2003-12-31', 4027200.0],
                      ['2002-12-31', 3948500.0],
                      ['2001-12-31', 3880500.0],
                      ['2000-12-31', 3857700.0],
                      ['1999-12-31', 3835100.0],
                      ['1998-12-31', 3815000.0],
                      ['1997-12-31', 3781300.0],
                      ['1996-12-31', 3732000.0],
                      ['1995-12-31', 3673400.0],
                      ['1994-12-31', 3620000.0],
                      ['1993-12-31', 3572200.0],
                      ['1992-12-31', 3531700.0],
                      ['1991-12-31', 3495100.0],
                      ['1990-12-31', 3329800.0],
                      ['1989-12-31', 3299200.0],
                      ['1988-12-31', 3283400.0],
                      ['1987-12-31', 3274400.0],
                      ['1986-12-31', 3246300.0],
                      ['1985-12-31', 3247100.0],
                      ['1984-12-31', 3227100.0],
                      ['1983-12-31', 3199300.0],
                      ['1982-12-31', 3156100.0],
                      ['1981-12-31', 3124900.0],
                      ['1980-12-31', 3112900.0],
                      ['1979-12-31', 3109000.0],
                      ['1978-12-31', 3121200.0],
                      ['1977-12-31', 3120200.0],
                      ['1976-12-31', 3110500.0],
                      ['1975-12-31', 3083100.0],
                      ['1974-12-31', 3023700.0],
                      ['1973-12-31', 2961300.0],
                      ['1972-12-31', 2903900.0],
                      ['1971-12-31', 2853000.0],
                      ['1970-12-31', 2810700.0],
                      ['1969-12-31', 2772800.0],
                      ['1968-12-31', 2748100.0],
                      ['1967-12-31', 2724100.0],
                      ['1966-12-31', 2675900.0],
                      ['1965-12-31', 2628400.0],
                      ['1964-12-31', 2585400.0],
                      ['1963-12-31', 2531800.0],
                      ['1962-12-31', 2482000.0],
                      ['1961-12-31', 2419700.0],
                      ['1960-12-31', 2371800.0],
                      ['1959-12-31', 2331100.0],
                      ['1958-12-31', 2281500.0],
                      ['1957-12-31', 2229400.0],
                      ['1956-12-31', 2178300.0],
                      ['1955-12-31', 2136200.0],
                      ['1954-12-31', 2092800.0],
                      ['1953-12-31', 2047400.0],
                      ['1952-12-31', 1994800.0],
                      ['1951-12-31', 1947300.0],
                      ['1950-12-31', 1908300.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'NZL_SP_POP_TOTL',
             'description': 'Population, total - New Zealand. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22193929,
             'limit': None,
             'name': 'Population, total - New Zealand',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:40:56.592Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
NIC

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 6217581.0],
                      ['2016-12-31', 6149928.0],
                      ['2015-12-31', 6082035.0],
                      ['2014-12-31', 6013997.0],
                      ['2013-12-31', 5945747.0],
                      ['2012-12-31', 5877108.0],
                      ['2011-12-31', 5807820.0],
                      ['2010-12-31', 5737723.0],
                      ['2009-12-31', 5666581.0],
                      ['2008-12-31', 5594506.0],
                      ['2007-12-31', 5522106.0],
                      ['2006-12-31', 5450211.0],
                      ['2005-12-31', 5379328.0],
                      ['2004-12-31', 5309703.0],
                      ['2003-12-31', 5240879.0],
                      ['2002-12-31', 5171734.0],
                      ['2001-12-31', 5100750.0],
                      ['2000-12-31', 5026796.0],
                      ['1999-12-31', 4949660.0],
                      ['1998-12-31', 4869626.0],
                      ['1997-12-31', 4786640.0],
                      ['1996-12-31', 4700779.0],
                      ['1995-12-31', 4612228.0],
                      ['1994-12-31', 4520725.0],
                      ['1993-12-31', 4426580.0],
                      ['1992-12-31', 4331277.0],
                      ['1991-12-31', 4236801.0],
                      ['1990-12-31', 4144565.0],
                      ['1989-12-31', 4055265.0],
                      ['1988-12-31', 3968454.0],
                      ['1987-12-31', 3882943.0],
                      ['1986-12-31', 3796917.0],
                      ['1985-12-31', 3709091.0],
                      ['1984-12-31', 3619253.0],
                      ['1983-12-31', 3527939.0],
                      ['1982-12-31', 3435525.0],
                      ['1981-12-31', 3342669.0],
                      ['1980-12-31', 3249910.0],
                      ['1979-12-31', 3157355.0],
                      ['1978-12-31', 3065117.0],
                      ['1977-12-31', 2973806.0],
                      ['1976-12-31', 2884155.0],
                      ['1975-12-31', 2796746.0],
                      ['1974-12-31', 2711848.0],
                      ['1973-12-31', 2629505.0],
                      ['1972-12-31', 2549774.0],
                      ['1971-12-31', 2472656.0],
                      ['1970-12-31', 2398096.0],
                      ['1969-12-31', 2326139.0],
                      ['1968-12-31', 2256782.0],
                      ['1967-12-31', 2189882.0],
                      ['1966-12-31', 2125240.0],
                      ['1965-12-31', 2062630.0],
                      ['1964-12-31', 2002119.0],
                      ['1963-12-31', 1943590.0],
                      ['1962-12-31', 1886562.0],
                      ['1961-12-31', 1830400.0],
                      ['1960-12-31', 1774699.0],
                      ['1959-12-31', 1719365.0],
                      ['1958-12-31', 1664605.0],
                      ['1957-12-31', 1610818.0],
                      ['1956-12-31', 1558474.0],
                      ['1955-12-31', 1508025.0],
                      ['1954-12-31', 1459854.0],
                      ['1953-12-31', 1414276.0],
                      ['1952-12-31', 1371518.0],
                      ['1951-12-31', 1331745.0],
                      ['1950-12-31', 1294992.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'NIC_SP_POP_TOTL',
             'description': 'Population, total - Nicaragua. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22185423,
             'limit': None,
             'name': 'Population, total - Nicaragua',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:40:35.016Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
NGA
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 190886311.0],
                      ['2016-12-31', 185989640.0],
                      ['2015-12-31', 181181744.0],
                      ['2014-12-31', 176460502.0],
                      ['2013-12-31', 171829303.0],
                      ['2012-12-31', 167297284.0],
                      ['2011-12-31', 162877076.0],
                      ['2010-12-31', 158578261.0],
                      ['2009-12-31', 154402181.0],
                      ['2008-12-31', 150347390.0],
                      ['2007-12-31', 146417024.0],
                      ['2006-12-31', 142614094.0],
                      ['2005-12-31', 138939478.0],
                      ['2004-12-31', 135393616.0],
                      ['2003-12-31', 131972533.0],
                      ['2002-12-31', 128666710.0],
                      ['2001-12-31', 125463434.0],
                      ['2000-12-31', 122352009.0],
                      ['1999-12-31', 119327073.0],
                      ['1998-12-31', 116385750.0],
                      ['1997-12-31', 113522705.0],
                      ['1996-12-31', 110732904.0],
                      ['1995-12-31', 108011465.0],
                      ['1994-12-31', 105355783.0],
                      ['1993-12-31', 102761737.0],
                      ['1992-12-31', 100221563.0],
                      ['1991-12-31', 97726323.0],
                      ['1990-12-31', 95269988.0],
                      ['1989-12-31', 92844353.0],
                      ['1988-12-31', 90450281.0],
                      ['1987-12-31', 88101628.0],
                      ['1986-12-31', 85818502.0],
                      ['1985-12-31', 83613300.0],
                      ['1984-12-31', 81497739.0],
                      ['1983-12-31', 79462277.0],
                      ['1982-12-31', 77472907.0],
                      ['1981-12-31', 75482552.0],
                      ['1980-12-31', 73460724.0],
                      ['1979-12-31', 71391290.0],
                      ['1978-12-31', 69293550.0],
                      ['1977-12-31', 67215805.0],
                      ['1976-12-31', 65226229.0],
                      ['1975-12-31', 63373572.0],
                      ['1974-12-31', 61673559.0],
                      ['1973-12-31', 60110433.0],
                      ['1972-12-31', 58662603.0],
                      ['1971-12-31', 57295210.0],
                      ['1970-12-31', 55981400.0],
                      ['1969-12-31', 54716735.0],
                      ['1968-12-31', 53505978.0],
                      ['1967-12-31', 52341834.0],
                      ['1966-12-31', 51217359.0],
                      ['1965-12-31', 50127214.0],
                      ['1964-12-31', 49066059.0],
                      ['1963-12-31', 48032246.0],
                      ['1962-12-31', 47029140.0],
                      ['1961-12-31', 46062905.0],
                      ['1960-12-31', 45137812.0],
                      ['1959-12-31', 44254686.0],
                      ['1958-12-31', 43411475.0],
                      ['1957-12-31', 42604508.0],
                      ['1956-12-31', 41830031.0],
                      ['1955-12-31', 41085563.0],
                      ['1954-12-31', 40370373.0],
                      ['1953-12-31', 39685757.0],
                      ['1952-12-31', 39035145.0],
                      ['1951-12-31', 38423978.0],
                      ['1950-12-31', 37859744.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'NGA_SP_POP_TOTL',
             'description': 'Population, total - Nigeria. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22183505,
             'limit': None,
             'name': 'Population, total - Nigeria',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:40:28.562Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
NER

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 21477348.0],
                      ['2016-12-31', 20672987.0],
                      ['2015-12-31', 19896965.0],
                      ['2014-12-31', 19148219.0],
                      ['2013-12-31', 18426372.0],
                      ['2012-12-31', 17731634.0],
                      ['2011-12-31', 17064636.0],
                      ['2010-12-31', 16425578.0],
                      ['2009-12-31', 15813913.0],
                      ['2008-12-31', 15228525.0],
                      ['2007-12-31', 14668338.0],
                      ['2006-12-31', 14132064.0],
                      ['2005-12-31', 13618449.0],
                      ['2004-12-31', 13127012.0],
                      ['2003-12-31', 12656870.0],
                      ['2002-12-31', 12206002.0],
                      ['2001-12-31', 11771976.0],
                      ['2000-12-31', 11352973.0],
                      ['1999-12-31', 10947829.0],
                      ['1998-12-31', 10556549.0],
                      ['1997-12-31', 10180061.0],
                      ['1996-12-31', 9819964.0],
                      ['1995-12-31', 9477333.0],
                      ['1994-12-31', 9151763.0],
                      ['1993-12-31', 8842415.0],
                      ['1992-12-31', 8549424.0],
                      ['1991-12-31', 8272976.0],
                      ['1990-12-31', 8012861.0],
                      ['1989-12-31', 7768995.0],
                      ['1988-12-31', 7540253.0],
                      ['1987-12-31', 7323969.0],
                      ['1986-12-31', 7116744.0],
                      ['1985-12-31', 6915927.0],
                      ['1984-12-31', 6720344.0],
                      ['1983-12-31', 6529894.0],
                      ['1982-12-31', 6344382.0],
                      ['1981-12-31', 6164006.0],
                      ['1980-12-31', 5988904.0],
                      ['1979-12-31', 5818506.0],
                      ['1978-12-31', 5652355.0],
                      ['1977-12-31', 5490921.0],
                      ['1976-12-31', 5334918.0],
                      ['1975-12-31', 5184811.0],
                      ['1974-12-31', 5040656.0],
                      ['1973-12-31', 4902006.0],
                      ['1972-12-31', 4768078.0],
                      ['1971-12-31', 4637829.0],
                      ['1970-12-31', 4510479.0],
                      ['1969-12-31', 4385758.0],
                      ['1968-12-31', 4263745.0],
                      ['1967-12-31', 4144395.0],
                      ['1966-12-31', 4027758.0],
                      ['1965-12-31', 3913934.0],
                      ['1964-12-31', 3802640.0],
                      ['1963-12-31', 3693866.0],
                      ['1962-12-31', 3588156.0],
                      ['1961-12-31', 3486295.0],
                      ['1960-12-31', 3388764.0],
                      ['1959-12-31', 3295583.0],
                      ['1958-12-31', 3206360.0],
                      ['1957-12-31', 3120437.0],
                      ['1956-12-31', 3037059.0],
                      ['1955-12-31', 2955541.0],
                      ['1954-12-31', 2875274.0],
                      ['1953-12-31', 2795806.0],
                      ['1952-12-31', 2716818.0],
                      ['1951-12-31', 2638137.0],
                      ['1950-12-31', 2559703.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'NER_SP_POP_TOTL',
             'description': 'Population, total - Niger. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22232013,
             'limit': None,
             'name': 'Population, total - Niger',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:40:21.932Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
NAF
{'quandl_error': {'code': 'QECx02',
                  'message': 'You have submitted an incorrect Quandl code. '
                             'Please check your Quandl codes and try again.'}}
NAC
{'quandl_error': {'code': 'QECx02',
                  'message': 'You have submitted an incorrect Quandl code. '
                             'Please check your Quandl codes and try again.'}}
MNP
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 55144.0],
                      ['2016-12-31', 55023.0],
                      ['2015-12-31', 54816.0],
                      ['2014-12-31', 54468.0],
                      ['2013-12-31', 54036.0],
                      ['2012-12-31', 53718.0],
                      ['2011-12-31', 53786.0],
                      ['2010-12-31', 54424.0],
                      ['2009-12-31', 55674.0],
                      ['2008-12-31', 57431.0],
                      ['2007-12-31', 59513.0],
                      ['2006-12-31', 61688.0],
                      ['2005-12-31', 63744.0],
                      ['2004-12-31', 65663.0],
                      ['2003-12-31', 67422.0],
                      ['2002-12-31', 68763.0],
                      ['2001-12-31', 69388.0],
                      ['2000-12-31', 69094.0],
                      ['1999-12-31', 67755.0],
                      ['1998-12-31', 65474.0],
                      ['1997-12-31', 62528.0],
                      ['1996-12-31', 59364.0],
                      ['1995-12-31', 56278.0],
                      ['1994-12-31', 53380.0],
                      ['1993-12-31', 50602.0],
                      ['1992-12-31', 47919.0],
                      ['1991-12-31', 45249.0],
                      ['1990-12-31', 42538.0],
                      ['1989-12-31', 39808.0],
                      ['1988-12-31', 37134.0],
                      ['1987-12-31', 34480.0],
                      ['1986-12-31', 31802.0],
                      ['1985-12-31', 29092.0],
                      ['1984-12-31', 26302.0],
                      ['1983-12-31', 23503.0],
                      ['1982-12-31', 20856.0],
                      ['1981-12-31', 18604.0],
                      ['1980-12-31', 16920.0],
                      ['1979-12-31', 15862.0],
                      ['1978-12-31', 15372.0],
                      ['1977-12-31', 15251.0],
                      ['1976-12-31', 15234.0],
                      ['1975-12-31', 15117.0],
                      ['1974-12-31', 14859.0],
                      ['1973-12-31', 14492.0],
                      ['1972-12-31', 14040.0],
                      ['1971-12-31', 13569.0],
                      ['1970-12-31', 13127.0],
                      ['1969-12-31', 12691.0],
                      ['1968-12-31', 12257.0],
                      ['1967-12-31', 11823.0],
                      ['1966-12-31', 11435.0],
                      ['1965-12-31', 11105.0],
                      ['1964-12-31', 10857.0],
                      ['1963-12-31', 10667.0],
                      ['1962-12-31', 10499.0],
                      ['1961-12-31', 10302.0],
                      ['1960-12-31', 10035.0],
                      ['1959-12-31', 9689.0],
                      ['1958-12-31', 9280.0],
                      ['1957-12-31', 8835.0],
                      ['1956-12-31', 8407.0],
                      ['1955-12-31', 8010.0],
                      ['1954-12-31', 7674.0],
                      ['1953-12-31', 7409.0],
                      ['1952-12-31', 7215.0],
                      ['1951-12-31', 7081.0],
                      ['1950-12-31', 6999.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'MNP_SP_POP_TOTL',
             'description': 'Population, total - Northern Mariana Islands. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22219595,
             'limit': None,
             'name': 'Population, total - Northern Mariana Islands',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:39:35.718Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
NOR

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 5282223.0],
                      ['2016-12-31', 5234519.0],
                      ['2015-12-31', 5190239.0],
                      ['2014-12-31', 5137232.0],
                      ['2013-12-31', 5079623.0],
                      ['2012-12-31', 5018573.0],
                      ['2011-12-31', 4953088.0],
                      ['2010-12-31', 4889252.0],
                      ['2009-12-31', 4828726.0],
                      ['2008-12-31', 4768212.0],
                      ['2007-12-31', 4709153.0],
                      ['2006-12-31', 4660677.0],
                      ['2005-12-31', 4623291.0],
                      ['2004-12-31', 4591910.0],
                      ['2003-12-31', 4564855.0],
                      ['2002-12-31', 4538159.0],
                      ['2001-12-31', 4513751.0],
                      ['2000-12-31', 4490967.0],
                      ['1999-12-31', 4461913.0],
                      ['1998-12-31', 4431464.0],
                      ['1997-12-31', 4405157.0],
                      ['1996-12-31', 4381336.0],
                      ['1995-12-31', 4359184.0],
                      ['1994-12-31', 4336613.0],
                      ['1993-12-31', 4311991.0],
                      ['1992-12-31', 4286401.0],
                      ['1991-12-31', 4261732.0],
                      ['1990-12-31', 4241473.0],
                      ['1989-12-31', 4226901.0],
                      ['1988-12-31', 4209488.0],
                      ['1987-12-31', 4186905.0],
                      ['1986-12-31', 4167354.0],
                      ['1985-12-31', 4152516.0],
                      ['1984-12-31', 4140099.0],
                      ['1983-12-31', 4128432.0],
                      ['1982-12-31', 4114787.0],
                      ['1981-12-31', 4099702.0],
                      ['1980-12-31', 4085620.0],
                      ['1979-12-31', 4072517.0],
                      ['1978-12-31', 4058671.0],
                      ['1977-12-31', 4043205.0],
                      ['1976-12-31', 4026152.0],
                      ['1975-12-31', 4007313.0],
                      ['1974-12-31', 3985258.0],
                      ['1973-12-31', 3960612.0],
                      ['1972-12-31', 3933004.0],
                      ['1971-12-31', 3903039.0],
                      ['1970-12-31', 3875763.0],
                      ['1969-12-31', 3847707.0],
                      ['1968-12-31', 3816486.0],
                      ['1967-12-31', 3784539.0],
                      ['1966-12-31', 3753012.0],
                      ['1965-12-31', 3723168.0],
                      ['1964-12-31', 3694339.0],
                      ['1963-12-31', 3666537.0],
                      ['1962-12-31', 3638918.0],
                      ['1961-12-31', 3609800.0],
                      ['1960-12-31', 3581239.0],
                      ['1959-12-31', 3551305.0],
                      ['1958-12-31', 3520775.0],
                      ['1957-12-31', 3489693.0],
                      ['1956-12-31', 3458366.0],
                      ['1955-12-31', 3427000.0],
                      ['1954-12-31', 3395643.0],
                      ['1953-12-31', 3364169.0],
                      ['1952-12-31', 3332263.0],
                      ['1951-12-31', 3299431.0],
                      ['1950-12-31', 3265000.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'NOR_SP_POP_TOTL',
             'description': 'Population, total - Norway. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22190183,
             'limit': None,
             'name': 'Population, total - Norway',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:40:45.369Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
OED
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 1300865255.0],
                      ['2016-12-31', 1292855641.0],
                      ['2015-12-31', 1284497900.0],
                      ['2014-12-31', 1276165062.0],
                      ['2013-12-31', 1267734036.0],
                      ['2012-12-31', 1259608786.0],
                      ['2011-12-31', 1251781641.0],
                      ['2010-12-31', 1245479028.0],
                      ['2009-12-31', 1237366149.0],
                      ['2008-12-31', 1228624922.0],
                      ['2007-12-31', 1219114314.0],
                      ['2006-12-31', 1210090990.0],
                      ['2005-12-31', 1201387655.0],
                      ['2004-12-31', 1193061799.0],
                      ['2003-12-31', 1184744057.0],
                      ['2002-12-31', 1176489220.0],
                      ['2001-12-31', 1168255846.0],
                      ['2000-12-31', 1160068208.0],
                      ['1999-12-31', 1152210193.0],
                      ['1998-12-31', 1144146467.0],
                      ['1997-12-31', 1136083409.0],
                      ['1996-12-31', 1127684727.0],
                      ['1995-12-31', 1119229507.0],
                      ['1994-12-31', 1110542679.0],
                      ['1993-12-31', 1101667703.0],
                      ['1992-12-31', 1092297098.0],
                      ['1991-12-31', 1082472189.0],
                      ['1990-12-31', 1072793105.0],
                      ['1989-12-31', 1063722318.0],
                      ['1988-12-31', 1055207746.0],
                      ['1987-12-31', 1047190374.0],
                      ['1986-12-31', 1039311168.0],
                      ['1985-12-31', 1031384389.0],
                      ['1984-12-31', 1023759567.0],
                      ['1983-12-31', 1016199100.0],
                      ['1982-12-31', 1008294124.0],
                      ['1981-12-31', 1000026812.0],
                      ['1980-12-31', 991341533.0],
                      ['1979-12-31', 982546160.0],
                      ['1978-12-31', 973625923.0],
                      ['1977-12-31', 964825121.0],
                      ['1976-12-31', 956010403.0],
                      ['1975-12-31', 947366074.0],
                      ['1974-12-31', 937199799.0],
                      ['1973-12-31', 926497991.0],
                      ['1972-12-31', 916834937.0],
                      ['1971-12-31', 906296731.0],
                      ['1970-12-31', 895979621.0],
                      ['1969-12-31', 886368544.0],
                      ['1968-12-31', 875810595.0],
                      ['1967-12-31', 867043486.0],
                      ['1966-12-31', 857372064.0],
                      ['1965-12-31', 847303180.0],
                      ['1964-12-31', 836716282.0],
                      ['1963-12-31', 825791048.0],
                      ['1962-12-31', 814836116.0],
                      ['1961-12-31', 803847992.0],
                      ['1960-12-31', 791487664.0],
                      ['1959-12-31', 776864403.0],
                      ['1958-12-31', 766555954.0],
                      ['1957-12-31', 756485187.0],
                      ['1956-12-31', 746589825.0],
                      ['1955-12-31', 736826052.0],
                      ['1954-12-31', 727126869.0],
                      ['1953-12-31', 717515421.0],
                      ['1952-12-31', 708010775.0],
                      ['1951-12-31', 698675911.0],
                      ['1950-12-31', 689591291.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'OED_SP_POP_TOTL',
             'description': 'Population, total - OECD members. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22196912,
             'limit': None,
             'name': 'Population, total - OECD members',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:41:01.229Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
OMN
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 4636262.0],
                      ['2016-12-31', 4424762.0],
                      ['2015-12-31', 4199810.0],
                      ['2014-12-31', 3960925.0],
                      ['2013-12-31', 3711481.0],
                      ['2012-12-31', 3464644.0],
                      ['2011-12-31', 3237268.0],

                      ['2010-12-31', 3041460.0],
                      ['2009-12-31', 2882942.0],
                      ['2008-12-31', 2759014.0],
                      ['2007-12-31', 2662762.0],
                      ['2006-12-31', 2582991.0],
                      ['2005-12-31', 2511269.0],
                      ['2004-12-31', 2444751.0],
                      ['2003-12-31', 2385255.0],
                      ['2002-12-31', 2334285.0],
                      ['2001-12-31', 2294787.0],
                      ['2000-12-31', 2267991.0],
                      ['1999-12-31', 2254918.0],
                      ['1998-12-31', 2251875.0],
                      ['1997-12-31', 2249773.0],
                      ['1996-12-31', 2236666.0],
                      ['1995-12-31', 2204283.0],
                      ['1994-12-31', 2148428.0],
                      ['1993-12-31', 2072111.0],
                      ['1992-12-31', 1983277.0],
                      ['1991-12-31', 1893771.0],
                      ['1990-12-31', 1812160.0],
                      ['1989-12-31', 1741160.0],
                      ['1988-12-31', 1678116.0],
                      ['1987-12-31', 1619864.0],
                      ['1986-12-31', 1561185.0],
                      ['1985-12-31', 1498417.0],
                      ['1984-12-31', 1431077.0],
                      ['1983-12-31', 1361097.0],
                      ['1982-12-31', 1290111.0],
                      ['1981-12-31', 1220587.0],
                      ['1980-12-31', 1154379.0],
                      ['1979-12-31', 1091853.0],
                      ['1978-12-31', 1032800.0],
                      ['1977-12-31', 977808.0],
                      ['1976-12-31', 927439.0],
                      ['1975-12-31', 882044.0],
                      ['1974-12-31', 841948.0],
                      ['1973-12-31', 806991.0],
                      ['1972-12-31', 776383.0],
                      ['1971-12-31', 748973.0],
                      ['1970-12-31', 723852.0],
                      ['1969-12-31', 700725.0],
                      ['1968-12-31', 679597.0],
                      ['1967-12-31', 660119.0],
                      ['1966-12-31', 642003.0],
                      ['1965-12-31', 625009.0],
                      ['1964-12-31', 608887.0],
                      ['1963-12-31', 593501.0],
                      ['1962-12-31', 578824.0],
                      ['1961-12-31', 564890.0],
                      ['1960-12-31', 551740.0],
                      ['1959-12-31', 539328.0],
                      ['1958-12-31', 527598.0],
                      ['1957-12-31', 516471.0],
                      ['1956-12-31', 505892.0],
                      ['1955-12-31', 495816.0],
                      ['1954-12-31', 486312.0],
                      ['1953-12-31', 477440.0],
                      ['1952-12-31', 469350.0],
                      ['1951-12-31', 462251.0],
                      ['1950-12-31', 456419.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'OMN_SP_POP_TOTL',
             'description': 'Population, total - Oman. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22198713,
             'limit': None,
             'name': 'Population, total - Oman',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:41:06.261Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
OSS
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 30621014.0],
                      ['2016-12-31', 30012500.0],
                      ['2015-12-31', 29396503.0],
                      ['2014-12-31', 28774019.0],
                      ['2013-12-31', 28153079.0],
                      ['2012-12-31', 27529595.0],
                      ['2011-12-31', 26900149.0],
                      ['2010-12-31', 26267053.0],
                      ['2009-12-31', 25615419.0],
                      ['2008-12-31', 24955735.0],
                      ['2007-12-31', 24300791.0],
                      ['2006-12-31', 23681565.0],
                      ['2005-12-31', 23112789.0],
                      ['2004-12-31', 22600520.0],
                      ['2003-12-31', 22141340.0],
                      ['2002-12-31', 21722065.0],
                      ['2001-12-31', 21324121.0],
                      ['2000-12-31', 20939372.0],
                      ['1999-12-31', 20549707.0],
                      ['1998-12-31', 20170823.0],
                      ['1997-12-31', 19820997.0],
                      ['1996-12-31', 19478909.0],
                      ['1995-12-31', 19149327.0],
                      ['1994-12-31', 18829542.0],
                      ['1993-12-31', 18507861.0],
                      ['1992-12-31', 18191020.0],
                      ['1991-12-31', 17850910.0],
                      ['1990-12-31', 17470899.0],
                      ['1989-12-31', 17075243.0],
                      ['1988-12-31', 16657359.0],
                      ['1987-12-31', 16230440.0],
                      ['1986-12-31', 15805945.0],
                      ['1985-12-31', 15397918.0],
                      ['1984-12-31', 15008538.0],
                      ['1983-12-31', 14639787.0],
                      ['1982-12-31', 14286062.0],
                      ['1981-12-31', 13946143.0],
                      ['1980-12-31', 13628831.0],
                      ['1979-12-31', 13332553.0],
                      ['1978-12-31', 13058255.0],
                      ['1977-12-31', 12802730.0],
                      ['1976-12-31', 12553340.0],
                      ['1975-12-31', 12306778.0],
                      ['1974-12-31', 12059314.0],
                      ['1973-12-31', 11816118.0],
                      ['1972-12-31', 11575349.0],
                      ['1971-12-31', 11337824.0],
                      ['1970-12-31', 11107495.0],
                      ['1969-12-31', 10888229.0],
                      ['1968-12-31', 10676961.0],
                      ['1967-12-31', 10473132.0],
                      ['1966-12-31', 10278079.0],
                      ['1965-12-31', 10086706.0],
                      ['1964-12-31', 9898587.0],
                      ['1963-12-31', 9715748.0],
                      ['1962-12-31', 9539303.0],
                      ['1961-12-31', 9366201.0],
                      ['1960-12-31', 9196324.0],
                      ['1959-12-31', 8981906.0],
                      ['1958-12-31', 8820804.0],
                      ['1957-12-31', 8663143.0],
                      ['1956-12-31', 8509584.0],
                      ['1955-12-31', 8396572.0],
                      ['1954-12-31', 8216742.0],
                      ['1953-12-31', 8077890.0],
                      ['1952-12-31', 7943827.0],
                      ['1951-12-31', 7813998.0],
                      ['1950-12-31', 7720590.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'OSS_SP_POP_TOTL',
             'description': 'Population, total - Other small states. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22200811,
             'limit': None,
             'name': 'Population, total - Other small states',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:41:10.756Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
PSS
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 2419188.0],
                      ['2016-12-31', 2388875.0],
                      ['2015-12-31', 2358955.0],
                      ['2014-12-31', 2329458.0],
                      ['2013-12-31', 2300045.0],
                      ['2012-12-31', 2271298.0],
                      ['2011-12-31', 2242763.0],
                      ['2010-12-31', 2214096.0],
                      ['2009-12-31', 2184837.0],
                      ['2008-12-31', 2155339.0],
                      ['2007-12-31', 2126235.0],
                      ['2006-12-31', 2098492.0],
                      ['2005-12-31', 2072665.0],
                      ['2004-12-31', 2049025.0],
                      ['2003-12-31', 2027212.0],
                      ['2002-12-31', 2006448.0],
                      ['2001-12-31', 1985712.0],
                      ['2000-12-31', 1964216.0],
                      ['1999-12-31', 1941848.0],
                      ['1998-12-31', 1918741.0],
                      ['1997-12-31', 1894564.0],
                      ['1996-12-31', 1869026.0],
                      ['1995-12-31', 1841944.0],
                      ['1994-12-31', 1812877.0],
                      ['1993-12-31', 1782065.0],
                      ['1992-12-31', 1750902.0],
                      ['1991-12-31', 1721262.0],
                      ['1990-12-31', 1694408.0],
                      ['1989-12-31', 1671076.0],
                      ['1988-12-31', 1650645.0],
                      ['1987-12-31', 1631160.0],
                      ['1986-12-31', 1609916.0],
                      ['1985-12-31', 1585014.0],
                      ['1984-12-31', 1555765.0],
                      ['1983-12-31', 1523011.0],
                      ['1982-12-31', 1488183.0],
                      ['1981-12-31', 1453516.0],
                      ['1980-12-31', 1420671.0],
                      ['1979-12-31', 1390032.0],
                      ['1978-12-31', 1361131.0],
                      ['1977-12-31', 1333618.0],
                      ['1976-12-31', 1306931.0],
                      ['1975-12-31', 1280559.0],
                      ['1974-12-31', 1254518.0],
                      ['1973-12-31', 1228877.0],
                      ['1972-12-31', 1203419.0],
                      ['1971-12-31', 1177890.0],
                      ['1970-12-31', 1152036.0],
                      ['1969-12-31', 1125870.0],
                      ['1968-12-31', 1099416.0],
                      ['1967-12-31', 1072398.0],
                      ['1966-12-31', 1044547.0],
                      ['1965-12-31', 1015765.0],
                      ['1964-12-31', 985873.0],
                      ['1963-12-31', 955101.0],
                      ['1962-12-31', 924221.0],
                      ['1961-12-31', 894214.0],
                      ['1960-12-31', 865809.0],
                      ['1959-12-31', 839287.0],
                      ['1958-12-31', 814551.0],
                      ['1957-12-31', 791235.0],
                      ['1956-12-31', 768922.0],
                      ['1955-12-31', 747283.0],
                      ['1954-12-31', 726177.0],
                      ['1953-12-31', 705524.0],
                      ['1952-12-31', 685598.0],
                      ['1951-12-31', 666722.0],
                      ['1950-12-31', 649406.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'PSS_SP_POP_TOTL',
             'description': 'Population, total - Pacific island small states. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22220298,
             'limit': None,
             'name': 'Population, total - Pacific island small states',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:42:14.846Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
PAK
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 197015955.0],
                      ['2016-12-31', 193203476.0],
                      ['2015-12-31', 189380513.0],
                      ['2014-12-31', 185546257.0],
                      ['2013-12-31', 181712595.0],
                      ['2012-12-31', 177911533.0],
                      ['2011-12-31', 174184265.0],

                      ['2010-12-31', 170560182.0],
                      ['2009-12-31', 167049580.0],
                      ['2008-12-31', 163644603.0],
                      ['2007-12-31', 160332974.0],
                      ['2006-12-31', 157093993.0],
                      ['2005-12-31', 153909667.0],
                      ['2004-12-31', 150780300.0],
                      ['2003-12-31', 147703401.0],
                      ['2002-12-31', 144654143.0],
                      ['2001-12-31', 141601437.0],
                      ['2000-12-31', 138523285.0],
                      ['1999-12-31', 135405584.0],
                      ['1998-12-31', 132253264.0],
                      ['1997-12-31', 129086987.0],
                      ['1996-12-31', 125938339.0],
                      ['1995-12-31', 122829148.0],
                      ['1994-12-31', 119769556.0],
                      ['1993-12-31', 116749560.0],
                      ['1992-12-31', 113747135.0],
                      ['1991-12-31', 110730420.0],
                      ['1990-12-31', 107678614.0],
                      ['1989-12-31', 104588490.0],
                      ['1988-12-31', 101474835.0],
                      ['1987-12-31', 98357473.0],
                      ['1986-12-31', 95264460.0],
                      ['1985-12-31', 92219488.0],
                      ['1984-12-31', 89228949.0],
                      ['1983-12-31', 86297640.0],
                      ['1982-12-31', 83445863.0],
                      ['1981-12-31', 80696945.0],
                      ['1980-12-31', 78068144.0],
                      ['1979-12-31', 75567682.0],
                      ['1978-12-31', 73194937.0],
                      ['1977-12-31', 70946231.0],
                      ['1976-12-31', 68813220.0],
                      ['1975-12-31', 66787901.0],
                      ['1974-12-31', 64870833.0],
                      ['1973-12-31', 63059481.0],
                      ['1972-12-31', 61338261.0],
                      ['1971-12-31', 59687140.0],
                      ['1970-12-31', 58090759.0],
                      ['1969-12-31', 56542434.0],
                      ['1968-12-31', 55042397.0],
                      ['1967-12-31', 53590929.0],
                      ['1966-12-31', 52191095.0],
                      ['1965-12-31', 50845221.0],
                      ['1964-12-31', 49551904.0],
                      ['1963-12-31', 48309315.0],
                      ['1962-12-31', 47119361.0],
                      ['1961-12-31', 45984892.0],
                      ['1960-12-31', 44908293.0],
                      ['1959-12-31', 43890982.0],
                      ['1958-12-31', 42933593.0],
                      ['1957-12-31', 42036393.0],
                      ['1956-12-31', 41199696.0],
                      ['1955-12-31', 40424296.0],
                      ['1954-12-31', 39711643.0],
                      ['1953-12-31', 39063874.0],
                      ['1952-12-31', 38483891.0],
                      ['1951-12-31', 37975281.0],
                      ['1950-12-31', 37542376.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'PAK_SP_POP_TOTL',
             'description': 'Population, total - Pakistan. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22202586,
             'limit': None,
             'name': 'Population, total - Pakistan',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:41:16.635Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
PLW
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 21729.0],
                      ['2016-12-31', 21503.0],
                      ['2015-12-31', 21288.0],
                      ['2014-12-31', 21094.0],
                      ['2013-12-31', 20920.0],
                      ['2012-12-31', 20758.0],
                      ['2011-12-31', 20599.0],
                      ['2010-12-31', 20470.0],
                      ['2009-12-31', 20342.0],
                      ['2008-12-31', 20228.0],
                      ['2007-12-31', 20116.0],
                      ['2006-12-31', 20012.0],
                      ['2005-12-31', 19906.0],
                      ['2004-12-31', 19804.0],
                      ['2003-12-31', 19700.0],
                      ['2002-12-31', 19574.0],
                      ['2001-12-31', 19404.0],
                      ['2000-12-31', 19175.0],
                      ['1999-12-31', 18879.0],
                      ['1998-12-31', 18524.0],
                      ['1997-12-31', 18123.0],
                      ['1996-12-31', 17691.0],
                      ['1995-12-31', 17253.0],
                      ['1994-12-31', 16806.0],
                      ['1993-12-31', 16342.0],
                      ['1992-12-31', 15894.0],
                      ['1991-12-31', 15474.0],
                      ['1990-12-31', 15088.0],
                      ['1989-12-31', 14757.0],
                      ['1988-12-31', 14490.0],
                      ['1987-12-31', 14240.0],
                      ['1986-12-31', 13985.0],
                      ['1985-12-31', 13696.0],
                      ['1984-12-31', 13372.0],
                      ['1983-12-31', 13012.0],
                      ['1982-12-31', 12663.0],
                      ['1981-12-31', 12387.0],
                      ['1980-12-31', 12194.0],
                      ['1979-12-31', 12124.0],
                      ['1978-12-31', 12153.0],
                      ['1977-12-31', 12225.0],
                      ['1976-12-31', 12285.0],
                      ['1975-12-31', 12278.0],
                      ['1974-12-31', 12197.0],
                      ['1973-12-31', 12046.0],
                      ['1972-12-31', 11852.0],
                      ['1971-12-31', 11654.0],
                      ['1970-12-31', 11480.0],
                      ['1969-12-31', 11331.0],
                      ['1968-12-31', 11205.0],
                      ['1967-12-31', 11080.0],
                      ['1966-12-31', 10946.0],
                      ['1965-12-31', 10782.0],
                      ['1964-12-31', 10593.0],
                      ['1963-12-31', 10378.0],
                      ['1962-12-31', 10151.0],
                      ['1961-12-31', 9900.0],
                      ['1960-12-31', 9642.0],
                      ['1959-12-31', 9359.0],
                      ['1958-12-31', 9087.0],
                      ['1957-12-31', 8802.0],
                      ['1956-12-31', 8524.0],
                      ['1955-12-31', 8255.0],
                      ['1954-12-31', 8014.0],
                      ['1953-12-31', 7791.0],
                      ['1952-12-31', 7613.0],
                      ['1951-12-31', 7497.0],
                      ['1950-12-31', 7441.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'PLW_SP_POP_TOTL',
             'description': 'Population, total - Palau. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22209112,
             'limit': None,
             'name': 'Population, total - Palau',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:41:38.973Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
PAN
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 4098587.0],
                      ['2016-12-31', 4034119.0],
                      ['2015-12-31', 3969249.0],
                      ['2014-12-31', 3903986.0],
                      ['2013-12-31', 3838462.0],
                      ['2012-12-31', 3772938.0],
                      ['2011-12-31', 3707782.0],
                      ['2010-12-31', 3643222.0],
                      ['2009-12-31', 3579385.0],
                      ['2008-12-31', 3516268.0],
                      ['2007-12-31', 3453807.0],
                      ['2006-12-31', 3391905.0],
                      ['2005-12-31', 3330465.0],
                      ['2004-12-31', 3269541.0],
                      ['2003-12-31', 3209174.0],
                      ['2002-12-31', 3149265.0],
                      ['2001-12-31', 3089684.0],
                      ['2000-12-31', 3030347.0],
                      ['1999-12-31', 2971197.0],
                      ['1998-12-31', 2912328.0],
                      ['1997-12-31', 2853941.0],
                      ['1996-12-31', 2796344.0],
                      ['1995-12-31', 2739730.0],
                      ['1994-12-31', 2684183.0],
                      ['1993-12-31', 2629644.0],
                      ['1992-12-31', 2576018.0],
                      ['1991-12-31', 2523181.0],
                      ['1990-12-31', 2471009.0],
                      ['1989-12-31', 2419491.0],
                      ['1988-12-31', 2368618.0],
                      ['1987-12-31', 2318332.0],
                      ['1986-12-31', 2268574.0],
                      ['1985-12-31', 2219276.0],
                      ['1984-12-31', 2170409.0],
                      ['1983-12-31', 2121939.0],
                      ['1982-12-31', 2073844.0],
                      ['1981-12-31', 2026065.0],
                      ['1980-12-31', 1978578.0],
                      ['1979-12-31', 1931389.0],
                      ['1978-12-31', 1884515.0],
                      ['1977-12-31', 1837890.0],
                      ['1976-12-31', 1791453.0],
                      ['1975-12-31', 1745205.0],
                      ['1974-12-31', 1699113.0],
                      ['1973-12-31', 1653256.0],
                      ['1972-12-31', 1607834.0],
                      ['1971-12-31', 1563115.0],
                      ['1970-12-31', 1519299.0],
                      ['1969-12-31', 1476479.0],
                      ['1968-12-31', 1434657.0],
                      ['1967-12-31', 1393799.0],
                      ['1966-12-31', 1353804.0],
                      ['1965-12-31', 1314626.0],
                      ['1964-12-31', 1276276.0],
                      ['1963-12-31', 1238823.0],
                      ['1962-12-31', 1202373.0],
                      ['1961-12-31', 1167035.0],
                      ['1960-12-31', 1132921.0],
                      ['1959-12-31', 1100067.0],
                      ['1958-12-31', 1068471.0],
                      ['1957-12-31', 1038127.0],
                      ['1956-12-31', 1008980.0],
                      ['1955-12-31', 981032.0],
                      ['1954-12-31', 954268.0],
                      ['1953-12-31', 928712.0],
                      ['1952-12-31', 904386.0],
                      ['1951-12-31', 881344.0],
                      ['1950-12-31', 859659.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'PAN_SP_POP_TOTL',
             'description': 'Population, total - Panama. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22204577,
             'limit': None,
             'name': 'Population, total - Panama',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:41:22.607Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
PNG

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 8251162.0],
                      ['2016-12-31', 8084991.0],
                      ['2015-12-31', 7919825.0],
                      ['2014-12-31', 7755785.0],
                      ['2013-12-31', 7592865.0],
                      ['2012-12-31', 7430836.0],
                      ['2011-12-31', 7269348.0],
                      ['2010-12-31', 7108239.0],
                      ['2009-12-31', 6947447.0],
                      ['2008-12-31', 6787187.0],
                      ['2007-12-31', 6627922.0],
                      ['2006-12-31', 6470272.0],
                      ['2005-12-31', 6314709.0],
                      ['2004-12-31', 6161517.0],
                      ['2003-12-31', 6010724.0],
                      ['2002-12-31', 5862316.0],
                      ['2001-12-31', 5716152.0],
                      ['2000-12-31', 5572222.0],
                      ['1999-12-31', 5430479.0],
                      ['1998-12-31', 5291178.0],
                      ['1997-12-31', 5154910.0],
                      ['1996-12-31', 5022437.0],
                      ['1995-12-31', 4894276.0],
                      ['1994-12-31', 4770606.0],
                      ['1993-12-31', 4651169.0],
                      ['1992-12-31', 4535520.0],
                      ['1991-12-31', 4423007.0],
                      ['1990-12-31', 4313059.0],
                      ['1989-12-31', 4205654.0],
                      ['1988-12-31', 4100729.0],
                      ['1987-12-31', 3997702.0],
                      ['1986-12-31', 3895852.0],
                      ['1985-12-31', 3794720.0],
                      ['1984-12-31', 3694041.0],
                      ['1983-12-31', 3594004.0],
                      ['1982-12-31', 3495199.0],
                      ['1981-12-31', 3398469.0],
                      ['1980-12-31', 3304473.0],
                      ['1979-12-31', 3213360.0],
                      ['1978-12-31', 3125034.0],
                      ['1977-12-31', 3039660.0],
                      ['1976-12-31', 2957339.0],
                      ['1975-12-31', 2878156.0],
                      ['1974-12-31', 2802243.0],
                      ['1973-12-31', 2729580.0],
                      ['1972-12-31', 2659851.0],
                      ['1971-12-31', 2592628.0],
                      ['1970-12-31', 2527586.0],
                      ['1969-12-31', 2464548.0],
                      ['1968-12-31', 2403595.0],
                      ['1967-12-31', 2344977.0],
                      ['1966-12-31', 2289109.0],
                      ['1965-12-31', 2236206.0],
                      ['1964-12-31', 2186340.0],
                      ['1963-12-31', 2139303.0],
                      ['1962-12-31', 2094687.0],
                      ['1961-12-31', 2051947.0],
                      ['1960-12-31', 2010677.0],
                      ['1959-12-31', 1970694.0],
                      ['1958-12-31', 1931986.0],
                      ['1957-12-31', 1894678.0],
                      ['1956-12-31', 1858885.0],
                      ['1955-12-31', 1824712.0],
                      ['1954-12-31', 1792140.0],
                      ['1953-12-31', 1761050.0],
                      ['1952-12-31', 1731230.0],
                      ['1951-12-31', 1702370.0],
                      ['1950-12-31', 1674036.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'PNG_SP_POP_TOTL',
             'description': 'Population, total - Papua New Guinea. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22210518,
             'limit': None,
             'name': 'Population, total - Papua New Guinea',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:41:44.133Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
PRY
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 6811297.0],
                      ['2016-12-31', 6725308.0],
                      ['2015-12-31', 6639119.0],
                      ['2014-12-31', 6552584.0],
                      ['2013-12-31', 6465740.0],
                      ['2012-12-31', 6379219.0],
                      ['2011-12-31', 6293783.0],
                      ['2010-12-31', 6209877.0],
                      ['2009-12-31', 6127837.0],
                      ['2008-12-31', 6047117.0],
                      ['2007-12-31', 5966159.0],
                      ['2006-12-31', 5882796.0],
                      ['2005-12-31', 5795494.0],
                      ['2004-12-31', 5703740.0],
                      ['2003-12-31', 5607950.0],
                      ['2002-12-31', 5508611.0],
                      ['2001-12-31', 5406624.0],
                      ['2000-12-31', 5302700.0],
                      ['1999-12-31', 5196937.0],
                      ['1998-12-31', 5089310.0],
                      ['1997-12-31', 4980344.0],
                      ['1996-12-31', 4870694.0],
                      ['1995-12-31', 4760850.0],
                      ['1994-12-31', 4651225.0],
                      ['1993-12-31', 4541902.0],
                      ['1992-12-31', 4432736.0],
                      ['1991-12-31', 4323410.0],
                      ['1990-12-31', 4213742.0],
                      ['1989-12-31', 4103911.0],
                      ['1988-12-31', 3994331.0],
                      ['1987-12-31', 3885436.0],
                      ['1986-12-31', 3777763.0],
                      ['1985-12-31', 3671826.0],
                      ['1984-12-31', 3567752.0],
                      ['1983-12-31', 3465793.0],
                      ['1982-12-31', 3366719.0],
                      ['1981-12-31', 3271456.0],
                      ['1980-12-31', 3180630.0],
                      ['1979-12-31', 3094482.0],
                      ['1978-12-31', 3012829.0],
                      ['1977-12-31', 2935375.0],
                      ['1976-12-31', 2861581.0],
                      ['1975-12-31', 2790962.0],
                      ['1974-12-31', 2723523.0],
                      ['1973-12-31', 2659088.0],
                      ['1972-12-31', 2596739.0],
                      ['1971-12-31', 2535359.0],
                      ['1970-12-31', 2474106.0],
                      ['1969-12-31', 2412566.0],
                      ['1968-12-31', 2350901.0],
                      ['1967-12-31', 2289582.0],
                      ['1966-12-31', 2229376.0],
                      ['1965-12-31', 2170859.0],
                      ['1964-12-31', 2114095.0],
                      ['1963-12-31', 2058915.0],
                      ['1962-12-31', 2005337.0],
                      ['1961-12-31', 1953328.0],
                      ['1960-12-31', 1902875.0],
                      ['1959-12-31', 1853939.0],
                      ['1958-12-31', 1806519.0],
                      ['1957-12-31', 1760578.0],
                      ['1956-12-31', 1716108.0],
                      ['1955-12-31', 1673009.0],
                      ['1954-12-31', 1631186.0],
                      ['1953-12-31', 1590497.0],
                      ['1952-12-31', 1550757.0],
                      ['1951-12-31', 1511767.0],
                      ['1950-12-31', 1473253.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'PRY_SP_POP_TOTL',
             'description': 'Population, total - Paraguay. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22217286,
             'limit': None,
             'name': 'Population, total - Paraguay',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:42:05.981Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
PER
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 32165485.0],
                      ['2016-12-31', 31773839.0],
                      ['2015-12-31', 31376671.0],
                      ['2014-12-31', 30973354.0],
                      ['2013-12-31', 30565716.0],
                      ['2012-12-31', 30158966.0],
                      ['2011-12-31', 29759989.0],
                      ['2010-12-31', 29373646.0],
                      ['2009-12-31', 29001507.0],
                      ['2008-12-31', 28641980.0],
                      ['2007-12-31', 28292724.0],
                      ['2006-12-31', 27949944.0],
                      ['2005-12-31', 27610410.0],
                      ['2004-12-31', 27273194.0],
                      ['2003-12-31', 26937738.0],
                      ['2002-12-31', 26601467.0],
                      ['2001-12-31', 26261363.0],
                      ['2000-12-31', 25914879.0],
                      ['1999-12-31', 25561299.0],
                      ['1998-12-31', 25199748.0],
                      ['1997-12-31', 24827406.0],
                      ['1996-12-31', 24441074.0],
                      ['1995-12-31', 24038760.0],
                      ['1994-12-31', 23619356.0],
                      ['1993-12-31', 23184228.0],
                      ['1992-12-31', 22737056.0],
                      ['1991-12-31', 22283128.0],
                      ['1990-12-31', 21826658.0],
                      ['1989-12-31', 21368859.0],
                      ['1988-12-31', 20909895.0],
                      ['1987-12-31', 20451710.0],
                      ['1986-12-31', 19996253.0],
                      ['1985-12-31', 19544956.0],
                      ['1984-12-31', 19099584.0],
                      ['1983-12-31', 18660439.0],
                      ['1982-12-31', 18225730.0],
                      ['1981-12-31', 17792549.0],
                      ['1980-12-31', 17359120.0],
                      ['1979-12-31', 16924753.0],
                      ['1978-12-31', 16491083.0],
                      ['1977-12-31', 16061323.0],

                      ['1976-12-31', 15639901.0],
                      ['1975-12-31', 15229947.0],
                      ['1974-12-31', 14832841.0],
                      ['1973-12-31', 14447648.0],
                      ['1972-12-31', 14072476.0],
                      ['1971-12-31', 13704335.0],
                      ['1970-12-31', 13341069.0],
                      ['1969-12-31', 12982449.0],
                      ['1968-12-31', 12629329.0],
                      ['1967-12-31', 12282082.0],
                      ['1966-12-31', 11941325.0],
                      ['1965-12-31', 11607681.0],
                      ['1964-12-31', 11281015.0],
                      ['1963-12-31', 10961540.0],
                      ['1962-12-31', 10650667.0],
                      ['1961-12-31', 10350242.0],
                      ['1960-12-31', 10061515.0],
                      ['1959-12-31', 9784910.0],
                      ['1958-12-31', 9520047.0],
                      ['1957-12-31', 9266079.0],
                      ['1956-12-31', 9021961.0],
                      ['1955-12-31', 8786757.0],
                      ['1954-12-31', 8559718.0],
                      ['1953-12-31', 8340377.0],
                      ['1952-12-31', 8128523.0],
                      ['1951-12-31', 7924210.0],
                      ['1950-12-31', 7727734.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'PER_SP_POP_TOTL',
             'description': 'Population, total - Peru. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22206249,
             'limit': None,
             'name': 'Population, total - Peru',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:41:28.640Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
PHL
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 104918090.0],
                      ['2016-12-31', 103320222.0],
                      ['2015-12-31', 101716359.0],
                      ['2014-12-31', 100102249.0],
                      ['2013-12-31', 98481032.0],
                      ['2012-12-31', 96866642.0],
                      ['2011-12-31', 95277940.0],
                      ['2010-12-31', 93726624.0],
                      ['2009-12-31', 92220879.0],
                      ['2008-12-31', 90751864.0],
                      ['2007-12-31', 89293490.0],
                      ['2006-12-31', 87809419.0],
                      ['2005-12-31', 86274237.0],
                      ['2004-12-31', 84678493.0],
                      ['2003-12-31', 83031954.0],
                      ['2002-12-31', 81352060.0],
                      ['2001-12-31', 79665315.0],
                      ['2000-12-31', 77991569.0],
                      ['1999-12-31', 76335812.0],
                      ['1998-12-31', 74693695.0],
                      ['1997-12-31', 73064764.0],
                      ['1996-12-31', 71446107.0],
                      ['1995-12-31', 69835715.0],
                      ['1994-12-31', 68236230.0],
                      ['1993-12-31', 66650247.0],
                      ['1992-12-31', 65075486.0],
                      ['1991-12-31', 63508459.0],
                      ['1990-12-31', 61947348.0],
                      ['1989-12-31', 60391867.0],
                      ['1988-12-31', 58845205.0],
                      ['1987-12-31', 57313311.0],
                      ['1986-12-31', 55804072.0],
                      ['1985-12-31', 54323648.0],
                      ['1984-12-31', 52873974.0],
                      ['1983-12-31', 51455033.0],
                      ['1982-12-31', 50068493.0],
                      ['1981-12-31', 48715592.0],
                      ['1980-12-31', 47396968.0],
                      ['1979-12-31', 46113995.0],
                      ['1978-12-31', 44866273.0],
                      ['1977-12-31', 43650333.0],
                      ['1976-12-31', 42461193.0],
                      ['1975-12-31', 41295124.0],
                      ['1974-12-31', 40149961.0],
                      ['1973-12-31', 39026082.0],
                      ['1972-12-31', 37925400.0],
                      ['1971-12-31', 36851055.0],
                      ['1970-12-31', 35804729.0],
                      ['1969-12-31', 34787588.0],
                      ['1968-12-31', 33797042.0],
                      ['1967-12-31', 32826599.0],
                      ['1966-12-31', 31867563.0],
                      ['1965-12-31', 30913933.0],
                      ['1964-12-31', 29962876.0],
                      ['1963-12-31', 29016771.0],
                      ['1962-12-31', 28081231.0],
                      ['1961-12-31', 27164617.0],
                      ['1960-12-31', 26273025.0],
                      ['1959-12-31', 25408603.0],
                      ['1958-12-31', 24570175.0],
                      ['1957-12-31', 23754593.0],
                      ['1956-12-31', 22958355.0],
                      ['1955-12-31', 22179101.0],
                      ['1954-12-31', 21416100.0],
                      ['1953-12-31', 20670544.0],
                      ['1952-12-31', 19945661.0],
                      ['1951-12-31', 19246611.0],
                      ['1950-12-31', 18580490.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'PHL_SP_POP_TOTL',
             'description': 'Population, total - Philippines. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22208107,
             'limit': None,
             'name': 'Population, total - Philippines',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:41:34.826Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
POL
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 37975841.0],
                      ['2016-12-31', 37970087.0],
                      ['2015-12-31', 37986412.0],
                      ['2014-12-31', 38011735.0],
                      ['2013-12-31', 38040196.0],
                      ['2012-12-31', 38063164.0],
                      ['2011-12-31', 38063255.0],
                      ['2010-12-31', 38042794.0],
                      ['2009-12-31', 38151603.0],
                      ['2008-12-31', 38125759.0],
                      ['2007-12-31', 38120560.0],
                      ['2006-12-31', 38141267.0],
                      ['2005-12-31', 38165445.0],
                      ['2004-12-31', 38182222.0],
                      ['2003-12-31', 38204570.0],
                      ['2002-12-31', 38230364.0],
                      ['2001-12-31', 38248076.0],
                      ['2000-12-31', 38258629.0],
                      ['1999-12-31', 38660271.0],
                      ['1998-12-31', 38663481.0],
                      ['1997-12-31', 38649660.0],
                      ['1996-12-31', 38624370.0],
                      ['1995-12-31', 38594998.0],
                      ['1994-12-31', 38542652.0],
                      ['1993-12-31', 38461408.0],
                      ['1992-12-31', 38363667.0],
                      ['1991-12-31', 38246193.0],
                      ['1990-12-31', 38110782.0],
                      ['1989-12-31', 37961529.0],
                      ['1988-12-31', 37824487.0],
                      ['1987-12-31', 37668045.0],
                      ['1986-12-31', 37456119.0],
                      ['1985-12-31', 37201885.0],
                      ['1984-12-31', 36904134.0],
                      ['1983-12-31', 36571808.0],
                      ['1982-12-31', 36230481.0],
                      ['1981-12-31', 35898587.0],
                      ['1980-12-31', 35574150.0],
                      ['1979-12-31', 35247217.0],
                      ['1978-12-31', 34965600.0],
                      ['1977-12-31', 34689050.0],
                      ['1976-12-31', 34356300.0],
                      ['1975-12-31', 34015199.0],
                      ['1974-12-31', 33678899.0],
                      ['1973-12-31', 33357200.0],
                      ['1972-12-31', 33055650.0],
                      ['1971-12-31', 32783500.0],
                      ['1970-12-31', 32664300.0],
                      ['1969-12-31', 32548300.0],
                      ['1968-12-31', 32294655.0],
                      ['1967-12-31', 31987155.0],
                      ['1966-12-31', 31681000.0],
                      ['1965-12-31', 31444950.0],
                      ['1964-12-31', 31139450.0],
                      ['1963-12-31', 30712000.0],
                      ['1962-12-31', 30308500.0],
                      ['1961-12-31', 29964000.0],
                      ['1960-12-31', 29637450.0],
                      ['1959-12-31', 28665037.0],
                      ['1958-12-31', 28324111.0],
                      ['1957-12-31', 27992667.0],
                      ['1956-12-31', 27650608.0],
                      ['1955-12-31', 27280997.0],
                      ['1954-12-31', 26871945.0],
                      ['1953-12-31', 26417754.0],
                      ['1952-12-31', 25919296.0],
                      ['1951-12-31', 25383633.0],
                      ['1950-12-31', 24824013.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'POL_SP_POP_TOTL',
             'description': 'Population, total - Poland. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22212406,
             'limit': None,
             'name': 'Population, total - Poland',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:41:49.473Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
PRT

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 10293718.0],
                      ['2016-12-31', 10325452.0],
                      ['2015-12-31', 10358076.0],
                      ['2014-12-31', 10401062.0],
                      ['2013-12-31', 10457295.0],
                      ['2012-12-31', 10514844.0],
                      ['2011-12-31', 10557560.0],
                      ['2010-12-31', 10573100.0],
                      ['2009-12-31', 10568247.0],
                      ['2008-12-31', 10558177.0],
                      ['2007-12-31', 10542964.0],
                      ['2006-12-31', 10522288.0],
                      ['2005-12-31', 10503330.0],
                      ['2004-12-31', 10483861.0],
                      ['2003-12-31', 10458821.0],
                      ['2002-12-31', 10419631.0],
                      ['2001-12-31', 10362722.0],
                      ['2000-12-31', 10289898.0],
                      ['1999-12-31', 10217828.0],
                      ['1998-12-31', 10160196.0],
                      ['1997-12-31', 10108977.0],
                      ['1996-12-31', 10063945.0],
                      ['1995-12-31', 10026176.0],
                      ['1994-12-31', 9991525.0],
                      ['1993-12-31', 9964675.0],
                      ['1992-12-31', 9952494.0],
                      ['1991-12-31', 9960235.0],
                      ['1990-12-31', 9983218.0],
                      ['1989-12-31', 10005000.0],
                      ['1988-12-31', 10019610.0],
                      ['1987-12-31', 10030031.0],
                      ['1986-12-31', 10032734.0],
                      ['1985-12-31', 10023613.0],
                      ['1984-12-31', 9996232.0],
                      ['1983-12-31', 9957865.0],
                      ['1982-12-31', 9911771.0],
                      ['1981-12-31', 9851362.0],
                      ['1980-12-31', 9766312.0],
                      ['1979-12-31', 9661265.0],
                      ['1978-12-31', 9558250.0],
                      ['1977-12-31', 9455675.0],
                      ['1976-12-31', 9355810.0],
                      ['1975-12-31', 9093470.0],
                      ['1974-12-31', 8754365.0],
                      ['1973-12-31', 8633100.0],
                      ['1972-12-31', 8630430.0],
                      ['1971-12-31', 8643756.0],
                      ['1970-12-31', 8680431.0],
                      ['1969-12-31', 8757705.0],
                      ['1968-12-31', 8836650.0],
                      ['1967-12-31', 8874520.0],
                      ['1966-12-31', 8930990.0],
                      ['1965-12-31', 8998595.0],
                      ['1964-12-31', 9035365.0],
                      ['1963-12-31', 9030355.0],
                      ['1962-12-31', 8993985.0],
                      ['1961-12-31', 8929316.0],
                      ['1960-12-31', 8857716.0],
                      ['1959-12-31', 8853393.0],
                      ['1958-12-31', 8818242.0],
                      ['1957-12-31', 8775803.0],
                      ['1956-12-31', 8724773.0],
                      ['1955-12-31', 8665530.0],
                      ['1954-12-31', 8600563.0],
                      ['1953-12-31', 8534730.0],
                      ['1952-12-31', 8475340.0],
                      ['1951-12-31', 8432070.0],
                      ['1950-12-31', 8416969.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'PRT_SP_POP_TOTL',
             'description': 'Population, total - Portugal. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22215447,
             'limit': None,
             'name': 'Population, total - Portugal',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:42:00.087Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
PRI
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 3337177.0],
                      ['2016-12-31', 3406520.0],
                      ['2015-12-31', 3473177.0],
                      ['2014-12-31', 3534874.0],
                      ['2013-12-31', 3593077.0],
                      ['2012-12-31', 3634488.0],
                      ['2011-12-31', 3678732.0],
                      ['2010-12-31', 3721525.0],
                      ['2009-12-31', 3740410.0],
                      ['2008-12-31', 3760866.0],
                      ['2007-12-31', 3782995.0],
                      ['2006-12-31', 3805214.0],
                      ['2005-12-31', 3821362.0],
                      ['2004-12-31', 3826878.0],
                      ['2003-12-31', 3826095.0],
                      ['2002-12-31', 3823701.0],
                      ['2001-12-31', 3818774.0],
                      ['2000-12-31', 3810605.0],
                      ['1999-12-31', 3800081.0],
                      ['1998-12-31', 3781101.0],
                      ['1997-12-31', 3759430.0],
                      ['1996-12-31', 3724655.0],
                      ['1995-12-31', 3683103.0],
                      ['1994-12-31', 3649237.0],
                      ['1993-12-31', 3615497.0],
                      ['1992-12-31', 3585176.0],
                      ['1991-12-31', 3562110.0],
                      ['1990-12-31', 3537000.0],
                      ['1989-12-31', 3505650.0],
                      ['1988-12-31', 3473898.0],
                      ['1987-12-31', 3441850.0],
                      ['1986-12-31', 3409554.0],
                      ['1985-12-31', 3377000.0],
                      ['1984-12-31', 3344190.0],
                      ['1983-12-31', 3311138.0],
                      ['1982-12-31', 3277453.0],
                      ['1981-12-31', 3242552.0],
                      ['1980-12-31', 3206000.0],
                      ['1979-12-31', 3168088.0],
                      ['1978-12-31', 3129421.0],
                      ['1977-12-31', 3088690.0],
                      ['1976-12-31', 3043854.0],
                      ['1975-12-31', 2994000.0],
                      ['1974-12-31', 2939299.0],
                      ['1973-12-31', 2878786.0],
                      ['1972-12-31', 2817256.0],
                      ['1971-12-31', 2762190.0],
                      ['1970-12-31', 2718000.0],
                      ['1969-12-31', 2684150.0],
                      ['1968-12-31', 2662064.0],
                      ['1967-12-31', 2645674.0],
                      ['1966-12-31', 2624995.0],
                      ['1965-12-31', 2594000.0],
                      ['1964-12-31', 2554066.0],
                      ['1963-12-31', 2504530.0],
                      ['1962-12-31', 2450322.0],
                      ['1961-12-31', 2399722.0],
                      ['1960-12-31', 2358000.0],
                      ['1959-12-31', 2335993.0],
                      ['1958-12-31', 2314191.0],
                      ['1957-12-31', 2292593.0],
                      ['1956-12-31', 2271197.0],
                      ['1955-12-31', 2250000.0],
                      ['1954-12-31', 2243766.0],
                      ['1953-12-31', 2237548.0],
                      ['1952-12-31', 2231348.0],
                      ['1951-12-31', 2225166.0],
                      ['1950-12-31', 2219000.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'PRI_SP_POP_TOTL',
             'description': 'Population, total - Puerto Rico. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22213482,
             'limit': None,
             'name': 'Population, total - Puerto Rico',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:41:52.849Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
QAT

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 2639211.0],
                      ['2016-12-31', 2569804.0],
                      ['2015-12-31', 2481539.0],
                      ['2014-12-31', 2374419.0],
                      ['2013-12-31', 2250473.0],
                      ['2012-12-31', 2109568.0],
                      ['2011-12-31', 1952054.0],
                      ['2010-12-31', 1779676.0],
                      ['2009-12-31', 1590780.0],
                      ['2008-12-31', 1389342.0],
                      ['2007-12-31', 1189633.0],
                      ['2006-12-31', 1010382.0],
                      ['2005-12-31', 864863.0],
                      ['2004-12-31', 758855.0],
                      ['2003-12-31', 688586.0],
                      ['2002-12-31', 645659.0],
                      ['2001-12-31', 616886.0],
                      ['2000-12-31', 592267.0],
                      ['1999-12-31', 569447.0],
                      ['1998-12-31', 550430.0],
                      ['1997-12-31', 534608.0],
                      ['1996-12-31', 522304.0],
                      ['1995-12-31', 513455.0],
                      ['1994-12-31', 507095.0],
                      ['1993-12-31', 501566.0],
                      ['1992-12-31', 495517.0],
                      ['1991-12-31', 487491.0],
                      ['1990-12-31', 476445.0],
                      ['1989-12-31', 461870.0],
                      ['1988-12-31', 443794.0],
                      ['1987-12-31', 422341.0],
                      ['1986-12-31', 397932.0],
                      ['1985-12-31', 371081.0],
                      ['1984-12-31', 341455.0],
                      ['1983-12-31', 309479.0],
                      ['1982-12-31', 277396.0],
                      ['1981-12-31', 248144.0],
                      ['1980-12-31', 223775.0],
                      ['1979-12-31', 205313.0],
                      ['1978-12-31', 192093.0],
                      ['1977-12-31', 182443.0],
                      ['1976-12-31', 173836.0],
                      ['1975-12-31', 164413.0],
                      ['1974-12-31', 153704.0],
                      ['1973-12-31', 142241.0],
                      ['1972-12-31', 130534.0],
                      ['1971-12-31', 119424.0],
                      ['1970-12-31', 109514.0],
                      ['1969-12-31', 100874.0],
                      ['1968-12-31', 93201.0],
                      ['1967-12-31', 86295.0],
                      ['1966-12-31', 79844.0],
                      ['1965-12-31', 73633.0],
                      ['1964-12-31', 67567.0],
                      ['1963-12-31', 61717.0],
                      ['1962-12-31', 56263.0],
                      ['1961-12-31', 51421.0],
                      ['1960-12-31', 47384.0],
                      ['1959-12-31', 44126.0],
                      ['1958-12-31', 41546.0],
                      ['1957-12-31', 39450.0],
                      ['1956-12-31', 37622.0],
                      ['1955-12-31', 35866.0],
                      ['1954-12-31', 34042.0],
                      ['1953-12-31', 32060.0],
                      ['1952-12-31', 29873.0],
                      ['1951-12-31', 27497.0],
                      ['1950-12-31', 25003.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'QAT_SP_POP_TOTL',
             'description': 'Population, total - Qatar. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22222470,
             'limit': None,
             'name': 'Population, total - Qatar',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:42:21.860Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
ROU
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 19586539.0],
                      ['2016-12-31', 19702332.0],
                      ['2015-12-31', 19815481.0],
                      ['2014-12-31', 19908979.0],
                      ['2013-12-31', 19983693.0],
                      ['2012-12-31', 20058035.0],
                      ['2011-12-31', 20147528.0],
                      ['2010-12-31', 20246871.0],
                      ['2009-12-31', 20367487.0],
                      ['2008-12-31', 20537875.0],
                      ['2007-12-31', 20882982.0],
                      ['2006-12-31', 21193760.0],
                      ['2005-12-31', 21319685.0],
                      ['2004-12-31', 21451748.0],
                      ['2003-12-31', 21574326.0],
                      ['2002-12-31', 21730496.0],
                      ['2001-12-31', 22131970.0],
                      ['2000-12-31', 22442971.0],
                      ['1999-12-31', 22472040.0],
                      ['1998-12-31', 22507344.0],
                      ['1997-12-31', 22553978.0],
                      ['1996-12-31', 22619004.0],
                      ['1995-12-31', 22684270.0],
                      ['1994-12-31', 22730211.0],
                      ['1993-12-31', 22763280.0],
                      ['1992-12-31', 22794284.0],
                      ['1991-12-31', 23001155.0],
                      ['1990-12-31', 23201835.0],
                      ['1989-12-31', 23161458.0],
                      ['1988-12-31', 23057662.0],
                      ['1987-12-31', 22949430.0],
                      ['1986-12-31', 22859269.0],
                      ['1985-12-31', 22755427.0],
                      ['1984-12-31', 22655940.0],
                      ['1983-12-31', 22588790.0],
                      ['1982-12-31', 22515389.0],
                      ['1981-12-31', 22415169.0],
                      ['1980-12-31', 22242653.0],
                      ['1979-12-31', 22090488.0],
                      ['1978-12-31', 21951464.0],
                      ['1977-12-31', 21756096.0],
                      ['1976-12-31', 21551634.0],
                      ['1975-12-31', 21293583.0],
                      ['1974-12-31', 21029429.0],
                      ['1973-12-31', 20835681.0],
                      ['1972-12-31', 20657957.0],
                      ['1971-12-31', 20461567.0],
                      ['1970-12-31', 20250398.0],
                      ['1969-12-31', 20009141.0],
                      ['1968-12-31', 19799831.0],
                      ['1967-12-31', 19534242.0],
                      ['1966-12-31', 19215450.0],
                      ['1965-12-31', 19031576.0],
                      ['1964-12-31', 18919126.0],
                      ['1963-12-31', 18797850.0],
                      ['1962-12-31', 18676550.0],
                      ['1961-12-31', 18555250.0],
                      ['1960-12-31', 18406905.0],
                      ['1959-12-31', 18254608.0],
                      ['1958-12-31', 18078643.0],
                      ['1957-12-31', 17886689.0],
                      ['1956-12-31', 17687296.0],
                      ['1955-12-31', 17485998.0],
                      ['1954-12-31', 17284001.0],
                      ['1953-12-31', 17077384.0],
                      ['1952-12-31', 16856828.0],
                      ['1951-12-31', 16607889.0],
                      ['1950-12-31', 16310998.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'ROU_SP_POP_TOTL',
             'description': 'Population, total - Romania. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22224695,
             'limit': None,
             'name': 'Population, total - Romania',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:42:27.508Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
RUS

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 144495044.0],
                      ['2016-12-31', 144342396.0],
                      ['2015-12-31', 144096870.0],
                      ['2014-12-31', 143819666.0],
                      ['2013-12-31', 143506911.0],
                      ['2012-12-31', 143201676.0],
                      ['2011-12-31', 142960868.0],
                      ['2010-12-31', 142849449.0],
                      ['2009-12-31', 142785342.0],
                      ['2008-12-31', 142742350.0],
                      ['2007-12-31', 142805088.0],
                      ['2006-12-31', 143049528.0],
                      ['2005-12-31', 143518523.0],
                      ['2004-12-31', 144067054.0],
                      ['2003-12-31', 144648257.0],
                      ['2002-12-31', 145306046.0],
                      ['2001-12-31', 145976083.0],
                      ['2000-12-31', 146596557.0],
                      ['1999-12-31', 147214392.0],
                      ['1998-12-31', 147670692.0],
                      ['1997-12-31', 147915307.0],
                      ['1996-12-31', 148160042.0],
                      ['1995-12-31', 148375726.0],
                      ['1994-12-31', 148336000.0],
                      ['1993-12-31', 148520000.0],
                      ['1992-12-31', 148689000.0],
                      ['1991-12-31', 148624000.0],
                      ['1990-12-31', 148292000.0],
                      ['1989-12-31', 147721000.0],
                      ['1988-12-31', 146857000.0],
                      ['1987-12-31', 145908000.0],
                      ['1986-12-31', 144894000.0],
                      ['1985-12-31', 143858000.0],
                      ['1984-12-31', 142745000.0],
                      ['1983-12-31', 141668000.0],
                      ['1982-12-31', 140823000.0],
                      ['1981-12-31', 139941000.0],
                      ['1980-12-31', 139010000.0],
                      ['1979-12-31', 138027000.0],
                      ['1978-12-31', 137060000.0],
                      ['1977-12-31', 136100000.0],
                      ['1976-12-31', 135147000.0],
                      ['1975-12-31', 134200000.0],
                      ['1974-12-31', 133432000.0],
                      ['1973-12-31', 132669000.0],
                      ['1972-12-31', 131909000.0],
                      ['1971-12-31', 131155000.0],
                      ['1970-12-31', 130404000.0],
                      ['1969-12-31', 129664000.0],
                      ['1968-12-31', 128928000.0],
                      ['1967-12-31', 128196000.0],
                      ['1966-12-31', 127468000.0],
                      ['1965-12-31', 126745000.0],
                      ['1964-12-31', 125345000.0],
                      ['1963-12-31', 123960000.0],
                      ['1962-12-31', 122591000.0],
                      ['1961-12-31', 121236000.0],
                      ['1960-12-31', 119897000.0],
                      ['1959-12-31', 118148000.0],
                      ['1958-12-31', 116424000.0],
                      ['1957-12-31', 114725000.0],
                      ['1956-12-31', 113051000.0],
                      ['1955-12-31', 111401500.0],
                      ['1954-12-31', 109574025.0],
                      ['1953-12-31', 107743349.0],
                      ['1952-12-31', 105950299.0],
                      ['1951-12-31', 104248118.0],
                      ['1950-12-31', 102702461.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'RUS_SP_POP_TOTL',
             'description': 'Population, total - Russian Federation. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22226000,
             'limit': None,
             'name': 'Population, total - Russian Federation',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:42:33.131Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
RWA
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 12208407.0],
                      ['2016-12-31', 11917508.0],
                      ['2015-12-31', 11629553.0],
                      ['2014-12-31', 11345357.0],
                      ['2013-12-31', 11065151.0],
                      ['2012-12-31', 10788853.0],
                      ['2011-12-31', 10516071.0],
                      ['2010-12-31', 10246842.0],
                      ['2009-12-31', 9977446.0],
                      ['2008-12-31', 9708169.0],
                      ['2007-12-31', 9447402.0],
                      ['2006-12-31', 9206580.0],
                      ['2005-12-31', 8991735.0],
                      ['2004-12-31', 8818438.0],
                      ['2003-12-31', 8680346.0],
                      ['2002-12-31', 8536205.0],
                      ['2001-12-31', 8329406.0],
                      ['2000-12-31', 8025703.0],
                      ['1999-12-31', 7593239.0],
                      ['1998-12-31', 7059813.0],
                      ['1997-12-31', 6522382.0],
                      ['1996-12-31', 6115168.0],
                      ['1995-12-31', 5928078.0],
                      ['1994-12-31', 6005095.0],
                      ['1993-12-31', 6299909.0],
                      ['1992-12-31', 6701851.0],
                      ['1991-12-31', 7051759.0],
                      ['1990-12-31', 7235798.0],
                      ['1989-12-31', 7216028.0],
                      ['1988-12-31', 7030179.0],
                      ['1987-12-31', 6732131.0],
                      ['1986-12-31', 6407672.0],
                      ['1985-12-31', 6120107.0],
                      ['1984-12-31', 5881906.0],
                      ['1983-12-31', 5673614.0],
                      ['1982-12-31', 5489322.0],
                      ['1981-12-31', 5315032.0],
                      ['1980-12-31', 5140716.0],
                      ['1979-12-31', 4968074.0],
                      ['1978-12-31', 4803725.0],
                      ['1977-12-31', 4647615.0],
                      ['1976-12-31', 4499509.0],
                      ['1975-12-31', 4359092.0],
                      ['1974-12-31', 4226799.0],
                      ['1973-12-31', 4102321.0],
                      ['1972-12-31', 3983700.0],
                      ['1971-12-31', 3868337.0],
                      ['1970-12-31', 3754541.0],
                      ['1969-12-31', 3640591.0],
                      ['1968-12-31', 3527263.0],
                      ['1967-12-31', 3418317.0],
                      ['1966-12-31', 3319082.0],
                      ['1965-12-31', 3232934.0],
                      ['1964-12-31', 3161724.0],
                      ['1963-12-31', 3102972.0],
                      ['1962-12-31', 3050604.0],
                      ['1961-12-31', 2996096.0],
                      ['1960-12-31', 2933428.0],
                      ['1959-12-31', 2860691.0],
                      ['1958-12-31', 2779550.0],
                      ['1957-12-31', 2693821.0],
                      ['1956-12-31', 2607950.0],
                      ['1955-12-31', 2525527.0],
                      ['1954-12-31', 2448825.0],
                      ['1953-12-31', 2378445.0],
                      ['1952-12-31', 2313311.0],
                      ['1951-12-31', 2250677.0],
                      ['1950-12-31', 2186185.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'RWA_SP_POP_TOTL',
             'description': 'Population, total - Rwanda. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22228000,
             'limit': None,
             'name': 'Population, total - Rwanda',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:42:39.575Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
WSM

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 196440.0],
                      ['2016-12-31', 195125.0],
                      ['2015-12-31', 193759.0],
                      ['2014-12-31', 192290.0],
                      ['2013-12-31', 190757.0],
                      ['2012-12-31', 189194.0],
                      ['2011-12-31', 187665.0],
                      ['2010-12-31', 186205.0],
                      ['2009-12-31', 184826.0],
                      ['2008-12-31', 183526.0],
                      ['2007-12-31', 182286.0],
                      ['2006-12-31', 181094.0],
                      ['2005-12-31', 179929.0],
                      ['2004-12-31', 178781.0],
                      ['2003-12-31', 177662.0],
                      ['2002-12-31', 176582.0],
                      ['2001-12-31', 175566.0],
                      ['2000-12-31', 174610.0],
                      ['1999-12-31', 173755.0],
                      ['1998-12-31', 172981.0],
                      ['1997-12-31', 172198.0],
                      ['1996-12-31', 171283.0],
                      ['1995-12-31', 170157.0],
                      ['1994-12-31', 168788.0],
                      ['1993-12-31', 167207.0],
                      ['1992-12-31', 165570.0],
                      ['1991-12-31', 164076.0],
                      ['1990-12-31', 162866.0],
                      ['1989-12-31', 161998.0],
                      ['1988-12-31', 161421.0],
                      ['1987-12-31', 161015.0],
                      ['1986-12-31', 160592.0],
                      ['1985-12-31', 160031.0],
                      ['1984-12-31', 159283.0],
                      ['1983-12-31', 158384.0],
                      ['1982-12-31', 157403.0],
                      ['1981-12-31', 156428.0],
                      ['1980-12-31', 155557.0],
                      ['1979-12-31', 154760.0],
                      ['1978-12-31', 154007.0],
                      ['1977-12-31', 153247.0],
                      ['1976-12-31', 152390.0],
                      ['1975-12-31', 151387.0],
                      ['1974-12-31', 150221.0],
                      ['1973-12-31', 148889.0],
                      ['1972-12-31', 147321.0],
                      ['1971-12-31', 145439.0],
                      ['1970-12-31', 143176.0],
                      ['1969-12-31', 140518.0],
                      ['1968-12-31', 137506.0],
                      ['1967-12-31', 134193.0],
                      ['1966-12-31', 130688.0],
                      ['1965-12-31', 127068.0],
                      ['1964-12-31', 123354.0],
                      ['1963-12-31', 119561.0],
                      ['1962-12-31', 115788.0],
                      ['1961-12-31', 112119.0],
                      ['1960-12-31', 108646.0],
                      ['1959-12-31', 105380.0],
                      ['1958-12-31', 102353.0],
                      ['1957-12-31', 99500.0],
                      ['1956-12-31', 96799.0],
                      ['1955-12-31', 94208.0],
                      ['1954-12-31', 91696.0],
                      ['1953-12-31', 89238.0],
                      ['1952-12-31', 86819.0],
                      ['1951-12-31', 84437.0],
                      ['1950-12-31', 82097.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'WSM_SP_POP_TOTL',
             'description': 'Population, total - Samoa. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22256490,
             'limit': None,
             'name': 'Population, total - Samoa',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:46:54.114Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
SMR
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 33400.0],
                      ['2016-12-31', 33203.0],
                      ['2015-12-31', 32960.0],
                      ['2014-12-31', 32657.0],
                      ['2013-12-31', 32303.0],
                      ['2012-12-31', 31914.0],
                      ['2011-12-31', 31504.0],
                      ['2010-12-31', 31110.0],
                      ['2009-12-31', 30723.0],
                      ['2008-12-31', 30351.0],
                      ['2007-12-31', 29977.0],
                      ['2006-12-31', 29614.0],
                      ['2005-12-31', 29240.0],
                      ['2004-12-31', 28866.0],
                      ['2003-12-31', 28494.0],
                      ['2002-12-31', 28121.0],
                      ['2001-12-31', 27762.0],
                      ['2000-12-31', 27418.0],
                      ['1999-12-31', 27096.0],
                      ['1998-12-31', 26799.0],
                      ['1997-12-31', 26508.0],
                      ['1996-12-31', 26209.0],
                      ['1995-12-31', 25877.0],
                      ['1994-12-31', 25516.0],
                      ['1993-12-31', 25141.0],
                      ['1992-12-31', 24749.0],
                      ['1991-12-31', 24386.0],
                      ['1990-12-31', 24043.0],
                      ['1989-12-31', 23740.0],
                      ['1988-12-31', 23466.0],
                      ['1987-12-31', 23210.0],
                      ['1986-12-31', 22961.0],
                      ['1985-12-31', 22708.0],
                      ['1984-12-31', 22455.0],
                      ['1983-12-31', 22210.0],
                      ['1982-12-31', 21943.0],
                      ['1981-12-31', 21666.0],
                      ['1980-12-31', 21361.0],
                      ['1979-12-31', 21030.0],
                      ['1978-12-31', 20660.0],
                      ['1977-12-31', 20296.0],
                      ['1976-12-31', 19980.0],
                      ['1975-12-31', 19735.0],
                      ['1974-12-31', 19562.0],
                      ['1973-12-31', 19466.0],
                      ['1972-12-31', 19398.0],
                      ['1971-12-31', 19303.0],
                      ['1970-12-31', 19138.0],
                      ['1969-12-31', 18895.0],
                      ['1968-12-31', 18589.0],
                      ['1967-12-31', 18229.0],
                      ['1966-12-31', 17835.0],
                      ['1965-12-31', 17441.0],
                      ['1964-12-31', 17032.0],
                      ['1963-12-31', 16621.0],
                      ['1962-12-31', 16199.0],
                      ['1961-12-31', 15789.0],
                      ['1960-12-31', 15397.0],
                      ['1959-12-31', 15021.0],
                      ['1958-12-31', 14669.0],
                      ['1957-12-31', 14346.0],
                      ['1956-12-31', 14048.0],
                      ['1955-12-31', 13772.0],
                      ['1954-12-31', 13511.0],
                      ['1953-12-31', 13290.0],
                      ['1952-12-31', 13092.0],
                      ['1951-12-31', 12917.0],
                      ['1950-12-31', 12781.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'SMR_SP_POP_TOTL',
             'description': 'Population, total - San Marino. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22245284,
             'limit': None,
             'name': 'Population, total - San Marino',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:43:28.519Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
STP
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 204327.0],
                      ['2016-12-31', 199910.0],
                      ['2015-12-31', 195553.0],
                      ['2014-12-31', 191266.0],
                      ['2013-12-31', 187045.0],
                      ['2012-12-31', 182889.0],
                      ['2011-12-31', 178800.0],
                      ['2010-12-31', 174776.0],
                      ['2009-12-31', 170813.0],
                      ['2008-12-31', 166913.0],
                      ['2007-12-31', 163101.0],
                      ['2006-12-31', 159328.0],
                      ['2005-12-31', 155630.0],
                      ['2004-12-31', 151969.0],
                      ['2003-12-31', 148372.0],
                      ['2002-12-31', 144889.0],
                      ['2001-12-31', 141622.0],
                      ['2000-12-31', 138606.0],
                      ['1999-12-31', 135886.0],
                      ['1998-12-31', 133418.0],
                      ['1997-12-31', 131107.0],
                      ['1996-12-31', 128821.0],
                      ['1995-12-31', 126454.0],
                      ['1994-12-31', 123973.0],
                      ['1993-12-31', 121407.0],
                      ['1992-12-31', 118816.0],
                      ['1991-12-31', 116294.0],
                      ['1990-12-31', 113893.0],
                      ['1989-12-31', 111627.0],
                      ['1988-12-31', 109470.0],
                      ['1987-12-31', 107415.0],
                      ['1986-12-31', 105474.0],
                      ['1985-12-31', 103634.0],
                      ['1984-12-31', 101915.0],
                      ['1983-12-31', 100318.0],
                      ['1982-12-31', 98706.0],
                      ['1981-12-31', 96950.0],
                      ['1980-12-31', 94949.0],
                      ['1979-12-31', 92649.0],
                      ['1978-12-31', 90089.0],
                      ['1977-12-31', 87434.0],
                      ['1976-12-31', 84885.0],
                      ['1975-12-31', 82607.0],
                      ['1974-12-31', 80670.0],
                      ['1973-12-31', 79022.0],
                      ['1972-12-31', 77537.0],
                      ['1971-12-31', 75988.0],
                      ['1970-12-31', 74253.0],
                      ['1969-12-31', 72241.0],
                      ['1968-12-31', 70046.0],
                      ['1967-12-31', 67873.0],
                      ['1966-12-31', 66063.0],
                      ['1965-12-31', 64796.0],
                      ['1964-12-31', 64212.0],
                      ['1963-12-31', 64177.0],
                      ['1962-12-31', 64432.0],
                      ['1961-12-31', 64551.0],
                      ['1960-12-31', 64253.0],
                      ['1959-12-31', 63478.0],
                      ['1958-12-31', 62319.0],
                      ['1957-12-31', 60991.0],
                      ['1956-12-31', 59746.0],
                      ['1955-12-31', 58783.0],
                      ['1954-12-31', 58234.0],
                      ['1953-12-31', 58165.0],
                      ['1952-12-31', 58523.0],
                      ['1951-12-31', 59202.0],
                      ['1950-12-31', 60002.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'STP_SP_POP_TOTL',
             'description': 'Population, total - Sao Tome and Principe. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22254455,
             'limit': None,
             'name': 'Population, total - Sao Tome and Principe',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:44:01.156Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
SAU

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 32938213.0],
                      ['2016-12-31', 32275687.0],
                      ['2015-12-31', 31557144.0],
                      ['2014-12-31', 30776722.0],
                      ['2013-12-31', 29944476.0],
                      ['2012-12-31', 29086357.0],
                      ['2011-12-31', 28238020.0],
                      ['2010-12-31', 27425676.0],
                      ['2009-12-31', 26661492.0],
                      ['2008-12-31', 25940770.0],
                      ['2007-12-31', 25252569.0],
                      ['2006-12-31', 24578301.0],
                      ['2005-12-31', 23905654.0],
                      ['2004-12-31', 23228890.0],
                      ['2003-12-31', 22556425.0],
                      ['2002-12-31', 21906308.0],
                      ['2001-12-31', 21303592.0],
                      ['2000-12-31', 20764312.0],
                      ['1999-12-31', 20294406.0],
                      ['1998-12-31', 19882458.0],
                      ['1997-12-31', 19505576.0],
                      ['1996-12-31', 19131578.0],
                      ['1995-12-31', 18735841.0],
                      ['1994-12-31', 18311090.0],
                      ['1993-12-31', 17859750.0],
                      ['1992-12-31', 17378833.0],
                      ['1991-12-31', 16867829.0],
                      ['1990-12-31', 16326815.0],
                      ['1989-12-31', 15755944.0],
                      ['1988-12-31', 15155223.0],
                      ['1987-12-31', 14525660.0],
                      ['1986-12-31', 13869012.0],
                      ['1985-12-31', 13189115.0],
                      ['1984-12-31', 12484967.0],
                      ['1983-12-31', 11763837.0],
                      ['1982-12-31', 11048080.0],
                      ['1981-12-31', 10366661.0],
                      ['1980-12-31', 9740599.0],
                      ['1979-12-31', 9179621.0],
                      ['1978-12-31', 8679840.0],
                      ['1977-12-31', 8231604.0],
                      ['1976-12-31', 7818613.0],
                      ['1975-12-31', 7428703.0],
                      ['1974-12-31', 7059334.0],
                      ['1973-12-31', 6714095.0],
                      ['1972-12-31', 6393894.0],
                      ['1971-12-31', 6100994.0],
                      ['1970-12-31', 5836389.0],
                      ['1969-12-31', 5599628.0],
                      ['1968-12-31', 5387486.0],
                      ['1967-12-31', 5194846.0],
                      ['1966-12-31', 5015204.0],
                      ['1965-12-31', 4843635.0],
                      ['1964-12-31', 4677404.0],
                      ['1963-12-31', 4516659.0],
                      ['1962-12-31', 4362864.0],
                      ['1961-12-31', 4218879.0],
                      ['1960-12-31', 4086539.0],
                      ['1959-12-31', 3965815.0],
                      ['1958-12-31', 3855084.0],
                      ['1957-12-31', 3751875.0],
                      ['1956-12-31', 3653561.0],
                      ['1955-12-31', 3558155.0],
                      ['1954-12-31', 3464552.0],
                      ['1953-12-31', 3372617.0],
                      ['1952-12-31', 3283300.0],
                      ['1951-12-31', 3198551.0],
                      ['1950-12-31', 3121335.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'SAU_SP_POP_TOTL',
             'description': 'Population, total - Saudi Arabia. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22231781,
             'limit': None,
             'name': 'Population, total - Saudi Arabia',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:42:49.940Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
SEN
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 15850567.0],
                      ['2016-12-31', 15411614.0],
                      ['2015-12-31', 14976994.0],
                      ['2014-12-31', 14546111.0],
                      ['2013-12-31', 14120320.0],
                      ['2012-12-31', 13703513.0],
                      ['2011-12-31', 13300910.0],
                      ['2010-12-31', 12916229.0],
                      ['2009-12-31', 12550917.0],
                      ['2008-12-31', 12203957.0],
                      ['2007-12-31', 11873557.0],
                      ['2006-12-31', 11556763.0],
                      ['2005-12-31', 11251266.0],
                      ['2004-12-31', 10955944.0],
                      ['2003-12-31', 10670990.0],
                      ['2002-12-31', 10396861.0],
                      ['2001-12-31', 10134497.0],
                      ['2000-12-31', 9884052.0],
                      ['1999-12-31', 9645957.0],
                      ['1998-12-31', 9418393.0],
                      ['1997-12-31', 9196528.0],
                      ['1996-12-31', 8974077.0],
                      ['1995-12-31', 8746606.0],
                      ['1994-12-31', 8512173.0],
                      ['1993-12-31', 8272170.0],
                      ['1992-12-31', 8029725.0],
                      ['1991-12-31', 7789653.0],
                      ['1990-12-31', 7555617.0],
                      ['1989-12-31', 7328600.0],
                      ['1988-12-31', 7107976.0],
                      ['1987-12-31', 6893896.0],
                      ['1986-12-31', 6686159.0],
                      ['1985-12-31', 6484738.0],
                      ['1984-12-31', 6289327.0],
                      ['1983-12-31', 6100495.0],
                      ['1982-12-31', 5920059.0],
                      ['1981-12-31', 5750338.0],
                      ['1980-12-31', 5592646.0],
                      ['1979-12-31', 5448110.0],
                      ['1978-12-31', 5315265.0],
                      ['1977-12-31', 5189539.0],
                      ['1976-12-31', 5064674.0],
                      ['1975-12-31', 4936209.0],
                      ['1974-12-31', 4802348.0],
                      ['1973-12-31', 4664444.0],
                      ['1972-12-31', 4525114.0],
                      ['1971-12-31', 4388458.0],
                      ['1970-12-31', 4257505.0],
                      ['1969-12-31', 4132844.0],
                      ['1968-12-31', 4013539.0],
                      ['1967-12-31', 3899237.0],
                      ['1966-12-31', 3789211.0],
                      ['1965-12-31', 3682876.0],
                      ['1964-12-31', 3580312.0],
                      ['1963-12-31', 3481745.0],
                      ['1962-12-31', 3386863.0],
                      ['1961-12-31', 3295293.0],
                      ['1960-12-31', 3206749.0],
                      ['1959-12-31', 3121092.0],
                      ['1958-12-31', 3038333.0],
                      ['1957-12-31', 2958536.0],
                      ['1956-12-31', 2881808.0],
                      ['1955-12-31', 2808225.0],
                      ['1954-12-31', 2737833.0],
                      ['1953-12-31', 2670589.0],
                      ['1952-12-31', 2606415.0],
                      ['1951-12-31', 2545160.0],
                      ['1950-12-31', 2486635.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'SEN_SP_POP_TOTL',
             'description': 'Population, total - Senegal. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22237531,
             'limit': None,
             'name': 'Population, total - Senegal',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:43:02.769Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
SRB

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 7022268.0],
                      ['2016-12-31', 7058322.0],
                      ['2015-12-31', 7095383.0],
                      ['2014-12-31', 7130576.0],
                      ['2013-12-31', 7164132.0],
                      ['2012-12-31', 7199077.0],
                      ['2011-12-31', 7234099.0],
                      ['2010-12-31', 7291436.0],
                      ['2009-12-31', 7320807.0],
                      ['2008-12-31', 7350222.0],
                      ['2007-12-31', 7381579.0],
                      ['2006-12-31', 7411569.0],
                      ['2005-12-31', 7440769.0],
                      ['2004-12-31', 7463157.0],
                      ['2003-12-31', 7480591.0],
                      ['2002-12-31', 7496522.0],
                      ['2001-12-31', 7503433.0],
                      ['2000-12-31', 7516346.0],
                      ['1999-12-31', 7540401.0],
                      ['1998-12-31', 7567745.0],
                      ['1997-12-31', 7596501.0],
                      ['1996-12-31', 7617794.0],
                      ['1995-12-31', 7625357.0],
                      ['1994-12-31', 7734639.0],
                      ['1993-12-31', 7699307.0],
                      ['1992-12-31', 7646424.0],
                      ['1991-12-31', 7595636.0],
                      ['1990-12-31', 7586000.0],
                      ['1959-12-31', 6589000.0],
                      ['1958-12-31', 6556000.0],
                      ['1957-12-31', 6509000.0],
                      ['1956-12-31', 6446000.0],
                      ['1955-12-31', 6368000.0],
                      ['1954-12-31', 6304000.0],
                      ['1953-12-31', 6243000.0],
                      ['1952-12-31', 6184000.0],
                      ['1951-12-31', 6128000.0],
                      ['1950-12-31', 6075000.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'SRB_SP_POP_TOTL',
             'description': 'Population, total - Serbia. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22247996,
             'limit': None,
             'name': 'Population, total - Serbia',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:43:37.462Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
SYC
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 95843.0],
                      ['2016-12-31', 94677.0],
                      ['2015-12-31', 93419.0],
                      ['2014-12-31', 91359.0],
                      ['2013-12-31', 89949.0],
                      ['2012-12-31', 88303.0],
                      ['2011-12-31', 87441.0],
                      ['2010-12-31', 89770.0],
                      ['2009-12-31', 87298.0],
                      ['2008-12-31', 86956.0],
                      ['2007-12-31', 85033.0],
                      ['2006-12-31', 84600.0],
                      ['2005-12-31', 82858.0],
                      ['2004-12-31', 82475.0],
                      ['2003-12-31', 82781.0],
                      ['2002-12-31', 83723.0],
                      ['2001-12-31', 81202.0],
                      ['2000-12-31', 81131.0],
                      ['1999-12-31', 80410.0],
                      ['1998-12-31', 78846.0],
                      ['1997-12-31', 77319.0],
                      ['1996-12-31', 76417.0],
                      ['1995-12-31', 75304.0],
                      ['1994-12-31', 74205.0],
                      ['1993-12-31', 72253.0],
                      ['1992-12-31', 70763.0],
                      ['1991-12-31', 70439.0],
                      ['1990-12-31', 69507.0],
                      ['1989-12-31', 69167.0],
                      ['1988-12-31', 68755.0],
                      ['1987-12-31', 68499.0],
                      ['1986-12-31', 65652.0],
                      ['1985-12-31', 65244.0],
                      ['1984-12-31', 64717.0],
                      ['1983-12-31', 64335.0],
                      ['1982-12-31', 64413.0],
                      ['1981-12-31', 64035.0],
                      ['1980-12-31', 63261.0],
                      ['1979-12-31', 62686.0],
                      ['1978-12-31', 62150.0],
                      ['1977-12-31', 61786.0],
                      ['1976-12-31', 60504.0],
                      ['1975-12-31', 59292.0],
                      ['1974-12-31', 57937.0],
                      ['1973-12-31', 56892.0],
                      ['1972-12-31', 56029.0],
                      ['1971-12-31', 54695.0],
                      ['1970-12-31', 53600.0],
                      ['1969-12-31', 52365.0],
                      ['1968-12-31', 51134.0],
                      ['1967-12-31', 49911.0],
                      ['1966-12-31', 48699.0],
                      ['1965-12-31', 47500.0],
                      ['1964-12-31', 46322.0],
                      ['1963-12-31', 45176.0],
                      ['1962-12-31', 44042.0],
                      ['1961-12-31', 42889.0],
                      ['1960-12-31', 41700.0],
                      ['1955-12-31', 35900.0],
                      ['1950-12-31', 32900.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'SYC_SP_POP_TOTL',
             'description': 'Population, total - Seychelles. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22264538,
             'limit': None,
             'name': 'Population, total - Seychelles',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:44:34.720Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
SLE
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 7557212.0],
                      ['2016-12-31', 7396190.0],
                      ['2015-12-31', 7237025.0],
                      ['2014-12-31', 7079162.0],
                      ['2013-12-31', 6922079.0],
                      ['2012-12-31', 6766103.0],
                      ['2011-12-31', 6611692.0],
                      ['2010-12-31', 6458720.0],
                      ['2009-12-31', 6310260.0],
                      ['2008-12-31', 6165372.0],
                      ['2007-12-31', 6015417.0],
                      ['2006-12-31', 5848692.0],
                      ['2005-12-31', 5658379.0],
                      ['2004-12-31', 5439695.0],
                      ['2003-12-31', 5199549.0],
                      ['2002-12-31', 4957216.0],
                      ['2001-12-31', 4739147.0],
                      ['2000-12-31', 4564297.0],
                      ['1999-12-31', 4437803.0],
                      ['1998-12-31', 4353646.0],
                      ['1997-12-31', 4305455.0],
                      ['1996-12-31', 4282350.0],
                      ['1995-12-31', 4274819.0],
                      ['1994-12-31', 4283621.0],
                      ['1993-12-31', 4307299.0],
                      ['1992-12-31', 4331332.0],
                      ['1991-12-31', 4337239.0],
                      ['1990-12-31', 4312246.0],
                      ['1989-12-31', 4249468.0],
                      ['1988-12-31', 4152984.0],
                      ['1987-12-31', 4034668.0],
                      ['1986-12-31', 3912438.0],
                      ['1985-12-31', 3799550.0],
                      ['1984-12-31', 3699467.0],
                      ['1983-12-31', 3608751.0],
                      ['1982-12-31', 3525399.0],
                      ['1981-12-31', 3445277.0],
                      ['1980-12-31', 3365441.0],
                      ['1979-12-31', 3286179.0],
                      ['1978-12-31', 3209263.0],
                      ['1977-12-31', 3134800.0],
                      ['1976-12-31', 3062956.0],
                      ['1975-12-31', 2993876.0],
                      ['1974-12-31', 2927468.0],
                      ['1973-12-31', 2863739.0],
                      ['1972-12-31', 2803031.0],
                      ['1971-12-31', 2745779.0],
                      ['1970-12-31', 2692259.0],
                      ['1969-12-31', 2642608.0],
                      ['1968-12-31', 2596568.0],
                      ['1967-12-31', 2553529.0],
                      ['1966-12-31', 2512652.0],
                      ['1965-12-31', 2473294.0],
                      ['1964-12-31', 2435204.0],
                      ['1963-12-31', 2398414.0],
                      ['1962-12-31', 2363013.0],
                      ['1961-12-31', 2329204.0],
                      ['1960-12-31', 2297110.0],
                      ['1959-12-31', 2266686.0],
                      ['1958-12-31', 2237772.0],
                      ['1957-12-31', 2210131.0],
                      ['1956-12-31', 2183523.0],
                      ['1955-12-31', 2157753.0],
                      ['1954-12-31', 2132731.0],
                      ['1953-12-31', 2108430.0],
                      ['1952-12-31', 2084942.0],
                      ['1951-12-31', 2062444.0],
                      ['1950-12-31', 2041203.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'SLE_SP_POP_TOTL',
             'description': 'Population, total - Sierra Leone. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22242458,
             'limit': None,
             'name': 'Population, total - Sierra Leone',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:43:19.697Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
SGP

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 5612253.0],
                      ['2016-12-31', 5607283.0],
                      ['2015-12-31', 5535002.0],
                      ['2014-12-31', 5469724.0],
                      ['2013-12-31', 5399162.0],
                      ['2012-12-31', 5312437.0],
                      ['2011-12-31', 5183688.0],
                      ['2010-12-31', 5076732.0],
                      ['2009-12-31', 4987573.0],
                      ['2008-12-31', 4839396.0],
                      ['2007-12-31', 4588599.0],
                      ['2006-12-31', 4401365.0],
                      ['2005-12-31', 4265762.0],
                      ['2004-12-31', 4166664.0],
                      ['2003-12-31', 4114826.0],
                      ['2002-12-31', 4175950.0],
                      ['2001-12-31', 4138012.0],
                      ['2000-12-31', 4027887.0],
                      ['1999-12-31', 3958723.0],
                      ['1998-12-31', 3927213.0],
                      ['1997-12-31', 3796038.0],
                      ['1996-12-31', 3670704.0],
                      ['1995-12-31', 3524506.0],
                      ['1994-12-31', 3419048.0],
                      ['1993-12-31', 3313471.0],
                      ['1992-12-31', 3230698.0],
                      ['1991-12-31', 3135083.0],
                      ['1990-12-31', 3047132.0],
                      ['1989-12-31', 2930901.0],
                      ['1988-12-31', 2846108.0],
                      ['1987-12-31', 2774789.0],
                      ['1986-12-31', 2733373.0],
                      ['1985-12-31', 2735957.0],
                      ['1984-12-31', 2732221.0],
                      ['1983-12-31', 2681061.0],
                      ['1982-12-31', 2646466.0],
                      ['1981-12-31', 2532835.0],
                      ['1980-12-31', 2413945.0],
                      ['1979-12-31', 2383500.0],
                      ['1978-12-31', 2353600.0],
                      ['1977-12-31', 2325300.0],
                      ['1976-12-31', 2293300.0],
                      ['1975-12-31', 2262600.0],
                      ['1974-12-31', 2229800.0],
                      ['1973-12-31', 2193000.0],
                      ['1972-12-31', 2152400.0],
                      ['1971-12-31', 2112900.0],
                      ['1970-12-31', 2074500.0],
                      ['1969-12-31', 2042500.0],
                      ['1968-12-31', 2012000.0],
                      ['1967-12-31', 1977600.0],
                      ['1966-12-31', 1934400.0],
                      ['1965-12-31', 1886900.0],
                      ['1964-12-31', 1841600.0],
                      ['1963-12-31', 1795000.0],
                      ['1962-12-31', 1750200.0],
                      ['1961-12-31', 1702400.0],
                      ['1960-12-31', 1646400.0],
                      ['1959-12-31', 1545001.0],
                      ['1958-12-31', 1488144.0],
                      ['1957-12-31', 1429047.0],
                      ['1956-12-31', 1367944.0],
                      ['1955-12-31', 1305726.0],
                      ['1954-12-31', 1240283.0],
                      ['1953-12-31', 1178077.0],
                      ['1952-12-31', 1120282.0],
                      ['1951-12-31', 1067968.0],
                      ['1950-12-31', 1022098.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'SGP_SP_POP_TOTL',
             'description': 'Population, total - Singapore. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22239289,
             'limit': None,
             'name': 'Population, total - Singapore',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:43:08.515Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
SXM
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 41109.0],
                      ['2016-12-31', 39969.0],
                      ['2015-12-31', 38824.0],
                      ['2014-12-31', 37685.0],
                      ['2013-12-31', 36607.0],
                      ['2012-12-31', 34640.0],
                      ['2011-12-31', 33435.0],
                      ['2010-12-31', 34056.0],
                      ['2009-12-31', 34238.0],
                      ['2008-12-31', 33964.0],
                      ['2007-12-31', 33811.0],
                      ['2006-12-31', 33441.0],
                      ['2005-12-31', 33011.0],
                      ['2004-12-31', 32488.0],
                      ['2003-12-31', 31472.0],
                      ['2002-12-31', 30777.0],
                      ['2001-12-31', 30600.0],
                      ['2000-12-31', 30519.0],
                      ['1999-12-31', 31084.0],
                      ['1998-12-31', 31240.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'SXM_SP_POP_TOTL',
             'description': 'Population, total - Sint Maarten (Dutch part). ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22263428,
             'limit': None,
             'name': 'Population, total - Sint Maarten (Dutch part)',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1998-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:44:30.262Z',
             'start_date': '1998-12-31',
             'transform': None,
             'type': 'Time Series'}}
SVK
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 5439892.0],
                      ['2016-12-31', 5430798.0],
                      ['2015-12-31', 5423801.0],
                      ['2014-12-31', 5418649.0],
                      ['2013-12-31', 5413393.0],
                      ['2012-12-31', 5407579.0],
                      ['2011-12-31', 5398384.0],
                      ['2010-12-31', 5391428.0],
                      ['2009-12-31', 5386406.0],
                      ['2008-12-31', 5379233.0],
                      ['2007-12-31', 5374622.0],
                      ['2006-12-31', 5373054.0],
                      ['2005-12-31', 5372807.0],
                      ['2004-12-31', 5372280.0],
                      ['2003-12-31', 5373374.0],
                      ['2002-12-31', 5376912.0],
                      ['2001-12-31', 5378867.0],
                      ['2000-12-31', 5388720.0],
                      ['1999-12-31', 5396020.0],
                      ['1998-12-31', 5390516.0],
                      ['1997-12-31', 5383291.0],
                      ['1996-12-31', 5373361.0],
                      ['1995-12-31', 5361999.0],
                      ['1994-12-31', 5346331.0],
                      ['1993-12-31', 5325305.0],
                      ['1992-12-31', 5305016.0],
                      ['1991-12-31', 5303294.0],
                      ['1990-12-31', 5299187.0],
                      ['1989-12-31', 5275942.0],
                      ['1988-12-31', 5250596.0],
                      ['1987-12-31', 5222840.0],
                      ['1986-12-31', 5193838.0],
                      ['1985-12-31', 5161768.0],
                      ['1984-12-31', 5127097.0],
                      ['1983-12-31', 5091971.0],
                      ['1982-12-31', 5055099.0],
                      ['1981-12-31', 5016105.0],
                      ['1980-12-31', 4979815.0],
                      ['1979-12-31', 4938973.0],
                      ['1978-12-31', 4890125.0],
                      ['1977-12-31', 4840501.0],
                      ['1976-12-31', 4789507.0],
                      ['1975-12-31', 4739105.0],
                      ['1974-12-31', 4689623.0],
                      ['1973-12-31', 4641445.0],
                      ['1972-12-31', 4596622.0],
                      ['1971-12-31', 4557449.0],
                      ['1970-12-31', 4538223.0],
                      ['1969-12-31', 4518607.0],
                      ['1968-12-31', 4483915.0],
                      ['1967-12-31', 4449367.0],
                      ['1966-12-31', 4411666.0],
                      ['1965-12-31', 4370983.0],
                      ['1964-12-31', 4327341.0],
                      ['1963-12-31', 4282017.0],
                      ['1962-12-31', 4238188.0],
                      ['1961-12-31', 4191667.0],
                      ['1960-12-31', 4068095.0],
                      ['1959-12-31', 4032799.0],
                      ['1958-12-31', 3969202.0],
                      ['1957-12-31', 3903115.0],
                      ['1956-12-31', 3834942.0],
                      ['1955-12-31', 3765317.0],
                      ['1954-12-31', 3695133.0],
                      ['1953-12-31', 3625562.0],
                      ['1952-12-31', 3558070.0],
                      ['1951-12-31', 3494399.0],
                      ['1950-12-31', 3436574.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'SVK_SP_POP_TOTL',
             'description': 'Population, total - Slovak Republic. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22257728,
             'limit': None,
             'name': 'Population, total - Slovak Republic',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:44:11.361Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
SVN

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 2066748.0],
                      ['2016-12-31', 2065042.0],
                      ['2015-12-31', 2063531.0],
                      ['2014-12-31', 2061980.0],
                      ['2013-12-31', 2059953.0],
                      ['2012-12-31', 2057159.0],
                      ['2011-12-31', 2052843.0],
                      ['2010-12-31', 2048583.0],
                      ['2009-12-31', 2039669.0],
                      ['2008-12-31', 2021316.0],
                      ['2007-12-31', 2018122.0],
                      ['2006-12-31', 2006868.0],
                      ['2005-12-31', 2000474.0],
                      ['2004-12-31', 1997012.0],
                      ['2003-12-31', 1995733.0],
                      ['2002-12-31', 1994530.0],
                      ['2001-12-31', 1992060.0],
                      ['2000-12-31', 1988925.0],
                      ['1999-12-31', 1983045.0],
                      ['1998-12-31', 1981629.0],
                      ['1997-12-31', 1985956.0],
                      ['1996-12-31', 1988628.0],
                      ['1995-12-31', 1989872.0],
                      ['1994-12-31', 1989443.0],
                      ['1993-12-31', 1991746.0],
                      ['1992-12-31', 1996498.0],
                      ['1991-12-31', 1999429.0],
                      ['1990-12-31', 1998161.0],
                      ['1989-12-31', 1996351.0],
                      ['1988-12-31', 1995196.0],
                      ['1987-12-31', 1989776.0],
                      ['1986-12-31', 1965964.0],
                      ['1985-12-31', 1941641.0],
                      ['1984-12-31', 1932154.0],
                      ['1983-12-31', 1922321.0],
                      ['1982-12-31', 1910334.0],
                      ['1981-12-31', 1906531.0],
                      ['1980-12-31', 1901315.0],
                      ['1979-12-31', 1882599.0],
                      ['1978-12-31', 1862548.0],
                      ['1977-12-31', 1842377.0],
                      ['1976-12-31', 1820249.0],
                      ['1975-12-31', 1793581.0],
                      ['1974-12-31', 1776132.0],
                      ['1973-12-31', 1766697.0],
                      ['1972-12-31', 1752233.0],
                      ['1971-12-31', 1738335.0],
                      ['1970-12-31', 1724891.0],
                      ['1969-12-31', 1713874.0],
                      ['1968-12-31', 1704546.0],
                      ['1967-12-31', 1689528.0],
                      ['1966-12-31', 1669905.0],
                      ['1965-12-31', 1649160.0],
                      ['1964-12-31', 1632114.0],
                      ['1963-12-31', 1616971.0],
                      ['1962-12-31', 1603649.0],
                      ['1961-12-31', 1594131.0],
                      ['1960-12-31', 1584720.0],
                      ['1959-12-31', 1570492.0],
                      ['1958-12-31', 1561352.0],
                      ['1957-12-31', 1552231.0],
                      ['1956-12-31', 1542741.0],
                      ['1955-12-31', 1532598.0],
                      ['1954-12-31', 1521658.0],
                      ['1953-12-31', 1509949.0],
                      ['1952-12-31', 1497673.0],
                      ['1951-12-31', 1485208.0],
                      ['1950-12-31', 1473094.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'SVN_SP_POP_TOTL',
             'description': 'Population, total - Slovenia. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22259511,
             'limit': None,
             'name': 'Population, total - Slovenia',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:44:16.653Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
SST
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 40324496.0],
                      ['2016-12-31', 39646847.0],
                      ['2015-12-31', 38960406.0],
                      ['2014-12-31', 38266156.0],
                      ['2013-12-31', 37572012.0],
                      ['2012-12-31', 36875022.0],
                      ['2011-12-31', 36171934.0],
                      ['2010-12-31', 35465245.0],
                      ['2009-12-31', 34739790.0],
                      ['2008-12-31', 34006389.0],
                      ['2007-12-31', 33278247.0],
                      ['2006-12-31', 32586895.0],
                      ['2005-12-31', 31947386.0],
                      ['2004-12-31', 31365918.0],
                      ['2003-12-31', 30838828.0],
                      ['2002-12-31', 30352305.0],
                      ['2001-12-31', 29887049.0],
                      ['2000-12-31', 29434279.0],
                      ['1999-12-31', 28976065.0],
                      ['1998-12-31', 28528151.0],
                      ['1997-12-31', 28107601.0],
                      ['1996-12-31', 27691618.0],
                      ['1995-12-31', 27284098.0],
                      ['1994-12-31', 26880995.0],
                      ['1993-12-31', 26471464.0],
                      ['1992-12-31', 26066187.0],
                      ['1991-12-31', 25642376.0],
                      ['1990-12-31', 25186921.0],
                      ['1989-12-31', 24726226.0],
                      ['1988-12-31', 24251665.0],
                      ['1987-12-31', 23770486.0],
                      ['1986-12-31', 23285884.0],
                      ['1985-12-31', 22806174.0],
                      ['1984-12-31', 22331260.0],
                      ['1983-12-31', 21865552.0],
                      ['1982-12-31', 21407906.0],
                      ['1981-12-31', 20963859.0],
                      ['1980-12-31', 20547258.0],
                      ['1979-12-31', 20157728.0],
                      ['1978-12-31', 19794779.0],
                      ['1977-12-31', 19453890.0],
                      ['1976-12-31', 19120333.0],
                      ['1975-12-31', 18789042.0],
                      ['1974-12-31', 18456078.0],
                      ['1973-12-31', 18127044.0],
                      ['1972-12-31', 17800127.0],
                      ['1971-12-31', 17476361.0],
                      ['1970-12-31', 17159590.0],
                      ['1969-12-31', 16853980.0],
                      ['1968-12-31', 16556001.0],
                      ['1967-12-31', 16263697.0],
                      ['1966-12-31', 15976545.0],
                      ['1965-12-31', 15688248.0],
                      ['1964-12-31', 15397706.0],
                      ['1963-12-31', 15107653.0],
                      ['1962-12-31', 14821270.0],
                      ['1961-12-31', 14538217.0],
                      ['1960-12-31', 14260440.0],
                      ['1959-12-31', 13940939.0],
                      ['1958-12-31', 13677235.0],
                      ['1957-12-31', 13418451.0],
                      ['1956-12-31', 13164152.0],
                      ['1955-12-31', 12949866.0],
                      ['1954-12-31', 12668034.0],
                      ['1953-12-31', 12426549.0],
                      ['1952-12-31', 12190103.0],
                      ['1951-12-31', 11959550.0],
                      ['1950-12-31', 11769002.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'SST_SP_POP_TOTL',
             'description': 'Population, total - Small states. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22253094,
             'limit': None,
             'name': 'Population, total - Small states',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:43:56.419Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
SLB

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 611343.0],
                      ['2016-12-31', 599419.0],
                      ['2015-12-31', 587482.0],
                      ['2014-12-31', 575504.0],
                      ['2013-12-31', 563513.0],
                      ['2012-12-31', 551531.0],
                      ['2011-12-31', 539614.0],
                      ['2010-12-31', 527790.0],
                      ['2009-12-31', 516079.0],
                      ['2008-12-31', 504477.0],
                      ['2007-12-31', 492940.0],
                      ['2006-12-31', 481422.0],
                      ['2005-12-31', 469885.0],
                      ['2004-12-31', 458324.0],
                      ['2003-12-31', 446769.0],
                      ['2002-12-31', 435262.0],
                      ['2001-12-31', 423853.0],
                      ['2000-12-31', 412609.0],
                      ['1999-12-31', 401538.0],
                      ['1998-12-31', 390643.0],
                      ['1997-12-31', 379947.0],
                      ['1996-12-31', 369469.0],
                      ['1995-12-31', 359225.0],
                      ['1994-12-31', 349225.0],
                      ['1993-12-31', 339456.0],
                      ['1992-12-31', 329953.0],
                      ['1991-12-31', 320753.0],
                      ['1990-12-31', 311840.0],
                      ['1989-12-31', 303253.0],
                      ['1988-12-31', 294964.0],
                      ['1987-12-31', 286863.0],
                      ['1986-12-31', 278838.0],
                      ['1985-12-31', 270801.0],
                      ['1984-12-31', 262709.0],
                      ['1983-12-31', 254596.0],
                      ['1982-12-31', 246493.0],
                      ['1981-12-31', 238479.0],
                      ['1980-12-31', 230607.0],
                      ['1979-12-31', 222897.0],
                      ['1978-12-31', 215347.0],
                      ['1977-12-31', 207937.0],
                      ['1976-12-31', 200640.0],
                      ['1975-12-31', 193445.0],
                      ['1974-12-31', 186332.0],
                      ['1973-12-31', 179349.0],
                      ['1972-12-31', 172598.0],
                      ['1971-12-31', 166212.0],
                      ['1970-12-31', 160290.0],
                      ['1969-12-31', 154875.0],
                      ['1968-12-31', 149921.0],
                      ['1967-12-31', 145351.0],
                      ['1966-12-31', 141026.0],
                      ['1965-12-31', 136847.0],
                      ['1964-12-31', 132782.0],
                      ['1963-12-31', 128866.0],
                      ['1962-12-31', 125064.0],
                      ['1961-12-31', 121396.0],
                      ['1960-12-31', 117866.0],
                      ['1959-12-31', 114465.0],
                      ['1958-12-31', 111182.0],
                      ['1957-12-31', 108018.0],
                      ['1956-12-31', 104965.0],
                      ['1955-12-31', 102024.0],
                      ['1954-12-31', 99215.0],
                      ['1953-12-31', 96560.0],
                      ['1952-12-31', 94077.0],
                      ['1951-12-31', 91809.0],
                      ['1950-12-31', 89794.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'SLB_SP_POP_TOTL',
             'description': 'Population, total - Solomon Islands. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22240714,
             'limit': None,
             'name': 'Population, total - Solomon Islands',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:43:13.505Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
SOM
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 14742523.0],
                      ['2016-12-31', 14317996.0],
                      ['2015-12-31', 13908129.0],
                      ['2014-12-31', 13513125.0],
                      ['2013-12-31', 13132349.0],
                      ['2012-12-31', 12763776.0],
                      ['2011-12-31', 12404725.0],
                      ['2010-12-31', 12053223.0],
                      ['2009-12-31', 11707990.0],
                      ['2008-12-31', 11369276.0],
                      ['2007-12-31', 11038596.0],
                      ['2006-12-31', 10718317.0],
                      ['2005-12-31', 10409925.0],
                      ['2004-12-31', 10116228.0],
                      ['2003-12-31', 9836397.0],
                      ['2002-12-31', 9564167.0],
                      ['2001-12-31', 9290823.0],
                      ['2000-12-31', 9011479.0],
                      ['1999-12-31', 8720231.0],
                      ['1998-12-31', 8422372.0],
                      ['1997-12-31', 8137475.0],
                      ['1996-12-31', 7892389.0],
                      ['1995-12-31', 7704894.0],
                      ['1994-12-31', 7583954.0],
                      ['1993-12-31', 7519811.0],
                      ['1992-12-31', 7488544.0],
                      ['1991-12-31', 7455936.0],
                      ['1990-12-31', 7397347.0],
                      ['1989-12-31', 7298417.0],
                      ['1988-12-31', 7165295.0],
                      ['1987-12-31', 7018109.0],
                      ['1986-12-31', 6887372.0],
                      ['1985-12-31', 6791716.0],
                      ['1984-12-31', 6747932.0],
                      ['1983-12-31', 6740220.0],
                      ['1982-12-31', 6716448.0],
                      ['1981-12-31', 6604872.0],
                      ['1980-12-31', 6359126.0],
                      ['1979-12-31', 5953615.0],
                      ['1978-12-31', 5417740.0],
                      ['1977-12-31', 4827362.0],
                      ['1976-12-31', 4289469.0],
                      ['1975-12-31', 3880320.0],
                      ['1974-12-31', 3627504.0],
                      ['1973-12-31', 3506008.0],
                      ['1972-12-31', 3475022.0],
                      ['1971-12-31', 3470324.0],
                      ['1970-12-31', 3444553.0],
                      ['1969-12-31', 3387632.0],
                      ['1968-12-31', 3313786.0],
                      ['1967-12-31', 3228495.0],
                      ['1966-12-31', 3143836.0],
                      ['1965-12-31', 3068437.0],
                      ['1964-12-31', 3001126.0],
                      ['1963-12-31', 2936443.0],
                      ['1962-12-31', 2874190.0],
                      ['1961-12-31', 2814096.0],
                      ['1960-12-31', 2755947.0],
                      ['1959-12-31', 2699595.0],
                      ['1958-12-31', 2644994.0],
                      ['1957-12-31', 2592133.0],
                      ['1956-12-31', 2540989.0],
                      ['1955-12-31', 2491520.0],
                      ['1954-12-31', 2443625.0],
                      ['1953-12-31', 2397159.0],
                      ['1952-12-31', 2351929.0],
                      ['1951-12-31', 2307673.0],
                      ['1950-12-31', 2264082.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'SOM_SP_POP_TOTL',
             'description': 'Population, total - Somalia. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22246350,
             'limit': None,
             'name': 'Population, total - Somalia',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:43:32.252Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
ZAF

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 56717156.0],
                      ['2016-12-31', 56015473.0],
                      ['2015-12-31', 55291225.0],
                      ['2014-12-31', 54539571.0],
                      ['2013-12-31', 53767396.0],
                      ['2012-12-31', 52998213.0],
                      ['2011-12-31', 52263516.0],
                      ['2010-12-31', 51584663.0],
                      ['2009-12-31', 50970818.0],
                      ['2008-12-31', 50412129.0],
                      ['2007-12-31', 49887181.0],
                      ['2006-12-31', 49364582.0],
                      ['2005-12-31', 48820586.0],
                      ['2004-12-31', 48247395.0],
                      ['2003-12-31', 47648727.0],
                      ['2002-12-31', 47026173.0],
                      ['2001-12-31', 46385006.0],
                      ['2000-12-31', 45728315.0],
                      ['1999-12-31', 45058775.0],
                      ['1998-12-31', 44372112.0],
                      ['1997-12-31', 43657024.0],
                      ['1996-12-31', 42898520.0],
                      ['1995-12-31', 42088165.0],
                      ['1994-12-31', 41218901.0],
                      ['1993-12-31', 40300161.0],
                      ['1992-12-31', 39360225.0],
                      ['1991-12-31', 38437855.0],
                      ['1990-12-31', 37560525.0],
                      ['1989-12-31', 36740883.0],
                      ['1988-12-31', 35970537.0],
                      ['1987-12-31', 35230249.0],
                      ['1986-12-31', 34490419.0],
                      ['1985-12-31', 33730148.0],
                      ['1984-12-31', 32943584.0],
                      ['1983-12-31', 32139708.0],
                      ['1982-12-31', 31330259.0],
                      ['1981-12-31', 30532954.0],
                      ['1980-12-31', 29760471.0],
                      ['1979-12-31', 29017049.0],
                      ['1978-12-31', 28298150.0],
                      ['1977-12-31', 27597297.0],
                      ['1976-12-31', 26904349.0],
                      ['1975-12-31', 26212405.0],
                      ['1974-12-31', 25519604.0],
                      ['1973-12-31', 24829693.0],
                      ['1972-12-31', 24148137.0],
                      ['1971-12-31', 23482813.0],
                      ['1970-12-31', 22839451.0],
                      ['1969-12-31', 22219897.0],
                      ['1968-12-31', 21622590.0],
                      ['1967-12-31', 21045785.0],
                      ['1966-12-31', 20486439.0],
                      ['1965-12-31', 19942303.0],
                      ['1964-12-31', 19412975.0],
                      ['1963-12-31', 18899275.0],
                      ['1962-12-31', 18401608.0],
                      ['1961-12-31', 17920673.0],
                      ['1960-12-31', 17456855.0],
                      ['1959-12-31', 17009989.0],
                      ['1958-12-31', 16579477.0],
                      ['1957-12-31', 16164413.0],
                      ['1956-12-31', 15763822.0],
                      ['1955-12-31', 15376829.0],
                      ['1954-12-31', 15002729.0],
                      ['1953-12-31', 14641017.0],
                      ['1952-12-31', 14291415.0],
                      ['1951-12-31', 13953843.0],
                      ['1950-12-31', 13628428.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'ZAF_SP_POP_TOTL',
             'description': 'Population, total - South Africa. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22260218,
             'limit': None,
             'name': 'Population, total - South Africa',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:47:06.704Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
CSA
{'quandl_error': {'code': 'QECx02',
                  'message': 'You have submitted an incorrect Quandl code. '
                             'Please check your Quandl codes and try again.'}}
SAS
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 1788388852.0],
                      ['2016-12-31', 1766393714.0],
                      ['2015-12-31', 1744199944.0],
                      ['2014-12-31', 1721847786.0],
                      ['2013-12-31', 1699310450.0],
                      ['2012-12-31', 1676615491.0],
                      ['2011-12-31', 1653798614.0],
                      ['2010-12-31', 1630806784.0],
                      ['2009-12-31', 1607663899.0],
                      ['2008-12-31', 1584359049.0],
                      ['2007-12-31', 1560818860.0],
                      ['2006-12-31', 1536943534.0],
                      ['2005-12-31', 1512670560.0],
                      ['2004-12-31', 1487975237.0],
                      ['2003-12-31', 1462906674.0],
                      ['2002-12-31', 1437568227.0],
                      ['2001-12-31', 1412104373.0],
                      ['2000-12-31', 1386625845.0],
                      ['1999-12-31', 1361185289.0],
                      ['1998-12-31', 1335777637.0],
                      ['1997-12-31', 1310387887.0],
                      ['1996-12-31', 1284978193.0],
                      ['1995-12-31', 1259530819.0],
                      ['1994-12-31', 1234059205.0],
                      ['1993-12-31', 1208612942.0],
                      ['1992-12-31', 1183253534.0],
                      ['1991-12-31', 1158058109.0],
                      ['1990-12-31', 1133089464.0],
                      ['1989-12-31', 1108386444.0],
                      ['1988-12-31', 1083963380.0],
                      ['1987-12-31', 1059829211.0],
                      ['1986-12-31', 1035982524.0],
                      ['1985-12-31', 1012429641.0],
                      ['1984-12-31', 989188965.0],
                      ['1983-12-31', 966293643.0],
                      ['1982-12-31', 943781613.0],
                      ['1981-12-31', 921696915.0],
                      ['1980-12-31', 900076467.0],
                      ['1979-12-31', 878933031.0],
                      ['1978-12-31', 858277856.0],
                      ['1977-12-31', 838142287.0],
                      ['1976-12-31', 818560436.0],
                      ['1975-12-31', 799553306.0],
                      ['1974-12-31', 781140577.0],
                      ['1973-12-31', 763310561.0],
                      ['1972-12-31', 746012374.0],
                      ['1971-12-31', 729173562.0],
                      ['1970-12-31', 712740919.0],
                      ['1969-12-31', 696697198.0],
                      ['1968-12-31', 681054882.0],
                      ['1967-12-31', 665826653.0],
                      ['1966-12-31', 651036352.0],
                      ['1965-12-31', 636701820.0],
                      ['1964-12-31', 622822615.0],
                      ['1963-12-31', 609391805.0],
                      ['1962-12-31', 596413939.0],
                      ['1961-12-31', 583894094.0],
                      ['1960-12-31', 571835666.0],
                      ['1959-12-31', 560239656.0],
                      ['1958-12-31', 549104725.0],
                      ['1957-12-31', 538428019.0],
                      ['1956-12-31', 528205900.0],
                      ['1955-12-31', 518434569.0],
                      ['1954-12-31', 509110295.0],
                      ['1953-12-31', 500229655.0],
                      ['1952-12-31', 491789547.0],
                      ['1951-12-31', 483786962.0],
                      ['1950-12-31', 476219309.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'SAS_SP_POP_TOTL',
             'description': 'Population, total - South Asia. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22230123,
             'limit': None,
             'name': 'Population, total - South Asia',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:42:44.978Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
SSD

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 12575714.0],
                      ['2016-12-31', 12230730.0],
                      ['2015-12-31', 11882136.0],
                      ['2014-12-31', 11530971.0],
                      ['2013-12-31', 11177490.0],
                      ['2012-12-31', 10818258.0],
                      ['2011-12-31', 10448857.0],
                      ['2010-12-31', 10067192.0],
                      ['2009-12-31', 9670667.0],
                      ['2008-12-31', 9263136.0],
                      ['2007-12-31', 8856800.0],
                      ['2006-12-31', 8468152.0],
                      ['2005-12-31', 8108877.0],
                      ['2004-12-31', 7787655.0],
                      ['2003-12-31', 7501642.0],
                      ['2002-12-31', 7237276.0],
                      ['2001-12-31', 6974442.0],
                      ['2000-12-31', 6700656.0],
                      ['1999-12-31', 6405864.0],
                      ['1998-12-31', 6099923.0],
                      ['1997-12-31', 5814006.0],
                      ['1996-12-31', 5591114.0],
                      ['1995-12-31', 5459519.0],
                      ['1994-12-31', 5431738.0],
                      ['1993-12-31', 5490915.0],
                      ['1992-12-31', 5599814.0],
                      ['1991-12-31', 5705378.0],
                      ['1990-12-31', 5768481.0],
                      ['1989-12-31', 5777498.0],
                      ['1988-12-31', 5741235.0],
                      ['1987-12-31', 5666078.0],
                      ['1986-12-31', 5565545.0],
                      ['1985-12-31', 5450424.0],
                      ['1984-12-31', 5319609.0],
                      ['1983-12-31', 5170558.0],
                      ['1982-12-31', 5011726.0],
                      ['1981-12-31', 4853927.0],
                      ['1980-12-31', 4705224.0],
                      ['1979-12-31', 4569423.0],
                      ['1978-12-31', 4445826.0],
                      ['1977-12-31', 4332287.0],
                      ['1976-12-31', 4224529.0],
                      ['1975-12-31', 4119438.0],
                      ['1974-12-31', 4017075.0],
                      ['1973-12-31', 3918922.0],
                      ['1972-12-31', 3824762.0],
                      ['1971-12-31', 3734418.0],
                      ['1970-12-31', 3647709.0],
                      ['1969-12-31', 3564465.0],
                      ['1968-12-31', 3484537.0],
                      ['1967-12-31', 3407800.0],
                      ['1966-12-31', 3334191.0],
                      ['1965-12-31', 3263638.0],
                      ['1964-12-31', 3196113.0],
                      ['1963-12-31', 3131557.0],
                      ['1962-12-31', 3069913.0],
                      ['1961-12-31', 3011110.0],
                      ['1960-12-31', 2955152.0],
                      ['1959-12-31', 2902083.0],
                      ['1958-12-31', 2852016.0],
                      ['1957-12-31', 2805106.0],
                      ['1956-12-31', 2761544.0],
                      ['1955-12-31', 2721544.0],
                      ['1954-12-31', 2685325.0],
                      ['1953-12-31', 2653097.0],
                      ['1952-12-31', 2625126.0],
                      ['1951-12-31', 2601651.0],
                      ['1950-12-31', 2582929.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'SSD_SP_POP_TOTL',
             'description': 'Population, total - South Sudan. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22250630,
             'limit': None,
             'name': 'Population, total - South Sudan',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:43:47.263Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
ESP
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 46572028.0],
                      ['2016-12-31', 46484062.0],
                      ['2015-12-31', 46444832.0],
                      ['2014-12-31', 46480882.0],
                      ['2013-12-31', 46620045.0],
                      ['2012-12-31', 46773055.0],
                      ['2011-12-31', 46742697.0],
                      ['2010-12-31', 46576897.0],
                      ['2009-12-31', 46362946.0],
                      ['2008-12-31', 45954106.0],
                      ['2007-12-31', 45226803.0],
                      ['2006-12-31', 44397319.0],
                      ['2005-12-31', 43653155.0],
                      ['2004-12-31', 42921895.0],
                      ['2003-12-31', 42187645.0],
                      ['2002-12-31', 41431558.0],
                      ['2001-12-31', 40850412.0],
                      ['2000-12-31', 40567864.0],
                      ['1999-12-31', 40386875.0],
                      ['1998-12-31', 40223509.0],
                      ['1997-12-31', 40057389.0],
                      ['1996-12-31', 39889852.0],
                      ['1995-12-31', 39724050.0],
                      ['1994-12-31', 39549108.0],
                      ['1993-12-31', 39361262.0],
                      ['1992-12-31', 39157685.0],
                      ['1991-12-31', 38966376.0],
                      ['1990-12-31', 38867322.0],
                      ['1989-12-31', 38827764.0],
                      ['1988-12-31', 38766939.0],
                      ['1987-12-31', 38684815.0],
                      ['1986-12-31', 38584624.0],
                      ['1985-12-31', 38469512.0],
                      ['1984-12-31', 38330364.0],
                      ['1983-12-31', 38171525.0],
                      ['1982-12-31', 37986012.0],
                      ['1981-12-31', 37758631.0],
                      ['1980-12-31', 37491165.0],
                      ['1979-12-31', 37191330.0],
                      ['1978-12-31', 36864898.0],
                      ['1977-12-31', 36511638.0],
                      ['1976-12-31', 36137812.0],
                      ['1975-12-31', 35757900.0],
                      ['1974-12-31', 35373335.0],
                      ['1973-12-31', 34988947.0],
                      ['1972-12-31', 34604469.0],
                      ['1971-12-31', 34224490.0],
                      ['1970-12-31', 33814531.0],
                      ['1969-12-31', 33441054.0],
                      ['1968-12-31', 33113134.0],
                      ['1967-12-31', 32682947.0],
                      ['1966-12-31', 32283194.0],
                      ['1965-12-31', 31954292.0],
                      ['1964-12-31', 31609195.0],
                      ['1963-12-31', 31296651.0],
                      ['1962-12-31', 31023366.0],
                      ['1961-12-31', 30739250.0],
                      ['1960-12-31', 30455000.0],
                      ['1959-12-31', 30115936.0],
                      ['1958-12-31', 29838623.0],
                      ['1957-12-31', 29577608.0],
                      ['1956-12-31', 29328890.0],
                      ['1955-12-31', 29089637.0],
                      ['1954-12-31', 28858741.0],
                      ['1953-12-31', 28637153.0],
                      ['1952-12-31', 28427994.0],
                      ['1951-12-31', 28236442.0],
                      ['1950-12-31', 28069737.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'ESP_SP_POP_TOTL',
             'description': 'Population, total - Spain. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22136616,
             'limit': None,
             'name': 'Population, total - Spain',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:31:44.346Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
LKA

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 21444000.0],
                      ['2016-12-31', 21203000.0],
                      ['2015-12-31', 20966000.0],
                      ['2014-12-31', 20771000.0],
                      ['2013-12-31', 20585000.0],
                      ['2012-12-31', 20425000.0],
                      ['2011-12-31', 20315017.0],
                      ['2010-12-31', 20198353.0],
                      ['2009-12-31', 20075086.0],
                      ['2008-12-31', 19945832.0],
                      ['2007-12-31', 19810789.0],
                      ['2006-12-31', 19670151.0],
                      ['2005-12-31', 19524558.0],
                      ['2004-12-31', 19372538.0],
                      ['2003-12-31', 19215307.0],
                      ['2002-12-31', 19059300.0],
                      ['2001-12-31', 18913054.0],
                      ['2000-12-31', 18781938.0],
                      ['1999-12-31', 18669103.0],
                      ['1998-12-31', 18570701.0],
                      ['1997-12-31', 18476505.0],
                      ['1996-12-31', 18372120.0],
                      ['1995-12-31', 18247121.0],
                      ['1994-12-31', 18098348.0],
                      ['1993-12-31', 17928576.0],
                      ['1992-12-31', 17740637.0],
                      ['1991-12-31', 17539633.0],
                      ['1990-12-31', 17329713.0],
                      ['1989-12-31', 17110713.0],
                      ['1988-12-31', 16882189.0],
                      ['1987-12-31', 16647945.0],
                      ['1986-12-31', 16412711.0],
                      ['1985-12-31', 16179796.0],
                      ['1984-12-31', 15951422.0],
                      ['1983-12-31', 15726802.0],
                      ['1982-12-31', 15502515.0],
                      ['1981-12-31', 15273391.0],
                      ['1980-12-31', 15035856.0],
                      ['1979-12-31', 14788607.0],
                      ['1978-12-31', 14533376.0],
                      ['1977-12-31', 14273272.0],
                      ['1976-12-31', 14012817.0],
                      ['1975-12-31', 13755161.0],
                      ['1974-12-31', 13501986.0],
                      ['1973-12-31', 13252087.0],
                      ['1972-12-31', 13002275.0],
                      ['1971-12-31', 12747842.0],
                      ['1970-12-31', 12485756.0],
                      ['1969-12-31', 12214968.0],
                      ['1968-12-31', 11937611.0],
                      ['1967-12-31', 11657660.0],
                      ['1966-12-31', 11380683.0],
                      ['1965-12-31', 11110828.0],
                      ['1964-12-31', 10849979.0],
                      ['1963-12-31', 10597520.0],
                      ['1962-12-31', 10352188.0],
                      ['1961-12-31', 10111646.0],
                      ['1960-12-31', 9874481.0],
                      ['1959-12-31', 9640836.0],
                      ['1958-12-31', 9412155.0],
                      ['1957-12-31', 9190662.0],
                      ['1956-12-31', 8978773.0],
                      ['1955-12-31', 8778449.0],
                      ['1954-12-31', 8591028.0],
                      ['1953-12-31', 8417119.0],
                      ['1952-12-31', 8256561.0],
                      ['1951-12-31', 8108434.0],
                      ['1950-12-31', 7971098.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'LKA_SP_POP_TOTL',
             'description': 'Population, total - Sri Lanka. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22182230,
             'limit': None,
             'name': 'Population, total - Sri Lanka',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:36:56.338Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
KNA
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 55345.0],
                      ['2016-12-31', 54821.0],
                      ['2015-12-31', 54288.0],
                      ['2014-12-31', 53739.0],
                      ['2013-12-31', 53169.0],
                      ['2012-12-31', 52591.0],
                      ['2011-12-31', 52006.0],
                      ['2010-12-31', 51445.0],
                      ['2009-12-31', 50886.0],
                      ['2008-12-31', 50332.0],
                      ['2007-12-31', 49783.0],
                      ['2006-12-31', 49210.0],
                      ['2005-12-31', 48611.0],
                      ['2004-12-31', 47971.0],
                      ['2003-12-31', 47306.0],
                      ['2002-12-31', 46641.0],
                      ['2001-12-31', 45990.0],
                      ['2000-12-31', 45374.0],
                      ['1999-12-31', 44824.0],
                      ['1998-12-31', 44317.0],
                      ['1997-12-31', 43846.0],
                      ['1996-12-31', 43373.0],
                      ['1995-12-31', 42891.0],
                      ['1994-12-31', 42373.0],
                      ['1993-12-31', 41846.0],
                      ['1992-12-31', 41361.0],
                      ['1991-12-31', 41013.0],
                      ['1990-12-31', 40834.0],
                      ['1989-12-31', 40852.0],
                      ['1988-12-31', 41047.0],
                      ['1987-12-31', 41351.0],
                      ['1986-12-31', 41697.0],
                      ['1985-12-31', 42013.0],
                      ['1984-12-31', 42294.0],
                      ['1983-12-31', 42542.0],
                      ['1982-12-31', 42762.0],
                      ['1981-12-31', 42976.0],
                      ['1980-12-31', 43210.0],
                      ['1979-12-31', 43457.0],
                      ['1978-12-31', 43703.0],
                      ['1977-12-31', 43942.0],
                      ['1976-12-31', 44148.0],
                      ['1975-12-31', 44276.0],
                      ['1974-12-31', 44331.0],
                      ['1973-12-31', 44316.0],
                      ['1972-12-31', 44326.0],
                      ['1971-12-31', 44495.0],
                      ['1970-12-31', 44885.0],
                      ['1969-12-31', 45534.0],
                      ['1968-12-31', 46402.0],
                      ['1967-12-31', 47380.0],
                      ['1966-12-31', 48358.0],
                      ['1965-12-31', 49214.0],
                      ['1964-12-31', 49930.0],
                      ['1963-12-31', 50525.0],
                      ['1962-12-31', 50966.0],
                      ['1961-12-31', 51193.0],
                      ['1960-12-31', 51195.0],
                      ['1959-12-31', 50972.0],
                      ['1958-12-31', 50544.0],
                      ['1957-12-31', 49955.0],
                      ['1956-12-31', 49251.0],
                      ['1955-12-31', 48492.0],
                      ['1954-12-31', 47737.0],
                      ['1953-12-31', 47053.0],
                      ['1952-12-31', 46489.0],
                      ['1951-12-31', 46143.0],
                      ['1950-12-31', 46049.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'KNA_SP_POP_TOTL',
             'description': 'Population, total - St. Kitts and Nevis. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22161212,
             'limit': None,
             'name': 'Population, total - St. Kitts and Nevis',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:35:48.526Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
LCA

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 178844.0],
                      ['2016-12-31', 178015.0],
                      ['2015-12-31', 177206.0],
                      ['2014-12-31', 176421.0],
                      ['2013-12-31', 175660.0],
                      ['2012-12-31', 174835.0],
                      ['2011-12-31', 173832.0],
                      ['2010-12-31', 172580.0],
                      ['2009-12-31', 171022.0],
                      ['2008-12-31', 169220.0],
                      ['2007-12-31', 167288.0],
                      ['2006-12-31', 165407.0],
                      ['2005-12-31', 163714.0],
                      ['2004-12-31', 162251.0],
                      ['2003-12-31', 160973.0],
                      ['2002-12-31', 159763.0],
                      ['2001-12-31', 158464.0],
                      ['2000-12-31', 156949.0],
                      ['1999-12-31', 155172.0],
                      ['1998-12-31', 153183.0],
                      ['1997-12-31', 151086.0],
                      ['1996-12-31', 149004.0],
                      ['1995-12-31', 147044.0],
                      ['1994-12-31', 145247.0],
                      ['1993-12-31', 143565.0],
                      ['1992-12-31', 141925.0],
                      ['1991-12-31', 140156.0],
                      ['1990-12-31', 138185.0],
                      ['1989-12-31', 135956.0],
                      ['1988-12-31', 133533.0],
                      ['1987-12-31', 131034.0],
                      ['1986-12-31', 128619.0],
                      ['1985-12-31', 126418.0],
                      ['1984-12-31', 124468.0],
                      ['1983-12-31', 122740.0],
                      ['1982-12-31', 121154.0],
                      ['1981-12-31', 119594.0],
                      ['1980-12-31', 117987.0],
                      ['1979-12-31', 116290.0],
                      ['1978-12-31', 114546.0],
                      ['1977-12-31', 112831.0],
                      ['1976-12-31', 111208.0],
                      ['1975-12-31', 109769.0],
                      ['1974-12-31', 108532.0],
                      ['1973-12-31', 107466.0],
                      ['1972-12-31', 106455.0],
                      ['1971-12-31', 105390.0],
                      ['1970-12-31', 104160.0],
                      ['1969-12-31', 102749.0],
                      ['1968-12-31', 101179.0],
                      ['1967-12-31', 99527.0],
                      ['1966-12-31', 97881.0],
                      ['1965-12-31', 96302.0],
                      ['1964-12-31', 94814.0],
                      ['1963-12-31', 93399.0],
                      ['1962-12-31', 92084.0],
                      ['1961-12-31', 90914.0],
                      ['1960-12-31', 89897.0],
                      ['1959-12-31', 89044.0],
                      ['1958-12-31', 88330.0],
                      ['1957-12-31', 87719.0],
                      ['1956-12-31', 87178.0],
                      ['1955-12-31', 86654.0],
                      ['1954-12-31', 86106.0],
                      ['1953-12-31', 85491.0],
                      ['1952-12-31', 84763.0],
                      ['1951-12-31', 83874.0],
                      ['1950-12-31', 82784.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'LCA_SP_POP_TOTL',
             'description': 'Population, total - St. Lucia. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22175930,
             'limit': None,
             'name': 'Population, total - St. Lucia',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:36:34.869Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
MAF
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 32125.0],
                      ['2016-12-31', 31949.0],
                      ['2015-12-31', 31754.0],
                      ['2014-12-31', 31530.0],
                      ['2013-12-31', 31264.0],
                      ['2012-12-31', 30959.0],
                      ['2011-12-31', 30615.0],
                      ['2010-12-31', 30235.0],
                      ['2009-12-31', 29820.0],
                      ['2008-12-31', 29376.0],
                      ['2007-12-31', 28905.0],
                      ['2006-12-31', 28414.0],
                      ['2005-12-31', 27906.0],
                      ['2004-12-31', 27514.0],
                      ['2003-12-31', 27363.0],
                      ['2002-12-31', 27450.0],
                      ['2001-12-31', 27782.0],
                      ['2000-12-31', 28384.0],
                      ['1999-12-31', 29305.0],
                      ['1998-12-31', 30358.0],
                      ['1997-12-31', 31304.0],
                      ['1996-12-31', 32102.0],
                      ['1995-12-31', 32712.0],
                      ['1994-12-31', 33098.0],
                      ['1993-12-31', 33238.0],
                      ['1992-12-31', 32892.0],
                      ['1991-12-31', 31821.0],
                      ['1990-12-31', 30036.0],
                      ['1989-12-31', 27676.0],
                      ['1988-12-31', 24873.0],
                      ['1987-12-31', 21628.0],
                      ['1986-12-31', 18337.0],
                      ['1985-12-31', 15392.0],
                      ['1984-12-31', 12790.0],
                      ['1983-12-31', 10547.0],
                      ['1982-12-31', 8670.0],
                      ['1981-12-31', 7868.0],
                      ['1980-12-31', 7580.0],
                      ['1979-12-31', 7303.0],
                      ['1978-12-31', 7035.0],
                      ['1977-12-31', 6778.0],
                      ['1976-12-31', 6530.0],
                      ['1975-12-31', 6291.0],
                      ['1974-12-31', 6078.0],
                      ['1973-12-31', 5915.0],
                      ['1972-12-31', 5756.0],
                      ['1971-12-31', 5601.0],
                      ['1970-12-31', 5450.0],
                      ['1969-12-31', 5303.0],
                      ['1968-12-31', 5161.0],
                      ['1967-12-31', 5033.0],
                      ['1966-12-31', 4936.0],
                      ['1965-12-31', 4841.0],
                      ['1964-12-31', 4748.0],
                      ['1963-12-31', 4656.0],
                      ['1962-12-31', 4566.0],
                      ['1961-12-31', 4453.0],
                      ['1960-12-31', 4279.0],
                      ['1959-12-31', 4111.0],
                      ['1958-12-31', 3950.0],
                      ['1957-12-31', 3795.0],
                      ['1956-12-31', 3646.0],
                      ['1955-12-31', 3503.0],
                      ['1954-12-31', 3366.0],
                      ['1953-12-31', 3234.0],
                      ['1952-12-31', 3108.0],
                      ['1951-12-31', 2986.0],
                      ['1950-12-31', 2869.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'MAF_SP_POP_TOTL',
             'description': 'Population, total - St. Martin (French part). ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22193924,
             'limit': None,
             'name': 'Population, total - St. Martin (French part)',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:37:35.996Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
VCT
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 109897.0],
                      ['2016-12-31', 109643.0],
                      ['2015-12-31', 109455.0],
                      ['2014-12-31', 109357.0],
                      ['2013-12-31', 109320.0],
                      ['2012-12-31', 109328.0],
                      ['2011-12-31', 109341.0],
                      ['2010-12-31', 109315.0],
                      ['2009-12-31', 109253.0],
                      ['2008-12-31', 109165.0],
                      ['2007-12-31', 109047.0],
                      ['2006-12-31', 108907.0],
                      ['2005-12-31', 108744.0],
                      ['2004-12-31', 108559.0],
                      ['2003-12-31', 108350.0],
                      ['2002-12-31', 108146.0],
                      ['2001-12-31', 107988.0],
                      ['2000-12-31', 107898.0],
                      ['1999-12-31', 107880.0],
                      ['1998-12-31', 107922.0],
                      ['1997-12-31', 108004.0],
                      ['1996-12-31', 108075.0],
                      ['1995-12-31', 108122.0],
                      ['1994-12-31', 108129.0],
                      ['1993-12-31', 108092.0],
                      ['1992-12-31', 108003.0],
                      ['1991-12-31', 107814.0],
                      ['1990-12-31', 107505.0],
                      ['1989-12-31', 107084.0],
                      ['1988-12-31', 106536.0],
                      ['1987-12-31', 105896.0],
                      ['1986-12-31', 105198.0],
                      ['1985-12-31', 104477.0],
                      ['1984-12-31', 103742.0],
                      ['1983-12-31', 102984.0],
                      ['1982-12-31', 102204.0],
                      ['1981-12-31', 101379.0],
                      ['1980-12-31', 100505.0],
                      ['1979-12-31', 99590.0],
                      ['1978-12-31', 98633.0],
                      ['1977-12-31', 97649.0],
                      ['1976-12-31', 96641.0],
                      ['1975-12-31', 95611.0],
                      ['1974-12-31', 94568.0],
                      ['1973-12-31', 93517.0],
                      ['1972-12-31', 92463.0],
                      ['1971-12-31', 91440.0],
                      ['1970-12-31', 90452.0],
                      ['1969-12-31', 89516.0],
                      ['1968-12-31', 88613.0],
                      ['1967-12-31', 87736.0],
                      ['1966-12-31', 86857.0],
                      ['1965-12-31', 85970.0],
                      ['1964-12-31', 85069.0],
                      ['1963-12-31', 84167.0],
                      ['1962-12-31', 83206.0],
                      ['1961-12-31', 82142.0],
                      ['1960-12-31', 80949.0],
                      ['1959-12-31', 79618.0],
                      ['1958-12-31', 78168.0],
                      ['1957-12-31', 76635.0],
                      ['1956-12-31', 75080.0],
                      ['1955-12-31', 73523.0],
                      ['1954-12-31', 72022.0],
                      ['1953-12-31', 70593.0],
                      ['1952-12-31', 69271.0],
                      ['1951-12-31', 68059.0],
                      ['1950-12-31', 66998.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'VCT_SP_POP_TOTL',
             'description': 'Population, total - St. Vincent and the '
                            'Grenadines. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22248026,
             'limit': None,
             'name': 'Population, total - St. Vincent and the Grenadines',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:46:25.814Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
SSF

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 1061107721.0],
                      ['2016-12-31', 1033212743.0],
                      ['2015-12-31', 1005850049.0],
                      ['2014-12-31', 979017918.0],
                      ['2013-12-31', 952734072.0],
                      ['2012-12-31', 927039875.0],
                      ['2011-12-31', 901989926.0],
                      ['2010-12-31', 877628367.0],
                      ['2009-12-31', 853953657.0],
                      ['2008-12-31', 830965556.0],
                      ['2007-12-31', 808660166.0],
                      ['2006-12-31', 787035792.0],
                      ['2005-12-31', 766080507.0],
                      ['2004-12-31', 745788118.0],
                      ['2003-12-31', 726140617.0],
                      ['2002-12-31', 707099850.0],
                      ['2001-12-31', 688615995.0],
                      ['2000-12-31', 670649638.0],
                      ['1999-12-31', 653179863.0],
                      ['1998-12-31', 636182577.0],
                      ['1997-12-31', 619607956.0],
                      ['1996-12-31', 603385639.0],
                      ['1995-12-31', 587469624.0],
                      ['1994-12-31', 571828603.0],
                      ['1993-12-31', 556451898.0],
                      ['1992-12-31', 541365685.0],
                      ['1991-12-31', 526599014.0],
                      ['1990-12-31', 512177101.0],
                      ['1989-12-31', 498102752.0],
                      ['1988-12-31', 484357710.0],
                      ['1987-12-31', 470938971.0],
                      ['1986-12-31', 457835414.0],
                      ['1985-12-31', 445048059.0],
                      ['1984-12-31', 432573431.0],
                      ['1983-12-31', 420413518.0],
                      ['1982-12-31', 408577033.0],
                      ['1981-12-31', 397065556.0],
                      ['1980-12-31', 385885281.0],
                      ['1979-12-31', 375034981.0],
                      ['1978-12-31', 364515830.0],
                      ['1977-12-31', 354343159.0],
                      ['1976-12-31', 344522341.0],
                      ['1975-12-31', 335064879.0],
                      ['1974-12-31', 325972033.0],
                      ['1973-12-31', 317234127.0],
                      ['1972-12-31', 308831549.0],
                      ['1971-12-31', 300737023.0],
                      ['1970-12-31', 292929074.0],
                      ['1969-12-31', 285397999.0],
                      ['1968-12-31', 278138996.0],
                      ['1967-12-31', 271139271.0],
                      ['1966-12-31', 264386171.0],
                      ['1965-12-31', 257868609.0],
                      ['1964-12-31', 251576403.0],
                      ['1963-12-31', 245503266.0],
                      ['1962-12-31', 239647139.0],
                      ['1961-12-31', 234008580.0],
                      ['1960-12-31', 228586005.0],
                      ['1959-12-31', 223339134.0],
                      ['1958-12-31', 218341068.0],
                      ['1957-12-31', 213541461.0],
                      ['1956-12-31', 208931789.0],
                      ['1955-12-31', 204540648.0],
                      ['1954-12-31', 200254891.0],
                      ['1953-12-31', 196178549.0],
                      ['1952-12-31', 192274606.0],
                      ['1951-12-31', 188543586.0],
                      ['1950-12-31', 185021215.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'SSF_SP_POP_TOTL',
             'description': 'Population, total - Sub-Saharan Africa (all '
                            'income levels). ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22251824,
             'limit': None,
             'name': 'Population, total - Sub-Saharan Africa (all income '
                     'levels)',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:43:52.050Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
SSA
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 1061011878.0],
                      ['2016-12-31', 1033118066.0],
                      ['2015-12-31', 1005756630.0],
                      ['2014-12-31', 978926559.0],
                      ['2013-12-31', 952644123.0],
                      ['2012-12-31', 926951572.0],
                      ['2011-12-31', 901902485.0],
                      ['2010-12-31', 877538597.0],
                      ['2009-12-31', 853866359.0],
                      ['2008-12-31', 830878600.0],
                      ['2007-12-31', 808575133.0],
                      ['2006-12-31', 786951192.0],
                      ['2005-12-31', 765997649.0],
                      ['2004-12-31', 745705643.0],
                      ['2003-12-31', 726057836.0],
                      ['2002-12-31', 707016127.0],
                      ['2001-12-31', 688534793.0],
                      ['2000-12-31', 670568507.0],
                      ['1999-12-31', 653099453.0],
                      ['1998-12-31', 636103731.0],
                      ['1997-12-31', 619530637.0],
                      ['1996-12-31', 603309222.0],
                      ['1995-12-31', 587394320.0],
                      ['1994-12-31', 571754398.0],
                      ['1993-12-31', 556379645.0],
                      ['1992-12-31', 541294922.0],
                      ['1991-12-31', 526528575.0],
                      ['1990-12-31', 512107594.0],
                      ['1989-12-31', 498033585.0],
                      ['1988-12-31', 484288955.0],
                      ['1987-12-31', 470870472.0],
                      ['1986-12-31', 457769762.0],
                      ['1985-12-31', 444982815.0],
                      ['1984-12-31', 432508714.0],
                      ['1983-12-31', 420349183.0],
                      ['1982-12-31', 408512620.0],
                      ['1981-12-31', 397001521.0],
                      ['1980-12-31', 385822020.0],
                      ['1979-12-31', 374972295.0],
                      ['1978-12-31', 364453680.0],
                      ['1977-12-31', 354281373.0],
                      ['1976-12-31', 344461837.0],
                      ['1975-12-31', 335005587.0],
                      ['1974-12-31', 325914096.0],
                      ['1973-12-31', 317177235.0],
                      ['1972-12-31', 308775520.0],
                      ['1971-12-31', 300682328.0],
                      ['1970-12-31', 292875474.0],
                      ['1969-12-31', 285345634.0],
                      ['1968-12-31', 278087862.0],
                      ['1967-12-31', 271089360.0],
                      ['1966-12-31', 264337472.0],
                      ['1965-12-31', 257821109.0],
                      ['1964-12-31', 251530081.0],
                      ['1963-12-31', 245458090.0],
                      ['1962-12-31', 239603097.0],
                      ['1961-12-31', 233965691.0],
                      ['1960-12-31', 228544305.0],
                      ['1959-12-31', 223339134.0],
                      ['1958-12-31', 218341068.0],
                      ['1957-12-31', 213541461.0],
                      ['1956-12-31', 208931789.0],
                      ['1955-12-31', 204504748.0],
                      ['1954-12-31', 200254891.0],
                      ['1953-12-31', 196178549.0],
                      ['1952-12-31', 192274606.0],
                      ['1951-12-31', 188543586.0],
                      ['1950-12-31', 184988315.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'SSA_SP_POP_TOTL',
             'description': 'Population, total - Sub-Saharan Africa '
                            '(developing only). ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22249642,
             'limit': None,
             'name': 'Population, total - Sub-Saharan Africa (developing only)',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:43:42.918Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
CAA
{'quandl_error': {'code': 'QECx02',
                  'message': 'You have submitted an incorrect Quandl code. '
                             'Please check your Quandl codes and try again.'}}
XZN

{'quandl_error': {'code': 'QECx02',
                  'message': 'You have submitted an incorrect Quandl code. '
                             'Please check your Quandl codes and try again.'}}
SXZ
{'quandl_error': {'code': 'QECx02',
                  'message': 'You have submitted an incorrect Quandl code. '
                             'Please check your Quandl codes and try again.'}}
SDN
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 40533330.0],
                      ['2016-12-31', 39578828.0],
                      ['2015-12-31', 38647803.0],
                      ['2014-12-31', 37737913.0],
                      ['2013-12-31', 36849918.0],
                      ['2012-12-31', 35990192.0],
                      ['2011-12-31', 35167314.0],
                      ['2010-12-31', 34385963.0],
                      ['2009-12-31', 33650619.0],
                      ['2008-12-31', 32955496.0],
                      ['2007-12-31', 32282526.0],
                      ['2006-12-31', 31607064.0],
                      ['2005-12-31', 30911914.0],
                      ['2004-12-31', 30186341.0],
                      ['2003-12-31', 29435944.0],
                      ['2002-12-31', 28679565.0],
                      ['2001-12-31', 27945005.0],
                      ['2000-12-31', 27250535.0],
                      ['1999-12-31', 26607042.0],
                      ['1998-12-31', 26003542.0],
                      ['1997-12-31', 25410451.0],
                      ['1996-12-31', 24786190.0],
                      ['1995-12-31', 24102986.0],
                      ['1994-12-31', 23347885.0],
                      ['1993-12-31', 22535937.0],
                      ['1992-12-31', 21701476.0],
                      ['1991-12-31', 20893625.0],
                      ['1990-12-31', 20147590.0],
                      ['1989-12-31', 19475609.0],
                      ['1988-12-31', 18866319.0],
                      ['1987-12-31', 18302587.0],
                      ['1986-12-31', 17757169.0],
                      ['1985-12-31', 17210187.0],
                      ['1984-12-31', 16658054.0],
                      ['1983-12-31', 16107730.0],
                      ['1982-12-31', 15562194.0],
                      ['1981-12-31', 15027270.0],
                      ['1980-12-31', 14507468.0],
                      ['1979-12-31', 14002303.0],
                      ['1978-12-31', 13510421.0],
                      ['1977-12-31', 13034625.0],
                      ['1976-12-31', 12578407.0],
                      ['1975-12-31', 12144135.0],
                      ['1974-12-31', 11732958.0],
                      ['1973-12-31', 11343926.0],
                      ['1972-12-31', 10974622.0],
                      ['1971-12-31', 10621472.0],
                      ['1970-12-31', 10281700.0],
                      ['1969-12-31', 9954410.0],
                      ['1968-12-31', 9639840.0],
                      ['1967-12-31', 9337657.0],
                      ['1966-12-31', 9047798.0],
                      ['1965-12-31', 8770097.0],
                      ['1964-12-31', 8503994.0],
                      ['1963-12-31', 8248812.0],
                      ['1962-12-31', 8004121.0],
                      ['1961-12-31', 7769482.0],
                      ['1960-12-31', 7544491.0],
                      ['1959-12-31', 7328718.0],
                      ['1958-12-31', 7121741.0],
                      ['1957-12-31', 6923115.0],
                      ['1956-12-31', 6732437.0],
                      ['1955-12-31', 6549298.0],
                      ['1954-12-31', 6373308.0],
                      ['1953-12-31', 6204099.0],
                      ['1952-12-31', 6041325.0],
                      ['1951-12-31', 5884664.0],
                      ['1950-12-31', 5733789.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'SDN_SP_POP_TOTL',
             'description': 'Population, total - Sudan. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22235876,
             'limit': None,
             'name': 'Population, total - Sudan',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:42:56.115Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
SUR
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 563402.0],
                      ['2016-12-31', 558368.0],
                      ['2015-12-31', 553208.0],
                      ['2014-12-31', 547928.0],
                      ['2013-12-31', 542540.0],
                      ['2012-12-31', 537077.0],
                      ['2011-12-31', 531589.0],
                      ['2010-12-31', 526103.0],
                      ['2009-12-31', 520619.0],
                      ['2008-12-31', 515148.0],
                      ['2007-12-31', 509705.0],
                      ['2006-12-31', 504307.0],
                      ['2005-12-31', 498946.0],
                      ['2004-12-31', 493630.0],
                      ['2003-12-31', 488332.0],
                      ['2002-12-31', 483044.0],
                      ['2001-12-31', 477740.0],
                      ['2000-12-31', 472390.0],
                      ['1999-12-31', 467003.0],
                      ['1998-12-31', 461560.0],
                      ['1997-12-31', 455954.0],
                      ['1996-12-31', 450036.0],
                      ['1995-12-31', 443724.0],
                      ['1994-12-31', 437037.0],
                      ['1993-12-31', 430039.0],
                      ['1992-12-31', 422763.0],
                      ['1991-12-31', 415216.0],
                      ['1990-12-31', 407472.0],
                      ['1989-12-31', 399492.0],
                      ['1988-12-31', 391391.0],
                      ['1987-12-31', 383654.0],
                      ['1986-12-31', 376867.0],
                      ['1985-12-31', 371470.0],
                      ['1984-12-31', 367660.0],
                      ['1983-12-31', 365300.0],
                      ['1982-12-31', 364032.0],
                      ['1981-12-31', 363325.0],
                      ['1980-12-31', 362777.0],
                      ['1979-12-31', 362125.0],
                      ['1978-12-31', 361457.0],
                      ['1977-12-31', 361043.0],
                      ['1976-12-31', 361364.0],
                      ['1975-12-31', 362654.0],
                      ['1974-12-31', 365099.0],
                      ['1973-12-31', 368344.0],
                      ['1972-12-31', 371324.0],
                      ['1971-12-31', 372623.0],
                      ['1970-12-31', 371273.0],
                      ['1969-12-31', 366848.0],
                      ['1968-12-31', 359733.0],
                      ['1967-12-31', 350751.0],
                      ['1966-12-31', 341133.0],
                      ['1965-12-31', 331793.0],
                      ['1964-12-31', 322997.0],
                      ['1963-12-31', 314528.0],
                      ['1962-12-31', 306328.0],
                      ['1961-12-31', 298188.0],
                      ['1960-12-31', 289966.0],
                      ['1959-12-31', 281668.0],
                      ['1958-12-31', 273382.0],
                      ['1957-12-31', 265273.0],
                      ['1956-12-31', 257485.0],
                      ['1955-12-31', 250088.0],
                      ['1954-12-31', 243088.0],
                      ['1953-12-31', 236347.0],
                      ['1952-12-31', 229652.0],
                      ['1951-12-31', 222679.0],
                      ['1950-12-31', 215002.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'SUR_SP_POP_TOTL',
             'description': 'Population, total - Suriname. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22255975,
             'limit': None,
             'name': 'Population, total - Suriname',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:44:06.373Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
SWZ

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 1367254.0],
                      ['2016-12-31', 1343098.0],
                      ['2015-12-31', 1319011.0],
                      ['2014-12-31', 1295097.0],
                      ['2013-12-31', 1271456.0],
                      ['2012-12-31', 1248158.0],
                      ['2011-12-31', 1225258.0],
                      ['2010-12-31', 1202843.0],
                      ['2009-12-31', 1180675.0],
                      ['2008-12-31', 1158897.0],
                      ['2007-12-31', 1138434.0],
                      ['2006-12-31', 1120514.0],
                      ['2005-12-31', 1105873.0],
                      ['2004-12-31', 1095053.0],
                      ['2003-12-31', 1087392.0],
                      ['2002-12-31', 1080930.0],
                      ['2001-12-31', 1072927.0],
                      ['2000-12-31', 1061468.0],
                      ['1999-12-31', 1045629.0],
                      ['1998-12-31', 1026009.0],
                      ['1997-12-31', 1003995.0],
                      ['1996-12-31', 981764.0],
                      ['1995-12-31', 960792.0],
                      ['1994-12-31', 941774.0],
                      ['1993-12-31', 924025.0],
                      ['1992-12-31', 906034.0],
                      ['1991-12-31', 885623.0],
                      ['1990-12-31', 861373.0],
                      ['1989-12-31', 832682.0],
                      ['1988-12-31', 800456.0],
                      ['1987-12-31', 766707.0],
                      ['1986-12-31', 734243.0],
                      ['1985-12-31', 705085.0],
                      ['1984-12-31', 679976.0],
                      ['1983-12-31', 658320.0],
                      ['1982-12-31', 639237.0],
                      ['1981-12-31', 621276.0],
                      ['1980-12-31', 603372.0],
                      ['1979-12-31', 585344.0],
                      ['1978-12-31', 567559.0],
                      ['1977-12-31', 550118.0],
                      ['1976-12-31', 533214.0],
                      ['1975-12-31', 517024.0],
                      ['1974-12-31', 501512.0],
                      ['1973-12-31', 486561.0],
                      ['1972-12-31', 472230.0],
                      ['1971-12-31', 458605.0],
                      ['1970-12-31', 445729.0],
                      ['1969-12-31', 433588.0],
                      ['1968-12-31', 422140.0],
                      ['1967-12-31', 411352.0],
                      ['1966-12-31', 401183.0],
                      ['1965-12-31', 391546.0],
                      ['1964-12-31', 382469.0],
                      ['1963-12-31', 373897.0],
                      ['1962-12-31', 365636.0],
                      ['1961-12-31', 357453.0],
                      ['1960-12-31', 349174.0],
                      ['1959-12-31', 340748.0],
                      ['1958-12-31', 332221.0],
                      ['1957-12-31', 323712.0],
                      ['1956-12-31', 315341.0],
                      ['1955-12-31', 307226.0],
                      ['1954-12-31', 299486.0],
                      ['1953-12-31', 292178.0],
                      ['1952-12-31', 285334.0],
                      ['1951-12-31', 278952.0],
                      ['1950-12-31', 273003.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'SWZ_SP_POP_TOTL',
             'description': 'Population, total - Swaziland. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22262888,
             'limit': None,
             'name': 'Population, total - Swaziland',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:44:27.867Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
SWE
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 10067744.0],
                      ['2016-12-31', 9923085.0],
                      ['2015-12-31', 9799186.0],
                      ['2014-12-31', 9696110.0],
                      ['2013-12-31', 9600379.0],
                      ['2012-12-31', 9519374.0],
                      ['2011-12-31', 9449213.0],
                      ['2010-12-31', 9378126.0],
                      ['2009-12-31', 9298515.0],
                      ['2008-12-31', 9219637.0],
                      ['2007-12-31', 9148092.0],
                      ['2006-12-31', 9080505.0],
                      ['2005-12-31', 9029572.0],
                      ['2004-12-31', 8993531.0],
                      ['2003-12-31', 8958229.0],
                      ['2002-12-31', 8924958.0],
                      ['2001-12-31', 8895960.0],
                      ['2000-12-31', 8872109.0],
                      ['1999-12-31', 8857874.0],
                      ['1998-12-31', 8850974.0],
                      ['1997-12-31', 8846062.0],
                      ['1996-12-31', 8840998.0],
                      ['1995-12-31', 8826939.0],
                      ['1994-12-31', 8780745.0],
                      ['1993-12-31', 8718561.0],
                      ['1992-12-31', 8668067.0],
                      ['1991-12-31', 8617375.0],
                      ['1990-12-31', 8558835.0],
                      ['1989-12-31', 8492964.0],
                      ['1988-12-31', 8436489.0],
                      ['1987-12-31', 8397804.0],
                      ['1986-12-31', 8369829.0],
                      ['1985-12-31', 8350386.0],
                      ['1984-12-31', 8336605.0],
                      ['1983-12-31', 8329033.0],
                      ['1982-12-31', 8325263.0],
                      ['1981-12-31', 8320503.0],
                      ['1980-12-31', 8310531.0],
                      ['1979-12-31', 8293678.0],
                      ['1978-12-31', 8275599.0],
                      ['1977-12-31', 8251540.0],
                      ['1976-12-31', 8222286.0],
                      ['1975-12-31', 8192437.0],
                      ['1974-12-31', 8159955.0],
                      ['1973-12-31', 8136312.0],
                      ['1972-12-31', 8122300.0],
                      ['1971-12-31', 8098334.0],
                      ['1970-12-31', 8042801.0],
                      ['1969-12-31', 7968072.0],
                      ['1968-12-31', 7912273.0],
                      ['1967-12-31', 7867931.0],
                      ['1966-12-31', 7807797.0],
                      ['1965-12-31', 7733853.0],
                      ['1964-12-31', 7661354.0],
                      ['1963-12-31', 7604328.0],
                      ['1962-12-31', 7561588.0],
                      ['1961-12-31', 7519998.0],
                      ['1960-12-31', 7484656.0],
                      ['1959-12-31', 7434674.0],
                      ['1958-12-31', 7390134.0],
                      ['1957-12-31', 7346541.0],
                      ['1956-12-31', 7303942.0],
                      ['1955-12-31', 7261994.0],
                      ['1954-12-31', 7219871.0],
                      ['1953-12-31', 7176203.0],
                      ['1952-12-31', 7129070.0],
                      ['1951-12-31', 7076003.0],
                      ['1950-12-31', 7014001.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'SWE_SP_POP_TOTL',
             'description': 'Population, total - Sweden. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22261234,
             'limit': None,
             'name': 'Population, total - Sweden',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:44:21.852Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
CHE

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 8466017.0],
                      ['2016-12-31', 8373338.0],
                      ['2015-12-31', 8282396.0],
                      ['2014-12-31', 8188649.0],
                      ['2013-12-31', 8089346.0],
                      ['2012-12-31', 7996861.0],
                      ['2011-12-31', 7912398.0],
                      ['2010-12-31', 7824909.0],
                      ['2009-12-31', 7743831.0],
                      ['2008-12-31', 7647675.0],
                      ['2007-12-31', 7551117.0],
                      ['2006-12-31', 7483934.0],
                      ['2005-12-31', 7437115.0],
                      ['2004-12-31', 7389625.0],
                      ['2003-12-31', 7339001.0],
                      ['2002-12-31', 7284753.0],
                      ['2001-12-31', 7229854.0],
                      ['2000-12-31', 7184250.0],
                      ['1999-12-31', 7143991.0],
                      ['1998-12-31', 7110001.0],
                      ['1997-12-31', 7088906.0],
                      ['1996-12-31', 7071850.0],
                      ['1995-12-31', 7040687.0],
                      ['1994-12-31', 6993795.0],
                      ['1993-12-31', 6938265.0],
                      ['1992-12-31', 6875364.0],
                      ['1991-12-31', 6799978.0],
                      ['1990-12-31', 6715519.0],
                      ['1989-12-31', 6646912.0],
                      ['1988-12-31', 6593386.0],
                      ['1987-12-31', 6545106.0],
                      ['1986-12-31', 6504124.0],
                      ['1985-12-31', 6470365.0],
                      ['1984-12-31', 6441865.0],
                      ['1983-12-31', 6418773.0],
                      ['1982-12-31', 6391309.0],
                      ['1981-12-31', 6354074.0],
                      ['1980-12-31', 6319408.0],
                      ['1979-12-31', 6294365.0],
                      ['1978-12-31', 6281738.0],
                      ['1977-12-31', 6281174.0],
                      ['1976-12-31', 6302504.0],
                      ['1975-12-31', 6338632.0],
                      ['1974-12-31', 6341405.0],
                      ['1973-12-31', 6307347.0],
                      ['1972-12-31', 6260956.0],
                      ['1971-12-31', 6213399.0],
                      ['1970-12-31', 6180877.0],
                      ['1969-12-31', 6136387.0],
                      ['1968-12-31', 6067714.0],
                      ['1967-12-31', 5991785.0],
                      ['1966-12-31', 5918002.0],
                      ['1965-12-31', 5856472.0],
                      ['1964-12-31', 5789228.0],
                      ['1963-12-31', 5694247.0],
                      ['1962-12-31', 5573815.0],
                      ['1961-12-31', 5434294.0],
                      ['1960-12-31', 5327827.0],
                      ['1959-12-31', 5213340.0],
                      ['1958-12-31', 5143629.0],
                      ['1957-12-31', 5082961.0],
                      ['1956-12-31', 5026644.0],
                      ['1955-12-31', 4970798.0],
                      ['1954-12-31', 4912879.0],
                      ['1953-12-31', 4851983.0],
                      ['1952-12-31', 4788955.0],
                      ['1951-12-31', 4726281.0],
                      ['1950-12-31', 4668088.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'CHE_SP_POP_TOTL',
             'description': 'Population, total - Switzerland. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22087087,
             'limit': None,
             'name': 'Population, total - Switzerland',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:28:59.037Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
SYR
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 18269868.0],
                      ['2016-12-31', 18430453.0],
                      ['2015-12-31', 18734987.0],
                      ['2014-12-31', 19203090.0],
                      ['2013-12-31', 19809141.0],
                      ['2012-12-31', 20420701.0],
                      ['2011-12-31', 20863993.0],
                      ['2010-12-31', 21018834.0],
                      ['2009-12-31', 20824893.0],
                      ['2008-12-31', 20325443.0],
                      ['2007-12-31', 19632806.0],
                      ['2006-12-31', 18914977.0],
                      ['2005-12-31', 18294611.0],
                      ['2004-12-31', 17806638.0],
                      ['2003-12-31', 17415266.0],
                      ['2002-12-31', 17087901.0],
                      ['2001-12-31', 16766899.0],
                      ['2000-12-31', 16410848.0],
                      ['1999-12-31', 16016092.0],
                      ['1998-12-31', 15602210.0],
                      ['1997-12-31', 15177456.0],
                      ['1996-12-31', 14755286.0],
                      ['1995-12-31', 14345492.0],
                      ['1994-12-31', 13949697.0],
                      ['1993-12-31', 13564167.0],
                      ['1992-12-31', 13187085.0],
                      ['1991-12-31', 12815219.0],
                      ['1990-12-31', 12446171.0],
                      ['1989-12-31', 12080444.0],
                      ['1988-12-31', 11719071.0],
                      ['1987-12-31', 11360852.0],
                      ['1986-12-31', 11004272.0],
                      ['1985-12-31', 10648632.0],
                      ['1984-12-31', 10293049.0],
                      ['1983-12-31', 9938847.0],
                      ['1982-12-31', 9590227.0],
                      ['1981-12-31', 9252851.0],
                      ['1980-12-31', 8930774.0],
                      ['1979-12-31', 8625690.0],
                      ['1978-12-31', 8336418.0],
                      ['1977-12-31', 8060649.0],
                      ['1976-12-31', 7794662.0],
                      ['1975-12-31', 7535714.0],
                      ['1974-12-31', 7283177.0],
                      ['1973-12-31', 7037851.0],
                      ['1972-12-31', 6800141.0],
                      ['1971-12-31', 6570857.0],
                      ['1970-12-31', 6350541.0],
                      ['1969-12-31', 6139048.0],
                      ['1968-12-31', 5935860.0],
                      ['1967-12-31', 5740710.0],
                      ['1966-12-31', 5553246.0],
                      ['1965-12-31', 5373137.0],
                      ['1964-12-31', 5200336.0],
                      ['1963-12-31', 5034646.0],
                      ['1962-12-31', 4875422.0],
                      ['1961-12-31', 4721896.0],
                      ['1960-12-31', 4573512.0],
                      ['1959-12-31', 4430101.0],
                      ['1958-12-31', 4291803.0],
                      ['1957-12-31', 4158976.0],
                      ['1956-12-31', 4032069.0],
                      ['1955-12-31', 3911501.0],
                      ['1954-12-31', 3797624.0],
                      ['1953-12-31', 3690735.0],
                      ['1952-12-31', 3591006.0],
                      ['1951-12-31', 3498526.0],
                      ['1950-12-31', 3413331.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'SYR_SP_POP_TOTL',
             'description': 'Population, total - Syrian Arab Republic. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22265478,
             'limit': None,
             'name': 'Population, total - Syrian Arab Republic',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:44:40.137Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
TJK

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 8921343.0],
                      ['2016-12-31', 8734951.0],
                      ['2015-12-31', 8548651.0],
                      ['2014-12-31', 8362745.0],
                      ['2013-12-31', 8177809.0],
                      ['2012-12-31', 7995062.0],
                      ['2011-12-31', 7815949.0],
                      ['2010-12-31', 7641630.0],
                      ['2009-12-31', 7472819.0],
                      ['2008-12-31', 7309728.0],
                      ['2007-12-31', 7152385.0],
                      ['2006-12-31', 7000557.0],
                      ['2005-12-31', 6854176.0],
                      ['2004-12-31', 6712841.0],
                      ['2003-12-31', 6576877.0],
                      ['2002-12-31', 6447688.0],
                      ['2001-12-31', 6327125.0],
                      ['2000-12-31', 6216205.0],
                      ['1999-12-31', 6114886.0],
                      ['1998-12-31', 6021691.0],
                      ['1997-12-31', 5934282.0],
                      ['1996-12-31', 5849540.0],
                      ['1995-12-31', 5764712.0],
                      ['1994-12-31', 5679832.0],
                      ['1993-12-31', 5594114.0],
                      ['1992-12-31', 5502976.0],
                      ['1991-12-31', 5400714.0],
                      ['1990-12-31', 5283728.0],
                      ['1989-12-31', 5149803.0],
                      ['1988-12-31', 5001110.0],
                      ['1987-12-31', 4843951.0],
                      ['1986-12-31', 4687283.0],
                      ['1985-12-31', 4537789.0],
                      ['1984-12-31', 4397525.0],
                      ['1983-12-31', 4265247.0],
                      ['1982-12-31', 4140258.0],
                      ['1981-12-31', 4020778.0],
                      ['1980-12-31', 3905413.0],
                      ['1979-12-31', 3794420.0],
                      ['1978-12-31', 3688385.0],
                      ['1977-12-31', 3586499.0],
                      ['1976-12-31', 3487644.0],
                      ['1975-12-31', 3390935.0],
                      ['1974-12-31', 3296095.0],
                      ['1973-12-31', 3203019.0],
                      ['1972-12-31', 3111264.0],
                      ['1971-12-31', 3020391.0],
                      ['1970-12-31', 2930079.0],
                      ['1969-12-31', 2840228.0],
                      ['1968-12-31', 2750894.0],
                      ['1967-12-31', 2662230.0],
                      ['1966-12-31', 2574478.0],
                      ['1965-12-31', 2487953.0],
                      ['1964-12-31', 2402455.0],
                      ['1963-12-31', 2318234.0],
                      ['1962-12-31', 2236559.0],
                      ['1961-12-31', 2159123.0],
                      ['1960-12-31', 2087038.0],
                      ['1959-12-31', 2020554.0],
                      ['1958-12-31', 1959137.0],
                      ['1957-12-31', 1901775.0],
                      ['1956-12-31', 1847251.0],
                      ['1955-12-31', 1794414.0],
                      ['1954-12-31', 1742345.0],
                      ['1953-12-31', 1690334.0],
                      ['1952-12-31', 1637950.0],
                      ['1951-12-31', 1584992.0],
                      ['1950-12-31', 1531501.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'TJK_SP_POP_TOTL',
             'description': 'Population, total - Tajikistan. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22269381,
             'limit': None,
             'name': 'Population, total - Tajikistan',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:45:05.804Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
TZA
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 57310019.0],
                      ['2016-12-31', 55572201.0],
                      ['2015-12-31', 53879957.0],
                      ['2014-12-31', 52234869.0],
                      ['2013-12-31', 50636595.0],
                      ['2012-12-31', 49082997.0],
                      ['2011-12-31', 47570902.0],
                      ['2010-12-31', 46098591.0],
                      ['2009-12-31', 44664231.0],
                      ['2008-12-31', 43270144.0],
                      ['2007-12-31', 41923715.0],
                      ['2006-12-31', 40634948.0],
                      ['2005-12-31', 39410545.0],
                      ['2004-12-31', 38249984.0],
                      ['2003-12-31', 37149072.0],
                      ['2002-12-31', 36105808.0],
                      ['2001-12-31', 35117019.0],
                      ['2000-12-31', 34178042.0],
                      ['1999-12-31', 33291540.0],
                      ['1998-12-31', 32451713.0],
                      ['1997-12-31', 31635251.0],
                      ['1996-12-31', 30811854.0],
                      ['1995-12-31', 29960776.0],
                      ['1994-12-31', 29070615.0],
                      ['1993-12-31', 28149328.0],
                      ['1992-12-31', 27219619.0],
                      ['1991-12-31', 26315013.0],
                      ['1990-12-31', 25459604.0],
                      ['1989-12-31', 24660575.0],
                      ['1988-12-31', 23909954.0],
                      ['1987-12-31', 23198533.0],
                      ['1986-12-31', 22511243.0],
                      ['1985-12-31', 21836999.0],
                      ['1984-12-31', 21173603.0],
                      ['1983-12-31', 20524666.0],
                      ['1982-12-31', 19891548.0],
                      ['1981-12-31', 19277108.0],
                      ['1980-12-31', 18683157.0],
                      ['1979-12-31', 18109884.0],
                      ['1978-12-31', 17555494.0],
                      ['1977-12-31', 17017670.0],
                      ['1976-12-31', 16493305.0],
                      ['1975-12-31', 15980301.0],
                      ['1974-12-31', 15477294.0],
                      ['1973-12-31', 14985131.0],
                      ['1972-12-31', 14506617.0],
                      ['1971-12-31', 14045824.0],
                      ['1970-12-31', 13605529.0],
                      ['1969-12-31', 13186557.0],
                      ['1968-12-31', 12787489.0],
                      ['1967-12-31', 12406040.0],
                      ['1966-12-31', 12038903.0],
                      ['1965-12-31', 11683528.0],
                      ['1964-12-31', 11339097.0],
                      ['1963-12-31', 11005905.0],
                      ['1962-12-31', 10683906.0],
                      ['1961-12-31', 10373398.0],
                      ['1960-12-31', 10074507.0],
                      ['1959-12-31', 9787033.0],
                      ['1958-12-31', 9510514.0],
                      ['1957-12-31', 9244352.0],
                      ['1956-12-31', 8987975.0],
                      ['1955-12-31', 8740986.0],
                      ['1954-12-31', 8503221.0],
                      ['1953-12-31', 8274746.0],
                      ['1952-12-31', 8055911.0],
                      ['1951-12-31', 7847305.0],
                      ['1950-12-31', 7649761.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'TZA_SP_POP_TOTL',
             'description': 'Population, total - Tanzania. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22275677,
             'limit': None,
             'name': 'Population, total - Tanzania',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:45:47.266Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
THA

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 69037513.0],
                      ['2016-12-31', 68863514.0],
                      ['2015-12-31', 68657600.0],
                      ['2014-12-31', 68416772.0],
                      ['2013-12-31', 68143065.0],
                      ['2012-12-31', 67843979.0],
                      ['2011-12-31', 67530130.0],
                      ['2010-12-31', 67208808.0],
                      ['2009-12-31', 66881867.0],
                      ['2008-12-31', 66545760.0],
                      ['2007-12-31', 66195615.0],
                      ['2006-12-31', 65824164.0],
                      ['2005-12-31', 65425470.0],
                      ['2004-12-31', 65002231.0],
                      ['2003-12-31', 64554952.0],
                      ['2002-12-31', 64073164.0],
                      ['2001-12-31', 63543322.0],
                      ['2000-12-31', 62958021.0],
                      ['1999-12-31', 62306651.0],
                      ['1998-12-31', 61597283.0],
                      ['1997-12-31', 60863506.0],
                      ['1996-12-31', 60151472.0],
                      ['1995-12-31', 59491790.0],
                      ['1994-12-31', 58901666.0],
                      ['1993-12-31', 58364891.0],
                      ['1992-12-31', 57837878.0],
                      ['1991-12-31', 57258401.0],
                      ['1990-12-31', 56582821.0],
                      ['1989-12-31', 55795106.0],
                      ['1988-12-31', 54912334.0],
                      ['1987-12-31', 53964406.0],
                      ['1986-12-31', 52996467.0],
                      ['1985-12-31', 52041469.0],
                      ['1984-12-31', 51108082.0],
                      ['1983-12-31', 50186199.0],
                      ['1982-12-31', 49267560.0],
                      ['1981-12-31', 48337503.0],
                      ['1980-12-31', 47385323.0],
                      ['1979-12-31', 46412307.0],
                      ['1978-12-31', 45423436.0],
                      ['1977-12-31', 44416010.0],
                      ['1976-12-31', 43386841.0],
                      ['1975-12-31', 42334954.0],
                      ['1974-12-31', 41259536.0],
                      ['1973-12-31', 40164966.0],
                      ['1972-12-31', 39061994.0],
                      ['1971-12-31', 37964925.0],
                      ['1970-12-31', 36884913.0],
                      ['1969-12-31', 35826804.0],
                      ['1968-12-31', 34790945.0],
                      ['1967-12-31', 33778504.0],
                      ['1966-12-31', 32789096.0],
                      ['1965-12-31', 31822796.0],
                      ['1964-12-31', 30881332.0],
                      ['1963-12-31', 29967041.0],
                      ['1962-12-31', 29081034.0],
                      ['1961-12-31', 28224204.0],
                      ['1960-12-31', 27397175.0],
                      ['1959-12-31', 26600275.0],
                      ['1958-12-31', 25833553.0],
                      ['1957-12-31', 25096792.0],
                      ['1956-12-31', 24389519.0],
                      ['1955-12-31', 23711046.0],
                      ['1954-12-31', 23060430.0],
                      ['1953-12-31', 22436533.0],
                      ['1952-12-31', 21837985.0],
                      ['1951-12-31', 21263202.0],
                      ['1950-12-31', 20710360.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'THA_SP_POP_TOTL',
             'description': 'Population, total - Thailand. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22268411,
             'limit': None,
             'name': 'Population, total - Thailand',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:44:59.856Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
TLS
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 1296311.0],
                      ['2016-12-31', 1268671.0],
                      ['2015-12-31', 1240977.0],
                      ['2014-12-31', 1212814.0],
                      ['2013-12-31', 1184366.0],
                      ['2012-12-31', 1156760.0],
                      ['2011-12-31', 1131523.0],
                      ['2010-12-31', 1109591.0],
                      ['2009-12-31', 1092021.0],
                      ['2008-12-31', 1078110.0],
                      ['2007-12-31', 1064973.0],
                      ['2006-12-31', 1048621.0],
                      ['2005-12-31', 1026484.0],
                      ['2004-12-31', 996698.0],
                      ['2003-12-31', 960852.0],
                      ['2002-12-31', 923825.0],
                      ['2001-12-31', 892531.0],
                      ['2000-12-31', 871607.0],
                      ['1999-12-31', 863269.0],
                      ['1998-12-31', 865194.0],
                      ['1997-12-31', 871994.0],
                      ['1996-12-31', 875916.0],
                      ['1995-12-31', 871447.0],
                      ['1994-12-31', 856684.0],
                      ['1993-12-31', 833611.0],
                      ['1992-12-31', 805435.0],
                      ['1991-12-31', 777011.0],
                      ['1990-12-31', 751933.0],
                      ['1989-12-31', 731444.0],
                      ['1988-12-31', 714474.0],
                      ['1987-12-31', 699522.0],
                      ['1986-12-31', 684184.0],
                      ['1985-12-31', 666945.0],
                      ['1984-12-31', 646688.0],
                      ['1983-12-31', 624648.0],
                      ['1982-12-31', 604430.0],
                      ['1981-12-31', 591005.0],
                      ['1980-12-31', 587563.0],
                      ['1979-12-31', 595872.0],
                      ['1978-12-31', 613857.0],
                      ['1977-12-31', 636096.0],
                      ['1976-12-31', 654947.0],
                      ['1975-12-31', 664984.0],
                      ['1974-12-31', 664223.0],
                      ['1973-12-31', 654437.0],
                      ['1972-12-31', 638499.0],
                      ['1971-12-31', 620945.0],
                      ['1970-12-31', 605125.0],
                      ['1969-12-31', 591739.0],
                      ['1968-12-31', 579807.0],
                      ['1967-12-31', 569031.0],
                      ['1966-12-31', 558676.0],
                      ['1965-12-31', 548218.0],
                      ['1964-12-31', 537786.0],
                      ['1963-12-31', 527749.0],
                      ['1962-12-31', 518107.0],
                      ['1961-12-31', 508845.0],
                      ['1960-12-31', 499950.0],
                      ['1959-12-31', 491423.0],
                      ['1958-12-31', 483279.0],
                      ['1957-12-31', 475546.0],
                      ['1956-12-31', 468246.0],
                      ['1955-12-31', 461385.0],
                      ['1954-12-31', 454968.0],
                      ['1953-12-31', 448981.0],
                      ['1952-12-31', 443420.0],
                      ['1951-12-31', 438237.0],
                      ['1950-12-31', 433397.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'TLS_SP_POP_TOTL',
             'description': 'Population, total - Timor-Leste. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22270825,
             'limit': None,
             'name': 'Population, total - Timor-Leste',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:45:15.166Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
TGO

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 7797694.0],
                      ['2016-12-31', 7606374.0],
                      ['2015-12-31', 7416802.0],
                      ['2014-12-31', 7228915.0],
                      ['2013-12-31', 7042948.0],
                      ['2012-12-31', 6859482.0],
                      ['2011-12-31', 6679282.0],
                      ['2010-12-31', 6502952.0],
                      ['2009-12-31', 6330472.0],
                      ['2008-12-31', 6161796.0],
                      ['2007-12-31', 5997385.0],
                      ['2006-12-31', 5837792.0],
                      ['2005-12-31', 5683268.0],
                      ['2004-12-31', 5534598.0],
                      ['2003-12-31', 5391401.0],
                      ['2002-12-31', 5251472.0],
                      ['2001-12-31', 5111770.0],
                      ['2000-12-31', 4970367.0],
                      ['1999-12-31', 4825704.0],
                      ['1998-12-31', 4679023.0],
                      ['1997-12-31', 4534551.0],
                      ['1996-12-31', 4398238.0],
                      ['1995-12-31', 4274024.0],
                      ['1994-12-31', 4163642.0],
                      ['1993-12-31', 4064926.0],
                      ['1992-12-31', 3973327.0],
                      ['1991-12-31', 3882271.0],
                      ['1990-12-31', 3786940.0],
                      ['1989-12-31', 3686373.0],
                      ['1988-12-31', 3581928.0],
                      ['1987-12-31', 3474080.0],
                      ['1986-12-31', 3364020.0],
                      ['1985-12-31', 3252994.0],
                      ['1984-12-31', 3140237.0],
                      ['1983-12-31', 3026238.0],
                      ['1982-12-31', 2915066.0],
                      ['1981-12-31', 2812039.0],
                      ['1980-12-31', 2720839.0],
                      ['1979-12-31', 2642846.0],
                      ['1978-12-31', 2576469.0],
                      ['1977-12-31', 2518566.0],
                      ['1976-12-31', 2464455.0],
                      ['1975-12-31', 2410446.0],
                      ['1974-12-31', 2356622.0],
                      ['1973-12-31', 2303345.0],
                      ['1972-12-31', 2247582.0],
                      ['1971-12-31', 2185662.0],
                      ['1970-12-31', 2115522.0],
                      ['1969-12-31', 2034907.0],
                      ['1968-12-31', 1945780.0],
                      ['1967-12-31', 1855442.0],
                      ['1966-12-31', 1774029.0],
                      ['1965-12-31', 1708630.0],
                      ['1964-12-31', 1662073.0],
                      ['1963-12-31', 1631764.0],
                      ['1962-12-31', 1612755.0],
                      ['1961-12-31', 1597526.0],
                      ['1960-12-31', 1580513.0],
                      ['1959-12-31', 1559674.0],
                      ['1958-12-31', 1535969.0],
                      ['1957-12-31', 1512029.0],
                      ['1956-12-31', 1490731.0],
                      ['1955-12-31', 1473839.0],
                      ['1954-12-31', 1461520.0],
                      ['1953-12-31', 1452088.0],
                      ['1952-12-31', 1441906.0],
                      ['1951-12-31', 1425487.0],
                      ['1950-12-31', 1395457.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'TGO_SP_POP_TOTL',
             'description': 'Population, total - Togo. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22267428,
             'limit': None,
             'name': 'Population, total - Togo',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:44:53.688Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
TON
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 108020.0],
                      ['2016-12-31', 107122.0],
                      ['2015-12-31', 106364.0],
                      ['2014-12-31', 105782.0],
                      ['2013-12-31', 105328.0],
                      ['2012-12-31', 104951.0],
                      ['2011-12-31', 104577.0],
                      ['2010-12-31', 104137.0],
                      ['2009-12-31', 103604.0],
                      ['2008-12-31', 103005.0],
                      ['2007-12-31', 102357.0],
                      ['2006-12-31', 101689.0],
                      ['2005-12-31', 101041.0],
                      ['2004-12-31', 100406.0],
                      ['2003-12-31', 99789.0],
                      ['2002-12-31', 99184.0],
                      ['2001-12-31', 98611.0],
                      ['2000-12-31', 98082.0],
                      ['1999-12-31', 97591.0],
                      ['1998-12-31', 97135.0],
                      ['1997-12-31', 96725.0],
                      ['1996-12-31', 96369.0],
                      ['1995-12-31', 96076.0],
                      ['1994-12-31', 95833.0],
                      ['1993-12-31', 95644.0],
                      ['1992-12-31', 95496.0],
                      ['1991-12-31', 95333.0],
                      ['1990-12-31', 95153.0],
                      ['1989-12-31', 94929.0],
                      ['1988-12-31', 94667.0],
                      ['1987-12-31', 94384.0],
                      ['1986-12-31', 94145.0],
                      ['1985-12-31', 93953.0],
                      ['1984-12-31', 93842.0],
                      ['1983-12-31', 93774.0],
                      ['1982-12-31', 93681.0],
                      ['1981-12-31', 93453.0],
                      ['1980-12-31', 93007.0],
                      ['1979-12-31', 92300.0],
                      ['1978-12-31', 91364.0],
                      ['1977-12-31', 90295.0],
                      ['1976-12-31', 89254.0],
                      ['1975-12-31', 88348.0],
                      ['1974-12-31', 87609.0],
                      ['1973-12-31', 86988.0],
                      ['1972-12-31', 86347.0],
                      ['1971-12-31', 85518.0],
                      ['1970-12-31', 84369.0],
                      ['1969-12-31', 82877.0],
                      ['1968-12-31', 81097.0],
                      ['1967-12-31', 79052.0],
                      ['1966-12-31', 76779.0],
                      ['1965-12-31', 74362.0],
                      ['1964-12-31', 71757.0],
                      ['1963-12-31', 69005.0],
                      ['1962-12-31', 66259.0],
                      ['1961-12-31', 63745.0],
                      ['1960-12-31', 61601.0],
                      ['1959-12-31', 59873.0],
                      ['1958-12-31', 58508.0],
                      ['1957-12-31', 57387.0],
                      ['1956-12-31', 56366.0],
                      ['1955-12-31', 55323.0],
                      ['1954-12-31', 54150.0],
                      ['1953-12-31', 52783.0],
                      ['1952-12-31', 51170.0],
                      ['1951-12-31', 49315.0],
                      ['1950-12-31', 47220.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'TON_SP_POP_TOTL',
             'description': 'Population, total - Tonga. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22271525,
             'limit': None,
             'name': 'Population, total - Tonga',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:45:20.151Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
TTO
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 1369125.0],
                      ['2016-12-31', 1364962.0],
                      ['2015-12-31', 1360092.0],
                      ['2014-12-31', 1354493.0],
                      ['2013-12-31', 1348248.0],
                      ['2012-12-31', 1341588.0],
                      ['2011-12-31', 1334788.0],
                      ['2010-12-31', 1328100.0],
                      ['2009-12-31', 1321618.0],
                      ['2008-12-31', 1315372.0],
                      ['2007-12-31', 1309260.0],
                      ['2006-12-31', 1303144.0],
                      ['2005-12-31', 1296934.0],
                      ['2004-12-31', 1290535.0],
                      ['2003-12-31', 1284052.0],
                      ['2002-12-31', 1277837.0],
                      ['2001-12-31', 1272380.0],
                      ['2000-12-31', 1267984.0],
                      ['1999-12-31', 1264775.0],
                      ['1998-12-31', 1262542.0],
                      ['1997-12-31', 1260678.0],
                      ['1996-12-31', 1258364.0],
                      ['1995-12-31', 1255001.0],
                      ['1994-12-31', 1250318.0],
                      ['1993-12-31', 1244407.0],
                      ['1992-12-31', 1237487.0],
                      ['1991-12-31', 1229907.0],
                      ['1990-12-31', 1221900.0],
                      ['1989-12-31', 1213624.0],
                      ['1988-12-31', 1204893.0],
                      ['1987-12-31', 1195247.0],
                      ['1986-12-31', 1184051.0],
                      ['1985-12-31', 1170928.0],
                      ['1984-12-31', 1155695.0],
                      ['1983-12-31', 1138676.0],
                      ['1982-12-31', 1120611.0],
                      ['1981-12-31', 1102556.0],
                      ['1980-12-31', 1085308.0],
                      ['1979-12-31', 1069202.0],
                      ['1978-12-31', 1054116.0],
                      ['1977-12-31', 1039761.0],
                      ['1976-12-31', 1025658.0],
                      ['1975-12-31', 1011490.0],
                      ['1974-12-31', 997053.0],
                      ['1973-12-31', 982592.0],
                      ['1972-12-31', 968741.0],
                      ['1971-12-31', 956366.0],
                      ['1970-12-31', 945993.0],
                      ['1969-12-31', 937848.0],
                      ['1968-12-31', 931468.0],
                      ['1967-12-31', 925909.0],
                      ['1966-12-31', 919903.0],
                      ['1965-12-31', 912417.0],
                      ['1964-12-31', 903275.0],
                      ['1963-12-31', 892569.0],
                      ['1962-12-31', 880023.0],
                      ['1961-12-31', 865360.0],
                      ['1960-12-31', 848479.0],
                      ['1959-12-31', 829489.0],
                      ['1958-12-31', 808663.0],
                      ['1957-12-31', 786433.0],
                      ['1956-12-31', 763354.0],
                      ['1955-12-31', 740035.0],
                      ['1954-12-31', 717156.0],
                      ['1953-12-31', 695465.0],
                      ['1952-12-31', 675741.0],
                      ['1951-12-31', 658833.0],
                      ['1950-12-31', 645635.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'TTO_SP_POP_TOTL',
             'description': 'Population, total - Trinidad and Tobago. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22272395,
             'limit': None,
             'name': 'Population, total - Trinidad and Tobago',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:45:25.208Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
TUN

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 11532127.0],
                      ['2016-12-31', 11403248.0],
                      ['2015-12-31', 11273661.0],
                      ['2014-12-31', 11143908.0],
                      ['2013-12-31', 11014558.0],
                      ['2012-12-31', 10886668.0],
                      ['2011-12-31', 10761467.0],
                      ['2010-12-31', 10639931.0],
                      ['2009-12-31', 10521834.0],
                      ['2008-12-31', 10407336.0],
                      ['2007-12-31', 10298087.0],
                      ['2006-12-31', 10196136.0],
                      ['2005-12-31', 10102482.0],
                      ['2004-12-31', 10017601.0],
                      ['2003-12-31', 9939678.0],
                      ['2002-12-31', 9864326.0],
                      ['2001-12-31', 9785701.0],
                      ['2000-12-31', 9699197.0],
                      ['1999-12-31', 9603742.0],
                      ['1998-12-31', 9499395.0],
                      ['1997-12-31', 9384152.0],
                      ['1996-12-31', 9256037.0],
                      ['1995-12-31', 9113975.0],
                      ['1994-12-31', 8956596.0],
                      ['1993-12-31', 8784888.0],
                      ['1992-12-31', 8603225.0],
                      ['1991-12-31', 8417684.0],
                      ['1990-12-31', 8232797.0],
                      ['1989-12-31', 8050932.0],
                      ['1988-12-31', 7871459.0],
                      ['1987-12-31', 7692254.0],
                      ['1986-12-31', 7509756.0],
                      ['1985-12-31', 7321876.0],
                      ['1984-12-31', 7127941.0],
                      ['1983-12-31', 6930387.0],
                      ['1982-12-31', 6733961.0],
                      ['1981-12-31', 6545024.0],
                      ['1980-12-31', 6368167.0],
                      ['1979-12-31', 6205212.0],
                      ['1978-12-31', 6054911.0],
                      ['1977-12-31', 5915006.0],
                      ['1976-12-31', 5781796.0],
                      ['1975-12-31', 5652476.0],
                      ['1974-12-31', 5526764.0],
                      ['1973-12-31', 5405355.0],
                      ['1972-12-31', 5287543.0],
                      ['1971-12-31', 5172691.0],
                      ['1970-12-31', 5060397.0],
                      ['1969-12-31', 4950153.0],
                      ['1968-12-31', 4842167.0],
                      ['1967-12-31', 4737627.0],
                      ['1966-12-31', 4638275.0],
                      ['1965-12-31', 4545339.0],
                      ['1964-12-31', 4458611.0],
                      ['1963-12-31', 4377637.0],
                      ['1962-12-31', 4303131.0],
                      ['1961-12-31', 4235937.0],
                      ['1960-12-31', 4176266.0],
                      ['1959-12-31', 4123439.0],
                      ['1958-12-31', 4075963.0],
                      ['1957-12-31', 4031785.0],
                      ['1956-12-31', 3988478.0],
                      ['1955-12-31', 3943528.0],
                      ['1954-12-31', 3894387.0],
                      ['1953-12-31', 3838507.0],
                      ['1952-12-31', 3773355.0],
                      ['1951-12-31', 3696450.0],
                      ['1950-12-31', 3605306.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'TUN_SP_POP_TOTL',
             'description': 'Population, total - Tunisia. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22273355,
             'limit': None,
             'name': 'Population, total - Tunisia',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:45:31.654Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
TUR
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 80745020.0],
                      ['2016-12-31', 79512426.0],
                      ['2015-12-31', 78271472.0],
                      ['2014-12-31', 77030628.0],
                      ['2013-12-31', 75787333.0],
                      ['2012-12-31', 74569867.0],
                      ['2011-12-31', 73409455.0],
                      ['2010-12-31', 72326914.0],
                      ['2009-12-31', 71339185.0],
                      ['2008-12-31', 70440032.0],
                      ['2007-12-31', 69597281.0],
                      ['2006-12-31', 68763405.0],
                      ['2005-12-31', 67903406.0],
                      ['2004-12-31', 67007855.0],
                      ['2003-12-31', 66085803.0],
                      ['2002-12-31', 65143054.0],
                      ['2001-12-31', 64191474.0],
                      ['2000-12-31', 63240121.0],
                      ['1999-12-31', 62287326.0],
                      ['1998-12-31', 61329590.0],
                      ['1997-12-31', 60372499.0],
                      ['1996-12-31', 59423208.0],
                      ['1995-12-31', 58486381.0],
                      ['1994-12-31', 57564132.0],
                      ['1993-12-31', 56653729.0],
                      ['1992-12-31', 55748875.0],
                      ['1991-12-31', 54840531.0],
                      ['1990-12-31', 53921699.0],
                      ['1989-12-31', 52992429.0],
                      ['1988-12-31', 52053704.0],
                      ['1987-12-31', 51100878.0],
                      ['1986-12-31', 50128489.0],
                      ['1985-12-31', 49133883.0],
                      ['1984-12-31', 48114105.0],
                      ['1983-12-31', 47073422.0],
                      ['1982-12-31', 46025357.0],
                      ['1981-12-31', 44988356.0],
                      ['1980-12-31', 43975921.0],
                      ['1979-12-31', 42993991.0],
                      ['1978-12-31', 42039935.0],
                      ['1977-12-31', 41108248.0],
                      ['1976-12-31', 40189511.0],
                      ['1975-12-31', 39277211.0],
                      ['1974-12-31', 38370241.0],
                      ['1973-12-31', 37472298.0],
                      ['1972-12-31', 36587225.0],
                      ['1971-12-31', 35720568.0],
                      ['1970-12-31', 34876267.0],
                      ['1969-12-31', 34055361.0],
                      ['1968-12-31', 33256432.0],
                      ['1967-12-31', 32477961.0],
                      ['1966-12-31', 31717477.0],
                      ['1965-12-31', 30972965.0],
                      ['1964-12-31', 30244232.0],
                      ['1963-12-31', 29531342.0],
                      ['1962-12-31', 28832805.0],
                      ['1961-12-31', 28146893.0],
                      ['1960-12-31', 27472331.0],
                      ['1959-12-31', 26808621.0],
                      ['1958-12-31', 26155911.0],
                      ['1957-12-31', 25514810.0],
                      ['1956-12-31', 24886111.0],
                      ['1955-12-31', 24270585.0],
                      ['1954-12-31', 23668906.0],
                      ['1953-12-31', 23081575.0],
                      ['1952-12-31', 22508947.0],
                      ['1951-12-31', 21951206.0],
                      ['1950-12-31', 21408401.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'TUR_SP_POP_TOTL',
             'description': 'Population, total - Turkey. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22274345,
             'limit': None,
             'name': 'Population, total - Turkey',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:45:37.955Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
TKM

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 5758075.0],
                      ['2016-12-31', 5662544.0],
                      ['2015-12-31', 5565284.0],
                      ['2014-12-31', 5466241.0],
                      ['2013-12-31', 5366277.0],
                      ['2012-12-31', 5267839.0],
                      ['2011-12-31', 5174061.0],
                      ['2010-12-31', 5087210.0],
                      ['2009-12-31', 5007950.0],
                      ['2008-12-31', 4935762.0],
                      ['2007-12-31', 4870137.0],
                      ['2006-12-31', 4810105.0],
                      ['2005-12-31', 4754641.0],
                      ['2004-12-31', 4703398.0],
                      ['2003-12-31', 4655741.0],
                      ['2002-12-31', 4610002.0],
                      ['2001-12-31', 4564080.0],
                      ['2000-12-31', 4516131.0],
                      ['1999-12-31', 4466132.0],
                      ['1998-12-31', 4413477.0],
                      ['1997-12-31', 4355114.0],
                      ['1996-12-31', 4287344.0],
                      ['1995-12-31', 4207840.0],
                      ['1994-12-31', 4115099.0],
                      ['1993-12-31', 4010789.0],
                      ['1992-12-31', 3899843.0],
                      ['1991-12-31', 3789185.0],
                      ['1990-12-31', 3683966.0],
                      ['1989-12-31', 3585867.0],
                      ['1988-12-31', 3493894.0],
                      ['1987-12-31', 3407319.0],
                      ['1986-12-31', 3324456.0],
                      ['1985-12-31', 3244018.0],
                      ['1984-12-31', 3166221.0],
                      ['1983-12-31', 3091511.0],
                      ['1982-12-31', 3019066.0],
                      ['1981-12-31', 2947779.0],
                      ['1980-12-31', 2876808.0],
                      ['1979-12-31', 2805818.0],
                      ['1978-12-31', 2734896.0],
                      ['1977-12-31', 2664257.0],
                      ['1976-12-31', 2594311.0],
                      ['1975-12-31', 2525361.0],
                      ['1974-12-31', 2457382.0],
                      ['1973-12-31', 2390213.0],
                      ['1972-12-31', 2324013.0],
                      ['1971-12-31', 2258964.0],
                      ['1970-12-31', 2195173.0],
                      ['1969-12-31', 2132799.0],
                      ['1968-12-31', 2071789.0],
                      ['1967-12-31', 2011763.0],
                      ['1966-12-31', 1952141.0],
                      ['1965-12-31', 1892599.0],
                      ['1964-12-31', 1833063.0],
                      ['1963-12-31', 1773853.0],
                      ['1962-12-31', 1715408.0],
                      ['1961-12-31', 1658362.0],
                      ['1960-12-31', 1603258.0],
                      ['1959-12-31', 1550411.0],
                      ['1958-12-31', 1500017.0],
                      ['1957-12-31', 1452173.0],
                      ['1956-12-31', 1406981.0],
                      ['1955-12-31', 1364634.0],
                      ['1954-12-31', 1325434.0],
                      ['1953-12-31', 1289826.0],
                      ['1952-12-31', 1258388.0],
                      ['1951-12-31', 1231829.0],
                      ['1950-12-31', 1210994.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'TKM_SP_POP_TOTL',
             'description': 'Population, total - Turkmenistan. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22270150,
             'limit': None,
             'name': 'Population, total - Turkmenistan',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:45:10.323Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
TCA
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 35446.0],
                      ['2016-12-31', 34900.0],
                      ['2015-12-31', 34339.0],
                      ['2014-12-31', 33739.0],
                      ['2013-12-31', 33108.0],
                      ['2012-12-31', 32431.0],
                      ['2011-12-31', 31731.0],
                      ['2010-12-31', 30994.0],
                      ['2009-12-31', 30245.0],
                      ['2008-12-31', 29481.0],
                      ['2007-12-31', 28640.0],
                      ['2006-12-31', 27642.0],
                      ['2005-12-31', 26448.0],
                      ['2004-12-31', 25028.0],
                      ['2003-12-31', 23410.0],
                      ['2002-12-31', 21742.0],
                      ['2001-12-31', 20185.0],
                      ['2000-12-31', 18873.0],
                      ['1999-12-31', 17864.0],
                      ['1998-12-31', 17115.0],
                      ['1997-12-31', 16528.0],
                      ['1996-12-31', 15966.0],
                      ['1995-12-31', 15332.0],
                      ['1994-12-31', 14597.0],
                      ['1993-12-31', 13789.0],
                      ['1992-12-31', 12968.0],
                      ['1991-12-31', 12206.0],
                      ['1990-12-31', 11552.0],
                      ['1989-12-31', 11017.0],
                      ['1988-12-31', 10582.0],
                      ['1987-12-31', 10224.0],
                      ['1986-12-31', 9875.0],
                      ['1985-12-31', 9506.0],
                      ['1984-12-31', 9095.0],
                      ['1983-12-31', 8669.0],
                      ['1982-12-31', 8244.0],
                      ['1981-12-31', 7858.0],
                      ['1980-12-31', 7519.0],
                      ['1979-12-31', 7264.0],
                      ['1978-12-31', 7053.0],
                      ['1977-12-31', 6886.0],
                      ['1976-12-31', 6723.0],
                      ['1975-12-31', 6548.0],
                      ['1974-12-31', 6346.0],
                      ['1973-12-31', 6126.0],
                      ['1972-12-31', 5922.0],
                      ['1971-12-31', 5756.0],
                      ['1970-12-31', 5633.0],
                      ['1969-12-31', 5571.0],
                      ['1968-12-31', 5559.0],
                      ['1967-12-31', 5590.0],
                      ['1966-12-31', 5629.0],
                      ['1965-12-31', 5672.0],
                      ['1964-12-31', 5710.0],
                      ['1963-12-31', 5740.0],
                      ['1962-12-31', 5763.0],
                      ['1961-12-31', 5763.0],
                      ['1960-12-31', 5726.0],
                      ['1959-12-31', 5656.0],
                      ['1958-12-31', 5559.0],
                      ['1957-12-31', 5446.0],
                      ['1956-12-31', 5315.0],
                      ['1955-12-31', 5197.0],
                      ['1954-12-31', 5093.0],
                      ['1953-12-31', 5014.0],
                      ['1952-12-31', 4981.0],
                      ['1951-12-31', 4987.0],
                      ['1950-12-31', 5051.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'TCA_SP_POP_TOTL',
             'description': 'Population, total - Turks and Caicos Islands. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22265843,
             'limit': None,
             'name': 'Population, total - Turks and Caicos Islands',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:44:42.323Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
TUV
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 11192.0],
                      ['2016-12-31', 11097.0],
                      ['2015-12-31', 11001.0],
                      ['2014-12-31', 10908.0],
                      ['2013-12-31', 10819.0],
                      ['2012-12-31', 10725.0],
                      ['2011-12-31', 10628.0],
                      ['2010-12-31', 10531.0],
                      ['2009-12-31', 10441.0],
                      ['2008-12-31', 10340.0],
                      ['2007-12-31', 10243.0],
                      ['2006-12-31', 10137.0],
                      ['2005-12-31', 10027.0],
                      ['2004-12-31', 9894.0],
                      ['2003-12-31', 9767.0],
                      ['2002-12-31', 9635.0],
                      ['2001-12-31', 9512.0],
                      ['2000-12-31', 9420.0],
                      ['1999-12-31', 9345.0],
                      ['1998-12-31', 9306.0],
                      ['1997-12-31', 9277.0],
                      ['1996-12-31', 9256.0],
                      ['1995-12-31', 9230.0],
                      ['1994-12-31', 9190.0],
                      ['1993-12-31', 9156.0],
                      ['1992-12-31', 9109.0],
                      ['1991-12-31', 9053.0],
                      ['1990-12-31', 9003.0],
                      ['1989-12-31', 8947.0],
                      ['1988-12-31', 8883.0],
                      ['1987-12-31', 8820.0],
                      ['1986-12-31', 8747.0],
                      ['1985-12-31', 8650.0],
                      ['1984-12-31', 8530.0],
                      ['1983-12-31', 8413.0],
                      ['1982-12-31', 8284.0],
                      ['1981-12-31', 8154.0],
                      ['1980-12-31', 8052.0],
                      ['1979-12-31', 7962.0],
                      ['1978-12-31', 7888.0],
                      ['1977-12-31', 7816.0],
                      ['1976-12-31', 7749.0],
                      ['1975-12-31', 7677.0],
                      ['1974-12-31', 7616.0],
                      ['1973-12-31', 7537.0],
                      ['1972-12-31', 7458.0],
                      ['1971-12-31', 7381.0],
                      ['1970-12-31', 7303.0],
                      ['1969-12-31', 7214.0],
                      ['1968-12-31', 7133.0],
                      ['1967-12-31', 7040.0],
                      ['1966-12-31', 6938.0],
                      ['1965-12-31', 6815.0],
                      ['1964-12-31', 6684.0],
                      ['1963-12-31', 6538.0],
                      ['1962-12-31', 6389.0],
                      ['1961-12-31', 6246.0],
                      ['1960-12-31', 6104.0],
                      ['1959-12-31', 5982.0],
                      ['1958-12-31', 5864.0],
                      ['1957-12-31', 5760.0],
                      ['1956-12-31', 5658.0],
                      ['1955-12-31', 5569.0],
                      ['1954-12-31', 5473.0],
                      ['1953-12-31', 5371.0],
                      ['1952-12-31', 5293.0],
                      ['1951-12-31', 5220.0],
                      ['1950-12-31', 5166.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'TUV_SP_POP_TOTL',
             'description': 'Population, total - Tuvalu. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22274820,
             'limit': None,
             'name': 'Population, total - Tuvalu',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:45:41.417Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
UGA

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 42862958.0],
                      ['2016-12-31', 41487965.0],
                      ['2015-12-31', 40144870.0],
                      ['2014-12-31', 38833338.0],
                      ['2013-12-31', 37553726.0],
                      ['2012-12-31', 36306796.0],
                      ['2011-12-31', 35093648.0],
                      ['2010-12-31', 33915133.0],
                      ['2009-12-31', 32771895.0],
                      ['2008-12-31', 31663896.0],
                      ['2007-12-31', 30590487.0],
                      ['2006-12-31', 29550662.0],
                      ['2005-12-31', 28543940.0],
                      ['2004-12-31', 27568436.0],
                      ['2003-12-31', 26624820.0],
                      ['2002-12-31', 25718048.0],
                      ['2001-12-31', 24854892.0],
                      ['2000-12-31', 24039274.0],
                      ['1999-12-31', 23272995.0],
                      ['1998-12-31', 22551789.0],
                      ['1997-12-31', 21865931.0],
                      ['1996-12-31', 21202118.0],
                      ['1995-12-31', 20550291.0],
                      ['1994-12-31', 19907634.0],
                      ['1993-12-31', 19275422.0],
                      ['1992-12-31', 18652889.0],
                      ['1991-12-31', 18040438.0],
                      ['1990-12-31', 17438907.0],
                      ['1989-12-31', 16846090.0],
                      ['1988-12-31', 16262533.0],
                      ['1987-12-31', 15695411.0],
                      ['1986-12-31', 15154521.0],
                      ['1985-12-31', 14646624.0],
                      ['1984-12-31', 14174470.0],
                      ['1983-12-31', 13735271.0],
                      ['1982-12-31', 13323332.0],
                      ['1981-12-31', 12930209.0],
                      ['1980-12-31', 12549540.0],
                      ['1979-12-31', 12178544.0],
                      ['1978-12-31', 11818307.0],
                      ['1977-12-31', 11470867.0],
                      ['1976-12-31', 11139833.0],
                      ['1975-12-31', 10827147.0],
                      ['1974-12-31', 10533716.0],
                      ['1973-12-31', 10256429.0],
                      ['1972-12-31', 9988380.0],
                      ['1971-12-31', 9720399.0],
                      ['1970-12-31', 9446064.0],
                      ['1969-12-31', 9162833.0],
                      ['1968-12-31', 8872920.0],
                      ['1967-12-31', 8580676.0],
                      ['1966-12-31', 8292776.0],
                      ['1965-12-31', 8014401.0],
                      ['1964-12-31', 7746198.0],
                      ['1963-12-31', 7487429.0],
                      ['1962-12-31', 7240174.0],
                      ['1961-12-31', 7006633.0],
                      ['1960-12-31', 6788214.0],
                      ['1959-12-31', 6585105.0],
                      ['1958-12-31', 6396463.0],
                      ['1957-12-31', 6220629.0],
                      ['1956-12-31', 6055517.0],
                      ['1955-12-31', 5898835.0],
                      ['1954-12-31', 5748208.0],
                      ['1953-12-31', 5601239.0],
                      ['1952-12-31', 5455540.0],
                      ['1951-12-31', 5308668.0],
                      ['1950-12-31', 5158190.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'UGA_SP_POP_TOTL',
             'description': 'Population, total - Uganda. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22237934,
             'limit': None,
             'name': 'Population, total - Uganda',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:45:53.877Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
UKR
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 44831159.0],
                      ['2016-12-31', 45004645.0],
                      ['2015-12-31', 45154029.0],
                      ['2014-12-31', 45271947.0],
                      ['2013-12-31', 45489600.0],
                      ['2012-12-31', 45593300.0],
                      ['2011-12-31', 45706100.0],
                      ['2010-12-31', 45870700.0],
                      ['2009-12-31', 46053300.0],
                      ['2008-12-31', 46258200.0],
                      ['2007-12-31', 46509350.0],
                      ['2006-12-31', 46787750.0],
                      ['2005-12-31', 47105150.0],
                      ['2004-12-31', 47451600.0],
                      ['2003-12-31', 47812950.0],
                      ['2002-12-31', 48202500.0],
                      ['2001-12-31', 48683865.0],
                      ['2000-12-31', 49175848.0],
                      ['1999-12-31', 49673350.0],
                      ['1998-12-31', 50143939.0],
                      ['1997-12-31', 50594105.0],
                      ['1996-12-31', 51057189.0],
                      ['1995-12-31', 51512299.0],
                      ['1994-12-31', 51921041.0],
                      ['1993-12-31', 52179210.0],
                      ['1992-12-31', 52150266.0],
                      ['1991-12-31', 52000470.0],
                      ['1990-12-31', 51892000.0],
                      ['1989-12-31', 51773000.0],
                      ['1988-12-31', 51521000.0],
                      ['1987-12-31', 51293000.0],
                      ['1986-12-31', 51097000.0],
                      ['1985-12-31', 50917000.0],
                      ['1984-12-31', 50754000.0],
                      ['1983-12-31', 50564000.0],
                      ['1982-12-31', 50384000.0],
                      ['1981-12-31', 50221000.0],
                      ['1980-12-31', 49968812.0],
                      ['1979-12-31', 49751257.0],
                      ['1978-12-31', 49526883.0],
                      ['1977-12-31', 49290905.0],
                      ['1976-12-31', 49036456.0],
                      ['1975-12-31', 48758987.0],
                      ['1974-12-31', 48455122.0],
                      ['1973-12-31', 48127172.0],
                      ['1972-12-31', 47783011.0],
                      ['1971-12-31', 47433805.0],
                      ['1970-12-31', 47086761.0],
                      ['1969-12-31', 46746669.0],
                      ['1968-12-31', 46409002.0],
                      ['1967-12-31', 46060452.0],
                      ['1966-12-31', 45682308.0],
                      ['1965-12-31', 45261935.0],
                      ['1964-12-31', 44794327.0],
                      ['1963-12-31', 44285899.0],
                      ['1962-12-31', 43749470.0],
                      ['1961-12-31', 43203635.0],
                      ['1960-12-31', 42662149.0],
                      ['1959-12-31', 42130316.0],
                      ['1958-12-31', 41606288.0],
                      ['1957-12-31', 41083976.0],
                      ['1956-12-31', 40556527.0],
                      ['1955-12-31', 40019449.0],
                      ['1954-12-31', 39471674.0],
                      ['1953-12-31', 38916264.0],
                      ['1952-12-31', 38360509.0],
                      ['1951-12-31', 37815815.0],
                      ['1950-12-31', 37297648.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'UKR_SP_POP_TOTL',
             'description': 'Population, total - Ukraine. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22239838,
             'limit': None,
             'name': 'Population, total - Ukraine',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:45:59.970Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
ARE

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 9400145.0],
                      ['2016-12-31', 9269612.0],
                      ['2015-12-31', 9154302.0],
                      ['2014-12-31', 9070867.0],
                      ['2013-12-31', 9006263.0],
                      ['2012-12-31', 8900453.0],
                      ['2011-12-31', 8672475.0],
                      ['2010-12-31', 8270684.0],
                      ['2009-12-31', 7666393.0],
                      ['2008-12-31', 6894278.0],
                      ['2007-12-31', 6044067.0],
                      ['2006-12-31', 5242032.0],
                      ['2005-12-31', 4579562.0],
                      ['2004-12-31', 4087931.0],
                      ['2003-12-31', 3741932.0],
                      ['2002-12-31', 3507232.0],
                      ['2001-12-31', 3326032.0],
                      ['2000-12-31', 3154925.0],
                      ['1999-12-31', 2988162.0],
                      ['1998-12-31', 2838145.0],
                      ['1997-12-31', 2700010.0],
                      ['1996-12-31', 2571020.0],
                      ['1995-12-31', 2448820.0],
                      ['1994-12-31', 2328686.0],
                      ['1993-12-31', 2207405.0],
                      ['1992-12-31', 2086639.0],
                      ['1991-12-31', 1970026.0],
                      ['1990-12-31', 1860174.0],
                      ['1989-12-31', 1756043.0],
                      ['1988-12-31', 1655849.0],
                      ['1987-12-31', 1560718.0],
                      ['1986-12-31', 1472218.0],
                      ['1985-12-31', 1391052.0],
                      ['1984-12-31', 1318478.0],
                      ['1983-12-31', 1253060.0],
                      ['1982-12-31', 1189545.0],
                      ['1981-12-31', 1120900.0],
                      ['1980-12-31', 1042384.0],
                      ['1979-12-31', 952040.0],
                      ['1978-12-31', 852262.0],
                      ['1977-12-31', 748117.0],
                      ['1976-12-31', 646943.0],
                      ['1975-12-31', 554324.0],
                      ['1974-12-31', 471364.0],
                      ['1973-12-31', 397174.0],
                      ['1972-12-31', 332760.0],
                      ['1971-12-31', 278808.0],
                      ['1970-12-31', 235499.0],
                      ['1969-12-31', 203820.0],
                      ['1968-12-31', 183194.0],
                      ['1967-12-31', 170283.0],
                      ['1966-12-31', 160481.0],
                      ['1965-12-31', 150362.0],
                      ['1964-12-31', 138529.0],
                      ['1963-12-31', 125566.0],
                      ['1962-12-31', 112472.0],
                      ['1961-12-31', 101078.0],
                      ['1960-12-31', 92634.0],
                      ['1959-12-31', 87362.0],
                      ['1958-12-31', 84559.0],
                      ['1957-12-31', 83068.0],
                      ['1956-12-31', 81682.0],
                      ['1955-12-31', 79578.0],
                      ['1954-12-31', 76460.0],
                      ['1953-12-31', 72630.0],
                      ['1952-12-31', 69063.0],
                      ['1951-12-31', 67320.0],
                      ['1950-12-31', 69588.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'ARE_SP_POP_TOTL',
             'description': 'Population, total - United Arab Emirates. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22087510,
             'limit': None,
             'name': 'Population, total - United Arab Emirates',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:26:28.205Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
GBR
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 66022273.0],
                      ['2016-12-31', 65595565.0],
                      ['2015-12-31', 65128861.0],
                      ['2014-12-31', 64613160.0],
                      ['2013-12-31', 64128226.0],
                      ['2012-12-31', 63700300.0],
                      ['2011-12-31', 63258918.0],
                      ['2010-12-31', 62766365.0],
                      ['2009-12-31', 62276270.0],
                      ['2008-12-31', 61806995.0],
                      ['2007-12-31', 61322463.0],
                      ['2006-12-31', 60846820.0],
                      ['2005-12-31', 60401206.0],
                      ['2004-12-31', 59987905.0],
                      ['2003-12-31', 59647577.0],
                      ['2002-12-31', 59370479.0],
                      ['2001-12-31', 59119673.0],
                      ['2000-12-31', 58892514.0],
                      ['1999-12-31', 58682466.0],
                      ['1998-12-31', 58487141.0],
                      ['1997-12-31', 58316954.0],
                      ['1996-12-31', 58166950.0],
                      ['1995-12-31', 58019030.0],
                      ['1994-12-31', 57865745.0],
                      ['1993-12-31', 57718614.0],
                      ['1992-12-31', 57580402.0],
                      ['1991-12-31', 57424897.0],
                      ['1990-12-31', 57247586.0],
                      ['1989-12-31', 57076711.0],
                      ['1988-12-31', 56928327.0],
                      ['1987-12-31', 56802050.0],
                      ['1986-12-31', 56681396.0],
                      ['1985-12-31', 56550268.0],
                      ['1984-12-31', 56422072.0],
                      ['1983-12-31', 56332848.0],
                      ['1982-12-31', 56313641.0],
                      ['1981-12-31', 56333829.0],
                      ['1980-12-31', 56314216.0],
                      ['1979-12-31', 56246951.0],
                      ['1978-12-31', 56196504.0],
                      ['1977-12-31', 56193492.0],
                      ['1976-12-31', 56211968.0],
                      ['1975-12-31', 56225800.0],
                      ['1974-12-31', 56229974.0],
                      ['1973-12-31', 56194527.0],
                      ['1972-12-31', 56086065.0],
                      ['1971-12-31', 55896223.0],
                      ['1970-12-31', 55663250.0],
                      ['1969-12-31', 55441750.0],
                      ['1968-12-31', 55211700.0],
                      ['1967-12-31', 54943600.0],
                      ['1966-12-31', 54648500.0],
                      ['1965-12-31', 54348050.0],
                      ['1964-12-31', 54000000.0],
                      ['1963-12-31', 53650000.0],
                      ['1962-12-31', 53250000.0],
                      ['1961-12-31', 52800000.0],
                      ['1960-12-31', 52400000.0],
                      ['1959-12-31', 52218942.0],
                      ['1958-12-31', 51921175.0],
                      ['1957-12-31', 51650279.0],
                      ['1956-12-31', 51404774.0],
                      ['1955-12-31', 51184529.0],
                      ['1954-12-31', 50991454.0],
                      ['1953-12-31', 50829901.0],
                      ['1952-12-31', 50706811.0],
                      ['1951-12-31', 50631571.0],
                      ['1950-12-31', 50616012.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'GBR_SP_POP_TOTL',
             'description': 'Population, total - United Kingdom. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22151519,
             'limit': None,
             'name': 'Population, total - United Kingdom',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:32:32.993Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
USA

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 325719178.0],
                      ['2016-12-31', 323405935.0],
                      ['2015-12-31', 321039839.0],
                      ['2014-12-31', 318622525.0],
                      ['2013-12-31', 316234505.0],
                      ['2012-12-31', 313993272.0],
                      ['2011-12-31', 311644280.0],
                      ['2010-12-31', 309338421.0],
                      ['2009-12-31', 306771529.0],
                      ['2008-12-31', 304093966.0],
                      ['2007-12-31', 301231207.0],
                      ['2006-12-31', 298379912.0],
                      ['2005-12-31', 295516599.0],
                      ['2004-12-31', 292805298.0],
                      ['2003-12-31', 290107933.0],
                      ['2002-12-31', 287625193.0],
                      ['2001-12-31', 284968955.0],
                      ['2000-12-31', 282162411.0],
                      ['1999-12-31', 279040000.0],
                      ['1998-12-31', 275854000.0],
                      ['1997-12-31', 272657000.0],
                      ['1996-12-31', 269394000.0],
                      ['1995-12-31', 266278000.0],
                      ['1994-12-31', 263126000.0],
                      ['1993-12-31', 259919000.0],
                      ['1992-12-31', 256514000.0],
                      ['1991-12-31', 252981000.0],
                      ['1990-12-31', 249623000.0],
                      ['1989-12-31', 246819000.0],
                      ['1988-12-31', 244499000.0],
                      ['1987-12-31', 242289000.0],
                      ['1986-12-31', 240133000.0],
                      ['1985-12-31', 237924000.0],
                      ['1984-12-31', 235825000.0],
                      ['1983-12-31', 233792000.0],
                      ['1982-12-31', 231664000.0],
                      ['1981-12-31', 229466000.0],
                      ['1980-12-31', 227225000.0],
                      ['1979-12-31', 225055000.0],
                      ['1978-12-31', 222585000.0],
                      ['1977-12-31', 220239000.0],
                      ['1976-12-31', 218035000.0],
                      ['1975-12-31', 215973000.0],
                      ['1974-12-31', 213854000.0],
                      ['1973-12-31', 211909000.0],
                      ['1972-12-31', 209896000.0],
                      ['1971-12-31', 207661000.0],
                      ['1970-12-31', 205052000.0],
                      ['1969-12-31', 202677000.0],
                      ['1968-12-31', 200706000.0],
                      ['1967-12-31', 198712000.0],
                      ['1966-12-31', 196560000.0],
                      ['1965-12-31', 194303000.0],
                      ['1964-12-31', 191889000.0],
                      ['1963-12-31', 189242000.0],
                      ['1962-12-31', 186538000.0],
                      ['1961-12-31', 183691000.0],
                      ['1960-12-31', 180671000.0],
                      ['1959-12-31', 177622013.0],
                      ['1958-12-31', 174624481.0],
                      ['1957-12-31', 171677535.0],
                      ['1956-12-31', 168780321.0],
                      ['1955-12-31', 165932000.0],
                      ['1954-12-31', 163105107.0],
                      ['1953-12-31', 160326373.0],
                      ['1952-12-31', 157594980.0],
                      ['1951-12-31', 154910120.0],
                      ['1950-12-31', 152271000.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'USA_SP_POP_TOTL',
             'description': 'Population, total - United States. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22244952,
             'limit': None,
             'name': 'Population, total - United States',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:46:15.977Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
UMC
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 2576202556.0],
                      ['2016-12-31', 2556921923.0],
                      ['2015-12-31', 2537437057.0],
                      ['2014-12-31', 2517979764.0],
                      ['2013-12-31', 2498184210.0],
                      ['2012-12-31', 2478491686.0],
                      ['2011-12-31', 2459175685.0],
                      ['2010-12-31', 2440543075.0],
                      ['2009-12-31', 2422393813.0],
                      ['2008-12-31', 2404283410.0],
                      ['2007-12-31', 2386824787.0],
                      ['2006-12-31', 2369650785.0],
                      ['2005-12-31', 2352105140.0],
                      ['2004-12-31', 2334313912.0],
                      ['2003-12-31', 2316548374.0],
                      ['2002-12-31', 2298541505.0],
                      ['2001-12-31', 2280191396.0],
                      ['2000-12-31', 2260805982.0],
                      ['1999-12-31', 2239999771.0],
                      ['1998-12-31', 2217937280.0],
                      ['1997-12-31', 2194549894.0],
                      ['1996-12-31', 2170438981.0],
                      ['1995-12-31', 2146161975.0],
                      ['1994-12-31', 2121533883.0],
                      ['1993-12-31', 2096571016.0],
                      ['1992-12-31', 2071319405.0],
                      ['1991-12-31', 2045004596.0],
                      ['1990-12-31', 2016620835.0],
                      ['1989-12-31', 1986535300.0],
                      ['1988-12-31', 1954964969.0],
                      ['1987-12-31', 1922510337.0],
                      ['1986-12-31', 1890186436.0],
                      ['1985-12-31', 1859330151.0],
                      ['1984-12-31', 1829977999.0],
                      ['1983-12-31', 1801397199.0],
                      ['1982-12-31', 1771981636.0],
                      ['1981-12-31', 1742621330.0],
                      ['1980-12-31', 1715481307.0],
                      ['1979-12-31', 1689044984.0],
                      ['1978-12-31', 1662349096.0],
                      ['1977-12-31', 1635986172.0],
                      ['1976-12-31', 1609703779.0],
                      ['1975-12-31', 1581987657.0],
                      ['1974-12-31', 1552810129.0],
                      ['1973-12-31', 1521452091.0],
                      ['1972-12-31', 1488762369.0],
                      ['1971-12-31', 1455203204.0],
                      ['1970-12-31', 1419934207.0],
                      ['1969-12-31', 1385327913.0],
                      ['1968-12-31', 1351687548.0],
                      ['1967-12-31', 1319719672.0],
                      ['1966-12-31', 1288677630.0],
                      ['1965-12-31', 1256855898.0],
                      ['1964-12-31', 1227973800.0],
                      ['1963-12-31', 1200060408.0],
                      ['1962-12-31', 1171820698.0],
                      ['1961-12-31', 1154967480.0],
                      ['1960-12-31', 1150568959.0],
                      ['1959-12-31', 1145957254.0],
                      ['1958-12-31', 1122986527.0],
                      ['1957-12-31', 1100519969.0],
                      ['1956-12-31', 1078540112.0],
                      ['1955-12-31', 1057035381.0],
                      ['1954-12-31', 1034042325.0],
                      ['1953-12-31', 1011579880.0],
                      ['1952-12-31', 989692372.0],
                      ['1951-12-31', 968444889.0],
                      ['1950-12-31', 947920625.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'UMC_SP_POP_TOTL',
             'description': 'Population, total - Upper middle income. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22241445,
             'limit': None,
             'name': 'Population, total - Upper middle income',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:46:05.109Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
URY

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 3456750.0],
                      ['2016-12-31', 3444006.0],
                      ['2015-12-31', 3431552.0],
                      ['2014-12-31', 3419546.0],
                      ['2013-12-31', 3408005.0],
                      ['2012-12-31', 3396777.0],
                      ['2011-12-31', 3385624.0],
                      ['2010-12-31', 3374415.0],
                      ['2009-12-31', 3362755.0],
                      ['2008-12-31', 3350824.0],
                      ['2007-12-31', 3339741.0],
                      ['2006-12-31', 3331043.0],
                      ['2005-12-31', 3325612.0],
                      ['2004-12-31', 3324096.0],
                      ['2003-12-31', 3325637.0],
                      ['2002-12-31', 3327773.0],
                      ['2001-12-31', 3327103.0],
                      ['2000-12-31', 3321245.0],
                      ['1999-12-31', 3309318.0],
                      ['1998-12-31', 3292138.0],
                      ['1997-12-31', 3271010.0],
                      ['1996-12-31', 3248035.0],
                      ['1995-12-31', 3224804.0],
                      ['1994-12-31', 3201607.0],
                      ['1993-12-31', 3178155.0],
                      ['1992-12-31', 3154855.0],
                      ['1991-12-31', 3132050.0],
                      ['1990-12-31', 3109989.0],
                      ['1989-12-31', 3088984.0],
                      ['1988-12-31', 3069099.0],
                      ['1987-12-31', 3049966.0],
                      ['1986-12-31', 3031038.0],
                      ['1985-12-31', 3011908.0],
                      ['1984-12-31', 2992645.0],
                      ['1983-12-31', 2973463.0],
                      ['1982-12-31', 2954282.0],
                      ['1981-12-31', 2935036.0],
                      ['1980-12-31', 2915778.0],
                      ['1979-12-31', 2896023.0],
                      ['1978-12-31', 2875966.0],
                      ['1977-12-31', 2857105.0],
                      ['1976-12-31', 2841429.0],
                      ['1975-12-31', 2830172.0],
                      ['1974-12-31', 2824069.0],
                      ['1973-12-31', 2822081.0],
                      ['1972-12-31', 2821439.0],
                      ['1971-12-31', 2818270.0],
                      ['1970-12-31', 2809803.0],
                      ['1969-12-31', 2795046.0],
                      ['1968-12-31', 2774774.0],
                      ['1967-12-31', 2750093.0],
                      ['1966-12-31', 2722877.0],
                      ['1965-12-31', 2694537.0],
                      ['1964-12-31', 2665390.0],
                      ['1963-12-31', 2635129.0],
                      ['1962-12-31', 2603887.0],
                      ['1961-12-31', 2571690.0],
                      ['1960-12-31', 2538651.0],
                      ['1959-12-31', 2505015.0],
                      ['1958-12-31', 2471153.0],
                      ['1957-12-31', 2437499.0],
                      ['1956-12-31', 2404499.0],
                      ['1955-12-31', 2372568.0],
                      ['1954-12-31', 2342042.0],
                      ['1953-12-31', 2313213.0],
                      ['1952-12-31', 2286265.0],
                      ['1951-12-31', 2261342.0],
                      ['1950-12-31', 2238507.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'URY_SP_POP_TOTL',
             'description': 'Population, total - Uruguay. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22243232,
             'limit': None,
             'name': 'Population, total - Uruguay',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:46:10.712Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
UZB
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 32387200.0],
                      ['2016-12-31', 31847900.0],
                      ['2015-12-31', 31298900.0],
                      ['2014-12-31', 30757700.0],
                      ['2013-12-31', 30243200.0],
                      ['2012-12-31', 29774500.0],
                      ['2011-12-31', 29339400.0],
                      ['2010-12-31', 28562400.0],
                      ['2009-12-31', 27767400.0],
                      ['2008-12-31', 27302800.0],
                      ['2007-12-31', 26868000.0],
                      ['2006-12-31', 26488250.0],
                      ['2005-12-31', 26167000.0],
                      ['2004-12-31', 25864350.0],
                      ['2003-12-31', 25567650.0],
                      ['2002-12-31', 25271850.0],
                      ['2001-12-31', 24964450.0],
                      ['2000-12-31', 24650400.0],
                      ['1999-12-31', 24311650.0],
                      ['1998-12-31', 24051000.0],
                      ['1997-12-31', 23667000.0],
                      ['1996-12-31', 23225000.0],
                      ['1995-12-31', 22785000.0],
                      ['1994-12-31', 22377000.0],
                      ['1993-12-31', 21942000.0],
                      ['1992-12-31', 21449000.0],
                      ['1991-12-31', 20952000.0],
                      ['1990-12-31', 20510000.0],
                      ['1989-12-31', 19979127.0],
                      ['1988-12-31', 19501225.0],
                      ['1987-12-31', 19029877.0],
                      ['1986-12-31', 18565477.0],
                      ['1985-12-31', 18108300.0],
                      ['1984-12-31', 17659975.0],
                      ['1983-12-31', 17221212.0],
                      ['1982-12-31', 16790069.0],
                      ['1981-12-31', 16363562.0],
                      ['1980-12-31', 15939744.0],
                      ['1979-12-31', 15516862.0],
                      ['1978-12-31', 15096012.0],
                      ['1977-12-31', 14681459.0],
                      ['1976-12-31', 14279120.0],
                      ['1975-12-31', 13892638.0],
                      ['1974-12-31', 13525094.0],
                      ['1973-12-31', 13173590.0],
                      ['1972-12-31', 12828625.0],
                      ['1971-12-31', 12477058.0],
                      ['1970-12-31', 12110028.0],
                      ['1969-12-31', 11723846.0],
                      ['1968-12-31', 11323095.0],
                      ['1967-12-31', 10917446.0],
                      ['1966-12-31', 10520879.0],
                      ['1965-12-31', 10143740.0],
                      ['1964-12-31', 9788986.0],
                      ['1963-12-31', 9454250.0],
                      ['1962-12-31', 9138097.0],
                      ['1961-12-31', 8837349.0],
                      ['1960-12-31', 8549493.0],
                      ['1959-12-31', 8273556.0],
                      ['1958-12-31', 8009770.0],
                      ['1957-12-31', 7758928.0],
                      ['1956-12-31', 7521586.0],
                      ['1955-12-31', 7297296.0],
                      ['1954-12-31', 7084378.0],
                      ['1953-12-31', 6879763.0],
                      ['1952-12-31', 6678989.0],
                      ['1951-12-31', 6476160.0],
                      ['1950-12-31', 6264056.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'UZB_SP_POP_TOTL',
             'description': 'Population, total - Uzbekistan. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22246523,
             'limit': None,
             'name': 'Population, total - Uzbekistan',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:46:20.994Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
VUT

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 276244.0],
                      ['2016-12-31', 270402.0],
                      ['2015-12-31', 264603.0],
                      ['2014-12-31', 258850.0],
                      ['2013-12-31', 253142.0],
                      ['2012-12-31', 247485.0],
                      ['2011-12-31', 241871.0],
                      ['2010-12-31', 236295.0],
                      ['2009-12-31', 230785.0],
                      ['2008-12-31', 225340.0],
                      ['2007-12-31', 219953.0],
                      ['2006-12-31', 214634.0],
                      ['2005-12-31', 209370.0],
                      ['2004-12-31', 204143.0],
                      ['2003-12-31', 198964.0],
                      ['2002-12-31', 193956.0],
                      ['2001-12-31', 189290.0],
                      ['2000-12-31', 185063.0],
                      ['1999-12-31', 181345.0],
                      ['1998-12-31', 178078.0],
                      ['1997-12-31', 174999.0],
                      ['1996-12-31', 171801.0],
                      ['1995-12-31', 168235.0],
                      ['1994-12-31', 164208.0],
                      ['1993-12-31', 159814.0],
                      ['1992-12-31', 155243.0],
                      ['1991-12-31', 150778.0],
                      ['1990-12-31', 146634.0],
                      ['1989-12-31', 142849.0],
                      ['1988-12-31', 139366.0],
                      ['1987-12-31', 136125.0],
                      ['1986-12-31', 133038.0],
                      ['1985-12-31', 130027.0],
                      ['1984-12-31', 127092.0],
                      ['1983-12-31', 124249.0],
                      ['1982-12-31', 121435.0],
                      ['1981-12-31', 118580.0],
                      ['1980-12-31', 115632.0],
                      ['1979-12-31', 112580.0],
                      ['1978-12-31', 109429.0],
                      ['1977-12-31', 106222.0],
                      ['1976-12-31', 103028.0],
                      ['1975-12-31', 99872.0],
                      ['1974-12-31', 96796.0],
                      ['1973-12-31', 93765.0],
                      ['1972-12-31', 90823.0],
                      ['1971-12-31', 88022.0],
                      ['1970-12-31', 85389.0],
                      ['1969-12-31', 82940.0],
                      ['1968-12-31', 80673.0],
                      ['1967-12-31', 78522.0],
                      ['1966-12-31', 76413.0],
                      ['1965-12-31', 74289.0],
                      ['1964-12-31', 72131.0],
                      ['1963-12-31', 69964.0],
                      ['1962-12-31', 67808.0],
                      ['1961-12-31', 65713.0],
                      ['1960-12-31', 63699.0],
                      ['1959-12-31', 61794.0],
                      ['1958-12-31', 59983.0],
                      ['1957-12-31', 58245.0],
                      ['1956-12-31', 56565.0],
                      ['1955-12-31', 54924.0],
                      ['1954-12-31', 53330.0],
                      ['1953-12-31', 51771.0],
                      ['1952-12-31', 50297.0],
                      ['1951-12-31', 48923.0],
                      ['1950-12-31', 47697.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'VUT_SP_POP_TOTL',
             'description': 'Population, total - Vanuatu. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22253663,
             'limit': None,
             'name': 'Population, total - Vanuatu',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:46:44.477Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
VEN
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 31977065.0],
                      ['2016-12-31', 31568179.0],
                      ['2015-12-31', 31155134.0],
                      ['2014-12-31', 30738378.0],
                      ['2013-12-31', 30317848.0],
                      ['2012-12-31', 29893080.0],
                      ['2011-12-31', 29463291.0],
                      ['2010-12-31', 29028033.0],
                      ['2009-12-31', 28587323.0],
                      ['2008-12-31', 28141701.0],
                      ['2007-12-31', 27691965.0],
                      ['2006-12-31', 27239168.0],
                      ['2005-12-31', 26784161.0],
                      ['2004-12-31', 26327225.0],
                      ['2003-12-31', 25868523.0],
                      ['2002-12-31', 25408700.0],
                      ['2001-12-31', 24948476.0],
                      ['2000-12-31', 24488340.0],
                      ['1999-12-31', 24028689.0],
                      ['1998-12-31', 23569454.0],
                      ['1997-12-31', 23110178.0],
                      ['1996-12-31', 22650102.0],
                      ['1995-12-31', 22188667.0],
                      ['1994-12-31', 21726352.0],
                      ['1993-12-31', 21263443.0],
                      ['1992-12-31', 20799075.0],
                      ['1991-12-31', 20332079.0],
                      ['1990-12-31', 19861956.0],
                      ['1989-12-31', 19388342.0],
                      ['1988-12-31', 18912526.0],
                      ['1987-12-31', 18437794.0],
                      ['1986-12-31', 17968552.0],
                      ['1985-12-31', 17508059.0],
                      ['1984-12-31', 17057785.0],
                      ['1983-12-31', 16617346.0],
                      ['1982-12-31', 16185894.0],
                      ['1981-12-31', 15761799.0],
                      ['1980-12-31', 15343916.0],
                      ['1979-12-31', 14931739.0],
                      ['1978-12-31', 14525931.0],
                      ['1977-12-31', 14127787.0],
                      ['1976-12-31', 13739142.0],
                      ['1975-12-31', 13360987.0],
                      ['1974-12-31', 12994025.0],
                      ['1973-12-31', 12636969.0],
                      ['1972-12-31', 12286439.0],
                      ['1971-12-31', 11937805.0],
                      ['1970-12-31', 11587761.0],
                      ['1969-12-31', 11235491.0],
                      ['1968-12-31', 10881995.0],
                      ['1967-12-31', 10528054.0],
                      ['1966-12-31', 10175140.0],
                      ['1965-12-31', 9824692.0],
                      ['1964-12-31', 9476252.0],
                      ['1963-12-31', 9130349.0],
                      ['1962-12-31', 8790589.0],
                      ['1961-12-31', 8461685.0],
                      ['1960-12-31', 8146847.0],
                      ['1959-12-31', 7846954.0],
                      ['1958-12-31', 7560819.0],
                      ['1957-12-31', 7285973.0],
                      ['1956-12-31', 7019411.0],
                      ['1955-12-31', 6758373.0],
                      ['1954-12-31', 6500641.0],
                      ['1953-12-31', 6244652.0],
                      ['1952-12-31', 5989551.0],
                      ['1951-12-31', 5735169.0],
                      ['1950-12-31', 5481978.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'VEN_SP_POP_TOTL',
             'description': 'Population, total - Venezuela, RB. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22249851,
             'limit': None,
             'name': 'Population, total - Venezuela, RB',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:46:31.627Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
VNM

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 95540800.0],
                      ['2016-12-31', 94569072.0],
                      ['2015-12-31', 93571567.0],
                      ['2014-12-31', 92544915.0],
                      ['2013-12-31', 91497725.0],
                      ['2012-12-31', 90451881.0],
                      ['2011-12-31', 89436644.0],
                      ['2010-12-31', 88472512.0],
                      ['2009-12-31', 87565407.0],
                      ['2008-12-31', 86707801.0],
                      ['2007-12-31', 85889590.0],
                      ['2006-12-31', 85094617.0],
                      ['2005-12-31', 84308843.0],
                      ['2004-12-31', 83527678.0],
                      ['2003-12-31', 82747662.0],
                      ['2002-12-31', 81956496.0],
                      ['2001-12-31', 81139919.0],
                      ['2000-12-31', 80285562.0],
                      ['1999-12-31', 79391374.0],
                      ['1998-12-31', 78452897.0],
                      ['1997-12-31', 77453335.0],
                      ['1996-12-31', 76372719.0],
                      ['1995-12-31', 75198977.0],
                      ['1994-12-31', 73925082.0],
                      ['1993-12-31', 72560427.0],
                      ['1992-12-31', 71130448.0],
                      ['1991-12-31', 69670902.0],
                      ['1990-12-31', 68209605.0],
                      ['1989-12-31', 66757402.0],
                      ['1988-12-31', 65313708.0],
                      ['1987-12-31', 63881297.0],
                      ['1986-12-31', 62459560.0],
                      ['1985-12-31', 61049373.0],
                      ['1984-12-31', 59653090.0],
                      ['1983-12-31', 58277387.0],
                      ['1982-12-31', 56931824.0],
                      ['1981-12-31', 55627746.0],
                      ['1980-12-31', 54372514.0],
                      ['1979-12-31', 53169673.0],
                      ['1978-12-31', 52015281.0],
                      ['1977-12-31', 50899504.0],
                      ['1976-12-31', 49808071.0],
                      ['1975-12-31', 48729392.0],
                      ['1974-12-31', 47661773.0],
                      ['1973-12-31', 46604726.0],
                      ['1972-12-31', 45549483.0],
                      ['1971-12-31', 44485908.0],
                      ['1970-12-31', 43407287.0],
                      ['1969-12-31', 42309665.0],
                      ['1968-12-31', 41195835.0],
                      ['1967-12-31', 40074699.0],
                      ['1966-12-31', 38959334.0],
                      ['1965-12-31', 37860012.0],
                      ['1964-12-31', 36780985.0],
                      ['1963-12-31', 35722091.0],
                      ['1962-12-31', 34684165.0],
                      ['1961-12-31', 33666772.0],
                      ['1960-12-31', 32670629.0],
                      ['1959-12-31', 31698431.0],
                      ['1958-12-31', 30754608.0],
                      ['1957-12-31', 29844531.0],
                      ['1956-12-31', 28973874.0],
                      ['1955-12-31', 28147786.0],
                      ['1954-12-31', 27370702.0],
                      ['1953-12-31', 26646172.0],
                      ['1952-12-31', 25976838.0],
                      ['1951-12-31', 25364453.0],
                      ['1950-12-31', 24809906.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'VNM_SP_POP_TOTL',
             'description': 'Population, total - Vietnam. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22252029,
             'limit': None,
             'name': 'Population, total - Vietnam',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:46:38.941Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
VIR
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 107268.0],
                      ['2016-12-31', 107510.0],
                      ['2015-12-31', 107710.0],
                      ['2014-12-31', 107884.0],
                      ['2013-12-31', 108044.0],
                      ['2012-12-31', 108191.0],
                      ['2011-12-31', 108292.0],
                      ['2010-12-31', 108358.0],
                      ['2009-12-31', 108405.0],
                      ['2008-12-31', 108399.0],
                      ['2007-12-31', 108339.0],
                      ['2006-12-31', 108371.0],
                      ['2005-12-31', 108454.0],
                      ['2004-12-31', 108467.0],
                      ['2003-12-31', 108506.0],
                      ['2002-12-31', 108510.0],
                      ['2001-12-31', 108549.0],
                      ['2000-12-31', 108642.0],
                      ['1999-12-31', 108599.0],
                      ['1998-12-31', 108537.0],
                      ['1997-12-31', 108357.0],
                      ['1996-12-31', 108095.0],
                      ['1995-12-31', 107818.0],
                      ['1994-12-31', 107318.0],
                      ['1993-12-31', 106578.0],
                      ['1992-12-31', 105712.0],
                      ['1991-12-31', 104807.0],
                      ['1990-12-31', 103963.0],
                      ['1989-12-31', 101041.0],
                      ['1988-12-31', 100952.0],
                      ['1987-12-31', 100901.0],
                      ['1986-12-31', 100842.0],
                      ['1985-12-31', 100760.0],
                      ['1984-12-31', 100600.0],
                      ['1983-12-31', 100348.0],
                      ['1982-12-31', 100068.0],
                      ['1981-12-31', 99853.0],
                      ['1980-12-31', 99636.0],
                      ['1979-12-31', 96183.0],
                      ['1978-12-31', 95929.0],
                      ['1977-12-31', 93203.0],
                      ['1976-12-31', 96166.0],
                      ['1975-12-31', 94484.0],
                      ['1974-12-31', 89941.0],
                      ['1973-12-31', 84121.0],
                      ['1972-12-31', 76319.0],
                      ['1971-12-31', 70937.0],
                      ['1970-12-31', 63476.0],
                      ['1969-12-31', 60300.0],
                      ['1968-12-31', 55700.0],
                      ['1967-12-31', 49100.0],
                      ['1966-12-31', 46200.0],
                      ['1965-12-31', 43500.0],
                      ['1964-12-31', 40800.0],
                      ['1963-12-31', 39800.0],
                      ['1962-12-31', 35000.0],
                      ['1961-12-31', 34300.0],
                      ['1960-12-31', 32500.0],
                      ['1959-12-31', 31000.0],
                      ['1958-12-31', 30000.0],
                      ['1957-12-31', 29400.0],
                      ['1956-12-31', 28400.0],
                      ['1955-12-31', 27600.0],
                      ['1954-12-31', 27200.0],
                      ['1953-12-31', 26900.0],
                      ['1952-12-31', 27900.0],
                      ['1951-12-31', 27700.0],
                      ['1950-12-31', 26900.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'VIR_SP_POP_TOTL',
             'description': 'Population, total - Virgin Islands (U.S.). ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22250592,
             'limit': None,
             'name': 'Population, total - Virgin Islands (U.S.)',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:46:34.145Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
PSE
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 4684777.0],
                      ['2016-12-31', 4551566.0],
                      ['2015-12-31', 4422143.0],
                      ['2014-12-31', 4294682.0],
                      ['2013-12-31', 4169506.0],
                      ['2012-12-31', 4046901.0],
                      ['2011-12-31', 3927051.0],
                      ['2010-12-31', 3811102.0],
                      ['2009-12-31', 3702218.0],
                      ['2008-12-31', 3596688.0],
                      ['2007-12-31', 3494496.0],
                      ['2006-12-31', 3406334.0],
                      ['2005-12-31', 3320396.0],
                      ['2004-12-31', 3236626.0],
                      ['2003-12-31', 3154969.0],
                      ['2002-12-31', 3075373.0],
                      ['2001-12-31', 2997784.0],
                      ['2000-12-31', 2922153.0],
                      ['1999-12-31', 2848431.0],
                      ['1998-12-31', 2776568.0],
                      ['1997-12-31', 2706518.0],
                      ['1996-12-31', 2587997.0],
                      ['1995-12-31', 2474666.0],
                      ['1994-12-31', 2366298.0],
                      ['1993-12-31', 2262676.0],
                      ['1992-12-31', 2163591.0],
                      ['1991-12-31', 2068845.0],

                      ['1990-12-31', 1978248.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'PSE_SP_POP_TOTL',
             'description': 'Population, total - West Bank and Gaza. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22218780,
             'limit': None,
             'name': 'Population, total - West Bank and Gaza',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1990-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:42:10.988Z',
             'start_date': '1990-12-31',
             'transform': None,
             'type': 'Time Series'}}
WLD
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 7530360149.0],
                      ['2016-12-31', 7444157356.0],
                      ['2015-12-31', 7357559450.0],
                      ['2014-12-31', 7271322821.0],
                      ['2013-12-31', 7185137526.0],
                      ['2012-12-31', 7099557649.0],
                      ['2011-12-31', 7014983968.0],
                      ['2010-12-31', 6932869743.0],
                      ['2009-12-31', 6849569339.0],
                      ['2008-12-31', 6766296679.0],
                      ['2007-12-31', 6683223772.0],
                      ['2006-12-31', 6601476541.0],
                      ['2005-12-31', 6520298763.0],
                      ['2004-12-31', 6439825381.0],
                      ['2003-12-31', 6359899296.0],
                      ['2002-12-31', 6280530065.0],
                      ['2001-12-31', 6201340258.0],
                      ['2000-12-31', 6121682736.0],
                      ['1999-12-31', 6041818586.0],
                      ['1998-12-31', 5961166037.0],
                      ['1997-12-31', 5879433900.0],
                      ['1996-12-31', 5796632117.0],
                      ['1995-12-31', 5713794372.0],
                      ['1994-12-31', 5628791176.0],
                      ['1993-12-31', 5544873088.0],
                      ['1992-12-31', 5459753865.0],
                      ['1991-12-31', 5375488619.0],
                      ['1990-12-31', 5288103214.0],
                      ['1989-12-31', 5197758286.0],
                      ['1988-12-31', 5108813278.0],
                      ['1987-12-31', 5020001104.0],
                      ['1986-12-31', 4932113625.0],
                      ['1985-12-31', 4846338372.0],
                      ['1984-12-31', 4763043102.0],
                      ['1983-12-31', 4681262096.0],
                      ['1982-12-31', 4599181616.0],
                      ['1981-12-31', 4517802648.0],
                      ['1980-12-31', 4439337768.0],
                      ['1979-12-31', 4362863944.0],
                      ['1978-12-31', 4287155675.0],
                      ['1977-12-31', 4213305195.0],
                      ['1976-12-31', 4140647339.0],
                      ['1975-12-31', 4067740568.0],
                      ['1974-12-31', 3992871281.0],
                      ['1973-12-31', 3916243701.0],
                      ['1972-12-31', 3840269676.0],
                      ['1971-12-31', 3763393039.0],
                      ['1970-12-31', 3685753341.0],
                      ['1969-12-31', 3610178793.0],
                      ['1968-12-31', 3535355316.0],
                      ['1967-12-31', 3464689185.0],
                      ['1966-12-31', 3394783653.0],
                      ['1965-12-31', 3324545319.0],
                      ['1964-12-31', 3257459749.0],
                      ['1963-12-31', 3191786428.0],
                      ['1962-12-31', 3126509809.0],
                      ['1961-12-31', 3073368589.0],
                      ['1960-12-31', 3032160395.0],
                      ['1959-12-31', 2962994188.0],
                      ['1958-12-31', 2907448172.0],
                      ['1957-12-31', 2853524953.0],
                      ['1956-12-31', 2801150287.0],
                      ['1955-12-31', 2759222985.0],
                      ['1954-12-31', 2698902480.0],
                      ['1953-12-31', 2649084043.0],
                      ['1952-12-31', 2600935487.0],
                      ['1951-12-31', 2554602477.0],
                      ['1950-12-31', 2517759294.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'WLD_SP_POP_TOTL',
             'description': 'Population, total - World. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22255093,
             'limit': None,
             'name': 'Population, total - World',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:46:49.297Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
YEM
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 28250420.0],
                      ['2016-12-31', 27584213.0],
                      ['2015-12-31', 26916207.0],
                      ['2014-12-31', 26246327.0],
                      ['2013-12-31', 25576322.0],
                      ['2012-12-31', 24909969.0],
                      ['2011-12-31', 24252206.0],
                      ['2010-12-31', 23606779.0],
                      ['2009-12-31', 22974929.0],
                      ['2008-12-31', 22356391.0],
                      ['2007-12-31', 21751605.0],
                      ['2006-12-31', 21160534.0],
                      ['2005-12-31', 20582927.0],
                      ['2004-12-31', 20017068.0],
                      ['2003-12-31', 19462086.0],
                      ['2002-12-31', 18919179.0],
                      ['2001-12-31', 18390135.0],
                      ['2000-12-31', 17874725.0],
                      ['1999-12-31', 17378098.0],
                      ['1998-12-31', 16896210.0],
                      ['1997-12-31', 16408954.0],
                      ['1996-12-31', 15889449.0],
                      ['1995-12-31', 15320653.0],
                      ['1994-12-31', 14692686.0],
                      ['1993-12-31', 14017239.0],
                      ['1992-12-31', 13325583.0],
                      ['1991-12-31', 12661614.0],
                      ['1990-12-31', 12057039.0],
                      ['1989-12-31', 11523267.0],
                      ['1988-12-31', 11051504.0],
                      ['1987-12-31', 10628585.0],
                      ['1986-12-31', 10232733.0],
                      ['1985-12-31', 9847899.0],
                      ['1984-12-31', 9472170.0],
                      ['1983-12-31', 9111097.0],
                      ['1982-12-31', 8764621.0],
                      ['1981-12-31', 8434017.0],
                      ['1980-12-31', 8120497.0],
                      ['1979-12-31', 7821552.0],
                      ['1978-12-31', 7536764.0],
                      ['1977-12-31', 7271872.0],
                      ['1976-12-31', 7034868.0],
                      ['1975-12-31', 6830692.0],
                      ['1974-12-31', 6661566.0],
                      ['1973-12-31', 6523452.0],
                      ['1972-12-31', 6407295.0],
                      ['1971-12-31', 6300554.0],
                      ['1970-12-31', 6193810.0],
                      ['1969-12-31', 6083619.0],
                      ['1968-12-31', 5971407.0],
                      ['1967-12-31', 5858638.0],
                      ['1966-12-31', 5748588.0],
                      ['1965-12-31', 5643643.0],
                      ['1964-12-31', 5543339.0],
                      ['1963-12-31', 5446063.0],
                      ['1962-12-31', 5351799.0],
                      ['1961-12-31', 5260501.0],
                      ['1960-12-31', 5172135.0],
                      ['1959-12-31', 5086541.0],
                      ['1958-12-31', 5003533.0],
                      ['1957-12-31', 4922886.0],
                      ['1956-12-31', 4844325.0],
                      ['1955-12-31', 4767587.0],
                      ['1954-12-31', 4692418.0],
                      ['1953-12-31', 4618551.0],
                      ['1952-12-31', 4545741.0],
                      ['1951-12-31', 4473749.0],
                      ['1950-12-31', 4402320.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'YEM_SP_POP_TOTL',
             'description': 'Population, total - Yemen, Rep.. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22258252,
             'limit': None,
             'name': 'Population, total - Yemen, Rep.',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:47:00.269Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
ZMB

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 17094130.0],
                      ['2016-12-31', 16591390.0],
                      ['2015-12-31', 16100587.0],
                      ['2014-12-31', 15620974.0],
                      ['2013-12-31', 15153210.0],
                      ['2012-12-31', 14699937.0],
                      ['2011-12-31', 14264756.0],
                      ['2010-12-31', 13850033.0],
                      ['2009-12-31', 13456417.0],
                      ['2008-12-31', 13082517.0],
                      ['2007-12-31', 12725974.0],
                      ['2006-12-31', 12383446.0],
                      ['2005-12-31', 12052156.0],
                      ['2004-12-31', 11731746.0],
                      ['2003-12-31', 11421984.0],
                      ['2002-12-31', 11120409.0],
                      ['2001-12-31', 10824125.0],
                      ['2000-12-31', 10531221.0],
                      ['1999-12-31', 10239714.0],
                      ['1998-12-31', 9950224.0],
                      ['1997-12-31', 9666578.0],
                      ['1996-12-31', 9394304.0],
                      ['1995-12-31', 9137077.0],
                      ['1994-12-31', 8896109.0],
                      ['1993-12-31', 8669168.0],
                      ['1992-12-31', 8452275.0],
                      ['1991-12-31', 8239732.0],
                      ['1990-12-31', 8027253.0],
                      ['1989-12-31', 7813808.0],
                      ['1988-12-31', 7600072.0],
                      ['1987-12-31', 7385686.0],
                      ['1986-12-31', 7170656.0],
                      ['1985-12-31', 6955212.0],
                      ['1984-12-31', 6738765.0],
                      ['1983-12-31', 6521542.0],
                      ['1982-12-31', 6305709.0],
                      ['1981-12-31', 6094206.0],
                      ['1980-12-31', 5889230.0],
                      ['1979-12-31', 5691749.0],
                      ['1978-12-31', 5501445.0],
                      ['1977-12-31', 5317631.0],
                      ['1976-12-31', 5139030.0],
                      ['1975-12-31', 4964831.0],
                      ['1974-12-31', 4794754.0],
                      ['1973-12-31', 4629402.0],
                      ['1972-12-31', 4469895.0],
                      ['1971-12-31', 4317748.0],
                      ['1970-12-31', 4173928.0],
                      ['1969-12-31', 4038923.0],
                      ['1968-12-31', 3912085.0],
                      ['1967-12-31', 3791887.0],
                      ['1966-12-31', 3676189.0],
                      ['1965-12-31', 3563407.0],
                      ['1964-12-31', 3452942.0],
                      ['1963-12-31', 3345145.0],
                      ['1962-12-31', 3240587.0],
                      ['1961-12-31', 3140264.0],
                      ['1960-12-31', 3044846.0],
                      ['1959-12-31', 2954483.0],
                      ['1958-12-31', 2868841.0],
                      ['1957-12-31', 2787337.0],
                      ['1956-12-31', 2709359.0],
                      ['1955-12-31', 2634464.0],
                      ['1954-12-31', 2562483.0],
                      ['1953-12-31', 2493513.0],
                      ['1952-12-31', 2427991.0],
                      ['1951-12-31', 2366628.0],
                      ['1950-12-31', 2310442.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'ZMB_SP_POP_TOTL',
             'description': 'Population, total - Zambia. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22262239,
             'limit': None,
             'name': 'Population, total - Zambia',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:47:13.630Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}
ZWE
{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date', 'Value'],
             'data': [['2017-12-31', 16529904.0],
                      ['2016-12-31', 16150362.0],
                      ['2015-12-31', 15777451.0],
                      ['2014-12-31', 15411675.0],
                      ['2013-12-31', 15054506.0],
                      ['2012-12-31', 14710826.0],
                      ['2011-12-31', 14386649.0],
                      ['2010-12-31', 14086317.0],
                      ['2009-12-31', 13810599.0],
                      ['2008-12-31', 13558469.0],
                      ['2007-12-31', 13329909.0],
                      ['2006-12-31', 13124267.0],
                      ['2005-12-31', 12940032.0],
                      ['2004-12-31', 12777511.0],
                      ['2003-12-31', 12633897.0],
                      ['2002-12-31', 12500525.0],
                      ['2001-12-31', 12366165.0],
                      ['2000-12-31', 12222251.0],
                      ['1999-12-31', 12064537.0],
                      ['1998-12-31', 11893272.0],
                      ['1997-12-31', 11709997.0],
                      ['1996-12-31', 11518262.0],
                      ['1995-12-31', 11320346.0],
                      ['1994-12-31', 11116948.0],
                      ['1993-12-31', 10905756.0],
                      ['1992-12-31', 10682868.0],
                      ['1991-12-31', 10443043.0],
                      ['1990-12-31', 10183113.0],
                      ['1989-12-31', 9902540.0],
                      ['1988-12-31', 9604302.0],
                      ['1987-12-31', 9293283.0],
                      ['1986-12-31', 8976205.0],
                      ['1985-12-31', 8658857.0],
                      ['1984-12-31', 8342195.0],
                      ['1983-12-31', 8027565.0],
                      ['1982-12-31', 7721536.0],
                      ['1981-12-31', 7431940.0],
                      ['1980-12-31', 7164172.0],
                      ['1979-12-31', 6921790.0],
                      ['1978-12-31', 6703182.0],
                      ['1977-12-31', 6501893.0],
                      ['1976-12-31', 6308300.0],
                      ['1975-12-31', 6115370.0],
                      ['1974-12-31', 5920943.0],
                      ['1973-12-31', 5727044.0],
                      ['1972-12-31', 5535874.0],
                      ['1971-12-31', 5351195.0],
                      ['1970-12-31', 5175618.0],
                      ['1969-12-31', 5009514.0],
                      ['1968-12-31', 4851431.0],
                      ['1967-12-31', 4700041.0],
                      ['1966-12-31', 4553433.0],
                      ['1965-12-31', 4410212.0],
                      ['1964-12-31', 4269863.0],
                      ['1963-12-31', 4132756.0],
                      ['1962-12-31', 3999419.0],
                      ['1961-12-31', 3870756.0],
                      ['1960-12-31', 3747369.0],
                      ['1959-12-31', 3629356.0],
                      ['1958-12-31', 3516399.0],
                      ['1957-12-31', 3407908.0],
                      ['1956-12-31', 3303265.0],
                      ['1955-12-31', 3202015.0],
                      ['1954-12-31', 3103899.0],
                      ['1953-12-31', 3008925.0],
                      ['1952-12-31', 2917368.0],
                      ['1951-12-31', 2829750.0],
                      ['1950-12-31', 2746852.0]],
             'database_code': 'WWDI',
             'database_id': 13565,
             'dataset_code': 'ZWE_SP_POP_TOTL',
             'description': 'Population, total - Zimbabwe. ',
             'end_date': '2017-12-31',
             'frequency': 'annual',
             'id': 22264110,
             'limit': None,
             'name': 'Population, total - Zimbabwe',
             'newest_available_date': '2017-12-31',
             'oldest_available_date': '1950-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-12-25T11:47:20.271Z',
             'start_date': '1950-12-31',
             'transform': None,
             'type': 'Time Series'}}

In [ ]:
for item in data:
    {
    
    }